export const DATA_RETENTION_CLEANUP_INTERVAL_MINUTES = 10
export const DATA_RETENTION_CLEANUP_BATCH_SIZE = 1000
export const DATA_RETENTION_CLEANUP_MAX_BATCHES_PER_RUN = 20
export const DATA_RETENTION_CLEANUP_BATCH_PAUSE_MS = 25
