-- Code generated by backend-go/scripts/generate-provider-model-catalog.ts; DO NOT EDIT.
-- Snapshot as-of date: 2026-07-15
-- Snapshot SHA-256: 233ec689b79bad43bf213bbd52d39af8c65c561a4cdbe22431101f0e8e5c71cf
-- Provider row counts total/visible: gpt=81/81, anthropic=43/17, gemini=9/9, deepseek=4/4, glm=18/17
-- Check from the backend directory:
--   pnpm exec tsx ../backend-go/scripts/generate-provider-model-catalog.ts --check --output <migration-path>

-- +goose Up
UPDATE juhe_business.provider_model_catalog
SET status = 'disabled',
    catalog_visible = false,
    updated_at = now()
WHERE provider_code IN ('gpt', 'anthropic', 'gemini', 'deepseek', 'glm');

INSERT INTO juhe_business.provider_model_catalog (
  id, provider_code, model, status, mode, catalog_order, release_date, shutdown_date,
  supported_api_protocols_json, supported_service_tiers_json, supported_reasoning_efforts_json,
  default_reasoning_effort, codex_supported_reasoning_levels_json, codex_default_reasoning_level,
  codex_multi_agent_version, context_window_tokens,
  input_usd_per_1m, output_usd_per_1m, cached_input_usd_per_1m,
  cache_write_usd_per_1m, cache_write_1h_usd_per_1m,
  service_tier_prices_json,
  long_context_input_token_threshold, long_context_input_cost_multiplier,
  long_context_output_cost_multiplier,
  image_input_usd_per_1m, image_output_usd_per_1m,
  audio_input_usd_per_1m, audio_output_usd_per_1m, output_usd_per_image,
  max_input_tokens, max_output_tokens, max_tokens,
  supports_prompt_caching, catalog_visible, source, created_at, updated_at
) VALUES
  (
    'provider_model_gpt_gpt_5_6_sol_69ec47b65152', 'gpt', 'gpt-5.6-sol', 'active', 'chat', 0, '2026-06-26', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '["none","low","medium","high","xhigh","max"]', NULL, '["low","medium","high","xhigh","max","ultra"]', 'low', 'v2',
    1050000, 5, 30, 0.5, 6.25, NULL, '{"priority":{"inputUsdPer1M":10,"outputUsdPer1M":60,"cachedInputUsdPer1M":1,"cacheWriteUsdPer1M":12.5},"flex":{"inputUsdPer1M":2.5,"outputUsdPer1M":15,"cachedInputUsdPer1M":0.25,"cacheWriteUsdPer1M":3.125}}',
    272000, 2, 1.5, NULL, NULL,
    NULL, NULL, NULL, 922000, 128000,
    NULL, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_6_terra_747e31961b81', 'gpt', 'gpt-5.6-terra', 'active', 'chat', 1, '2026-06-26', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '["none","low","medium","high","xhigh","max"]', NULL, '["low","medium","high","xhigh","max","ultra"]', 'medium', 'v2',
    1050000, 2.5, 15, 0.25, 3.125, NULL, '{"priority":{"inputUsdPer1M":5,"outputUsdPer1M":30,"cachedInputUsdPer1M":0.5,"cacheWriteUsdPer1M":6.25},"flex":{"inputUsdPer1M":1.25,"outputUsdPer1M":7.5,"cachedInputUsdPer1M":0.125,"cacheWriteUsdPer1M":1.5625}}',
    272000, 2, 1.5, NULL, NULL,
    NULL, NULL, NULL, 922000, 128000,
    NULL, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_6_luna_1bee2584a5e4', 'gpt', 'gpt-5.6-luna', 'active', 'chat', 2, '2026-06-26', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '["none","low","medium","high","xhigh","max"]', NULL, '["low","medium","high","xhigh","max"]', 'medium', NULL,
    1050000, 1, 6, 0.1, 1.25, NULL, '{"priority":{"inputUsdPer1M":2,"outputUsdPer1M":12,"cachedInputUsdPer1M":0.2,"cacheWriteUsdPer1M":2.5},"flex":{"inputUsdPer1M":0.5,"outputUsdPer1M":3,"cachedInputUsdPer1M":0.05,"cacheWriteUsdPer1M":0.625}}',
    272000, 2, 1.5, NULL, NULL,
    NULL, NULL, NULL, 922000, 128000,
    NULL, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_5_d2e052b00bdc', 'gpt', 'gpt-5.5', 'active', 'chat', NULL, '2026-04-23', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '["none","low","medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    1050000, 5, 30, 0.5, NULL, NULL, '{"priority":{"inputUsdPer1M":12.5,"outputUsdPer1M":75,"cachedInputUsdPer1M":1.25}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_5_2026_04_23_9919b5734f6b', 'gpt', 'gpt-5.5-2026-04-23', 'active', 'chat', NULL, '2026-04-23', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '["none","low","medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    1050000, 5, 30, 0.5, NULL, NULL, '{"priority":{"inputUsdPer1M":12.5,"outputUsdPer1M":75,"cachedInputUsdPer1M":1.25}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_5_pro_88ac1010cdea', 'gpt', 'gpt-5.5-pro', 'active', 'responses', NULL, '2026-04-23', NULL,
    '["responses"]', '["priority","flex"]', '["medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    1050000, 30, 180, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_5_pro_2026_04_23_e5087247bb73', 'gpt', 'gpt-5.5-pro-2026-04-23', 'active', 'responses', NULL, '2026-04-23', NULL,
    '["responses"]', '["priority","flex"]', '["medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    1050000, 30, 180, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_image_2_8e41874070f5', 'gpt', 'gpt-image-2', 'active', 'image_generation', NULL, '2026-04-21', NULL,
    '["images"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 10, 1.25, NULL, NULL, '{}',
    NULL, NULL, NULL, 8, 30,
    NULL, NULL, NULL, NULL, NULL,
    NULL, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_image_2_2026_04_21_d590408c9e34', 'gpt', 'gpt-image-2-2026-04-21', 'active', 'image_generation', NULL, '2026-04-21', NULL,
    '["images"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 10, 1.25, NULL, NULL, '{}',
    NULL, NULL, NULL, 8, 30,
    NULL, NULL, NULL, NULL, NULL,
    NULL, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_4_mini_a723c7a16805', 'gpt', 'gpt-5.4-mini', 'active', 'chat', NULL, '2026-03-17', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '["none","low","medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    400000, 0.75, 4.5, 0.075, NULL, NULL, '{"priority":{"inputUsdPer1M":1.5,"outputUsdPer1M":9,"cachedInputUsdPer1M":0.15}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 272000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_4_mini_2026_03_17_4000f0679d4d', 'gpt', 'gpt-5.4-mini-2026-03-17', 'active', 'chat', NULL, '2026-03-17', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '["none","low","medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    400000, 0.75, 4.5, 0.075, NULL, NULL, '{"priority":{"inputUsdPer1M":1.5,"outputUsdPer1M":9,"cachedInputUsdPer1M":0.15}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 272000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_4_nano_2de63c573784', 'gpt', 'gpt-5.4-nano', 'active', 'chat', NULL, '2026-03-17', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '["none","low","medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    400000, 0.2, 1.25, 0.02, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 272000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_4_nano_2026_03_17_34f28862f6ec', 'gpt', 'gpt-5.4-nano-2026-03-17', 'active', 'chat', NULL, '2026-03-17', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '["none","low","medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    400000, 0.2, 1.25, 0.02, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 272000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_4_717f0170de40', 'gpt', 'gpt-5.4', 'active', 'chat', NULL, '2026-03-05', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '["none","low","medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    1050000, 2.5, 15, 0.25, NULL, NULL, '{"priority":{"inputUsdPer1M":5,"outputUsdPer1M":30,"cachedInputUsdPer1M":0.5}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_4_2026_03_05_8779654fecda', 'gpt', 'gpt-5.4-2026-03-05', 'active', 'chat', NULL, '2026-03-05', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '["none","low","medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    1050000, 2.5, 15, 0.25, NULL, NULL, '{"priority":{"inputUsdPer1M":5,"outputUsdPer1M":30,"cachedInputUsdPer1M":0.5}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_4_pro_7506552aa7c3', 'gpt', 'gpt-5.4-pro', 'active', 'responses', NULL, '2026-03-05', NULL,
    '["responses"]', '["priority","flex"]', '["medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    1050000, 30, 180, 3, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_4_pro_2026_03_05_971128cea5ea', 'gpt', 'gpt-5.4-pro-2026-03-05', 'active', 'responses', NULL, '2026-03-05', NULL,
    '["responses"]', '["priority","flex"]', '["medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    1050000, 30, 180, 3, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_3_chat_latest_fa39c354c944', 'gpt', 'gpt-5.3-chat-latest', 'active', 'chat', NULL, '2026-02-01', NULL,
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.75, 14, 0.175, NULL, NULL, '{"priority":{"inputUsdPer1M":3.5,"outputUsdPer1M":28,"cachedInputUsdPer1M":0.35}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 16384,
    16384, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_3_codex_5fde1c078277', 'gpt', 'gpt-5.3-codex', 'active', 'responses', NULL, '2026-02-01', NULL,
    '["responses"]', '["priority"]', '[]', NULL, '[]', NULL, NULL,
    400000, 1.75, 14, 0.175, NULL, NULL, '{"priority":{"inputUsdPer1M":3.5,"outputUsdPer1M":28,"cachedInputUsdPer1M":0.35}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 272000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_audio_1_5_65bbaeefe59f', 'gpt', 'gpt-audio-1.5', 'active', 'chat', NULL, '2026-02-01', NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 2.5, 10, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 16384,
    16384, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_image_1_5_d66f11f468b7', 'gpt', 'gpt-image-1.5', 'active', 'image_generation', NULL, '2026-02-01', NULL,
    '["images"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 10, 1.25, NULL, NULL, '{}',
    NULL, NULL, NULL, 8, 32,
    NULL, NULL, NULL, NULL, NULL,
    NULL, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_realtime_1_5_016138eff138', 'gpt', 'gpt-realtime-1.5', 'active', 'chat', NULL, '2026-02-01', NULL,
    '["realtime"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 4, 16, 0.4, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 32000, 4096,
    4096, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_2_codex_d2cdf8bc7de2', 'gpt', 'gpt-5.2-codex', 'active', 'responses', NULL, '2026-01-01', '2026-07-23',
    '["responses"]', '["priority"]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.75, 14, 0.175, NULL, NULL, '{"priority":{"inputUsdPer1M":3.5,"outputUsdPer1M":28,"cachedInputUsdPer1M":0.35}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 400000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4o_mini_transcribe_2025_12_15_de782e4732ce', 'gpt', 'gpt-4o-mini-transcribe-2025-12-15', 'active', 'audio_transcription', NULL, '2025-12-15', NULL,
    '["audio"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.25, 5, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 16000, 2000,
    NULL, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4o_mini_tts_2025_12_15_4e7624540fa8', 'gpt', 'gpt-4o-mini-tts-2025-12-15', 'active', 'audio_speech', NULL, '2025-12-15', NULL,
    '["audio"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 2.5, 10, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_realtime_mini_2025_12_15_c1c343c81eaf', 'gpt', 'gpt-realtime-mini-2025-12-15', 'active', 'chat', NULL, '2025-12-15', NULL,
    '["realtime"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.6, 2.4, 0.06, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 4096,
    4096, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_2_eba4fa2cf5c3', 'gpt', 'gpt-5.2', 'active', 'chat', NULL, '2025-12-11', NULL,
    '["chat_completions","responses"]', '["priority"]', '["none","low","medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    NULL, 1.75, 14, 0.175, NULL, NULL, '{"priority":{"inputUsdPer1M":3.5,"outputUsdPer1M":28,"cachedInputUsdPer1M":0.35}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 400000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_2_2025_12_11_a043e85a080a', 'gpt', 'gpt-5.2-2025-12-11', 'active', 'chat', NULL, '2025-12-11', NULL,
    '["chat_completions","responses"]', '["priority"]', '["none","low","medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    NULL, 1.75, 14, 0.175, NULL, NULL, '{"priority":{"inputUsdPer1M":3.5,"outputUsdPer1M":28,"cachedInputUsdPer1M":0.35}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 400000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_2_chat_latest_ac156dc14c91', 'gpt', 'gpt-5.2-chat-latest', 'active', 'chat', NULL, '2025-12-11', NULL,
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.75, 14, 0.175, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 16384,
    16384, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_2_pro_eeb8721bf21c', 'gpt', 'gpt-5.2-pro', 'active', 'responses', NULL, '2025-12-11', NULL,
    '["responses"]', '["priority"]', '["medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    NULL, 21, 168, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 400000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_2_pro_2025_12_11_bbcfb2a7e6f1', 'gpt', 'gpt-5.2-pro-2025-12-11', 'active', 'responses', NULL, '2025-12-11', NULL,
    '["responses"]', '["priority"]', '["medium","high","xhigh"]', NULL, '[]', NULL, NULL,
    NULL, 21, 168, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 400000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_1_28d89196b564', 'gpt', 'gpt-5.1', 'active', 'chat', NULL, '2025-11-13', NULL,
    '["chat_completions","responses"]', '["priority"]', '["none","low","medium","high"]', NULL, '[]', NULL, NULL,
    NULL, 1.25, 10, 0.125, NULL, NULL, '{"priority":{"inputUsdPer1M":2.5,"outputUsdPer1M":20,"cachedInputUsdPer1M":0.25}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 400000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_1_2025_11_13_35c8c1007049', 'gpt', 'gpt-5.1-2025-11-13', 'active', 'chat', NULL, '2025-11-13', NULL,
    '["chat_completions","responses"]', '["priority"]', '["none","low","medium","high"]', NULL, '[]', NULL, NULL,
    NULL, 1.25, 10, 0.125, NULL, NULL, '{"priority":{"inputUsdPer1M":2.5,"outputUsdPer1M":20,"cachedInputUsdPer1M":0.25}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 400000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_1_chat_latest_68c45bdedea2', 'gpt', 'gpt-5.1-chat-latest', 'active', 'chat', NULL, '2025-11-13', '2026-07-23',
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.25, 10, 0.125, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 16384,
    16384, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_1_codex_684af5248712', 'gpt', 'gpt-5.1-codex', 'active', 'responses', NULL, '2025-11-13', '2026-07-23',
    '["responses"]', '["priority"]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.25, 10, 0.125, NULL, NULL, '{"priority":{"inputUsdPer1M":2.5,"outputUsdPer1M":20,"cachedInputUsdPer1M":0.25}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 400000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_1_codex_max_35146cec8df9', 'gpt', 'gpt-5.1-codex-max', 'active', 'responses', NULL, '2025-11-13', '2026-07-23',
    '["responses"]', '["priority"]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.25, 10, 0.125, NULL, NULL, '{"priority":{"inputUsdPer1M":2.5,"outputUsdPer1M":20,"cachedInputUsdPer1M":0.25}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 400000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_1_codex_mini_3ba405490474', 'gpt', 'gpt-5.1-codex-mini', 'active', 'responses', NULL, '2025-11-13', '2026-07-23',
    '["responses"]', '["priority"]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.25, 2, 0.025, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 400000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_pro_ce7311ed7ec1', 'gpt', 'gpt-5-pro', 'active', 'responses', NULL, '2025-10-06', NULL,
    '["responses"]', '["priority"]', '[]', NULL, '[]', NULL, NULL,
    400000, 15, 120, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 272000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_pro_2025_10_06_915aab63bf49', 'gpt', 'gpt-5-pro-2025-10-06', 'active', 'responses', NULL, '2025-10-06', NULL,
    '["responses"]', '["priority"]', '[]', NULL, '[]', NULL, NULL,
    400000, 15, 120, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 272000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_audio_mini_45ba941f7b65', 'gpt', 'gpt-audio-mini', 'active', 'chat', NULL, '2025-10-06', NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.6, 2.4, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 16384,
    16384, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_image_1_mini_f4f65c824837', 'gpt', 'gpt-image-1-mini', 'active', 'image_generation', NULL, '2025-10-06', NULL,
    '["images"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 2, NULL, 0.2, NULL, NULL, '{}',
    NULL, NULL, NULL, 2.5, 8,
    NULL, NULL, NULL, NULL, NULL,
    NULL, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_realtime_mini_8cd027a5c666', 'gpt', 'gpt-realtime-mini', 'active', 'chat', NULL, '2025-10-06', NULL,
    '["realtime"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.6, 2.4, 0.06, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 4096,
    4096, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_codex_8c4845a2a869', 'gpt', 'gpt-5-codex', 'active', 'responses', NULL, '2025-09-01', '2026-07-23',
    '["responses"]', '["priority"]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.25, 10, 0.125, NULL, NULL, '{"priority":{"inputUsdPer1M":2.5,"outputUsdPer1M":20,"cachedInputUsdPer1M":0.25}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 400000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_audio_112b94873ad2', 'gpt', 'gpt-audio', 'active', 'chat', NULL, '2025-09-01', NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 2.5, 10, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 16384,
    16384, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_realtime_cb9a5d66d8ac', 'gpt', 'gpt-realtime', 'active', 'chat', NULL, '2025-09-01', NULL,
    '["realtime"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 4, 16, 0.4, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 32000, 4096,
    4096, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_1576fd0b9fe4', 'gpt', 'gpt-5', 'active', 'chat', NULL, '2025-08-07', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '["minimal","low","medium","high"]', NULL, '[]', NULL, NULL,
    400000, 1.25, 10, 0.125, NULL, NULL, '{"priority":{"inputUsdPer1M":2.5,"outputUsdPer1M":20,"cachedInputUsdPer1M":0.25}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 272000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_2025_08_07_d037b8c88624', 'gpt', 'gpt-5-2025-08-07', 'active', 'chat', NULL, '2025-08-07', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '["minimal","low","medium","high"]', NULL, '[]', NULL, NULL,
    400000, 1.25, 10, 0.125, NULL, NULL, '{"priority":{"inputUsdPer1M":2.5,"outputUsdPer1M":20,"cachedInputUsdPer1M":0.25}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 272000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_chat_latest_3dfe6bd6db71', 'gpt', 'gpt-5-chat-latest', 'active', 'chat', NULL, '2025-08-07', '2026-07-23',
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.25, 10, 0.125, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 16384,
    16384, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_mini_ace6afb48c6d', 'gpt', 'gpt-5-mini', 'active', 'chat', NULL, '2025-08-07', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '[]', NULL, '[]', NULL, NULL,
    400000, 0.25, 2, 0.025, NULL, NULL, '{"priority":{"inputUsdPer1M":0.45,"outputUsdPer1M":3.6,"cachedInputUsdPer1M":0.045}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 272000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_mini_2025_08_07_afd4fa5f10e1', 'gpt', 'gpt-5-mini-2025-08-07', 'active', 'chat', NULL, '2025-08-07', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '[]', NULL, '[]', NULL, NULL,
    400000, 0.25, 2, 0.025, NULL, NULL, '{"priority":{"inputUsdPer1M":0.45,"outputUsdPer1M":3.6,"cachedInputUsdPer1M":0.045}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 272000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_nano_8322547ec9b0', 'gpt', 'gpt-5-nano', 'active', 'chat', NULL, '2025-08-07', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '[]', NULL, '[]', NULL, NULL,
    400000, 0.05, 0.4, 0.005, NULL, NULL, '{"priority":{"inputUsdPer1M":0.2,"outputUsdPer1M":0.8,"cachedInputUsdPer1M":0.05}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 272000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_nano_2025_08_07_7b49ad423b66', 'gpt', 'gpt-5-nano-2025-08-07', 'active', 'chat', NULL, '2025-08-07', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '[]', NULL, '[]', NULL, NULL,
    400000, 0.05, 0.4, 0.005, NULL, NULL, '{"priority":{"inputUsdPer1M":0.2,"outputUsdPer1M":0.8,"cachedInputUsdPer1M":0.05}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 272000, 128000,
    128000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_5_search_api_7638fac7cb9b', 'gpt', 'gpt-5-search-api', 'active', 'chat', NULL, '2025-08-07', NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 200000, NULL,
    200000, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_o3_pro_4360f43de406', 'gpt', 'o3-pro', 'active', 'responses', NULL, '2025-06-01', NULL,
    '["responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 20, 80, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 200000, 100000,
    100000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_image_1_8debda0f1bc4', 'gpt', 'gpt-image-1', 'active', 'image_generation', NULL, '2025-04-23', '2026-10-23',
    '["images"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 10, 1.25, NULL, NULL, '{}',
    NULL, NULL, NULL, 10, 40,
    NULL, NULL, NULL, NULL, NULL,
    NULL, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_o3_1a480748433d', 'gpt', 'o3', 'active', 'chat', NULL, '2025-04-16', NULL,
    '["chat_completions","responses"]', '["priority","flex"]', '[]', NULL, '[]', NULL, NULL,
    NULL, 2, 8, 0.5, NULL, NULL, '{"priority":{"inputUsdPer1M":3.5,"outputUsdPer1M":14,"cachedInputUsdPer1M":0.875}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 200000, 100000,
    100000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_o4_mini_7e0c4e65546c', 'gpt', 'o4-mini', 'active', 'chat', NULL, '2025-04-16', '2026-10-23',
    '["chat_completions","responses"]', '["priority","flex"]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.1, 4.4, 0.275, NULL, NULL, '{"priority":{"inputUsdPer1M":2,"outputUsdPer1M":8,"cachedInputUsdPer1M":0.5}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 200000, 100000,
    100000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4_1_0a34cb02b9c6', 'gpt', 'gpt-4.1', 'active', 'chat', NULL, '2025-04-14', NULL,
    '["chat_completions","responses"]', '["priority"]', '[]', NULL, '[]', NULL, NULL,
    NULL, 2, 8, 0.5, NULL, NULL, '{"priority":{"inputUsdPer1M":3.5,"outputUsdPer1M":14,"cachedInputUsdPer1M":0.875}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1047576, 32768,
    32768, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4_1_mini_dda6092389fe', 'gpt', 'gpt-4.1-mini', 'active', 'chat', NULL, '2025-04-14', NULL,
    '["chat_completions","responses"]', '["priority"]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.4, 1.6, 0.1, NULL, NULL, '{"priority":{"inputUsdPer1M":0.7,"outputUsdPer1M":2.8,"cachedInputUsdPer1M":0.175}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1047576, 32768,
    32768, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4_1_nano_48e5ddab8a0b', 'gpt', 'gpt-4.1-nano', 'active', 'chat', NULL, '2025-04-14', '2026-10-23',
    '["chat_completions","responses"]', '["priority"]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.1, 0.4, 0.025, NULL, NULL, '{"priority":{"inputUsdPer1M":0.2,"outputUsdPer1M":0.8,"cachedInputUsdPer1M":0.05}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1047576, 32768,
    32768, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4o_mini_transcribe_c7b9dd09f0d7', 'gpt', 'gpt-4o-mini-transcribe', 'active', 'audio_transcription', NULL, '2025-03-20', NULL,
    '["audio"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.25, 5, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 16000, 2000,
    NULL, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4o_mini_tts_7301116ea6ee', 'gpt', 'gpt-4o-mini-tts', 'active', 'audio_speech', NULL, '2025-03-20', NULL,
    '["audio"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 2.5, 10, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_o1_pro_bce236c484d0', 'gpt', 'o1-pro', 'active', 'responses', NULL, '2025-03-19', '2026-10-23',
    '["responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 150, 600, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 200000, 100000,
    100000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4o_transcribe_f7efc4eb8899', 'gpt', 'gpt-4o-transcribe', 'active', 'audio_transcription', NULL, '2025-03-01', NULL,
    '["audio"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 2.5, 10, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 16000, 2000,
    NULL, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4o_transcribe_diarize_1130df8b7237', 'gpt', 'gpt-4o-transcribe-diarize', 'active', 'audio_transcription', NULL, '2025-03-01', NULL,
    '["audio"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 2.5, 10, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 16000, 2000,
    NULL, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_o3_mini_4c68eeb96c58', 'gpt', 'o3-mini', 'active', 'chat', NULL, '2025-01-31', '2026-10-23',
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.1, 4.4, 0.55, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 200000, 100000,
    100000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_o1_10560fdf0593', 'gpt', 'o1', 'active', 'chat', NULL, '2024-12-17', '2026-10-23',
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 15, 60, 7.5, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 200000, 100000,
    100000, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4o_mini_c4b6eb3e57e0', 'gpt', 'gpt-4o-mini', 'active', 'chat', NULL, '2024-07-18', NULL,
    '["chat_completions","responses"]', '["priority"]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.15, 0.6, 0.075, NULL, NULL, '{"priority":{"inputUsdPer1M":0.25,"outputUsdPer1M":1,"cachedInputUsdPer1M":0.125}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 16384,
    16384, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4o_44f2c7d60c2f', 'gpt', 'gpt-4o', 'active', 'chat', NULL, '2024-05-13', NULL,
    '["chat_completions","responses"]', '["priority"]', '[]', NULL, '[]', NULL, NULL,
    NULL, 2.5, 10, 1.25, NULL, NULL, '{"priority":{"inputUsdPer1M":4.25,"outputUsdPer1M":17,"cachedInputUsdPer1M":2.125}}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 16384,
    16384, true, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4o_2024_05_13_32f3e511a748', 'gpt', 'gpt-4o-2024-05-13', 'active', 'chat', NULL, '2024-05-13', '2026-10-23',
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 15, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 4096,
    4096, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4_turbo_6ccd0ff91598', 'gpt', 'gpt-4-turbo', 'active', 'chat', NULL, '2024-04-09', '2026-10-23',
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 10, 30, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 4096,
    4096, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4_turbo_2024_04_09_cb7434b40395', 'gpt', 'gpt-4-turbo-2024-04-09', 'active', 'chat', NULL, '2024-04-09', '2026-10-23',
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 10, 30, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 4096,
    4096, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_3_5_turbo_4ddb9442f2fb', 'gpt', 'gpt-3.5-turbo', 'active', 'chat', NULL, '2024-01-25', '2026-10-23',
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.5, 1.5, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 16385, 4096,
    4096, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_3_5_turbo_0125_98d60bdf38af', 'gpt', 'gpt-3.5-turbo-0125', 'active', 'chat', NULL, '2024-01-25', '2026-10-23',
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.5, 1.5, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 16385, 4096,
    4096, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_babbage_002_cfbf0287adef', 'gpt', 'babbage-002', 'active', 'completion', NULL, '2024-01-04', '2026-09-28',
    '["completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.4, 0.4, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 16384, 4096,
    16384, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_davinci_002_9a234f92ffa3', 'gpt', 'davinci-002', 'active', 'completion', NULL, '2024-01-04', '2026-09-28',
    '["completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 2, 2, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 16384, 4096,
    16384, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_3_5_turbo_1106_0c09af079e8d', 'gpt', 'gpt-3.5-turbo-1106', 'active', 'chat', NULL, '2023-11-06', '2026-09-28',
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1, 2, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 16385, 4096,
    4096, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4_1106_preview_9916d1e421cd', 'gpt', 'gpt-4-1106-preview', 'active', 'chat', NULL, '2023-11-06', '2026-10-23',
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 10, 30, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 128000, 4096,
    4096, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_3_5_turbo_instruct_156116659872', 'gpt', 'gpt-3.5-turbo-instruct', 'active', 'completion', NULL, '2023-07-06', '2026-09-28',
    '["completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.5, 2, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 4096, 4096,
    4096, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4_a6fc3842b3ea', 'gpt', 'gpt-4', 'active', 'chat', NULL, '2023-06-13', '2026-10-23',
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 30, 60, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 8192, 4096,
    8192, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gpt_gpt_4_0613_46343f55aa36', 'gpt', 'gpt-4-0613', 'active', 'chat', NULL, '2023-06-13', '2026-10-23',
    '["chat_completions","responses"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 30, 60, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 8192, 4096,
    8192, false, true,
    'openai-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_fable_5_ee9ac0815761', 'anthropic', 'claude-fable-5', 'active', NULL, 10, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 10, 50, 1, 12.5, 20, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 128000,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_mythos_5_a494ec25808d', 'anthropic', 'claude-mythos-5', 'active', NULL, 20, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 10, 50, 1, 12.5, 20, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 128000,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_sonnet_5_2772a21f5ca7', 'anthropic', 'claude-sonnet-5', 'active', NULL, 25, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    200000, 2, 10, 0.2, 2.5, 4, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 128000,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_opus_4_8_079e4ab886e5', 'anthropic', 'claude-opus-4-8', 'active', NULL, 40, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 128000,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_opus_4_7_2c0ca3d5dd91', 'anthropic', 'claude-opus-4-7', 'active', NULL, 50, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 128000,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_opus_4_6_7532b0330ba1', 'anthropic', 'claude-opus-4-6', 'active', NULL, 60, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 128000,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_opus_4_6_thinking_993d13cf8729', 'anthropic', 'claude-opus-4-6-thinking', 'active', NULL, 70, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_opus_4_5_9c0ba1c5b1c3', 'anthropic', 'claude-opus-4-5', 'active', NULL, 80, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_opus_4_5_20251101_28407c961049', 'anthropic', 'claude-opus-4-5-20251101', 'active', NULL, 90, '2025-11-01', NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_opus_4_1_37102436e62a', 'anthropic', 'claude-opus-4-1', 'active', NULL, 100, '2025-08-05', '2026-08-05',
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 15, 75, 1.5, 18.75, 30, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 200000, 32000,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_opus_4_1_20250805_49c63afbdbff', 'anthropic', 'claude-opus-4-1-20250805', 'active', NULL, 110, '2025-08-05', '2026-08-05',
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 15, 75, 1.5, 18.75, 30, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 200000, 32000,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_sonnet_4_6_f36c8ffc8ee9', 'anthropic', 'claude-sonnet-4-6', 'active', NULL, 120, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, NULL,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_sonnet_4_6_thinking_3fee0c1d9baa', 'anthropic', 'claude-sonnet-4-6-thinking', 'active', NULL, 130, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_sonnet_4_5_8f70ef7d868b', 'anthropic', 'claude-sonnet-4-5', 'active', NULL, 140, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_sonnet_4_5_20250929_cddbb8f7b505', 'anthropic', 'claude-sonnet-4-5-20250929', 'active', NULL, 150, '2025-09-29', NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_haiku_4_5_f0431e921dfe', 'anthropic', 'claude-haiku-4-5', 'active', NULL, 160, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1, 5, 0.1, 1.25, 2, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_haiku_4_5_20251001_e01af2bd1bf9', 'anthropic', 'claude-haiku-4-5-20251001', 'active', NULL, 170, '2025-10-01', NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1, 5, 0.1, 1.25, 2, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, true, true,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_best_2569439632bb', 'anthropic', 'best', 'active', NULL, 210, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 10, 50, 1, 12.5, 20, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 128000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_fable_34262fd035c8', 'anthropic', 'fable', 'active', NULL, 220, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 10, 50, 1, 12.5, 20, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 128000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_opus_b261045e1596', 'anthropic', 'opus', 'active', NULL, 230, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 128000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_opus_1m_3b4fe3557e31', 'anthropic', 'opus[1m]', 'active', NULL, 240, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 128000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_opusplan_eccc363c04e9', 'anthropic', 'opusplan', 'active', NULL, 250, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 128000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_sonnet_a323611fa1aa', 'anthropic', 'sonnet', 'active', NULL, 260, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, NULL,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_sonnet_1m_7c21f4723f11', 'anthropic', 'sonnet[1m]', 'active', NULL, 270, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, NULL,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_haiku_6219212f9ec7', 'anthropic', 'haiku', 'active', NULL, 280, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1, 5, 0.1, 1.25, 2, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_antigravity_claude_opus_4_6_thinking_2767f8531135', 'anthropic', 'antigravity-claude-opus-4-6-thinking', 'active', NULL, 900, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_antigravity_claude_opus_4_6_thinking_bbce7ab21f88', 'anthropic', 'antigravity/claude-opus-4-6-thinking', 'active', NULL, 901, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_google_antigravity_claude_opus_4_6_thinking_fd54efd56e47', 'anthropic', 'google/antigravity-claude-opus-4-6-thinking', 'active', NULL, 902, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_google_antigravity_claude_opus_4_6_thinking_fab06390c642', 'anthropic', 'google-antigravity/claude-opus-4-6-thinking', 'active', NULL, 903, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_google_antigravity_claude_opus_4_6_thinking_2251c0eddbf7', 'anthropic', 'google-antigravity:claude-opus-4-6-thinking', 'active', NULL, 904, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_opus_4_6_antigravity_9f8b955f3c2c', 'anthropic', 'claude-opus-4-6-antigravity', 'active', NULL, 905, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 5, 25, 0.5, 6.25, 10, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_sonnet_4_6_antigravity_16de98384c59', 'anthropic', 'claude-sonnet-4-6-antigravity', 'active', NULL, 920, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_antigravity_claude_sonnet_4_6_a92e39c85ef3', 'anthropic', 'antigravity-claude-sonnet-4-6', 'active', NULL, 921, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_antigravity_claude_sonnet_4_6_c1985910453d', 'anthropic', 'antigravity/claude-sonnet-4-6', 'active', NULL, 922, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_google_antigravity_claude_sonnet_4_6_f88a37b50d48', 'anthropic', 'google/antigravity-claude-sonnet-4-6', 'active', NULL, 923, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_google_antigravity_claude_sonnet_4_6_bbea917b9ae3', 'anthropic', 'google-antigravity/claude-sonnet-4-6', 'active', NULL, 924, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_google_antigravity_claude_sonnet_4_6_0cbad9221125', 'anthropic', 'google-antigravity:claude-sonnet-4-6', 'active', NULL, 925, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_antigravity_claude_sonnet_4_6_thinking_708e8be13ef7', 'anthropic', 'antigravity-claude-sonnet-4-6-thinking', 'active', NULL, 930, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_antigravity_claude_sonnet_4_6_thinking_3a3e9c2715d4', 'anthropic', 'antigravity/claude-sonnet-4-6-thinking', 'active', NULL, 931, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_google_antigravity_claude_sonnet_4_6_thinking_623d8220eb68', 'anthropic', 'google/antigravity-claude-sonnet-4-6-thinking', 'active', NULL, 932, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_google_antigravity_claude_sonnet_4_6_thinking_21f1b1b903c1', 'anthropic', 'google-antigravity/claude-sonnet-4-6-thinking', 'active', NULL, 933, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_google_antigravity_claude_sonnet_4_6_thinking_92399ec91a1e', 'anthropic', 'google-antigravity:claude-sonnet-4-6-thinking', 'active', NULL, 934, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 3, 15, 0.3, 3.75, 6, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1000000, 64000,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_anthropic_claude_fake_5_0abbf97e424f', 'anthropic', 'claude-fake-5', 'active', NULL, 999, NULL, NULL,
    '["messages","message_token_counting"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1, 5, 0.1, 1.25, 2, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, true, false,
    'anthropic-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gemini_gemini_3_5_flash_d1d419e2959d', 'gemini', 'gemini-3.5-flash', 'active', 'chat', 10, NULL, NULL,
    '["chat_completions","generate_content","stream_generate_content","count_tokens"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.5, 9, 0.15, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1048576, 65536,
    NULL, true, true,
    'gemini-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gemini_gemini_3_1_pro_preview_4ac8c0321b1e', 'gemini', 'gemini-3.1-pro-preview', 'active', 'chat', 20, NULL, NULL,
    '["chat_completions","generate_content","stream_generate_content","count_tokens"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 2, 12, 0.2, NULL, NULL, '{}',
    200000, 2, 1.5, NULL, NULL,
    NULL, NULL, NULL, 1048576, 65536,
    NULL, true, true,
    'gemini-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gemini_gemini_3_1_pro_preview_customtools_e18e934d95f3', 'gemini', 'gemini-3.1-pro-preview-customtools', 'active', 'chat', 30, NULL, NULL,
    '["chat_completions","generate_content","stream_generate_content","count_tokens"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 2, 12, 0.2, NULL, NULL, '{}',
    200000, 2, 1.5, NULL, NULL,
    NULL, NULL, NULL, 1048576, 65536,
    NULL, true, true,
    'gemini-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gemini_gemini_3_flash_preview_31231c90128f', 'gemini', 'gemini-3-flash-preview', 'active', 'chat', 40, NULL, NULL,
    '["chat_completions","generate_content","stream_generate_content","count_tokens"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.5, 3, 0.05, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    1, NULL, NULL, 1048576, 65536,
    NULL, true, true,
    'gemini-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gemini_gemini_3_1_flash_lite_a9e6fdfe1cce', 'gemini', 'gemini-3.1-flash-lite', 'active', 'chat', 50, NULL, NULL,
    '["chat_completions","generate_content","stream_generate_content","count_tokens"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.25, 1.5, 0.025, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    0.5, NULL, NULL, 1048576, 65536,
    NULL, true, true,
    'gemini-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gemini_gemini_2_5_pro_266d2f999746', 'gemini', 'gemini-2.5-pro', 'active', 'chat', 60, NULL, NULL,
    '["chat_completions","generate_content","stream_generate_content","count_tokens"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 1.25, 10, 0.125, NULL, NULL, '{}',
    200000, 2, 1.5, NULL, NULL,
    NULL, NULL, NULL, 1048576, 65536,
    NULL, true, true,
    'gemini-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gemini_gemini_2_5_flash_5bb3a7289e5c', 'gemini', 'gemini-2.5-flash', 'active', 'chat', 70, NULL, NULL,
    '["chat_completions","generate_content","stream_generate_content","count_tokens"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.3, 2.5, 0.03, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    1, NULL, NULL, 1048576, 65536,
    NULL, true, true,
    'gemini-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gemini_gemini_2_5_flash_lite_e2490a0c9987', 'gemini', 'gemini-2.5-flash-lite', 'active', 'chat', 80, NULL, NULL,
    '["chat_completions","generate_content","stream_generate_content","count_tokens"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.1, 0.4, 0.01, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    0.3, NULL, NULL, 1048576, 65536,
    NULL, true, true,
    'gemini-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_gemini_gemini_embedding_2_5c457b1283cc', 'gemini', 'gemini-embedding-2', 'active', 'embedding', 100, NULL, NULL,
    '["embed_content"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.2, NULL, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, false, true,
    'gemini-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_deepseek_deepseek_v4_flash_818049327933', 'deepseek', 'deepseek-v4-flash', 'active', 'chat', 10, '2026-06-20', NULL,
    '["chat_completions","messages"]', '[]', '[]', NULL, '[]', NULL, NULL,
    1000000, 0.14, 0.28, 0.0028, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 384000,
    NULL, true, true,
    'deepseek-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_deepseek_deepseek_v4_pro_f44510035c81', 'deepseek', 'deepseek-v4-pro', 'active', 'chat', 20, '2026-06-20', NULL,
    '["chat_completions","messages"]', '[]', '[]', NULL, '[]', NULL, NULL,
    1000000, 0.435, 0.87, 0.003625, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 384000,
    NULL, true, true,
    'deepseek-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_deepseek_deepseek_chat_12c633c4cb57', 'deepseek', 'deepseek-chat', 'active', 'chat', 50, '2025-01-20', '2026-07-24',
    '["chat_completions","messages"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.27, 1.1, 0.07, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 64000, 8000,
    NULL, true, true,
    'deepseek-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_deepseek_deepseek_reasoner_b26f63cbe6b8', 'deepseek', 'deepseek-reasoner', 'active', 'chat', 60, '2025-01-20', '2026-07-24',
    '["chat_completions","messages"]', '[]', '[]', NULL, '[]', NULL, NULL,
    NULL, 0.55, 2.19, 0.14, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 64000, 8000,
    NULL, true, true,
    'deepseek-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_5_2_4079508ea630', 'glm', 'glm-5.2', 'active', 'chat', 10, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    1000000, 1.4, 4.4, 0.26, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 128000,
    NULL, true, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_5_1_8c8cef7f6ad7', 'glm', 'glm-5.1', 'active', 'chat', 20, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    200000, 1.4, 4.4, 0.26, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 128000,
    NULL, true, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_5_2f978e8599cb', 'glm', 'glm-5', 'active', 'chat', 30, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    200000, 1, 3.2, 0.2, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 128000,
    NULL, true, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_5_turbo_5a20c6426707', 'glm', 'glm-5-turbo', 'active', 'chat', 40, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    200000, 1.2, 4, 0.24, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 128000,
    NULL, true, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_4_7_06fe0abe7510', 'glm', 'glm-4.7', 'active', 'chat', 50, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    200000, 0.6, 2.2, 0.11, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 131072,
    NULL, true, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_4_7_flashx_915a00825409', 'glm', 'glm-4.7-flashx', 'active', 'chat', 60, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    200000, 0.07, 0.4, 0.01, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 131072,
    NULL, true, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_4_7_flash_3f279bfab524', 'glm', 'glm-4.7-flash', 'active', 'chat', 70, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    200000, 0, 0, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 131072,
    NULL, false, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_4_6_ac358f6de6a3', 'glm', 'glm-4.6', 'active', 'chat', 80, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    200000, 0.6, 2.2, 0.11, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 131072,
    NULL, true, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_4_5_a4d3ca3811aa', 'glm', 'glm-4.5', 'active', 'chat', 90, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    128000, 0.6, 2.2, 0.11, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 98304,
    NULL, true, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_4_5_x_759ab58fc00c', 'glm', 'glm-4.5-x', 'active', 'chat', 100, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    128000, 2.2, 8.9, 0.45, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 98304,
    NULL, true, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_4_5_air_4f922ed8bede', 'glm', 'glm-4.5-air', 'active', 'chat', 110, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    128000, 0.2, 1.1, 0.03, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 98304,
    NULL, true, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_4_5_airx_4eea060e01f9', 'glm', 'glm-4.5-airx', 'active', 'chat', 120, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    128000, 1.1, 4.5, 0.22, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 98304,
    NULL, true, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_4_5_flash_c6b1bee2780b', 'glm', 'glm-4.5-flash', 'active', 'chat', 130, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    128000, 0, 0, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 98304,
    NULL, false, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_4_32b_0414_128k_322f59a0898f', 'glm', 'glm-4-32b-0414-128k', 'active', 'chat', 140, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    128000, 0.1, 0.1, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 16000,
    NULL, false, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_4_long_38f0ac5ef2ea', 'glm', 'glm-4-long', 'active', 'chat', 150, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    1000000, 0.14, 0.14, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 4000,
    NULL, false, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_4_flashx_250414_b1d10f3c9ba8', 'glm', 'glm-4-flashx-250414', 'active', 'chat', 160, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    128000, 0, 0, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 16000,
    NULL, false, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_4_flash_250414_1674c2fb57a0', 'glm', 'glm-4-flash-250414', 'active', 'chat', 170, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    128000, 0, 0, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 16000,
    NULL, false, true,
    'glm-pricing-snapshot', now(), now()
  ),
  (
    'provider_model_glm_glm_5_2_free_14308a730cb6', 'glm', 'glm-5.2-free', 'active', 'chat', 999, NULL, NULL,
    '["chat_completions"]', '[]', '[]', NULL, '[]', NULL, NULL,
    1000000, 0, 0, NULL, NULL, NULL, '{}',
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, 128000,
    NULL, false, false,
    'glm-pricing-snapshot', now(), now()
  )
ON CONFLICT (provider_code, model) DO UPDATE SET
  status = 'active',
  mode = EXCLUDED.mode,
  catalog_order = EXCLUDED.catalog_order,
  release_date = EXCLUDED.release_date,
  shutdown_date = EXCLUDED.shutdown_date,
  supported_api_protocols_json = EXCLUDED.supported_api_protocols_json,
  supported_service_tiers_json = EXCLUDED.supported_service_tiers_json,
  supported_reasoning_efforts_json = EXCLUDED.supported_reasoning_efforts_json,
  default_reasoning_effort = EXCLUDED.default_reasoning_effort,
  codex_supported_reasoning_levels_json = EXCLUDED.codex_supported_reasoning_levels_json,
  codex_default_reasoning_level = EXCLUDED.codex_default_reasoning_level,
  codex_multi_agent_version = EXCLUDED.codex_multi_agent_version,
  context_window_tokens = EXCLUDED.context_window_tokens,
  long_context_input_token_threshold = EXCLUDED.long_context_input_token_threshold,
  long_context_input_cost_multiplier = EXCLUDED.long_context_input_cost_multiplier,
  long_context_output_cost_multiplier = EXCLUDED.long_context_output_cost_multiplier,
  max_input_tokens = EXCLUDED.max_input_tokens,
  max_output_tokens = EXCLUDED.max_output_tokens,
  max_tokens = EXCLUDED.max_tokens,
  supports_prompt_caching = EXCLUDED.supports_prompt_caching,
  catalog_visible = EXCLUDED.catalog_visible,
  source = EXCLUDED.source,
  updated_at = EXCLUDED.updated_at;

-- +goose Down
-- no-op: provider model catalog rows are current business metadata.
