package statsagg

import (
	"context"
	"database/sql"

	_ "modernc.org/sqlite"
)

// SQLiteTestSchema 是 statsagg 测试库的最小 stats 库 schema，列定义对齐
// backend-go/projects/maintenance/internal/schema/sqlite_schema.go（只读参考，
// 仅保留被本包聚合/窗口链路读写的表）。禁止用于生产初始化。
var SQLiteTestSchema = []string{
	// usage 记录源表（USAGE_STATS_RECORD_SELECT_COLUMNS 全列）
	`CREATE TABLE IF NOT EXISTS usage_records (
		id TEXT NOT NULL,
		system_account_id TEXT NOT NULL,
		trace_id TEXT NOT NULL,
		traffic_source TEXT NOT NULL,
		client_ip TEXT,
		api_key_id TEXT,
		group_id TEXT,
		account_id TEXT,
		endpoint TEXT,
		provider_code TEXT,
		provider_protocol_profile_id TEXT,
		model TEXT,
		status_code REAL,
		success REAL NOT NULL DEFAULT 0,
		failure_attribution TEXT,
		first_token_ms REAL,
		duration_ms REAL,
		input_tokens REAL,
		output_tokens REAL,
		cache_read_tokens REAL,
		cache_read_cost_usd REAL,
		cache_write_tokens REAL,
		cache_write_1h_tokens REAL,
		cache_write_cost_usd REAL,
		thinking_tokens REAL,
		input_image_tokens REAL,
		output_image_tokens REAL,
		cost_usd REAL,
		error_code TEXT,
		error_message TEXT,
		account_owner_system_account_id TEXT,
		group_owner_system_account_id TEXT,
		account_access_type TEXT,
		group_access_type TEXT,
		account_authorization_id TEXT,
		account_authorization_source_type TEXT,
		account_authorization_source_team_id TEXT,
		group_authorization_id TEXT,
		group_authorization_source_type TEXT,
		group_authorization_source_team_id TEXT,
		created_at TEXT NOT NULL,
		PRIMARY KEY (id)
	)`,
	`CREATE TABLE IF NOT EXISTS stats_job_state (
		scope_type TEXT NOT NULL,
		scope_id TEXT NOT NULL DEFAULT '',
		job_name TEXT NOT NULL,
		cursor_created_at TEXT,
		cursor_id TEXT,
		last_success_at TEXT,
		last_error_message TEXT,
		lag_seconds REAL,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (scope_type, scope_id, job_name)
	)`,
	// usage_stats 汇总与 5 个时间桶
	statsBucketTable("usage_stats_totals", "", usageStatsAccumulatorColumns),
	statsBucketTable("usage_stats_minute", "stat_minute", usageStatsAccumulatorColumns),
	statsBucketTable("usage_stats_hourly", "stat_hour", usageStatsAccumulatorColumns),
	statsBucketTable("usage_stats_daily", "stat_date", usageStatsAccumulatorColumns),
	statsBucketTable("usage_stats_weekly", "stat_week", usageStatsAccumulatorColumns),
	statsBucketTable("usage_stats_monthly", "stat_month", usageStatsAccumulatorColumns),
	statsModelTable("usage_model_minute", "stat_minute"),
	statsModelTable("usage_model_hourly", "stat_hour"),
	statsModelTable("usage_model_daily", "stat_date"),
	statsModelTable("usage_model_weekly", "stat_week"),
	statsModelTable("usage_model_monthly", "stat_month"),
	statsErrorTable("usage_error_minute", "stat_minute"),
	statsErrorTable("usage_error_hourly", "stat_hour"),
	statsErrorTable("usage_error_daily", "stat_date"),
	statsErrorTable("usage_error_weekly", "stat_week"),
	statsErrorTable("usage_error_monthly", "stat_month"),
	statsLatencyTable("usage_latency_minute", "stat_minute"),
	statsLatencyTable("usage_latency_hourly", "stat_hour"),
	statsLatencyTable("usage_latency_daily", "stat_date"),
	statsLatencyTable("usage_latency_weekly", "stat_week"),
	statsLatencyTable("usage_latency_monthly", "stat_month"),
	// 排行快照与派生窗口
	`CREATE TABLE IF NOT EXISTS usage_rank_snapshots (
		system_account_id TEXT NOT NULL,
		scope_type TEXT NOT NULL,
		window_key TEXT NOT NULL,
		metric TEXT NOT NULL,
		snapshot_at TEXT NOT NULL,
		rank INTEGER NOT NULL,
		scope_id TEXT NOT NULL,
		metric_value REAL NOT NULL,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (scope_type, window_key, metric, system_account_id, rank)
	)`,
	`CREATE TABLE IF NOT EXISTS ai_performance_summary_windows (
		system_account_id TEXT NOT NULL,
		window_key TEXT NOT NULL,
		start_date TEXT NOT NULL,
		end_date TEXT NOT NULL,
		request_count INTEGER NOT NULL DEFAULT 0,
		duration_ms_sum INTEGER NOT NULL DEFAULT 0,
		duration_ms_count INTEGER NOT NULL DEFAULT 0,
		duration_ms_max INTEGER NOT NULL DEFAULT 0,
		first_token_ms_sum INTEGER NOT NULL DEFAULT 0,
		first_token_ms_count INTEGER NOT NULL DEFAULT 0,
		first_token_ms_max INTEGER NOT NULL DEFAULT 0,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id, window_key)
	)`,
	`CREATE TABLE IF NOT EXISTS usage_overview_summary_windows (
		system_account_id TEXT NOT NULL,
		window_key TEXT NOT NULL,
		start_date TEXT NOT NULL,
		end_date TEXT NOT NULL,
		request_count INTEGER NOT NULL DEFAULT 0,
		success_count INTEGER NOT NULL DEFAULT 0,
		error_count INTEGER NOT NULL DEFAULT 0,
		input_tokens INTEGER NOT NULL DEFAULT 0,
		output_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_cost_usd REAL NOT NULL DEFAULT 0,
		cache_write_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_1h_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_cost_usd REAL NOT NULL DEFAULT 0,
		thinking_tokens INTEGER NOT NULL DEFAULT 0,
		input_image_tokens INTEGER NOT NULL DEFAULT 0,
		output_image_tokens INTEGER NOT NULL DEFAULT 0,
		total_cost_usd REAL NOT NULL DEFAULT 0,
		duration_ms_sum INTEGER NOT NULL DEFAULT 0,
		duration_ms_count INTEGER NOT NULL DEFAULT 0,
		first_token_ms_sum INTEGER NOT NULL DEFAULT 0,
		first_token_ms_count INTEGER NOT NULL DEFAULT 0,
		last_used_at TEXT,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id, window_key)
	)`,
	`CREATE TABLE IF NOT EXISTS usage_overview_trend_windows (
		system_account_id TEXT NOT NULL,
		window_key TEXT NOT NULL,
		start_date TEXT NOT NULL,
		end_date TEXT NOT NULL,
		bucket_key TEXT NOT NULL,
		request_count INTEGER NOT NULL DEFAULT 0,
		error_count INTEGER NOT NULL DEFAULT 0,
		input_tokens INTEGER NOT NULL DEFAULT 0,
		output_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_cost_usd REAL NOT NULL DEFAULT 0,
		cache_write_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_1h_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_cost_usd REAL NOT NULL DEFAULT 0,
		thinking_tokens INTEGER NOT NULL DEFAULT 0,
		input_image_tokens INTEGER NOT NULL DEFAULT 0,
		output_image_tokens INTEGER NOT NULL DEFAULT 0,
		total_cost_usd REAL NOT NULL DEFAULT 0,
		duration_ms_sum INTEGER NOT NULL DEFAULT 0,
		duration_ms_count INTEGER NOT NULL DEFAULT 0,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id, window_key, bucket_key)
	)`,
	`CREATE TABLE IF NOT EXISTS usage_model_rank_windows (
		system_account_id TEXT NOT NULL,
		window_key TEXT NOT NULL,
		start_date TEXT NOT NULL,
		end_date TEXT NOT NULL,
		rank INTEGER NOT NULL,
		provider_code TEXT NOT NULL,
		model TEXT NOT NULL,
		request_count INTEGER NOT NULL DEFAULT 0,
		input_tokens INTEGER NOT NULL DEFAULT 0,
		output_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_cost_usd REAL NOT NULL DEFAULT 0,
		cache_write_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_1h_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_cost_usd REAL NOT NULL DEFAULT 0,
		thinking_tokens INTEGER NOT NULL DEFAULT 0,
		input_image_tokens INTEGER NOT NULL DEFAULT 0,
		output_image_tokens INTEGER NOT NULL DEFAULT 0,
		total_cost_usd REAL NOT NULL DEFAULT 0,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id, window_key, rank)
	)`,
	`CREATE TABLE IF NOT EXISTS usage_error_rank_windows (
		system_account_id TEXT NOT NULL,
		window_key TEXT NOT NULL,
		start_date TEXT NOT NULL,
		end_date TEXT NOT NULL,
		rank INTEGER NOT NULL,
		provider_code TEXT NOT NULL,
		error_code TEXT NOT NULL,
		status_code INTEGER NOT NULL DEFAULT 0,
		error_message TEXT,
		error_count INTEGER NOT NULL DEFAULT 0,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id, window_key, rank)
	)`,
	`CREATE TABLE IF NOT EXISTS usage_scope_range_windows (
		system_account_id TEXT NOT NULL,
		scope_type TEXT NOT NULL,
		scope_id TEXT NOT NULL DEFAULT '',
		start_date TEXT NOT NULL,
		end_date TEXT NOT NULL,
		request_count INTEGER NOT NULL DEFAULT 0,
		success_count INTEGER NOT NULL DEFAULT 0,
		error_count INTEGER NOT NULL DEFAULT 0,
		input_tokens INTEGER NOT NULL DEFAULT 0,
		output_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_cost_usd REAL NOT NULL DEFAULT 0,
		cache_write_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_1h_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_cost_usd REAL NOT NULL DEFAULT 0,
		thinking_tokens INTEGER NOT NULL DEFAULT 0,
		input_image_tokens INTEGER NOT NULL DEFAULT 0,
		output_image_tokens INTEGER NOT NULL DEFAULT 0,
		total_cost_usd REAL NOT NULL DEFAULT 0,
		duration_ms_sum INTEGER NOT NULL DEFAULT 0,
		duration_ms_count INTEGER NOT NULL DEFAULT 0,
		duration_ms_max INTEGER NOT NULL DEFAULT 0,
		first_token_ms_sum INTEGER NOT NULL DEFAULT 0,
		first_token_ms_count INTEGER NOT NULL DEFAULT 0,
		first_token_ms_max INTEGER NOT NULL DEFAULT 0,
		active_days INTEGER NOT NULL DEFAULT 0,
		last_used_at TEXT,
		last_error_at TEXT,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id, scope_type, scope_id, start_date, end_date)
	)`,
	// 授权摘要与范围窗口
	`CREATE TABLE IF NOT EXISTS authorization_team_usage_summary_daily (
		system_account_id TEXT NOT NULL,
		stat_date TEXT NOT NULL,
		team_filter_id TEXT NOT NULL DEFAULT '',
		resource_filter_type TEXT NOT NULL DEFAULT 'all',
		resource_filter_id TEXT NOT NULL DEFAULT '',
		row_count INTEGER NOT NULL DEFAULT 0,
		request_count INTEGER NOT NULL DEFAULT 0,
		success_count INTEGER NOT NULL DEFAULT 0,
		error_count INTEGER NOT NULL DEFAULT 0,
		input_tokens INTEGER NOT NULL DEFAULT 0,
		output_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_cost_usd REAL NOT NULL DEFAULT 0,
		cache_write_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_1h_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_cost_usd REAL NOT NULL DEFAULT 0,
		thinking_tokens INTEGER NOT NULL DEFAULT 0,
		input_image_tokens INTEGER NOT NULL DEFAULT 0,
		output_image_tokens INTEGER NOT NULL DEFAULT 0,
		total_cost_usd REAL NOT NULL DEFAULT 0,
		duration_ms_sum INTEGER NOT NULL DEFAULT 0,
		duration_ms_count INTEGER NOT NULL DEFAULT 0,
		duration_ms_max INTEGER NOT NULL DEFAULT 0,
		first_token_ms_sum INTEGER NOT NULL DEFAULT 0,
		first_token_ms_count INTEGER NOT NULL DEFAULT 0,
		first_token_ms_max INTEGER NOT NULL DEFAULT 0,
		last_used_at TEXT,
		last_error_at TEXT,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id, stat_date, team_filter_id, resource_filter_type, resource_filter_id)
	)`,
	`CREATE TABLE IF NOT EXISTS authorization_user_usage_summary_daily (
		system_account_id TEXT NOT NULL,
		stat_date TEXT NOT NULL,
		team_filter_id TEXT NOT NULL DEFAULT '',
		grantee_filter_system_account_id TEXT NOT NULL DEFAULT '',
		resource_filter_type TEXT NOT NULL DEFAULT 'all',
		resource_filter_id TEXT NOT NULL DEFAULT '',
		row_count INTEGER NOT NULL DEFAULT 0,
		request_count INTEGER NOT NULL DEFAULT 0,
		success_count INTEGER NOT NULL DEFAULT 0,
		error_count INTEGER NOT NULL DEFAULT 0,
		input_tokens INTEGER NOT NULL DEFAULT 0,
		output_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_cost_usd REAL NOT NULL DEFAULT 0,
		cache_write_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_1h_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_cost_usd REAL NOT NULL DEFAULT 0,
		thinking_tokens INTEGER NOT NULL DEFAULT 0,
		input_image_tokens INTEGER NOT NULL DEFAULT 0,
		output_image_tokens INTEGER NOT NULL DEFAULT 0,
		total_cost_usd REAL NOT NULL DEFAULT 0,
		duration_ms_sum INTEGER NOT NULL DEFAULT 0,
		duration_ms_count INTEGER NOT NULL DEFAULT 0,
		duration_ms_max INTEGER NOT NULL DEFAULT 0,
		first_token_ms_sum INTEGER NOT NULL DEFAULT 0,
		first_token_ms_count INTEGER NOT NULL DEFAULT 0,
		first_token_ms_max INTEGER NOT NULL DEFAULT 0,
		last_used_at TEXT,
		last_error_at TEXT,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id, stat_date, team_filter_id, grantee_filter_system_account_id, resource_filter_type, resource_filter_id)
	)`,
	`CREATE TABLE IF NOT EXISTS authorization_team_usage_range_windows (
		system_account_id TEXT NOT NULL,
		start_date TEXT NOT NULL,
		end_date TEXT NOT NULL,
		team_filter_id TEXT NOT NULL DEFAULT '',
		resource_filter_type TEXT NOT NULL DEFAULT 'all',
		resource_filter_id TEXT NOT NULL DEFAULT '',
		request_count INTEGER NOT NULL DEFAULT 0,
		input_tokens INTEGER NOT NULL DEFAULT 0,
		output_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_cost_usd REAL NOT NULL DEFAULT 0,
		cache_write_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_1h_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_cost_usd REAL NOT NULL DEFAULT 0,
		thinking_tokens INTEGER NOT NULL DEFAULT 0,
		input_image_tokens INTEGER NOT NULL DEFAULT 0,
		output_image_tokens INTEGER NOT NULL DEFAULT 0,
		total_cost_usd REAL NOT NULL DEFAULT 0,
		last_used_at TEXT,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id, start_date, end_date, team_filter_id, resource_filter_type, resource_filter_id)
	)`,
	`CREATE TABLE IF NOT EXISTS authorization_user_usage_range_windows (
		system_account_id TEXT NOT NULL,
		start_date TEXT NOT NULL,
		end_date TEXT NOT NULL,
		team_filter_id TEXT NOT NULL DEFAULT '',
		grantee_filter_system_account_id TEXT NOT NULL DEFAULT '',
		resource_filter_type TEXT NOT NULL DEFAULT 'all',
		resource_filter_id TEXT NOT NULL DEFAULT '',
		request_count INTEGER NOT NULL DEFAULT 0,
		input_tokens INTEGER NOT NULL DEFAULT 0,
		output_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_cost_usd REAL NOT NULL DEFAULT 0,
		cache_write_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_1h_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_cost_usd REAL NOT NULL DEFAULT 0,
		thinking_tokens INTEGER NOT NULL DEFAULT 0,
		input_image_tokens INTEGER NOT NULL DEFAULT 0,
		output_image_tokens INTEGER NOT NULL DEFAULT 0,
		total_cost_usd REAL NOT NULL DEFAULT 0,
		last_used_at TEXT,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id, start_date, end_date, team_filter_id, grantee_filter_system_account_id, resource_filter_type, resource_filter_id)
	)`,
	// 派生窗口脏标记
	`CREATE TABLE IF NOT EXISTS usage_overview_dirty_scopes (
		system_account_id TEXT NOT NULL,
		scope_id TEXT NOT NULL DEFAULT '',
		min_changed_date TEXT NOT NULL,
		generation INTEGER NOT NULL DEFAULT 0,
		first_dirty_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id)
	)`,
	`CREATE TABLE IF NOT EXISTS ai_performance_summary_dirty_system_accounts (
		system_account_id TEXT NOT NULL,
		min_stat_date TEXT NOT NULL,
		max_stat_date TEXT NOT NULL,
		generation INTEGER NOT NULL DEFAULT 0,
		first_dirty_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id)
	)`,
	`CREATE TABLE IF NOT EXISTS usage_quota_hourly_window_dirty_scopes (
		system_account_id TEXT NOT NULL,
		scope_type TEXT NOT NULL,
		scope_id TEXT NOT NULL DEFAULT '',
		generation INTEGER NOT NULL DEFAULT 0,
		first_dirty_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id, scope_type, scope_id)
	)`,
	// 账户质量/健康
	`CREATE TABLE IF NOT EXISTS account_quality_minute_stats (
		account_id TEXT NOT NULL,
		system_account_id TEXT NOT NULL,
		provider_code TEXT NOT NULL,
		stat_minute TEXT NOT NULL,
		request_count INTEGER NOT NULL DEFAULT 0,
		success_count INTEGER NOT NULL DEFAULT 0,
		error_count INTEGER NOT NULL DEFAULT 0,
		first_token_ms_sum INTEGER NOT NULL DEFAULT 0,
		first_token_ms_count INTEGER NOT NULL DEFAULT 0,
		last_sample_at TEXT,
		last_success_at TEXT,
		last_error_at TEXT,
		last_error_message TEXT,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (account_id, stat_minute)
	)`,
	`CREATE TABLE IF NOT EXISTS account_quality_dirty_accounts (
		account_id TEXT NOT NULL,
		first_dirty_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (account_id)
	)`,
	`CREATE TABLE IF NOT EXISTS account_health_hourly (
		account_id TEXT NOT NULL,
		system_account_id TEXT NOT NULL,
		provider_code TEXT NOT NULL,
		stat_hour TEXT NOT NULL,
		status TEXT NOT NULL,
		last_observed_at TEXT NOT NULL,
		last_record_id TEXT NOT NULL,
		status_code INTEGER,
		error_code TEXT,
		error_message TEXT,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (account_id, stat_hour)
	)`,
	// 系统指标
	`CREATE TABLE IF NOT EXISTS system_metrics_samples (
		sampled_at TEXT NOT NULL,
		cpu_percent REAL,
		memory_used_percent REAL,
		memory_total_bytes REAL,
		memory_free_bytes REAL,
		process_rss_bytes REAL,
		process_heap_used_bytes REAL,
		process_heap_total_bytes REAL,
		event_loop_lag_ms REAL,
		network_rx_bytes_per_sec REAL,
		network_tx_bytes_per_sec REAL,
		network_rx_total_bytes REAL,
		network_tx_total_bytes REAL,
		db_file_bytes REAL,
		stats_lag_seconds REAL,
		id TEXT NOT NULL,
		created_at TEXT NOT NULL,
		PRIMARY KEY (id)
	)`,
	`CREATE TABLE IF NOT EXISTS system_metrics_hourly (
		stat_hour TEXT NOT NULL,
		sample_count INTEGER NOT NULL DEFAULT 0,
		cpu_percent_sum REAL NOT NULL DEFAULT 0,
		cpu_percent_max REAL,
		memory_used_percent_sum REAL NOT NULL DEFAULT 0,
		memory_used_percent_max REAL,
		process_rss_bytes_sum REAL NOT NULL DEFAULT 0,
		process_rss_bytes_max REAL,
		process_heap_used_bytes_sum REAL NOT NULL DEFAULT 0,
		process_heap_used_bytes_max REAL,
		event_loop_lag_ms_sum REAL NOT NULL DEFAULT 0,
		event_loop_lag_ms_count INTEGER NOT NULL DEFAULT 0,
		event_loop_lag_ms_max REAL,
		network_rx_bytes_per_sec_sum REAL NOT NULL DEFAULT 0,
		network_rx_bytes_per_sec_max REAL,
		network_rx_bytes_per_sec_count INTEGER NOT NULL DEFAULT 0,
		network_tx_bytes_per_sec_sum REAL NOT NULL DEFAULT 0,
		network_tx_bytes_per_sec_max REAL,
		network_tx_bytes_per_sec_count INTEGER NOT NULL DEFAULT 0,
		network_rx_total_bytes_max REAL,
		network_tx_total_bytes_max REAL,
		db_file_bytes_max REAL,
		stats_lag_seconds_max REAL,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (stat_hour)
	)`,
	`CREATE TABLE IF NOT EXISTS process_event_loop_samples (
		sampled_at TEXT NOT NULL,
		process_role TEXT NOT NULL,
		process_pid REAL,
		event_loop_lag_ms REAL,
		process_rss_bytes REAL,
		process_heap_used_bytes REAL,
		process_heap_total_bytes REAL,
		process_external_bytes REAL,
		process_array_buffers_bytes REAL,
		id TEXT NOT NULL,
		created_at TEXT NOT NULL,
		PRIMARY KEY (id)
	)`,
	`CREATE TABLE IF NOT EXISTS process_event_loop_hourly (
		stat_hour TEXT NOT NULL,
		process_role TEXT NOT NULL,
		sample_count INTEGER NOT NULL DEFAULT 0,
		event_loop_lag_ms_sum REAL NOT NULL DEFAULT 0,
		event_loop_lag_ms_count INTEGER NOT NULL DEFAULT 0,
		event_loop_lag_ms_max REAL,
		process_rss_bytes_sum REAL NOT NULL DEFAULT 0,
		process_rss_bytes_max REAL,
		process_heap_used_bytes_sum REAL NOT NULL DEFAULT 0,
		process_heap_used_bytes_max REAL,
		process_heap_total_bytes_sum REAL NOT NULL DEFAULT 0,
		process_heap_total_bytes_max REAL,
		process_external_bytes_sum REAL NOT NULL DEFAULT 0,
		process_external_bytes_max REAL,
		process_array_buffers_bytes_sum REAL NOT NULL DEFAULT 0,
		process_array_buffers_bytes_max REAL,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (stat_hour, process_role)
	)`,
	`CREATE TABLE IF NOT EXISTS system_metrics_trend_windows (
		window_key TEXT NOT NULL,
		start_date TEXT NOT NULL,
		end_date TEXT NOT NULL,
		bucket_key TEXT NOT NULL,
		sample_count INTEGER NOT NULL DEFAULT 0,
		cpu_percent_sum REAL NOT NULL DEFAULT 0,
		cpu_percent_max REAL,
		memory_used_percent_sum REAL NOT NULL DEFAULT 0,
		memory_used_percent_max REAL,
		process_rss_bytes_sum REAL NOT NULL DEFAULT 0,
		process_rss_bytes_max REAL,
		process_heap_used_bytes_sum REAL NOT NULL DEFAULT 0,
		process_heap_used_bytes_max REAL,
		event_loop_lag_ms_sum REAL NOT NULL DEFAULT 0,
		event_loop_lag_ms_count INTEGER NOT NULL DEFAULT 0,
		event_loop_lag_ms_max REAL,
		network_rx_bytes_per_sec_sum REAL NOT NULL DEFAULT 0,
		network_rx_bytes_per_sec_max REAL,
		network_rx_bytes_per_sec_count INTEGER NOT NULL DEFAULT 0,
		network_tx_bytes_per_sec_sum REAL NOT NULL DEFAULT 0,
		network_tx_bytes_per_sec_max REAL,
		network_tx_bytes_per_sec_count INTEGER NOT NULL DEFAULT 0,
		network_rx_total_bytes_max REAL,
		network_tx_total_bytes_max REAL,
		db_file_bytes_max REAL,
		stats_lag_seconds_max REAL,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (window_key, bucket_key)
	)`,
	`CREATE TABLE IF NOT EXISTS process_event_loop_trend_windows (
		window_key TEXT NOT NULL,
		start_date TEXT NOT NULL,
		end_date TEXT NOT NULL,
		bucket_key TEXT NOT NULL,
		process_role TEXT NOT NULL,
		sample_count INTEGER NOT NULL DEFAULT 0,
		event_loop_lag_ms_sum REAL NOT NULL DEFAULT 0,
		event_loop_lag_ms_count INTEGER NOT NULL DEFAULT 0,
		event_loop_lag_ms_max REAL,
		process_rss_bytes_sum REAL NOT NULL DEFAULT 0,
		process_rss_bytes_max REAL,
		process_heap_used_bytes_sum REAL NOT NULL DEFAULT 0,
		process_heap_used_bytes_max REAL,
		process_heap_total_bytes_sum REAL NOT NULL DEFAULT 0,
		process_heap_total_bytes_max REAL,
		process_external_bytes_sum REAL NOT NULL DEFAULT 0,
		process_external_bytes_max REAL,
		process_array_buffers_bytes_sum REAL NOT NULL DEFAULT 0,
		process_array_buffers_bytes_max REAL,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (window_key, bucket_key, process_role)
	)`,
	// 授权查找最小表
	`CREATE TABLE IF NOT EXISTS resource_authorizations (
		id TEXT NOT NULL,
		resource_type TEXT NOT NULL,
		resource_id TEXT,
		grantee_system_account_id TEXT,
		PRIMARY KEY (id)
	)`,
	`CREATE TABLE IF NOT EXISTS accounts (
		id TEXT NOT NULL,
		system_account_id TEXT,
		authorization_instance_authorization_id TEXT,
		PRIMARY KEY (id)
	)`,
}

const usageStatsAccumulatorColumns = `
		request_count INTEGER NOT NULL DEFAULT 0,
		success_count INTEGER NOT NULL DEFAULT 0,
		error_count INTEGER NOT NULL DEFAULT 0,
		input_tokens INTEGER NOT NULL DEFAULT 0,
		output_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_cost_usd REAL NOT NULL DEFAULT 0,
		cache_write_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_1h_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_cost_usd REAL NOT NULL DEFAULT 0,
		thinking_tokens INTEGER NOT NULL DEFAULT 0,
		input_image_tokens INTEGER NOT NULL DEFAULT 0,
		output_image_tokens INTEGER NOT NULL DEFAULT 0,
		total_cost_usd REAL NOT NULL DEFAULT 0,
		duration_ms_sum INTEGER NOT NULL DEFAULT 0,
		duration_ms_count INTEGER NOT NULL DEFAULT 0,
		duration_ms_max INTEGER NOT NULL DEFAULT 0,
		first_token_ms_sum INTEGER NOT NULL DEFAULT 0,
		first_token_ms_count INTEGER NOT NULL DEFAULT 0,
		first_token_ms_max INTEGER NOT NULL DEFAULT 0,
		last_used_at TEXT,
		last_error_at TEXT,
		updated_at TEXT NOT NULL`

func statsBucketTable(tableName, timeColumn, accumulatorColumns string) string {
	keyColumns := "system_account_id TEXT NOT NULL, scope_type TEXT NOT NULL, scope_id TEXT NOT NULL DEFAULT ''"
	primaryKey := "PRIMARY KEY (system_account_id, scope_type, scope_id)"
	if timeColumn != "" {
		keyColumns += ", " + timeColumn + " TEXT NOT NULL"
		primaryKey = "PRIMARY KEY (system_account_id, scope_type, scope_id, " + timeColumn + ")"
	}
	return `CREATE TABLE IF NOT EXISTS ` + tableName + ` (` + keyColumns + `,` + accumulatorColumns + `,` + primaryKey + `)`
}

func statsModelTable(tableName, timeColumn string) string {
	return `CREATE TABLE IF NOT EXISTS ` + tableName + ` (
		system_account_id TEXT NOT NULL,
		` + timeColumn + ` TEXT NOT NULL,
		provider_code TEXT NOT NULL,
		model TEXT NOT NULL,
		request_count INTEGER NOT NULL DEFAULT 0,
		success_count INTEGER NOT NULL DEFAULT 0,
		error_count INTEGER NOT NULL DEFAULT 0,
		input_tokens INTEGER NOT NULL DEFAULT 0,
		output_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_tokens INTEGER NOT NULL DEFAULT 0,
		cache_read_cost_usd REAL NOT NULL DEFAULT 0,
		cache_write_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_1h_tokens INTEGER NOT NULL DEFAULT 0,
		cache_write_cost_usd REAL NOT NULL DEFAULT 0,
		thinking_tokens INTEGER NOT NULL DEFAULT 0,
		input_image_tokens INTEGER NOT NULL DEFAULT 0,
		output_image_tokens INTEGER NOT NULL DEFAULT 0,
		total_cost_usd REAL NOT NULL DEFAULT 0,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id, ` + timeColumn + `, provider_code, model)
	)`
}

func statsErrorTable(tableName, timeColumn string) string {
	return `CREATE TABLE IF NOT EXISTS ` + tableName + ` (
		system_account_id TEXT NOT NULL,
		` + timeColumn + ` TEXT NOT NULL,
		error_group TEXT NOT NULL,
		provider_code TEXT NOT NULL,
		error_code TEXT NOT NULL,
		status_code INTEGER NOT NULL DEFAULT 0,
		error_message TEXT,
		request_count INTEGER NOT NULL DEFAULT 0,
		error_count INTEGER NOT NULL DEFAULT 0,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id, ` + timeColumn + `, error_group, provider_code, error_code, status_code)
	)`
}

func statsLatencyTable(tableName, timeColumn string) string {
	return `CREATE TABLE IF NOT EXISTS ` + tableName + ` (
		system_account_id TEXT NOT NULL,
		scope_type TEXT NOT NULL,
		scope_id TEXT NOT NULL DEFAULT '',
		metric_type TEXT NOT NULL,
		` + timeColumn + ` TEXT NOT NULL,
		bucket_upper_bound_ms INTEGER NOT NULL,
		sample_count INTEGER NOT NULL DEFAULT 0,
		updated_at TEXT NOT NULL,
		PRIMARY KEY (system_account_id, scope_type, scope_id, metric_type, ` + timeColumn + `, bucket_upper_bound_ms)
	)`
}

// OpenSQLiteTestDB 打开一个隔离的内存/临时 SQLite 测试库并建表。
func OpenSQLiteTestDB(path string) (*sql.DB, error) {
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, err
	}
	// 串行写：SQLite 测试镜像 stats-writer 单写者契约，也让 -race 下的
	// 并发窗口竞争测试确定化。
	db.SetMaxOpenConns(1)
	ctx := context.Background()
	for _, statement := range SQLiteTestSchema {
		if _, err := db.ExecContext(ctx, statement); err != nil {
			db.Close()
			return nil, err
		}
	}
	return db, nil
}
