import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '../..')
const runPanel = readFileSync(resolve(root, 'src/views/model-checks/ModelCheckRunPanel.vue'), 'utf8')
const view = readFileSync(resolve(root, 'src/views/model-checks/ModelChecksView.vue'), 'utf8')
const detail = readFileSync(resolve(root, 'src/views/model-checks/ModelCheckRunDetailDrawer.vue'), 'utf8')
const history = readFileSync(resolve(root, 'src/views/model-checks/ModelCheckRunHistoryList.vue'), 'utf8')
const pageConfig = readFileSync(resolve(root, 'src/views/model-checks/modelCheckPageConfig.ts'), 'utf8')
const routes = readFileSync(resolve(root, '../backend/src/modules/model-checks/model-checks.routes.ts'), 'utf8')
const types = readFileSync(resolve(root, 'src/types/domain/model-checks.ts'), 'utf8')

assert(!runPanel.includes('极限长上下文'), '模型检测面板不得再暴露极限长上下文选项')
assert(!runPanel.includes('includeExtremeContext'), '模型检测面板不得再提交极限长上下文参数')
assert(!view.includes('includeExtremeContext'), '模型检测请求不得再携带极限长上下文参数')
assert(!types.includes('includeExtremeContext'), '模型检测类型不得再声明极限长上下文参数')
assert(types.includes("ModelCheckProfile = 'quick' | 'full'"), '模型检测前端类型必须支持 quick/full 两档')
assert(pageConfig.includes("defaultProfile: 'quick'"), '模型检测前端兜底必须默认快速检测')
assert(runPanel.includes('深度检测'), '模型检测面板必须提供深度检测开关')
assert(runPanel.includes('开始快速检测'), '深度检测关闭时按钮必须明确开始快速检测')
assert.match(runPanel, /class="model-checks-account-field"[\s\S]*?:disabled="accountSelectDisabled"[\s\S]*?class="model-checks-model-field"/, '快速检测仍必须允许选择目标账户')
assert.match(runPanel, /class="model-checks-comparison-field"[\s\S]*?:disabled="comparisonSelectDisabled"/, '快速检测必须禁用可信对比账户选择')
assert(view.includes("enabled ? 'full' : 'quick'"), '深度检测开关必须映射到现有 profile 字段')
assert(view.includes("form.profile === 'full' ? form.trustedComparisonAccountId?.trim() : undefined"), '快速提交必须防御性移除可信对比账户')
assert(view.includes('--profile ${form.profile}'), '模型检测终端命令必须显示实际 profile')
assert(routes.includes('profile: event.profile'), '活动检测摘要必须保留实际 profile')
assert(view.includes('applyModelCheckProfile(active.profile)'), '页面恢复后台检测时必须同步实际 profile')
assert(history.includes('modelCheckProfileText(record.profile)'), '模型检测历史必须展示快速/深度模式')
assert(detail.includes('label="检测模式"'), '模型检测详情必须展示检测模式')
assert(types.includes("interceptBaselineStatus?: 'unavailable' | 'calibration_pending' | 'active'"))
assert(detail.includes('固定开销基线'))
assert(detail.includes('待真实样本校准'))
assert(detail.includes("fixed_intercept_calibration_pending"))
assert(detail.includes("interceptStrongGateEnabled ? '已开启' : '已关闭'"))

console.log('模型可信前端契约回归通过：快速/深度开关、可信对比边界和详情模式展示符合预期')
