import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '../..')
const runPanel = readFileSync(resolve(root, 'src/views/model-checks/ModelCheckRunPanel.vue'), 'utf8')
const view = readFileSync(resolve(root, 'src/views/model-checks/ModelChecksView.vue'), 'utf8')
const detail = readFileSync(resolve(root, 'src/views/model-checks/ModelCheckRunDetailDrawer.vue'), 'utf8')
const formatters = readFileSync(resolve(root, 'src/views/model-checks/modelCheckFormatters.ts'), 'utf8')
const types = readFileSync(resolve(root, 'src/types/domain/model-checks.ts'), 'utf8')

assert(!runPanel.includes('极限长上下文'), '模型检测面板不得再暴露极限长上下文选项')
assert(!runPanel.includes('includeExtremeContext'), '模型检测面板不得再提交极限长上下文参数')
assert(!view.includes('includeExtremeContext'), '模型检测请求不得再携带极限长上下文参数')
assert(!types.includes('includeExtremeContext'), '模型检测类型不得再声明极限长上下文参数')
assert(types.includes("ModelCheckProfile = 'quick' | 'full'"), '模型检测类型必须支持 quick/full profile')
assert(runPanel.includes('深度检测'), '模型检测面板必须提供深度检测开关')
assert(runPanel.includes(':disabled="comparisonSelectDisabled"'), '可信对比账户选择必须受提交状态控制')
assert(runPanel.includes(':disabled="accountSelectDisabled"'), '目标 AI 账户选择不能被快速检测开关禁用')
assert(view.includes("profile: 'quick'"), '前端默认 profile 必须为 quick')
assert((view.match(/form\.profile = qualityPolicy\.value\.profile/g) ?? []).length >= 4, '加载、保存策略和重置表单都必须恢复用户显式保存的手动检测 profile')
assert(!view.includes('form.profile = nextOptions.defaultProfile'), '后端旧版 defaultProfile 不得把页面默认切回深度检测')
assert(view.includes('profile: form.profile'), '提交必须透传实际检测 profile')
assert(view.includes('const comparisonSelectDisabled = computed(() => submitting.value)'), '快速检测时必须允许选择可信对比账户')
assert(view.includes('trustedComparison: Boolean(trustedComparisonAccountId)'), '快速检测和深度检测都必须透传可信对比选择')
assert(!view.includes('快速检测不支持可信对比'), '前端不得再拦截快速检测的可信对比账户')
assert(types.includes("interceptBaselineStatus?: 'unavailable' | 'calibration_pending' | 'active'"))
assert(detail.includes('固定开销基线'))
assert(detail.includes('待真实样本校准'))
assert(detail.includes("fixed_intercept_calibration_pending"))
assert(detail.includes("interceptStrongGateEnabled ? '已开启' : '已关闭'"))
assert(detail.includes('visibleModelCheckChecks(props.run?.checks ?? [])'), '详情页必须过滤历史成功基础预检项')
assert(formatters.includes("check.itemType !== 'responses_basic' && check.itemType !== 'protocol_basic'"), '只允许过滤基础连通预检项')
assert(formatters.includes("check.evidenceSummary.success !== true || check.evidenceSummary.modelMismatch === true"), '失败或模型不匹配的基础预检仍必须展示')

console.log('模型可信前端契约回归通过：基础连通成功不再展示，异常诊断与可信度分项契约符合预期')
