import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { ChatRequestLifecycleEpochs } from '../../views/chat/chatRequestLifecycle'

const commandSource = readFileSync(new URL('../../views/chat/composer/chatComposerCommands.ts', import.meta.url), 'utf8')
const composerSource = readFileSync(new URL('../../views/chat/composer/AIComposer.vue', import.meta.url), 'utf8')
const viewSource = readFileSync(new URL('../../views/chat/ChatView.vue', import.meta.url), 'utf8')
const apiSource = readFileSync(new URL('../../api/domains/chat.ts', import.meta.url), 'utf8')
const typeSource = readFileSync(new URL('../../types/domain/chat.ts', import.meta.url), 'utf8')

assert.match(commandSource, /key: 'clear-input', kind: 'editor'/, '/clear-input 必须只代表编辑器动作')
assert.match(commandSource, /key: 'compact', kind: 'conversation', action: 'compact-context'/, '/compact 必须代表页面级上下文动作')
assert.match(commandSource, /key: 'clear', kind: 'conversation', action: 'clear-conversation'/, '/clear 必须代表页面级清空动作')
assert.match(composerSource, /item\.kind === 'conversation'[\s\S]{0,240}emit\('conversation-action', item\.action\)/, '会话命令必须只 emit 页面动作，不调用 editor.clear')
assert.match(composerSource, /item\.kind === 'editor'[\s\S]{0,220}insertContent\(item\.insert\)/, '编辑器命令必须保留插入语义')
assert.match(composerSource, /item\.key === 'clear-input'[\s\S]{0,80}clear\(\)/, '/clear-input 必须调用完整编辑器清理')
assert.match(apiSource, /compactContext:[\s\S]{0,300}context\/compactions/, '前端必须提供手动压缩 API')
assert.match(apiSource, /clearConversation:[\s\S]{0,220}\/clear/, '前端必须提供清空会话 API')
assert.match(typeSource, /errorCode\?: string[\s\S]{0,100}retryAt\?: string[\s\S]{0,100}attemptCount: number/, '上下文状态必须暴露安全失败字段')
assert.match(typeSource, /assistantMessageId: string[\s\S]{0,180}runnerState: 'running' \| 'missing' \| 'terminal'/, '提交状态必须暴露助手 ID 和 runner 状态')
const actionHandler = viewSource.slice(viewSource.indexOf('async function handleConversationAction'), viewSource.indexOf('function beginTurnEdit'))
assert.match(actionHandler, /window\.confirm\(/, '压缩和清空都必须先经过用户确认')
assert.match(actionHandler, /调用当前模型压缩较早上下文并产生相应用量/, '手动压缩确认必须明确模型调用会产生用量')
assert.match(actionHandler, /await chatApi\.compactContext/, '压缩确认后才能调用服务端 API')
assert.match(actionHandler, /await conversationMutationQueue\.enqueue\(conversation\.id, \(\) => chatApi\.clearConversation/, '清空确认后必须在同会话 mutation 队列中调用服务端 API')
assert.match(actionHandler, /invalidateChatConversationSyncConversation\(conversation\.systemAccountId, conversation\.id, cleared\.messageRevision\)/, '清空成功必须使该会话正在进行的旧同步失效并登记 revision 水位')
assert.match(actionHandler, /await drainChatConversationSyncConversation\(conversation\.systemAccountId, conversation\.id\)[\s\S]{0,180}await localCache\.deleteConversation/, '清空必须等待旧同步 flight 排空后再删缓存，避免迟到提交复活消息')
assert.match(actionHandler, /conversationLoadEpoch \+= 1/, '清空当前会话必须使清空前的页面加载 epoch 立即失效')
assert.match(actionHandler, /conversationMutationQueue\.enqueue\(conversation\.id, \(\) => chatApi\.clearConversation/, '清空必须与重命名和置顶共用同一会话 mutation 队列，保证后发清空最终生效')
assert.match(actionHandler, /await localCache\.deleteConversation/, '清空成功后才允许删除本地 IndexedDB 会话')
assert(actionHandler.indexOf('await chatApi.clearConversation') < actionHandler.indexOf('await localCache.deleteConversation'), '清空不得在服务端成功前清理本地缓存')
assert.match(actionHandler, /chatGenerationRuntime\.forget\(conversation\.systemAccountId, conversation\.id\)/, '清空成功必须移除该会话所有 runtime，包括尚无 turnId 的终态投影')
assert.match(actionHandler, /if \(selectedConversationId\.value === conversation\.id\) \{[\s\S]{0,500}composer\.value\?\.clear\(\)[\s\S]{0,500}messages\.value = \[\]/, '清空 A 返回时只有仍选中 A 才能清理当前编辑器和消息，不能误清已切换的 B')
assert.match(actionHandler, /catch \(error\)[\s\S]{0,180}message\.error/, '动作失败必须保留现有消息并提示错误')
assert.match(viewSource, /:disabled="generating \|\| submissionBlocked \|\| conversationActionLoading"/, '动作请求期间必须禁用编辑器避免并发操作')
assert.match(viewSource, /shouldAutomaticallyRetryPendingConfirmation\(pendingConfirmationRetryCount\)/, '待确认后台重试必须经过有界策略，耗尽后保留手动确认入口')
assert.match(viewSource, /async function refreshMessages[\s\S]{0,220}const loadEpoch = conversationLoadEpoch[\s\S]{0,500}isCurrentChatConversationLoad/, '直接消息刷新必须使用会话加载代次，清空前的迟到响应不得复活旧消息')
assert.match(viewSource, /function isRequestUiCurrent[\s\S]{0,500}request\.uiEpoch[\s\S]{0,500}conversationLoadEpoch/, '提交失败协程恢复草稿前必须验证请求所属页面代次')
assert.match(viewSource, /if \(resolution\.restoreSubmittedDraft && !rolledBackReplacement && isRequestUiCurrent\(input\.request\)\) composer\.value\?\.restore/, '清空后的旧提交失败协程不得恢复被清空草稿')
assert.match(viewSource, /if \(!isRequestUiCurrent\(failedRequest\)\) return[\s\S]{0,300}generating\.value = false[\s\S]{0,300}activeStopTarget = undefined[\s\S]{0,300}clearPendingConfirmation/, '旧失败协程必须在修改 generating、stop target 和 pending 前验证请求 lifecycle')
assert.match(viewSource, /function enterPendingConfirmation[\s\S]{0,180}!isRequestUiCurrent\(input\.request\)/, '旧请求在 clear 或新发送后不得重新写入 pending confirmation')

const lifecycle = new ChatRequestLifecycleEpochs()
const oldRequestEpoch = lifecycle.begin('conv_1')
assert.equal(lifecycle.isCurrent('conv_1', oldRequestEpoch), true)
lifecycle.invalidate('conv_1')
assert.equal(lifecycle.isCurrent('conv_1', oldRequestEpoch), false, 'clear 必须使旧失败协程失去 lifecycle 所有权')
const newRequestEpoch = lifecycle.begin('conv_1')
assert.equal(lifecycle.isCurrent('conv_1', newRequestEpoch), true)
assert.equal(lifecycle.isCurrent('conv_1', oldRequestEpoch), false, '新发送不得被旧失败协程误认为当前请求')

console.log('AI 问答手动压缩、清空和命令动作回归通过')
