import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const source = readFileSync('../frontend/src/views/chat/ChatMessageList.vue', 'utf8')
const toolSource = readFileSync('../frontend/src/views/chat/ChatToolEvent.vue', 'utf8')
const orderedProcessSource = readFileSync('../frontend/src/views/chat/ChatAssistantMessageContent.vue', 'utf8')
const generatedImageSource = readFileSync('../frontend/src/views/chat/ChatGeneratedImage.vue', 'utf8')
const generatedImageActionsSource = readFileSync('../frontend/src/views/chat/chatGeneratedImageActions.ts', 'utf8')
const markdownSource = readFileSync('../frontend/src/views/chat/ChatMarkdown.vue', 'utf8')
const thinkingSource = readFileSync('../frontend/src/views/chat/ChatThinkingIndicator.vue', 'utf8')
const errorMessageSource = readFileSync('../frontend/src/views/chat/chatErrorMessage.ts', 'utf8')
const messageProcessSource = readFileSync('../frontend/src/views/chat/chatMessageProcess.ts', 'utf8')
const chatViewSource = readFileSync('../frontend/src/views/chat/ChatView.vue', 'utf8')
const composerSource = readFileSync('../frontend/src/views/chat/composer/AIComposer.vue', 'utf8')
const userContentSource = readFileSync('../frontend/src/views/chat/ChatUserMessageContent.vue', 'utf8')

assert.match(source, /:key="messages\[item\.index\]\.turnId\s*\+\s*':'\s*\+\s*messages\[item\.index\]\.role"/, '虚拟消息行必须使用稳定 turn/role key，原位重试替换消息 id 时不能销毁正在派发事件的组件树')
assert.match(source, /message-row-user\s*\{\s*justify-content:\s*flex-end/, '用户消息必须位于右侧')
assert.match(source, /message-row-assistant\s*\{\s*justify-content:\s*flex-start/, 'AI 消息必须位于左侧')
assert.match(source, /message-bubble-user/, '用户消息需要独立气泡样式，不能和 AI 共用整行布局')
assert.doesNotMatch(source, /message-avatar|UserOutlined|RobotOutlined/, 'A 方案不能显示用户或 AI 头像')
assert.doesNotMatch(source, /message-meta|messages\[item\.index\]\.model|>我</, 'A 方案不能显示角色名、模型名或“我”')
assert.match(source, /message-bubble-user\s*\{[^}]*background:\s*#f[0-9a-f]{5}/is, '用户消息必须使用浅灰小气泡')
assert.match(source, /message-row-user\s+\.message-body\s*\{[^}]*display:\s*flex[^}]*flex-direction:\s*column[^}]*align-items:\s*flex-end/is, '用户消息 body 必须按列右对齐，不能让操作栏拉伸短气泡')
assert.match(source, /message-bubble-user\s*\{[^}]*width:\s*fit-content[^}]*max-width:\s*100%/is, '用户气泡必须按正文宽度收缩且不能溢出')
assert.match(source, /message-bubble-assistant\s*\{[^}]*background:\s*transparent[^}]*border:\s*0[^}]*box-shadow:\s*none/is, 'AI 正文必须无背景、无边框、无阴影')
assert.match(source, /message-row-assistant[\s\S]*?\.message-body\s*\{[^}]*max-width:\s*min\(100%,\s*960px\)/, 'AI 正文宽度必须为 min(100%, 960px)')
assert.match(source, /<time\s+:datetime=/, '用户操作区必须使用语义化 time 和 datetime')
assert.match(source, /aria-label="复制这条消息"/, '用户操作区必须提供中文复制按钮语义')
assert.match(source, /v-if="messages\[item\.index\]\.role === 'assistant' && messages\[item\.index\]\.status !== 'streaming' && hasAssistantActions\(messages\[item\.index\]\)"\s+class="message-actions message-actions-assistant"/, 'AI 消息底部操作区只能在终态显示')
assert.match(source, /function hasAssistantActions[\s\S]{0,300}completedGeneratedImages/, '纯图片 AI 消息也必须展示底部工具栏')
assert.match(source, /'复制 AI 回答'/, 'AI 操作区必须提供中文复制按钮语义')
assert.match(source, /'复制生成图片'/, '生成图片复制必须保留明确的中文语义')
assert.match(source, /message-actions-assistant[\s\S]{0,900}@click="copyAssistantMessage\(messages\[item\.index\]\)"/, 'AI 复制必须经过图片优先的统一处理')
assert.match(source, /<DownloadOutlined\s*\/>/, '生成图片下载必须进入消息底部工具栏')
assert.match(source, /aria-label="编辑这条消息"/, '最近可编辑消息必须提供中文编辑按钮语义')
assert.match(source, /CopyOutlined/, '复制操作必须使用图标而非文字按钮')
assert.match(source, /EditOutlined/, '编辑操作必须使用图标而非文字按钮')
assert.match(source, /messages\[item\.index\]\.id === editableMessageId/, '编辑入口只能出现在 editableMessageId')
assert.match(source, /message-actions\s*\{[^}]*min-height:\s*32px/is, 'action bar 必须始终保留固定高度，避免 hover 跳动')
assert.match(source, /message-actions-assistant\s*\{[^}]*justify-content:\s*flex-start/is, 'AI 操作区必须位于消息左下角')
assert.match(source, /\.message-row-user:hover[\s\S]{0,180}\.message-actions-controls/, '桌面 hover 必须显示用户操作')
assert.match(source, /\.message-row-user:focus-within[\s\S]{0,180}\.message-actions-controls/, '键盘 focus-within 必须显示用户操作')
assert.match(source, /\.message-row-assistant:hover[\s\S]{0,180}\.message-actions-controls/, '桌面 hover 必须显示 AI 操作')
assert.match(source, /\.message-row-assistant:focus-within[\s\S]{0,180}\.message-actions-controls/, '键盘 focus-within 必须显示 AI 操作')
assert.match(source, /@media\s*\(hover:\s*none\),\s*\(pointer:\s*coarse\)[\s\S]{0,300}\.message-actions-controls/, '粗指针设备必须常显操作')
assert.match(source, /min-width:\s*32px[^}]*min-height:\s*32px/is, '消息操作触控目标不能小于 32px')
assert.match(source, /复制失败，请稍后重试/, '复制失败必须显示中文提示')
assert.match(source, /class="message-row"[\s\S]{0,260}:class="\[`message-row-/, '必须保留虚拟 article 行')
assert.match(source, /:ref="measureElement"/, '必须保留虚拟列表测量 ref')
assert.match(source, /:data-index="item\.index"/, '必须保留虚拟列表 data-index')
assert.match(source, /:key="messages\[item\.index\]\.turnId\s*\+\s*':'\s*\+\s*messages\[item\.index\]\.role"/, '虚拟行 key 必须在同一轮替换期间保持稳定')
assert.match(source, /new ResizeObserver\(handleObservedResize\)/, '流式内容和可视区变化必须通过统一 ResizeObserver 跟随')
assert.match(source, /is-editing-turn[^\n]+opacity:\s*\.[0-9]+/, '编辑中必须淡化整轮消息')
assert.match(source, /message-status-text/, '非完成态必须放在正文下方使用低强调文字')
assert.match(source, /<ChatThinkingIndicator\s+v-if="shouldShowThinking/, '空白流式 AI 消息必须显示动态思考状态')
assert.match(source, /!message\.reasoningText\?\.trim\(\)[^\n]+!message\.toolEvents\?\.length[^\n]+!message\.contentBlocks\?\.length/, '已有正文、思考或工具过程时不得叠加空白思考状态')
assert.match(source, /message\.errorMessage \|\| chatErrorMessage\(message\.errorCode\)/, '探活确认得到的安全失败原因必须持久显示在气泡，其他失败再走公开错误码映射')
assert.match(errorMessageSource, /image_generation_not_enabled:\s*'图片生成失败：可用上游分组未开通图片生成功能'/, '图片账户全部因分组未开通而失败时必须在前端显示具体原因')
assert.match(toolSource, /tool\.status === 'failed'/, '失败工具组必须默认展开，让用户直接看到具体错误原因')
assert.match(messageProcessSource, /tool\.status === 'failed'[\s\S]{0,220}errorMessage \|\| chatErrorMessage\(errorCode\)/, '工具事件必须优先展示后端诊断详情，并兼容稳定错误码映射')
assert.match(source, /retryableMessageId/, '消息列表必须只在指定用户消息上显示重试入口')
assert.match(source, /ReloadOutlined/, '重新发送必须使用刷新图标')
assert.match(source, /emit\('retry-message',\s*messages\[item\.index\]\)/, '重试入口必须回传原用户消息')

assert.match(thinkingSource, /<span\s+role="status"\s+aria-live="polite"\s+aria-atomic="true">\{\{ label \}\}<\/span>/, '动态思考只播报状态标签')
assert.match(thinkingSource, /<time[^>]*aria-hidden="true"/, '每秒变化的计时文本必须对读屏隐藏，避免重复播报')
assert.doesNotMatch(thinkingSource, /<div class="chat-thinking"[^>]*(?:role="status"|aria-live=)/, '包含计时器的整个容器不能成为 live region')
assert.match(thinkingSource, /active:\s*'思考中'[\s\S]+checking:\s*'正在确认生成状态'[\s\S]+reconnecting:\s*'正在恢复连接'/, '动态思考必须区分活跃、确认和恢复连接状态')
assert.match(thinkingSource, /setInterval\([\s\S]{0,100}Date\.now\(\)[\s\S]{0,80}1_000/, '动态思考必须按秒更新可观察时长')
assert.match(thinkingSource, /font-variant-numeric:\s*tabular-nums/, '思考耗时必须使用等宽数字避免布局抖动')
assert.match(thinkingSource, /prefers-reduced-motion:\s*reduce/, '动态思考必须尊重减少动态效果偏好')
assert.match(errorMessageSource, /Readonly<Record<string, string>>/, '失败文案必须由封闭的公开错误码映射提供')
assert.match(errorMessageSource, /生成任务异常结束，请重新发送/, '未知内部错误不得原样泄露，必须使用安全兜底文案')

assert.match(userContentSource, /\.chat-user-image\s*\{[^}]*align-self:\s*flex-start/is, '小图必须脱离纵向 flex 容器的 stretch，保持自然尺寸')
assert.match(userContentSource, /\.chat-user-image\s*\{[^}]*max-width:\s*min\(360px,\s*100%\)[^}]*max-height:\s*320px/is, '大图仍必须受 360px 宽度和 320px 高度上限约束')
assert.match(userContentSource, /chatAssetContentUrl\(message\.conversationId,\s*block\.assetId,\s*'preview'\)/, '消息中的图片必须请求缩略图，不能直接加载原图')

assert.match(toolSource, /思考摘要/, 'reasoning 折叠必须命名为“思考摘要”')
assert.doesNotMatch(toolSource, /思考过程|JSON\.stringify|compactItem/, '过程区不能暴露“思考过程”或原始工具 JSON')
assert.match(toolSource, /相同条件重复/, '重复工具详情必须只显示重复次数')
assert.match(toolSource, /callCount/, '工具摘要必须显示聚合后的调用次数')
assert.match(toolSource, /v-if="tool\.summaries\.length \|\| tool\.duplicateCount"/, '只有存在可读详情时才允许渲染可展开 details')
assert.match(toolSource, /chat-process-summary-only/, '没有可读详情的工具只能显示不可展开摘要行')
assert.match(orderedProcessSource, /import ChatToolEvent from '\.\/ChatToolEvent\.vue'/, '实际助手消息组件必须挂载低噪工具投影，不能让聚合组件成为死代码')
assert.match(orderedProcessSource, /<ChatToolEvent[\s\S]{0,120}:message="entry\.message"/, '有序时间线中的连续工具段必须交给聚合组件渲染')
assert.match(toolSource, /generate_image:\s*'图片生成'/, '站内图像工具必须显示为“图片生成”，不能回退成通用工具调用')
assert.doesNotMatch(orderedProcessSource, /JSON\.stringify|formatItem\(/, '实际助手消息组件不得展示原始工具 JSON')
assert.match(toolSource, /manual\s*\?\?\s*isActiveToolGroup\(tool\)/, '工具组必须执行中自动展开、终态自动折叠')
assert.match(toolSource, /<summary[^>]*@click="rememberToggleIntent/, '只有用户操作工具摘要时才能记录手动展开状态')
assert.doesNotMatch(toolSource, /@toggle="rememberToggle/, '程序更新 open 不能被误判成用户手动展开')
assert.doesNotMatch(orderedProcessSource, /reuse-image|@reuse=/, '有序助手内容不得把生成图转发到输入框，连续编辑必须走普通对话')
assert.doesNotMatch(generatedImageSource, /defineEmits|EditOutlined|基于此图继续编辑|emit\('reuse'/, '生成图片卡片不得提供专用编辑或插入输入框流程')
assert.match(generatedImageSource, /chatAssetContentUrl\(props\.conversationId,\s*props\.block\.assetId,\s*'preview'\)/, '生成图片卡片必须加载 WebP 缩略图')
assert.match(generatedImageSource, /chatAssetContentUrl\(props\.conversationId,\s*props\.block\.assetId,\s*'original'\)/, '点击预览必须复用原图 URL')
assert.match(generatedImageSource, /<a-image[\s\S]{0,320}:preview="\{\s*src:\s*originalUrl\s*\}"/, '点击缩略图必须使用站内图片灯箱按需预览原图')
assert.doesNotMatch(generatedImageSource, /target="_blank"|:href="originalUrl"[\s\S]{0,180}<img/, '生成图片预览不得通过普通链接打开或改变当前会话路由')
assert.doesNotMatch(generatedImageSource, /figcaption|DownloadOutlined|chat-generated-image-download/, '图片正文不得再单独渲染下载行')
assert.match(generatedImageActionsSource, /fetch\(chatAssetContentUrl\(conversationId, assetId, 'original'\)/, '下载与复制必须复用受控原图资产')
assert.match(generatedImageActionsSource, /createObjectURL\(blob\)/, '下载必须走 blob 本地保存，避免整页打开原图 URL')
assert.match(generatedImageActionsSource, /anchor\.download = generatedImageFilename/, 'blob 下载必须写入文件名')
assert.match(generatedImageActionsSource, /new ClipboardItem\(\{ 'image\/png': png \}\)/, '复制必须写入真实图片 ClipboardItem')
assert.match(generatedImageActionsSource, /fetchGeneratedImageOriginal\(conversationId, assetId\)\.then\(convertImageToPng\)/, '复制必须以原图内容转为 PNG，不能复制 Markdown 附件文本')
assert.ok(markdownSource.includes("if (/^attachment:\\/\\//i.test(href)) return ''"), '内部 attachment Markdown 不得显示 alt 或书签名称')
assert.doesNotMatch(source, /reuse-image/, '消息列表不得暴露生成图复用事件')
assert.doesNotMatch(chatViewSource, /@reuse-image|reuseGeneratedImage|insertExistingAsset/, '聊天页不得把生成图插入输入框')
assert.match(chatViewSource, /turn\.status === 'failed'[\s\S]{0,100}errorMessage:\s*turn\.error\.message/, 'runtime 失败原因必须写入当前助手投影，不能只显示短暂 Toast')
assert.match(chatViewSource, /const unacceptedFailure = turn\.status === 'failed' && !turn\.turnId[\s\S]{0,500}if \(!turn\.reconciliationReason && !unacceptedFailure\) void refreshConversationFromSync/, '未被服务端接受的稳定失败必须保留乐观用户消息和失败助手消息，不能先用空服务端列表覆盖')
assert.doesNotMatch(composerSource, /insertExistingAsset/, '输入框不得保留仅供生成图专用复用的插入入口')
assert.match(composerSource, /chatAssetContentUrl\([^\n]+,\s*'preview'\)/, '输入框中已上传或复用图片必须请求缩略图')

console.log('AI 问答 A 方案消息布局与低噪过程展示回归通过')
