import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const source = readFileSync('../frontend/src/views/chat/ChatMessageList.vue', 'utf8')
const toolSource = readFileSync('../frontend/src/views/chat/ChatToolEvent.vue', 'utf8')
const userContentSource = readFileSync('../frontend/src/views/chat/ChatUserMessageContent.vue', 'utf8')

assert.match(source, /message-row-user\s*\{\s*justify-content:\s*flex-end/, '用户消息必须位于右侧')
assert.match(source, /message-row-assistant\s*\{\s*justify-content:\s*flex-start/, 'AI 消息必须位于左侧')
assert.match(source, /message-bubble-user/, '用户消息需要独立气泡样式，不能和 AI 共用整行布局')
assert.doesNotMatch(source, /message-avatar|UserOutlined|RobotOutlined/, 'A 方案不能显示用户或 AI 头像')
assert.doesNotMatch(source, /message-meta|messages\[item\.index\]\.model|>我</, 'A 方案不能显示角色名、模型名或“我”')
assert.match(source, /message-bubble-user\s*\{[^}]*background:\s*#f[0-9a-f]{5}/is, '用户消息必须使用浅灰小气泡')
assert.match(source, /message-row-user\s+\.message-body\s*\{[^}]*display:\s*flex[^}]*flex-direction:\s*column[^}]*align-items:\s*flex-end/is, '用户消息 body 必须按列右对齐，不能让操作栏拉伸短气泡')
assert.match(source, /message-bubble-user\s*\{[^}]*width:\s*fit-content[^}]*max-width:\s*100%/is, '用户气泡必须按正文宽度收缩且不能溢出')
assert.match(source, /message-bubble-assistant\s*\{[^}]*background:\s*transparent[^}]*border:\s*0[^}]*box-shadow:\s*none/is, 'AI 正文必须无背景、无边框、无阴影')
assert.match(source, /message-row-assistant[\s\S]*?\.message-body\s*\{[^}]*max-width:\s*min\(100%,\s*960px\)/, 'AI 正文宽度必须为 min(100%, 960px)')
assert.match(source, /<time\s+:datetime=/, '用户操作区必须使用语义化 time 和 datetime')
assert.match(source, /aria-label="复制这条消息"/, '用户操作区必须提供中文复制按钮语义')
assert.match(source, /v-if="messages\[item\.index\]\.role === 'assistant'"\s+class="message-actions message-actions-assistant"/, 'AI 消息底部必须提供独立左对齐操作区')
assert.match(source, /aria-label="复制 AI 回答"/, 'AI 操作区必须提供中文复制按钮语义')
assert.match(source, /message-actions-assistant[\s\S]{0,500}@click="copyMessage\(messages\[item\.index\]\.contentText\)"/, 'AI 复制只能读取最终回答正文')
assert.match(source, /aria-label="编辑这条消息"/, '最近可编辑消息必须提供中文编辑按钮语义')
assert.match(source, /CopyOutlined/, '复制操作必须使用图标而非文字按钮')
assert.match(source, /EditOutlined/, '编辑操作必须使用图标而非文字按钮')
assert.match(source, /messages\[item\.index\]\.id === editableMessageId/, '编辑入口只能出现在 editableMessageId')
assert.match(source, /message-actions\s*\{[^}]*min-height:\s*32px/is, 'action bar 必须始终保留固定高度，避免 hover 跳动')
assert.match(source, /message-actions-assistant\s*\{[^}]*justify-content:\s*flex-start/is, 'AI 操作区必须位于消息左下角')
assert.match(source, /\.message-row-user:hover[\s\S]{0,180}\.message-actions-controls/, '桌面 hover 必须显示用户操作')
assert.match(source, /\.message-row-user:focus-within[\s\S]{0,180}\.message-actions-controls/, '键盘 focus-within 必须显示用户操作')
assert.match(source, /\.message-row-assistant:hover[\s\S]{0,180}\.message-actions-controls/, '桌面 hover 必须显示 AI 操作')
assert.match(source, /\.message-row-assistant:focus-within[\s\S]{0,180}\.message-actions-controls/, '键盘 focus-within 必须显示 AI 操作')
assert.match(source, /@media\s*\(hover:\s*none\),\s*\(pointer:\s*coarse\)[\s\S]{0,300}\.message-actions-controls/, '粗指针设备必须常显操作')
assert.match(source, /min-width:\s*32px[^}]*min-height:\s*32px/is, '消息操作触控目标不能小于 32px')
assert.match(source, /复制失败，请稍后重试/, '复制失败必须显示中文提示')
assert.match(source, /class="message-row"[\s\S]{0,260}:class="\[`message-row-/, '必须保留虚拟 article 行')
assert.match(source, /:ref="measureElement"/, '必须保留虚拟列表测量 ref')
assert.match(source, /:data-index="item\.index"/, '必须保留虚拟列表 data-index')
assert.match(source, /:key="messages\[item\.index\]\.id"/, '虚拟行 key 必须保持消息 id')
assert.match(source, /new ResizeObserver\(handleObservedResize\)/, '流式内容和可视区变化必须通过统一 ResizeObserver 跟随')
assert.match(source, /is-editing-turn[^\n]+opacity:\s*\.[0-9]+/, '编辑中必须淡化整轮消息')
assert.match(source, /message-status-text/, '非完成态必须放在正文下方使用低强调文字')

assert.match(userContentSource, /\.chat-user-image\s*\{[^}]*align-self:\s*flex-start/is, '小图必须脱离纵向 flex 容器的 stretch，保持自然尺寸')
assert.match(userContentSource, /\.chat-user-image\s*\{[^}]*max-width:\s*min\(360px,\s*100%\)[^}]*max-height:\s*320px/is, '大图仍必须受 360px 宽度和 320px 高度上限约束')

assert.match(toolSource, /思考摘要/, 'reasoning 折叠必须命名为“思考摘要”')
assert.doesNotMatch(toolSource, /思考过程|JSON\.stringify|compactItem/, '过程区不能暴露“思考过程”或原始工具 JSON')
assert.match(toolSource, /相同条件重复/, '重复工具详情必须只显示重复次数')
assert.match(toolSource, /callCount/, '工具摘要必须显示聚合后的调用次数')
assert.match(toolSource, /v-if="tool\.summaries\.length \|\| tool\.duplicateCount"/, '只有存在可读详情时才允许渲染可展开 details')
assert.match(toolSource, /chat-process-summary-only/, '没有可读详情的工具只能显示不可展开摘要行')

console.log('AI 问答 A 方案消息布局与低噪过程展示回归通过')
