import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const view = readFileSync(new URL('../../views/providers/ProvidersView.vue', import.meta.url), 'utf8')
const api = readFileSync(new URL('../../api/domains/providers.ts', import.meta.url), 'utf8')
const resource = readFileSync(new URL('../../composables/useProviderOptionsResource.ts', import.meta.url), 'utf8')

function sourceBetween(source: string, start: string, end: string): string {
  const startIndex = source.indexOf(start)
  const endIndex = source.indexOf(end, startIndex + start.length)
  assert.notEqual(startIndex, -1, `缺少源码片段起点：${start}`)
  assert.notEqual(endIndex, -1, `缺少源码片段终点：${end}`)
  return source.slice(startIndex, endIndex)
}

assert.match(api, /listItems:.*\/providers\/list/, '首屏必须使用窄 provider list')
assert.match(api, /detail:.*\/providers\//, '模型目录必须有 provider detail API')
assert.match(resource, /listItemsOnly/, 'provider list resource 必须支持窄 DTO')
assert.match(view, /listItemsOnly: true/, '供应商页面首屏不得预加载完整 protocol profiles')
const loadProvidersSource = sourceBetween(view, 'async function loadProviders', 'async function openModelModal')
assert.match(loadProvidersSource, /providerListRequestSequence/, '供应商列表必须使用独立请求代次隔离迟到响应')
assert.match(loadProvidersSource, /isCurrentProviderListRequest/, '供应商列表写回、错误和 loading 必须校验当前身份上下文')
assert.match(view, /authState\.revision\.value[\s\S]*viewer\?\.id[\s\S]*viewer\?\.role[\s\S]*query\.viewScope[\s\S]*query\.systemAccountId[\s\S]*providerCode/, '模型请求签名必须包含 auth revision、viewer、viewScope、owner 与 provider code')
assert.match(view, /onDeactivated\([\s\S]*invalidateProviderPageRequests/, 'KeepAlive 停用必须作废模型请求')
assert.match(view, /onBeforeUnmount\(invalidateProviderPageRequests\)/, '卸载必须作废模型请求')
assert.match(view, /onActivated\([\s\S]*loadProviders\(true\)/, '重新激活必须刷新供应商列表')
assert.match(view, /watch\(\(\) => authState\.revision\.value[\s\S]*resetModelModal\(\)/, '身份切换必须关闭旧模型弹窗')
const openModelModalSource = sourceBetween(view, 'async function openModelModal', 'function handleProviderAction')
assert.doesNotMatch(openModelModalSource, /handleModelSystemAccountOptionsDropdown\(/, '打开模型目录不得模拟系统账户下拉展开')
assert.match(openModelModalSource, /await reloadActiveProviderModels\(\)/, '打开模型目录必须加载模型目录')
assert.doesNotMatch(openModelModalSource, /providers\.detail|ensureActiveProviderDetail/, '打开模型目录不得提前加载完整 provider detail')
const reloadModelsSource = sourceBetween(view, 'async function reloadActiveProviderModels', 'function modelRequestSignature')
assert.match(reloadModelsSource, /loadProviderModelCatalogResource/, '模型目录首开必须只加载必要的模型列表')
assert.doesNotMatch(reloadModelsSource, /providers\.detail|Promise\.all/, '模型目录刷新不得夹带完整 provider detail')
assert.match(reloadModelsSource, /providerModels\.value = \[\][\s\S]*modelLoading\.value = true[\s\S]*await loadProviderModelCatalogResource/, '模型 owner 或供应商作用域刷新开始时必须立即清空旧目录')
const createModelSource = sourceBetween(view, 'async function openCreateCustomModel', 'async function openEditCustomModel')
const editModelSource = sourceBetween(view, 'async function openEditCustomModel', 'async function saveCustomModel')
assert.match(createModelSource, /await ensureActiveProviderDetail\(\)/, '点击新增模型后才允许加载完整 provider detail')
assert.match(editModelSource, /await ensureActiveProviderDetail\(\)/, '点击编辑模型后才允许加载完整 provider detail')
assert.match(view, /const activeProviderDetail = ref<ProviderDefinition \| null>\(null\)/, '当前 owner 的完整 provider detail 必须与列表定义隔离存储')
assert.match(view, /activeProviderDetail\.value = detail/, '完整 provider detail 只能写入当前 owner 的独立状态')
assert.doesNotMatch(view, /activeProvider\.value = detail/, 'owner 级完整 detail 不得覆盖列表供应商定义')
assert.match(view, /function invalidateActiveProviderDetail[\s\S]*activeProviderDetail\.value = null[\s\S]*activeProviderScopedDefaultHealthCheckModel\.value = undefined/, '切换 owner 必须清除旧 owner 的完整配置与默认模型')
assert.match(view, /activeProviderDefaultHealthCheckModel = computed[\s\S]*selectedOwnerId[\s\S]*viewerId[\s\S]*: ''/, '未加载新 owner 详情时不得用上一 owner 或当前用户的默认模型标记目录')
assert.match(view, /@system-account-dropdown="handleModelSystemAccountOptionsDropdown"/, '系统账户候选必须保留真实下拉展开入口')
assert.match(view, /currentUserPrincipalSelection\(\)[\s\S]*modelSystemAccountFilterSelection\.value = currentUser/, '首次打开目录必须用登录态本地回显默认 owner，不得为标签预取 options')
assert.match(view, /onMissingSelectedIds:[\s\S]*invalidateActiveProviderDetail\(\)[\s\S]*reloadActiveProviderModels\(true\)/, '无效 owner 回退后必须作废旧详情并刷新当前模型列表')
assert.match(view, /watch\(\(\) => authState\.revision\.value[\s\S]*modelSystemAccountFilter\.value = ''[\s\S]*modelSystemAccountFilterSelection\.value = undefined/, '身份切换必须清空旧 owner，避免跨用户读写模型')
assert.match(view, /watch\(\(\) => authState\.revision\.value[\s\S]*providers\.value = \[\][\s\S]*loadProviders\(true\)/, '身份切换必须立即清空旧供应商列表，新身份加载失败时不得保留旧个性化信息')
assert.match(view, /function modelRowActions[\s\S]*if \(modelLoading\.value\) return \[\]/, '模型目录刷新期间不得保留旧行操作')
assert.match(view, /function handleModelAction[\s\S]*if \(modelLoading\.value\) return/, '模型目录刷新期间必须在事件入口拒绝旧行操作')
console.log('provider-catalog-progressive-loading-regression: ok')
