import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const view = readFileSync(new URL('../../views/providers/ProvidersView.vue', import.meta.url), 'utf8')
const api = readFileSync(new URL('../../api/domains/providers.ts', import.meta.url), 'utf8')
const resource = readFileSync(new URL('../../composables/useProviderOptionsResource.ts', import.meta.url), 'utf8')

function sourceBetween(source: string, start: string, end: string): string {
  const startIndex = source.indexOf(start)
  const endIndex = source.indexOf(end, startIndex + start.length)
  assert.notEqual(startIndex, -1, `缺少源码片段起点：${start}`)
  assert.notEqual(endIndex, -1, `缺少源码片段终点：${end}`)
  return source.slice(startIndex, endIndex)
}

assert.match(api, /listItems:.*\/providers\/list/, '首屏必须使用窄 provider list')
assert.match(api, /detail:.*\/providers\//, '供应商详情 API 必须保留给真正需要完整配置的交互')
assert.match(resource, /listItemsOnly/, 'provider list resource 必须支持窄 DTO')
assert.match(view, /listItemsOnly: true/, '供应商页面首屏不得预加载完整 protocol profiles')
const loadProvidersSource = sourceBetween(view, 'async function loadProviders', 'async function openModelModal')
assert.match(loadProvidersSource, /providerListRequestSequence/, '供应商列表必须使用独立请求代次隔离迟到响应')
assert.match(loadProvidersSource, /isCurrentProviderListRequest/, '供应商列表写回、错误和 loading 必须校验当前身份上下文')
assert.match(view, /authState\.revision\.value[\s\S]*viewer\?\.id[\s\S]*viewer\?\.role[\s\S]*query\.viewScope[\s\S]*query\.systemAccountId[\s\S]*providerCode/, '模型请求签名必须包含 auth revision、viewer、viewScope、owner 与 provider code')
assert.match(view, /onDeactivated\([\s\S]*invalidateProviderPageRequests/, 'KeepAlive 停用必须作废模型请求')
assert.match(view, /onBeforeUnmount\(invalidateProviderPageRequests\)/, '卸载必须作废模型请求')
assert.match(view, /onActivated\([\s\S]*loadProviders\(true\)/, '重新激活必须刷新供应商列表')
assert.match(view, /watch\(\(\) => authState\.revision\.value[\s\S]*resetModelModal\(\)/, '身份切换必须关闭旧模型弹窗')
const openModelModalSource = sourceBetween(view, 'async function openModelModal', 'function handleProviderAction')
assert.doesNotMatch(openModelModalSource, /handleModelSystemAccountOptionsDropdown\(/, '打开模型目录不得模拟系统账户下拉展开')
assert.match(openModelModalSource, /await reloadActiveProviderModels\(\)/, '打开模型目录必须加载模型目录')
assert.doesNotMatch(openModelModalSource, /providers\.detail|ensureActiveProviderDetail/, '打开模型目录不得提前加载完整 provider detail')
const reloadModelsSource = sourceBetween(view, 'async function reloadActiveProviderModels', 'function modelRequestSignature')
assert.match(reloadModelsSource, /loadProviderModelCatalogResource/, '模型目录首开必须只加载必要的模型列表')
assert.doesNotMatch(reloadModelsSource, /providers\.detail|Promise\.all/, '模型目录刷新不得夹带完整 provider detail')
assert.match(reloadModelsSource, /providerModels\.value = \[\][\s\S]*modelLoading\.value = true[\s\S]*await loadProviderModelCatalogResource/, '模型 owner 或供应商作用域刷新开始时必须立即清空旧目录')
const createModelSource = sourceBetween(view, 'function openCreateCustomModel', 'function openEditCustomModel')
const editModelSource = sourceBetween(view, 'function openEditCustomModel', 'async function saveCustomModel')
const saveModelSource = sourceBetween(view, 'async function saveCustomModel', 'async function deleteCustomModel')
assert.doesNotMatch(createModelSource, /await |providers\.detail|ensureActiveProviderDetail/, '打开新增模型弹窗不得发起详情请求')
assert.doesNotMatch(editModelSource, /await |providers\.detail|ensureActiveProviderDetail/, '打开编辑模型弹窗必须直接使用目录行数据')
assert.match(editModelSource, /editingCustomModelBaseline\.value = structuredClone\(baseline\)/, '编辑模型必须保存目录行形成的字段级 PATCH 基线')
assert.match(editModelSource, /editingExpectedUpdatedAt\.value = record\.updatedAt/, '编辑模型必须保存目录行版本用于并发控制')
assert.match(saveModelSource, /buildCustomModelMutationPatch\(editingCustomModelBaseline\.value, payload\)/, '模型更新必须只构造实际变化字段')
assert.match(saveModelSource, /hasCustomModelMutationChanges\(patch\)[\s\S]*没有需要保存的修改/, '模型没有变化时不得发送 PATCH')
assert.match(saveModelSource, /expectedUpdatedAt: editingExpectedUpdatedAt\.value,[\s\S]*\.\.\.patch/, '模型 PATCH 必须携带版本和差量字段')
assert.match(saveModelSource, /applyProviderModelMutationResult\([\s\S]*if \(!wasEditing\) await reloadActiveProviderModels\(true\)/, '编辑成功必须局部更新当前行，只有新增才刷新目录')
assert.doesNotMatch(view, /const activeProviderDetail|activeProviderDetail\.value|ensureActiveProviderDetail/, '模型新增和编辑不得维护或读取完整 provider detail')
assert.match(view, /activeProviderDefaultHealthCheckModel = computed[\s\S]*selectedOwnerId[\s\S]*viewerId[\s\S]*: ''/, '未加载新 owner 默认值时不得沿用上一 owner 或当前用户的默认模型标记目录')
assert.match(view, /@system-account-dropdown="handleModelSystemAccountOptionsDropdown"/, '系统账户候选必须保留真实下拉展开入口')
assert.match(view, /currentUserPrincipalSelection\(\)[\s\S]*modelSystemAccountFilterSelection\.value = currentUser/, '首次打开目录必须用登录态本地回显默认 owner，不得为标签预取 options')
assert.match(view, /onMissingSelectedIds:[\s\S]*invalidateActiveProviderDetail\(\)[\s\S]*reloadActiveProviderModels\(true\)/, '无效 owner 回退后必须作废旧默认模型状态并刷新当前模型列表')
assert.match(view, /watch\(\(\) => authState\.revision\.value[\s\S]*modelSystemAccountFilter\.value = ''[\s\S]*modelSystemAccountFilterSelection\.value = undefined/, '身份切换必须清空旧 owner，避免跨用户读写模型')
assert.match(view, /watch\(\(\) => authState\.revision\.value[\s\S]*providers\.value = \[\][\s\S]*loadProviders\(true\)/, '身份切换必须立即清空旧供应商列表，新身份加载失败时不得保留旧个性化信息')
assert.match(view, /function modelRowActions[\s\S]*if \(modelLoading\.value\) return \[\]/, '模型目录刷新期间不得保留旧行操作')
assert.match(view, /function handleModelAction[\s\S]*if \(modelLoading\.value\) return/, '模型目录刷新期间必须在事件入口拒绝旧行操作')
console.log('provider-catalog-progressive-loading-regression: ok')
