package j3bmodelcheck

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
)

// LegacyFactDisposition states the only two acceptable dispositions for a
// Node-owned J3b dataset/stats fact. A fact must either have an explicit Go
// target mapping or an explicit immutable-retention decision. It must never
// disappear from the inventory merely because no Go table exists yet.
type LegacyFactDisposition string

const (
	LegacyFactBackfill LegacyFactDisposition = "backfill"
	LegacyFactRetain   LegacyFactDisposition = "retain"
)

// LegacyJ3bFact describes one Node dataset/stats relation (or the narrowly
// scoped J3b row set inside a shared stats relation) that must be accounted
// for before a J3b owner cutover. Scope is empty for a whole table.
//
// Retain means immutable historical evidence must be retained outside a live
// Node execution path. It is not an assertion that retention has happened,
// and it is not permission to leave the Node owner active.
type LegacyJ3bFact struct {
	Name         string
	SourceSchema string
	SourceTable  string
	Scope        string
	Disposition  LegacyFactDisposition
	TargetSchema string
	TargetTable  string
	RetentionWhy string
}

// LegacyJ3bFactEvidence contains the independent evidence required to close
// an individual inventory disposition. Backfill verification must come from a
// complete bounded readback; retention verification must prove immutable
// preservation of the exact source/scope. Neither field is inferred from a
// declared inventory entry.
type LegacyJ3bFactEvidence struct {
	SourceSchema string `json:"sourceSchema"`
	SourceTable  string `json:"sourceTable"`
	Scope        string `json:"scope"`
	// Digest is the exact digest captured for the source fact (or its
	// immutable retained copy). SourceDigest/TargetDigest are optional
	// readback details; when both are present they must match.
	Digest          string `json:"digest"`
	SourceDigest    string `json:"sourceDigest"`
	TargetDigest    string `json:"targetDigest"`
	RetentionDigest string `json:"retentionDigest"`

	BackfillReadbackVerified bool `json:"backfillReadbackVerified"`
	RetentionVerified        bool `json:"retentionVerified"`

	// These flags distinguish an explicit JSON scope field (including an
	// intentionally empty scope) from a zero-value Go struct literal. Direct
	// callers remain source-compatible while CLI evidence cannot omit scope.
	evidenceFromJSON bool
	scopeSet         bool
}

// UnmarshalJSON records field presence so a CLI evidence document cannot
// silently omit an empty-but-required scope value.
func (e *LegacyJ3bFactEvidence) UnmarshalJSON(data []byte) error {
	type alias LegacyJ3bFactEvidence
	var decoded alias
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	*e = LegacyJ3bFactEvidence(decoded)
	e.evidenceFromJSON = true
	_, e.scopeSet = fields["scope"]
	return nil
}

// LegacyJ3bFactEvidenceDocument is the explicit, read-only input consumed by
// the maintenance inventory command. It contains observations only; it is
// never generated by this package and never used to perform a migration.
type LegacyJ3bFactEvidenceDocument struct {
	Facts map[string]LegacyJ3bFactEvidence `json:"facts"`
}

// LoadLegacyJ3bFactEvidence reads one complete evidence document. The caller
// supplies this path from an independently produced readback/retention
// report; an absent or malformed document is an input error, not readiness.
func LoadLegacyJ3bFactEvidence(path string) (map[string]LegacyJ3bFactEvidence, error) {
	path = strings.TrimSpace(path)
	if path == "" {
		return nil, fmt.Errorf("J3b inventory evidence requires an explicit file path")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read J3b inventory evidence file: %w", err)
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	var document LegacyJ3bFactEvidenceDocument
	if err := decoder.Decode(&document); err != nil {
		return nil, fmt.Errorf("decode J3b inventory evidence file: %w", err)
	}
	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		if err == nil {
			return nil, fmt.Errorf("decode J3b inventory evidence file: trailing JSON data")
		}
		return nil, fmt.Errorf("decode J3b inventory evidence file: %w", err)
	}
	if document.Facts == nil {
		return nil, fmt.Errorf("decode J3b inventory evidence file: facts object is required")
	}
	return document.Facts, nil
}

// LegacyJ3bFactCoverageReport is planning and evidence coverage only. Ready
// is deliberately fail-closed: it does not mean a schema was written or a
// data migration ran; it means every known Node legacy fact has a valid,
// independently verified disposition supplied by the caller.
type LegacyJ3bFactCoverageReport struct {
	Ready             bool              `json:"ready"`
	InventoryComplete bool              `json:"inventoryComplete"`
	Facts             map[string]string `json:"facts"`
}

// LegacyJ3bFactInventory is derived from Node's current dataset schema
// (model_check_*) and stats schema/read paths (model-trust.repository.ts and
// model-checks.repository.ts). The first five entries are the original
// backfill/readback set. The remaining trust projections and scoped shared
// state are intentionally visible as retention gates until a semantically
// equivalent Go storage mapping is implemented and verified.
//
// This inventory performs no DDL or DML and must not be treated as proof that
// any real backfill has completed.
var LegacyJ3bFactInventory = []LegacyJ3bFact{
	{Name: "model_check_runs", SourceSchema: "juhe_dataset", SourceTable: "model_check_runs", Disposition: LegacyFactBackfill, TargetSchema: SchemaName, TargetTable: "model_check_runs"},
	{Name: "model_check_items", SourceSchema: "juhe_dataset", SourceTable: "model_check_items", Disposition: LegacyFactBackfill, TargetSchema: SchemaName, TargetTable: "model_check_items"},
	{Name: "model_check_observations", SourceSchema: "juhe_dataset", SourceTable: "model_check_observations", Disposition: LegacyFactBackfill, TargetSchema: SchemaName, TargetTable: "model_check_observations"},
	{Name: "account_quality_health_hourly", SourceSchema: "juhe_stats", SourceTable: "account_quality_health_hourly", Disposition: LegacyFactBackfill, TargetSchema: SchemaName, TargetTable: "account_quality_health_hourly"},
	{Name: "model_token_intercept_baseline_versions", SourceSchema: "juhe_stats", SourceTable: "model_token_intercept_baseline_versions", Disposition: LegacyFactBackfill, TargetSchema: SchemaName, TargetTable: "model_token_intercept_baseline_versions"},

	{Name: "model_token_integrity_windows", SourceSchema: "juhe_stats", SourceTable: "model_token_integrity_windows", Disposition: LegacyFactRetain, RetentionWhy: "Go has no equivalent token-window projection relation yet; retain immutable historical evidence until mapped and read back."},
	{Name: "model_token_integrity_rounds", SourceSchema: "juhe_stats", SourceTable: "model_token_integrity_rounds", Disposition: LegacyFactRetain, RetentionWhy: "Go has no equivalent token-round projection relation yet; retain immutable historical evidence until mapped and read back."},
	{Name: "model_trust_window_sources", SourceSchema: "juhe_stats", SourceTable: "model_trust_window_sources", Disposition: LegacyFactRetain, RetentionWhy: "Go has no equivalent trust-source projection relation yet; retain immutable historical evidence until mapped and read back."},
	{Name: "model_identity_source_features", SourceSchema: "juhe_stats", SourceTable: "model_identity_source_features", Disposition: LegacyFactRetain, RetentionWhy: "Go has no equivalent identity-feature projection relation yet; retain immutable historical evidence until mapped and read back."},
	{Name: "model_identity_baseline_versions", SourceSchema: "juhe_stats", SourceTable: "model_identity_baseline_versions", Disposition: LegacyFactRetain, RetentionWhy: "Go has no equivalent identity-baseline relation yet; retain immutable historical evidence until mapped and read back."},
	{Name: "model_paired_similarity_windows", SourceSchema: "juhe_stats", SourceTable: "model_paired_similarity_windows", Disposition: LegacyFactRetain, RetentionWhy: "Go has no equivalent paired-similarity projection relation yet; retain immutable historical evidence until mapped and read back."},
	{Name: "model_account_trust_results", SourceSchema: "juhe_stats", SourceTable: "model_account_trust_results", Disposition: LegacyFactRetain, RetentionWhy: "Go has no equivalent trust-result projection relation yet; retain immutable historical evidence until mapped and read back."},
	{Name: "model_trust_latest_dirty_accounts", SourceSchema: "juhe_stats", SourceTable: "model_trust_latest_dirty_accounts", Disposition: LegacyFactRetain, RetentionWhy: "Go has no equivalent dirty-projection queue relation yet; retain immutable historical evidence until mapped and read back."},
	{Name: "model_trust_observation_receipts", SourceSchema: "juhe_stats", SourceTable: "model_trust_observation_receipts", Disposition: LegacyFactRetain, RetentionWhy: "Go has no equivalent aggregation receipt relation yet; retain immutable historical evidence until mapped and read back."},
	{Name: "stats_job_state:model-trust-observation-aggregation", SourceSchema: "juhe_stats", SourceTable: "stats_job_state", Scope: "scope_type=global;scope_id=;job_name=model-trust-observation-aggregation", Disposition: LegacyFactRetain, RetentionWhy: "The scoped Node aggregation cursor affects replay and retention boundaries; retain exact historical state until Go owns an equivalent cursor."},
	{Name: "background_job_leases:scheduled:model-trust-observation-aggregation:global", SourceSchema: "juhe_stats", SourceTable: "background_job_leases", Scope: "lease_key=scheduled:model-trust-observation-aggregation:global", Disposition: LegacyFactRetain, RetentionWhy: "The scoped Node aggregation lease is owner state, not disposable history; retain its final state until Go owns the corresponding coordinator."},
}

// ValidateLegacyJ3bFactCoverage checks that every known source fact has one,
// and only one, explicit disposition and that the caller supplied matching
// evidence. Missing entries, unknown entries, incomplete mappings, and absent
// retention decisions all keep Ready=false. It never opens a database or
// marks a migration complete.
func ValidateLegacyJ3bFactCoverage(inventory []LegacyJ3bFact, evidence map[string]LegacyJ3bFactEvidence) LegacyJ3bFactCoverageReport {
	report := LegacyJ3bFactCoverageReport{Facts: make(map[string]string, len(LegacyJ3bFactInventory))}
	expected := make(map[string]LegacyJ3bFact, len(LegacyJ3bFactInventory))
	for _, item := range LegacyJ3bFactInventory {
		expected[item.Name] = item
	}
	provided := make(map[string]LegacyJ3bFact, len(inventory))
	for _, item := range inventory {
		name := strings.TrimSpace(item.Name)
		if name == "" {
			report.Facts["__unnamed__"] = "inventory entry has no name"
			continue
		}
		if _, duplicate := provided[name]; duplicate {
			report.Facts[name] = "duplicate inventory entry"
			continue
		}
		provided[name] = item
	}

	complete := true
	ready := true
	for name, expectedItem := range expected {
		item, found := provided[name]
		if !found {
			report.Facts[name] = "coverage decision missing"
			complete, ready = false, false
			continue
		}
		if item.SourceSchema != expectedItem.SourceSchema || item.SourceTable != expectedItem.SourceTable || item.Scope != expectedItem.Scope {
			report.Facts[name] = "source mapping drift"
			complete, ready = false, false
			continue
		}
		if item.Disposition == LegacyFactBackfill && (strings.TrimSpace(item.TargetSchema) == "" || strings.TrimSpace(item.TargetTable) == "") {
			report.Facts[name] = "target mapping missing"
			complete, ready = false, false
			continue
		}
		if item.Disposition == LegacyFactRetain && strings.TrimSpace(item.RetentionWhy) == "" {
			report.Facts[name] = "retention decision missing"
			complete, ready = false, false
			continue
		}
		factEvidence, evidenceFound := evidence[name]
		if !evidenceFound {
			// Preserve the established disposition wording for a wholly absent
			// evidence entry while still keeping the gate closed.
			switch item.Disposition {
			case LegacyFactBackfill:
				report.Facts[name] = "backfill readback unverified"
			case LegacyFactRetain:
				report.Facts[name] = "immutable retention unverified"
			default:
				report.Facts[name] = "coverage evidence missing"
			}
			ready = false
			continue
		}
		if !legacyJ3bFactEvidenceHasIdentity(expectedItem, factEvidence) {
			report.Facts[name] = "source/scope/digest evidence missing"
			ready = false
			continue
		}
		if factEvidence.SourceSchema != expectedItem.SourceSchema || factEvidence.SourceTable != expectedItem.SourceTable || factEvidence.Scope != expectedItem.Scope {
			report.Facts[name] = "source/scope evidence drift"
			ready = false
			continue
		}
		switch item.Disposition {
		case LegacyFactBackfill:
			if !factEvidence.BackfillReadbackVerified {
				report.Facts[name] = "backfill readback unverified"
				ready = false
			} else if legacyJ3bFactEvidenceDigestMismatch(factEvidence) {
				report.Facts[name] = "backfill digest mismatch"
				ready = false
			} else {
				report.Facts[name] = "backfill readback verified"
			}
		case LegacyFactRetain:
			if !factEvidence.RetentionVerified {
				report.Facts[name] = "immutable retention unverified"
				ready = false
			} else if legacyJ3bFactEvidenceDigestMismatch(factEvidence) {
				report.Facts[name] = "immutable retention digest mismatch"
				ready = false
			} else {
				report.Facts[name] = "immutable retention verified"
			}
		default:
			report.Facts[name] = "coverage disposition missing"
			complete, ready = false, false
		}
	}
	for name := range provided {
		if _, known := expected[name]; !known {
			report.Facts[name] = "unknown inventory entry"
			complete, ready = false, false
		}
	}
	for name := range evidence {
		if _, known := expected[name]; !known {
			if _, alreadyReported := report.Facts[name]; !alreadyReported {
				report.Facts[name] = "unknown evidence entry"
			}
			complete, ready = false, false
		}
	}
	if _, unnamed := report.Facts["__unnamed__"]; unnamed {
		complete, ready = false, false
	}
	report.InventoryComplete = complete
	report.Ready = complete && ready
	return report
}

func legacyJ3bFactEvidenceHasIdentity(item LegacyJ3bFact, evidence LegacyJ3bFactEvidence) bool {
	if strings.TrimSpace(evidence.SourceSchema) == "" || strings.TrimSpace(evidence.SourceTable) == "" {
		return false
	}
	if evidence.evidenceFromJSON && !evidence.scopeSet {
		return false
	}
	return validInventoryDigest(legacyJ3bFactEvidenceDigest(evidence))
}

func legacyJ3bFactEvidenceDigest(evidence LegacyJ3bFactEvidence) string {
	for _, digest := range []string{evidence.Digest, evidence.SourceDigest, evidence.RetentionDigest, evidence.TargetDigest} {
		if value := strings.TrimSpace(digest); value != "" {
			return value
		}
	}
	return ""
}

func legacyJ3bFactEvidenceDigestMismatch(evidence LegacyJ3bFactEvidence) bool {
	source := strings.TrimSpace(evidence.SourceDigest)
	target := strings.TrimSpace(evidence.TargetDigest)
	return source != "" && target != "" && normalizeInventoryDigest(source) != normalizeInventoryDigest(target)
}

func validInventoryDigest(value string) bool {
	value = normalizeInventoryDigest(value)
	if len(value) != sha256.Size*2 {
		return false
	}
	_, err := hex.DecodeString(value)
	return err == nil
}

func normalizeInventoryDigest(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	if strings.HasPrefix(value, "sha256:") {
		value = strings.TrimPrefix(value, "sha256:")
	}
	return value
}

// LegacyJ3bFactNames returns the stable, sorted fact identifiers so command
// layers can render an auditable checklist without depending on map order.
func LegacyJ3bFactNames() []string {
	names := make([]string, 0, len(LegacyJ3bFactInventory))
	for _, item := range LegacyJ3bFactInventory {
		names = append(names, item.Name)
	}
	sort.Strings(names)
	return names
}

// FormatLegacyJ3bFactCoverageFailure makes a compact error safe for a command
// layer. The deterministic ordering keeps failed gates reproducible.
func FormatLegacyJ3bFactCoverageFailure(report LegacyJ3bFactCoverageReport) string {
	if report.Ready {
		return ""
	}
	names := make([]string, 0, len(report.Facts))
	for name := range report.Facts {
		names = append(names, name)
	}
	sort.Strings(names)
	parts := make([]string, 0, len(names))
	for _, name := range names {
		parts = append(parts, fmt.Sprintf("%s: %s", name, report.Facts[name]))
	}
	return strings.Join(parts, "; ")
}
