import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

import { shouldOfferChatImageGenerationTool } from '../../modules/chat/chat-tools.js'

const appSource = readFileSync('src/modules/system-api/system-api-app.ts', 'utf8')
const routesSource = readFileSync('src/modules/chat/chat.routes.ts', 'utf8')
assert.match(routesSource, /defaultImageModel:\s*z\.enum\(\['gpt-image-2'\]\)/, '会话更新接口必须只接受注册表中已启用的图像模型')
assert.match(routesSource, /defaultImageModel:\s*body\.defaultImageModel/, '会话更新接口必须把默认图像模型写入 repository')
const imageObservationSource = readFileSync('src/modules/chat/chat-image-observation.ts', 'utf8')
assert.match(imageObservationSource, /resolved\.blocks\?\.find\(\(block\) => block\.type === 'input_image'\)\?\.dataUrl/, '当前图片增加 assetId 文本标记后，图片说明仍必须按块类型读取 Data URL')
const modelContextSource = readFileSync('src/modules/chat/chat-model-context.ts', 'utf8')
const serverSource = readFileSync('src/server.ts', 'utf8')
const chatRepositorySource = readFileSync('src/storage/chat.repository.ts', 'utf8')
const chatAssetsRepositorySource = readFileSync('src/storage/chat-assets.repository.ts', 'utf8')
const chatAssetUploadSource = readFileSync('src/modules/chat/chat-asset-upload.ts', 'utf8')
const chatAssetInputSource = readFileSync('src/modules/chat/chat-asset-input.ts', 'utf8')
const chatContextCompactionSource = readFileSync('src/modules/chat/chat-context-compaction.ts', 'utf8')
const maintenanceCleanupSource = readFileSync('src/modules/background/maintenance-cleanup-jobs.ts', 'utf8')
const imageTransportSource = readFileSync('src/modules/chat/chat-image-generation-transport.ts', 'utf8')
const generatedArtifactSinkSource = readFileSync('src/modules/chat/tools/artifact-sink.ts', 'utf8')
const generationRunnerSource = readFileSync('src/modules/chat/chat-generation-runner.ts', 'utf8')

assert.equal(shouldOfferChatImageGenerationTool('请生成一份 Markdown 表格'), false)
assert.equal(shouldOfferChatImageGenerationTool('解释图片 Base64 处理流程'), false)
assert.equal(shouldOfferChatImageGenerationTool('请为我生成一张蓝色圆形图片'), true)
assert.equal(shouldOfferChatImageGenerationTool('直接给我生图'), true)
assert.equal(shouldOfferChatImageGenerationTool('Create an illustration of a quiet library'), true)
assert.equal(shouldOfferChatImageGenerationTool('画一只猫'), true, '中文实体绘画请求必须识别为明确位图意图')
assert.equal(shouldOfferChatImageGenerationTool('Draw a cat'), true, '英文实体绘画请求必须识别为明确位图意图')
assert.equal(shouldOfferChatImageGenerationTool('画一个系统流程图'), false, '结构图仍应交给 Mermaid/SVG，不能误触发位图工具')
assert.equal(shouldOfferChatImageGenerationTool('Draw a sequence diagram'), false, '英文结构图不能误触发位图工具')
assert.equal(shouldOfferChatImageGenerationTool('画一张架构图图片'), false, '带“图片”后缀的中文架构图仍不能误触发位图工具')
assert.equal(shouldOfferChatImageGenerationTool('生成一个流程图图片'), false, '带“图片”后缀的中文流程图仍不能误触发位图工具')
assert.equal(shouldOfferChatImageGenerationTool('Generate an architecture diagram image'), false, '带 image 后缀的英文结构图仍不能误触发位图工具')
assert.equal(shouldOfferChatImageGenerationTool('画系统架构'), false, '没有“图”后缀的系统架构仍属于结构化制图')
assert.equal(shouldOfferChatImageGenerationTool('画调用链'), false, '调用链应使用 Mermaid/SVG 等结构化制图能力')

assert.match(appSource, /my-chat.*forceSelfAccessScope.*chatRouter/, 'AI 问答路由必须挂在登录态和个人作用域之后')
for (const contract of [
  /chatRouter\.get\('\/api-keys'/,
  /chatRouter\.get\('\/conversations'/,
  /chatRouter\.post\('\/conversations'/,
  /chatRouter\.get\('\/conversations\/:conversationId\/messages'/,
  /chatRouter\.get\('\/conversations\/:conversationId\/submissions\/:clientMessageId'/,
  /chatRouter\.post\('\/conversations\/:conversationId\/context\/compactions'/,
  /chatRouter\.get\('\/conversations\/:conversationId\/context-status'/,
  /chatRouter\.post\('\/conversations\/:conversationId\/clear'/,
  /chatRouter\.get\('\/conversations\/:conversationId'/,
  /chatRouter\.patch\('\/conversations\/:conversationId'/,
  /chatRouter\.post\('\/conversations\/:conversationId\/assets'/,
  /chatRouter\.get\('\/conversations\/:conversationId\/assets\/:assetId\/content'/,
  /chatRouter\.get\('\/conversations\/:conversationId\/models'/,
  /chatRouter\.get\('\/conversations\/:conversationId\/models\/:modelId'/,
  /chatRouter\.post\('\/conversations\/:conversationId\/stream'/,
  /chatRouter\.get\('\/conversations\/:conversationId\/streams\/:turnId'/,
  /chatRouter\.post\('\/conversations\/:conversationId\/stop'/,
  /chatRouter\.delete\('\/conversations\/:conversationId'/
]) {
  assert.match(routesSource, contract)
}
assert.match(routesSource, /findChatApiKeySecretAsync/, '模型和发送必须通过聊天专用轻量查询按当前用户读取真实 API Key')
assert.doesNotMatch(routesSource, /findApiKeySecretAsync|findDefaultApiKeySecretForProviderAsync/, '聊天请求不得加载通用 API Key 用量摘要')
assert.match(routesSource, /createConversationSchema = z\.object\(\{ apiKeyId: z\.string\(\)[\s\S]{0,120}optional\(\)/, '创建会话必须允许省略 API Key')
assert.match(routesSource, /ensureChatApiKeyForSystemAccountAsync[\s\S]{0,240}findChatApiKeySecretAsync/, '省略 API Key 时必须绑定当前用户的 AI 对话专用 API Key')
const chatApiKeyRepositorySource = readFileSync('src/storage/chat-api-key.repository.ts', 'utf8')
assert.doesNotMatch(chatApiKeyRepositorySource, /usage-summary|loadApiKeyUsage|apiKeySummariesFromRows/, '聊天专用 Key 查询不得读取用量摘要或通用管理 DTO')
const modelsRouteSource = routesSource.slice(
  routesSource.indexOf("chatRouter.get('/conversations/:conversationId/models'"),
  routesSource.indexOf("chatRouter.post('/conversations/:conversationId/stream'")
)
const modelsLoadSource = routesSource.slice(
  routesSource.indexOf('async function loadOwnedChatModelListAsync'),
  routesSource.indexOf('function gatewayUrl')
)
assert.doesNotMatch(modelsRouteSource, /fetch\(gatewayUrl\('\/v1\/models'\)/, '聊天模型列表不得通过内部 HTTP 重走完整网关模型链路')
assert.doesNotMatch(modelsRouteSource, /listCachedOpenAIAccountsForGroupAsync|loadChatModelCatalogSnapshot/, '聊天模型列表不得读取分组账户快照，耗时不能随账户数量增长')
assert.match(modelsLoadSource, /listClientModelCatalogAsync[\s\S]*providerCodes/, '聊天模型列表必须按 API Key 供应商合集动态读取')
assert.match(modelsRouteSource, /listClientModelCatalogAsync[\s\S]*req\.params\.modelId/, '聊天模型能力必须按 modelId 从动态目录定点读取')
assert.doesNotMatch(modelsLoadSource, /readPublishedChatModelOptionsAsync/, '聊天列表和详情不得读取同一个完整能力快照')
assert.match(modelsRouteSource, /buildChatModelOptions/, '聊天模型能力必须按动态目录构建保守能力合集')
assert.match(modelsRouteSource, /res\.json\(ok\(modelOptions\)\)/, '聊天模型列表响应必须直接返回轻量 id 和 name 列表')
assert.match(modelsRouteSource, /chatRouter\.get\('\/conversations\/:conversationId\/models\/:modelId'[\s\S]*chat_model_not_found/, '聊天模型能力必须通过独立接口读取并保留稳定 404')
assert.match(routesSource, /buildChatTransportRequest/, 'AI 问答模型调用必须通过 Chat\/Responses transport 重新进入现有网关')
assert.doesNotMatch(routesSource, /toolsEnabled/, '聊天路由不得继续使用布尔 toolsEnabled')
assert.match(routesSource, /effectiveTools/, '聊天路由必须按实际工具集合传递 effectiveTools')
assert.match(routesSource, /createGenerateImageTool/, '图片生成必须注册为应用内部工具')
assert.match(routesSource, /ChatInternalToolOrchestrator/, 'Chat 与 Responses 必须复用同一内部工具编排器')
assert.match(routesSource, /functionCalling:\s*modelOption\.supportedTools\.includes\('function_calling'\)/, '只有模型明确支持 function calling 时才能注入内部工具')
assert.match(routesSource, /const imageGenerationEnabled\s*=\s*gatewayKey\?\.system_account_image_generation_enabled === 1[\s\S]{0,180}imageGenerationProvider\.endpoint/, '生图工具只能在用户权限开启且图像 provider 已配置时暴露')
assert.match(routesSource, /hasChatImageGenerationRoute\([\s\S]{0,120}groupIds[\s\S]{0,120}ownerId/, '生图工具暴露前必须确认 API Key 分组存在 gpt-image-2 调度账户')
assert.match(routesSource, /accounts\.some\(\(account\) => isChatImageGenerationAccount\(account\)\)/, '只有 Images 可用的 API Key 账户才能让聊天页暴露 gpt-image-2 工具')
assert.match(routesSource, /preferResponses:\s*supportsWebSearch\s*\|\|\s*imageCount\s*>\s*0/, '协议选择只应因联网或图片输入偏向 Responses，内部工具不能强绑协议')
assert.doesNotMatch(routesSource, /offersHostedImageGeneration/, '内部 generate_image 落地后不得保留旧托管生图分支')
assert.match(routesSource, /imageGeneration:[\s\S]{0,700}generateChatImage\([\s\S]{0,300}gatewayBaseUrl:\s*gatewayUrl\(''\)/, 'generate_image 必须通过现有本地网关 Images lane 执行')
assert.match(routesSource, /message\.started/, '统一 runner SSE 必须先发布 message.started')
assert.match(routesSource, /event\.toolName === 'generate_image'[\s\S]{0,400}imageEvent/, 'generate_image 完成时必须投影图片事件')
assert.match(generationRunnerSource, /type === 'output_image'/, '图片事件必须由统一 runner 投影为 output_image 块')
assert.match(generatedArtifactSinkSource, /commitChatGeneratedAsset/, '助手生成资产必须通过事务 API 写入 assistant_output 引用')
assert.match(generatedArtifactSinkSource, /commitChatGeneratedAsset\([\s\S]{0,1400}storedKeys\.length = 0/, '生成资产事务提交后必须解除对象补偿删除，后续消息终态失败不能制造破损资产')
assert.match(imageTransportSource, /n:\s*1|n = 1/, 'Images transport 必须固定 n=1')
assert.doesNotMatch(imageTransportSource, /response_format/, 'GPT Image transport 不得发送只适用于 DALL-E 的 response_format')
assert.match(imageTransportSource, /\/v1\/images\/edits[\s\S]+FormData[\s\S]+image\[\]/, 'Images transport 必须把已校验引用作为 multipart image[] 发送到 edits')
assert.match(imageTransportSource, /decodeBase64FieldToTempFile[\s\S]*field:\s*["']b64_json["']/, 'Images transport 必须通过 decoder 处理 b64_json')
assert.match(imageTransportSource, /reader\.cancel\(\)/, 'Images 响应提前失败时必须取消上游 body reader')
assert.match(routesSource, /readableStreamChunks[\s\S]{0,600}reader\.cancel\(\)/, 'Chat/Responses 上游流提前退出时必须取消 body reader')
assert.match(routesSource, /collectChatResponsesSse\([\s\S]{0,4200}maxMessageBytes,\s*runtimeConfig\.chat\.upstreamSseMaxEvents/, 'Responses collector 必须显式接收运行时 SSE 事件预算')
assert.match(routesSource, /listClientModelCatalogAsync[\s\S]{0,1200}defaultModel/, '新会话必须从动态模型目录第一项取得默认模型')
assert.match(routesSource, /chatConversationResponse\(conversation, defaultModel\)/, '创建响应必须携带轻量默认模型引用')
assert.match(routesSource, /collectChatResponsesSse\([\s\S]{0,1400}maxMessageBytes,\s*runtimeConfig\.chat\.upstreamSseMaxEvents\s*\)/, 'Responses collector 必须显式接收运行时 SSE 事件预算')
assert.match(routesSource, /collectOpenAIChatSse\([\s\S]{0,500}runtimeConfig\.chat\.upstreamSseMaxEvents\s*\)/, 'Chat Completions collector 必须显式接收同一运行时 SSE 事件预算')
const streamRouteIndex = routesSource.indexOf("chatRouter.post('/conversations/:conversationId/stream'")
const duplicateLookupIndex = routesSource.indexOf('await findChatTurnByClientMessageId', streamRouteIndex)
const turnLimitGuardIndex = routesSource.indexOf("throw new ChatConflictError('chat_turn_limit_exceeded')", duplicateLookupIndex)
const gatewayValidationIndex = routesSource.indexOf('const gatewayKey = await validateGatewayApiKeyAsync', streamRouteIndex)
const acceptTurnIndex = routesSource.indexOf('accepted = await acceptChatTurn', streamRouteIndex)
const contextReadIndex = routesSource.indexOf('await loadChatTransportHistory', streamRouteIndex)
const preparationClaimIndex = routesSource.indexOf('claimActiveChatPreparation', streamRouteIndex)
const conversationActionGuardIndex = routesSource.indexOf('const activeAction = getActiveChatConversationAction', streamRouteIndex)
const ownershipLookupIndex = routesSource.indexOf('await getChatConversation(client', streamRouteIndex)
const responseCloseIndex = routesSource.indexOf("res.once('close'", streamRouteIndex)
const beginAcceptanceIndex = routesSource.indexOf('beginActiveChatAcceptance', streamRouteIndex)
const transportBuildIndex = routesSource.indexOf('buildChatTransportRequest({', contextReadIndex)
const registryStartIndex = routesSource.indexOf('registry.start(runner)', acceptTurnIndex)
const upstreamFetchIndex = routesSource.indexOf('const upstream = await fetch')
assert(ownershipLookupIndex >= 0 && ownershipLookupIndex < preparationClaimIndex, '发送必须先验证会话归属再占用准备门禁，其他用户不能阻塞目标会话')
assert(duplicateLookupIndex >= 0 && duplicateLookupIndex < preparationClaimIndex, '重复 clientMessageId 必须优先于并发准备门禁返回稳定幂等结果')
assert(turnLimitGuardIndex > duplicateLookupIndex && turnLimitGuardIndex < preparationClaimIndex, '普通发送必须在幂等检查后、准备占用及所有昂贵工作前拒绝超出轮次上限')
assert(preparationClaimIndex >= 0 && preparationClaimIndex < gatewayValidationIndex, 'clientMessageId 准备状态必须在昂贵网关校验和长预检前登记，供断线对账查询')
assert(conversationActionGuardIndex >= 0 && conversationActionGuardIndex < preparationClaimIndex, '发送必须在占用 preparation 前拒绝会话级动作')
assert(responseCloseIndex >= 0 && responseCloseIndex < ownershipLookupIndex, '客户端断开监听必须在首个数据库等待前安装，不能丢失早期 close 事件')
assert(beginAcceptanceIndex >= 0 && beginAcceptanceIndex < acceptTurnIndex, '准备到接受必须先做原子取消检查')
assert.match(routesSource, /finally \{[\s\S]{0,180}deleteActiveChatPreparationIfMatches/, '发送请求无论成功失败都必须释放会话准备占用')
assert.match(routesSource, /state: 'accepted'[\s\S]{0,160}assistantStatus/, '提交状态接口必须返回 accepted 的 turnId 和助手状态')
assert.match(routesSource, /state: preparation \? 'preparing' : 'not_found'/, '提交状态接口必须区分 preparing 与权威 not_found')
assert.match(routesSource, /assistantMessageId:/, '提交状态接口必须返回助手 ID')
assert.match(routesSource, /const runnerState\s*=/, '提交状态接口必须计算 runner 状态')
assert.match(routesSource, /serverTime/, '提交状态接口必须返回服务端时间')
assert.match(routesSource, /context-status'[\s\S]{0,1200}errorCode:[\s\S]{0,120}retryAt:[\s\S]{0,120}attemptCount/, '上下文状态必须返回失败码、重试时间和尝试次数')
assert.match(routesSource, /compactBodySchema[\s\S]{0,160}strict\(\)/, '手动压缩 body 必须严格限制为模型字段')
assert.match(routesSource, /clearBodySchema[\s\S]{0,120}strict\(\)/, '清空 body 必须严格拒绝未知字段')
assert.match(chatContextCompactionSource, /startChatContextCompaction[\s\S]{0,500}acceptance/, '手动压缩必须先返回持久化接受边界')
assert.match(chatRepositorySource, /clearChatConversation/, '清空路由必须复用原子 clear 事务')
assert.match(routesSource, /claimActiveChatConversationAction[\s\S]{0,260}kind:\s*'compacting'/, '手动压缩必须先占用会话动作门禁')
assert.match(routesSource, /claimActiveChatConversationAction[\s\S]{0,260}kind:\s*'clearing'/, '清空必须在请求期间占用会话动作门禁')
assert.match(routesSource, /getActiveChatPreparationForConversation/, '压缩和清空必须拒绝当前会话的 active preparation')
assert.match(routesSource, /const stopBodySchema[\s\S]{0,400}turnId:[\s\S]{0,200}clientMessageId:/, 'stop 必须要求期望 turnId 或 clientMessageId，不能按会话盲停')
assert.match(routesSource, /registry\.get\(\{ ownerId:[\s\S]{0,180}turnId: expectedTurnId/, '内存流 stop 必须以 owner、conversation、turn 精确查找 runner')
assert.match(routesSource, /cancelActiveChatPreparation\([\s\S]{0,300}clientMessageId: body\.clientMessageId/, 'preparing stop 必须按 clientMessageId 精确取消')
assert.match(routesSource, /cancelActiveChatTurnIfMatches/, '服务重启后的孤立 streaming 轮次必须通过 repository 原子条件取消')
assert.match(routesSource, /validateFixedChatInputBudget/, '固定输入预算必须在接受轮次前独立预检')
assert(contextReadIndex >= 0 && contextReadIndex < acceptTurnIndex, '检查点上下文和硬水位必须在接受轮次前完成，避免超限消息半成功')
assert(contextReadIndex < transportBuildIndex && transportBuildIndex < acceptTurnIndex, '最终 transport 与请求体字节预检必须在消息落库前完成')
assert(acceptTurnIndex < registryStartIndex, 'accept 完成后必须同步登记 runner')
assert.match(routesSource, /chatGenerationRegistry/, 'chat 路由必须复用服务端 generation registry')
assert.match(routesSource, /failInterruptedChatTurnIfMatches/, 'DB active 但 runner 缺失时必须原子收口为中断失败')
assert.match(routesSource, /res\.once\('close'[\s\S]{0,100}if \(!accepted\) controller\?\.abort\(\)/, 'response close 只能在 accept 前取消 preparation controller')
assert.match(routesSource, /compactChatContextOnce/, '硬水位必须在发送前执行有界压缩')
assert.match(routesSource, /error instanceof ChatModelContextError[\s\S]{0,120}error\.reason !== 'load_limit'[\s\S]{0,300}compactChatContextOnce/, '超过本地 512 条装载上限时必须先分页压缩再重试，不能直接卡死会话')
assert.match(routesSource, /Buffer\.byteLength\(serializedTransportBody[\s\S]{0,300}!contextCompacted[\s\S]{0,300}compactChatContextOnce/, '请求体超过内部字节阈值时必须先尝试压缩历史')
assert.match(routesSource, /preparedContext\.unresolvedAssetIds\.length[\s\S]{0,700}历史图片语义说明仍在生成/, '历史图片说明未完成时必须短暂等待后拒绝本轮，不能回灌历史 Base64')
assert.match(routesSource, /targets:\s*preparedContext\.unresolvedAssets/, '历史图片说明调度必须携带上下文读取时捕获的轮次和消息身份')
assert.match(routesSource, /const observationTurnId = accepted!?\.turnId[\s\S]{0,120}const observationMessageId = accepted!?\.userMessage\.id[\s\S]{0,500}expectedTurnId:\s*observationTurnId[\s\S]{0,240}expectedMessageId:\s*observationMessageId/, '当前轮图片说明调度必须绑定已接受的用户轮次和消息')
assert.match(modelContextSource, /expectedTurnId:\s*message\.turnId[\s\S]{0,120}expectedMessageId:\s*message\.id/, '历史图片说明目标必须绑定产生该图片块的原用户消息')
assert.match(imageObservationSource, /claimChatAssetObservation[\s\S]{0,260}expectedTurnId:\s*target\.expectedTurnId[\s\S]{0,120}expectedMessageId:\s*target\.expectedMessageId/, '图片说明 claim 必须原子校验调度时捕获的轮次和消息身份')
assert.match(routesSource, /scheduleChatContextCompaction/, '软水位必须异步调度压缩')
assert.match(routesSource, /maxInternalChatRequestBytes/, '模型请求必须在内部网关前实测 JSON 字节')
assert.match(routesSource, /chat_image_not_supported/, 'Chat-only 图片输入必须返回稳定错误码')
assert.match(routesSource, /resolveChatBudgetContent/, '上下文预算必须按 transport 实际发送文本计算')
assert.match(routesSource, /recordChatContextUsage/, '完成响应后必须保存真实或明确标记的估算上下文用量')
assert.match(routesSource, /replaceTurnId:\s*z\.string\(\)\.trim\(\)\.min\(1\)\.max\(100\)\.optional\(\)/, 'stream body 必须接受最多 100 字符的 replaceTurnId')
assert.match(routesSource, /beforeSequenceNo:[\s\S]*max\(2_147_483_647/, '消息游标必须在 HTTP schema 层限制为 PostgreSQL int4')
assert.match(routesSource, /afterSequenceNo:[\s\S]*max\(2_147_483_647/, '增量消息游标必须在 HTTP schema 层限制为 PostgreSQL int4')
assert.match(routesSource, /fromSequenceNo:[\s\S]*max\(2_147_483_647/, '包含式刷新游标必须在 HTTP schema 层限制为 PostgreSQL int4')
assert.match(routesSource, /messagesQuerySchema[\s\S]{0,900}length <= 1, '消息游标只能指定一个'/, '消息查询必须在 HTTP schema 层拒绝多个游标')
assert.match(routesSource, /limit:[\s\S]{0,120}max\(100\)\.default\(100\)/, '消息列表无显式 limit 时必须读取最近 100 条')
assert.match(routesSource, /syncQuerySchema[\s\S]{0,300}Number\.MAX_SAFE_INTEGER/, 'knownRevision 必须限制为非负安全整数')
assert.match(routesSource, /chatRouter\.get\('\/conversations\/:conversationId\/sync'[\s\S]{0,1200}getChatConversationSyncHead/, '同步接口必须读取 repository 轻量同步 head')
assert.match(routesSource, /unchanged:\s*query\.knownRevision === head\.messageRevision/, '仅 knownRevision 与服务端 revision 相等时才能返回 unchanged')
assert.doesNotMatch(routesSource.match(/chatRouter\.get\('\/conversations\/:conversationId\/sync'[\s\S]*?\n}\)/)?.[0] ?? '', /contentText|contentBlocks|reasoning|tool_call/, '同步接口不得返回消息正文或工具 payload')
assert.match(routesSource, /contentBlocks:\s*body\.contentBlocks/, 'acceptChatTurn 必须保存实际输入块类型标记')
assert.match(routesSource, /type:\s*z\.literal\('input_image'\),\s*assetId:/, '图片输入 HTTP 契约只能接受资产 ID，不能接受 Data URL')
assert.match(routesSource, /filter\(\(block\) => block\.type === 'input_image'\)\.length <= 5[\s\S]{0,80}最多粘贴 5 张图片/, '伪造 contentBlocks 时后端 HTTP 契约必须限制单条消息最多 5 张图片')
assert.match(chatAssetInputSource, /maxChatImagesPerTurn = 5/, '资产解析边界必须独立限制单条消息最多 5 张图片')
assert.match(chatAssetsRepositorySource, /maxChatAssetsPerMessage = 5/, '消息资产绑定边界必须独立限制单条消息最多 5 张图片')
assert.doesNotMatch(routesSource, /type:\s*z\.literal\('input_image'\),\s*dataUrl:/, '图片 Data URL 不得进入 stream JSON 契约')
assert.match(routesSource, /uploadChatAsset\(\{[\s\S]*req,[\s\S]*conversationId:\s*conversation\.id/, '图片上传必须使用所属会话和当前登录用户写入资产')
assert.match(routesSource, /openChatAssetObject\(asset\.storageKey,[\s\S]{0,120}chatAssetGeneratedMaxBytes|sourceKind[\s\S]{0,160}chatAssetGeneratedMaxBytes/, '生成资产读取必须显式传入 16 MiB 上限')
assert.match(routesSource, /Cache-Control',\s*'private, max-age=86400, immutable'/, '版本化图片 URL 必须使用私有不可变缓存策略')
assert.match(routesSource, /ETag'[\s\S]{0,300}requestEtagMatches[\s\S]{0,120}status\(304\)/, '图片内容响应必须通过分版本 SHA-256 ETag 支持条件请求')
assert.match(routesSource, /query\.variant === 'preview'[\s\S]{0,300}previewStorageKey/, 'preview 查询必须优先读取独立缩略图对象')
assert.match(routesSource, /replaceTurnId:\s*body\.replaceTurnId/, 'acceptChatTurn 必须收到 replaceTurnId')
assert.match(routesSource, /maxTurnsPerConversation:\s*runtimeConfig\.chat\.maxTurnsPerConversation/, 'acceptChatTurn 必须收到运行时轮次上限并做最终竞态门禁')
assert.match(routesSource, /retentionDays:\s*runtimeConfig\.chat\.retentionDays/, 'acceptChatTurn 必须收到统一聊天保留天数')
assert.match(routesSource, /maxConversationsPerUser:\s*runtimeConfig\.chat\.maxConversationsPerUser/, '创建会话必须收到运行时会话上限')
assert.match(routesSource, /userTurnLimit:\s*runtimeConfig\.chat\.maxTurnsPerConversation/, '所有会话 API 响应必须附加当前运行时轮次上限')
assert.match(routesSource, /error instanceof ChatConflictError[\s\S]*status\(409\)[\s\S]*code: error\.code/, 'chat_replace_conflict 必须稳定映射到 HTTP 409 与机器码')
assert.doesNotMatch(chatRepositorySource, /config\/runtime|runtimeConfig/, '聊天 repository 不得读取全局运行配置，策略参数必须由调用方显式传入')
assert.doesNotMatch(chatAssetsRepositorySource, /config\/runtime|runtimeConfig/, '聊天资产 repository 不得读取全局运行配置，保留期必须由调用方显式传入')
assert.match(chatRepositorySource, /maxConversationsPerUser:\s*number/, 'createChatConversation 的会话上限参数必须必填')
assert.match(chatRepositorySource, /retentionDays:\s*number[\s\S]{0,100}maxTurnsPerConversation:\s*number/, 'acceptChatTurn 的保留期与轮次上限参数必须必填')
assert.match(chatAssetsRepositorySource, /retentionDays:\s*number/, '聊天资产创建和绑定入口的保留期必须必填')
assert.match(chatAssetUploadSource, /retentionDays:\s*number/, '上传入口必须显式接收保留期')
assert.match(chatAssetUploadSource, /createChatAsset\([\s\S]{0,800}retentionDays:\s*input\.retentionDays/, '上传入口必须把保留期传给资产 repository')
assert.doesNotMatch(chatRepositorySource, /user_turn_count\s*\?\?\s*0/, 'NOT NULL 用户轮次计数不得回退为 0')
assert.match(chatRepositorySource, /function normalizedChatUserTurnCount\(value: unknown\): number/, '用户轮次计数必须使用集中规范化 helper')
assert.match(chatRepositorySource, /Number\.isSafeInteger\(count\)/, '用户轮次计数 helper 必须校验安全整数')
assert.match(chatRepositorySource, /throw new Error\('聊天会话轮次计数无效'\)/, '用户轮次计数无效时必须 fail-fast')
assert.doesNotMatch(chatContextCompactionSource, /7\s*\*\s*86_400_000|earliestExpiresAt\s*\?\?\s*new Date/, 'checkpoint 不得在缺少来源到期时间时回退加 7 天')
assert.match(chatContextCompactionSource, /if \(!earliestExpiresAt\) throw new Error\('chat_context_source_expiry_missing'\)/, 'checkpoint 来源到期时间缺失时必须 fail-fast')
assert.doesNotMatch(maintenanceCleanupSource, /AI 问答 7 天保留清理/, 'AI 问答维护日志不得写死 7 天')
assert.doesNotMatch(routesSource, /baseUrl|base_url|proxyProfile/, 'AI 问答路由不能直接拼上游 Base URL 或代理配置')
assert.match(serverSource, /chatHttpProxy = createDbServiceHttpProxy\(\{ maxInFlight: 128, timeoutMs: 15 \* 60_000 \}\)/, 'AI 问答长连接必须使用独立代理池和 15 分钟超时')
assert(serverSource.indexOf('app.use(`${systemApiPrefix}/my-chat`, chatHttpProxy)') < serverSource.indexOf('app.use(systemApiPrefix, dbServiceHttpProxy)'), 'AI 问答独立代理必须挂在通用 System API 代理之前')

console.log('AI 问答路由契约回归通过')
