import type {
  AccountExportResult,
  AccountDefaultTestModelResult,
  AccountImportOptions,
  AccountImportResult,
  AccountListResult,
  AccountOptionSummary,
  AccountSummary,
  AccountTagSummary,
  AccountTestSession,
  AccountTestSessionDetail,
  AccountTestTask,
  AccountTrafficMigrationResult,
  AccountTrafficMigrationSourceStatus
} from '@/types/domain'
import type {
  AccountDraftTestPayload,
  AccountExportPayload,
  AccountListParams,
  AccountOptionParams,
  AccountTestPayload,
  ListParams,
  RequestControlOptions
} from '../contracts'
import { http, unwrap } from '../http'
import { accountListParams, accountOptionsParams } from '../params'

export const accountsApi = {
  list: (params?: AccountListParams) => unwrap<AccountListResult>(http.get('/accounts', { params: accountListParams(params) })),
  options: (params?: AccountOptionParams) => unwrap<AccountOptionSummary[]>(http.get('/accounts/options', { params: accountOptionsParams(params) })),
  tags: (params?: ListParams) => unwrap<AccountTagSummary[]>(http.get('/accounts/tags', { params })),
  deleteTag: (id: string, params?: ListParams) => http.delete(`/accounts/tags/${id}`, { params }),
  detail: (id: string, params?: ListParams) => unwrap<AccountSummary>(http.get(`/accounts/${id}`, { params })),
  editBasicDetail: (id: string, params?: ListParams) => unwrap<AccountSummary>(http.get(`/accounts/${id}/edit-basic`, { params })),
  advancedDetail: (id: string, params?: ListParams) => unwrap<AccountSummary>(http.get(`/accounts/${id}/advanced`, { params })),
  export: (payload: AccountExportPayload, params?: ListParams) => unwrap<AccountExportResult>(http.post('/accounts/export', payload, { params })),
  importPreview: (payload: { data: unknown; options?: AccountImportOptions }, params?: ListParams) => unwrap<AccountImportResult>(http.post('/accounts/import/preview', payload, { params })),
  importConfirm: (payload: { data: unknown; options?: AccountImportOptions }, params?: ListParams) => unwrap<AccountImportResult>(http.post('/accounts/import/confirm', payload, { params })),
  create: (payload: Record<string, unknown>, params?: ListParams) => unwrap<AccountSummary>(http.post('/accounts', payload, { params })),
  update: (id: string, payload: Record<string, unknown>, params?: ListParams) => unwrap<AccountSummary>(http.patch(`/accounts/${id}`, payload, { params })),
  updateTags: (id: string, payload: { tags: string[] }, params?: ListParams) => unwrap<AccountSummary>(http.patch(`/accounts/${id}/tags`, payload, { params })),
  updateAuthorizedDispatch: (id: string, payload: { status?: 'active' | 'disabled'; priority?: number; superPriorityEnabled?: boolean; fallbackEnabled?: boolean; clearFailureState?: boolean }, params?: ListParams) => unwrap<AccountSummary>(http.patch(`/accounts/${id}/authorized-dispatch`, payload, { params })),
  setDefaultTestModel: (id: string, model: string, params?: ListParams) => unwrap<AccountDefaultTestModelResult>(http.put(`/accounts/${id}/default-test-model`, { model }, { params })),
  bindGroup: (id: string, payload: { groupId: string }, params?: ListParams) => unwrap<AccountSummary>(http.post(`/accounts/${id}/group`, payload, { params })),
  migrateTraffic: (id: string, payload: { targetAccountId: string; sourceStatus?: AccountTrafficMigrationSourceStatus }, params?: ListParams) => unwrap<AccountTrafficMigrationResult>(http.post(`/accounts/${id}/traffic-migration`, payload, { params })),
  test: (id: string, payload?: AccountTestPayload, params?: ListParams, options?: RequestControlOptions) => unwrap<AccountTestTask>(http.post(`/accounts/${id}/test`, payload ?? {}, { params, signal: options?.signal })),
  testDraft: (payload: AccountDraftTestPayload, params?: ListParams, options?: RequestControlOptions) => unwrap<AccountTestTask>(http.post('/accounts/test-draft', payload, { params, signal: options?.signal })),
  createTestSession: (params?: ListParams) => unwrap<AccountTestSession>(http.post('/accounts/test-sessions', {}, { params })),
  activeTestSession: (params?: ListParams, options?: RequestControlOptions) => unwrap<AccountTestSessionDetail | null>(http.get('/accounts/test-sessions/active', { params, signal: options?.signal })),
  testSession: (sessionId: string, params?: ListParams, options?: RequestControlOptions) => unwrap<AccountTestSession>(http.get(`/accounts/test-sessions/${sessionId}`, { params, signal: options?.signal })),
  testSessionTasks: (sessionId: string, params?: ListParams, options?: RequestControlOptions) => unwrap<AccountTestTask[]>(http.get(`/accounts/test-sessions/${sessionId}/tasks`, { params, signal: options?.signal })),
  heartbeatTestSession: (sessionId: string, params?: ListParams) => unwrap<AccountTestSession>(http.post(`/accounts/test-sessions/${sessionId}/heartbeat`, {}, { params })),
  completeTestSession: (sessionId: string, params?: ListParams) => unwrap<AccountTestSession>(http.post(`/accounts/test-sessions/${sessionId}/complete`, {}, { params })),
  cancelTestSession: (sessionId: string, params?: ListParams) => unwrap<AccountTestSession>(http.post(`/accounts/test-sessions/${sessionId}/cancel`, {}, { params })),
  testTasks: (taskIds: string[], params?: ListParams, options?: RequestControlOptions) => unwrap<AccountTestTask[]>(http.get('/accounts/test-tasks', { params: { ...params, ids: taskIds.join(',') }, signal: options?.signal })),
  testTask: (taskId: string, params?: ListParams, options?: RequestControlOptions) => unwrap<AccountTestTask>(http.get(`/accounts/test-tasks/${taskId}`, { params, signal: options?.signal })),
  cancelTestTask: (taskId: string, params?: ListParams) => unwrap<AccountTestTask>(http.post(`/accounts/test-tasks/${taskId}/cancel`, {}, { params })),
  returnAuthorization: (id: string, params?: ListParams) => http.post(`/accounts/${id}/return-authorization`, {}, { params }),
  delete: (id: string, params?: ListParams) => http.delete(`/accounts/${id}`, { params })
}

export const myAccountsApi = {
  list: (params?: AccountListParams) => unwrap<AccountListResult>(http.get('/my-accounts', { params: accountListParams(params, false) })),
  options: (params?: AccountOptionParams) => unwrap<AccountOptionSummary[]>(http.get('/my-accounts/options', { params: accountOptionsParams(params, false) })),
  tags: () => unwrap<AccountTagSummary[]>(http.get('/my-accounts/tags')),
  deleteTag: (id: string) => http.delete(`/my-accounts/tags/${id}`),
  detail: (id: string) => unwrap<AccountSummary>(http.get(`/my-accounts/${id}`)),
  editBasicDetail: (id: string) => unwrap<AccountSummary>(http.get(`/my-accounts/${id}/edit-basic`)),
  advancedDetail: (id: string) => unwrap<AccountSummary>(http.get(`/my-accounts/${id}/advanced`)),
  export: (payload: AccountExportPayload) => unwrap<AccountExportResult>(http.post('/my-accounts/export', payload)),
  importPreview: (payload: { data: unknown; options?: AccountImportOptions }) => unwrap<AccountImportResult>(http.post('/my-accounts/import/preview', payload)),
  importConfirm: (payload: { data: unknown; options?: AccountImportOptions }) => unwrap<AccountImportResult>(http.post('/my-accounts/import/confirm', payload)),
  create: (payload: Record<string, unknown>) => unwrap<AccountSummary>(http.post('/my-accounts', payload)),
  update: (id: string, payload: Record<string, unknown>) => unwrap<AccountSummary>(http.patch(`/my-accounts/${id}`, payload)),
  updateTags: (id: string, payload: { tags: string[] }) => unwrap<AccountSummary>(http.patch(`/my-accounts/${id}/tags`, payload)),
  updateAuthorizedDispatch: (id: string, payload: { status?: 'active' | 'disabled'; priority?: number; superPriorityEnabled?: boolean; fallbackEnabled?: boolean; clearFailureState?: boolean }) => unwrap<AccountSummary>(http.patch(`/my-accounts/${id}/authorized-dispatch`, payload)),
  setDefaultTestModel: (id: string, model: string) => unwrap<AccountDefaultTestModelResult>(http.put(`/my-accounts/${id}/default-test-model`, { model })),
  bindGroup: (id: string, payload: { groupId: string }) => unwrap<AccountSummary>(http.post(`/my-accounts/${id}/group`, payload)),
  migrateTraffic: (id: string, payload: { targetAccountId: string; sourceStatus?: AccountTrafficMigrationSourceStatus }) => unwrap<AccountTrafficMigrationResult>(http.post(`/my-accounts/${id}/traffic-migration`, payload)),
  test: (id: string, payload?: AccountTestPayload, options?: RequestControlOptions) => unwrap<AccountTestTask>(http.post(`/my-accounts/${id}/test`, payload ?? {}, { signal: options?.signal })),
  testDraft: (payload: AccountDraftTestPayload, options?: RequestControlOptions) => unwrap<AccountTestTask>(http.post('/my-accounts/test-draft', payload, { signal: options?.signal })),
  createTestSession: () => unwrap<AccountTestSession>(http.post('/my-accounts/test-sessions', {})),
  activeTestSession: (options?: RequestControlOptions) => unwrap<AccountTestSessionDetail | null>(http.get('/my-accounts/test-sessions/active', { signal: options?.signal })),
  testSession: (sessionId: string, options?: RequestControlOptions) => unwrap<AccountTestSession>(http.get(`/my-accounts/test-sessions/${sessionId}`, { signal: options?.signal })),
  testSessionTasks: (sessionId: string, options?: RequestControlOptions) => unwrap<AccountTestTask[]>(http.get(`/my-accounts/test-sessions/${sessionId}/tasks`, { signal: options?.signal })),
  heartbeatTestSession: (sessionId: string) => unwrap<AccountTestSession>(http.post(`/my-accounts/test-sessions/${sessionId}/heartbeat`, {})),
  completeTestSession: (sessionId: string) => unwrap<AccountTestSession>(http.post(`/my-accounts/test-sessions/${sessionId}/complete`, {})),
  cancelTestSession: (sessionId: string) => unwrap<AccountTestSession>(http.post(`/my-accounts/test-sessions/${sessionId}/cancel`, {})),
  testTasks: (taskIds: string[], options?: RequestControlOptions) => unwrap<AccountTestTask[]>(http.get('/my-accounts/test-tasks', { params: { ids: taskIds.join(',') }, signal: options?.signal })),
  testTask: (taskId: string, options?: RequestControlOptions) => unwrap<AccountTestTask>(http.get(`/my-accounts/test-tasks/${taskId}`, { signal: options?.signal })),
  cancelTestTask: (taskId: string) => unwrap<AccountTestTask>(http.post(`/my-accounts/test-tasks/${taskId}/cancel`, {})),
  returnAuthorization: (id: string) => http.post(`/my-accounts/${id}/return-authorization`, {}),
  delete: (id: string) => http.delete(`/my-accounts/${id}`)
}
