// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresqueries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type JuheBusinessAccount struct {
	ID                              string
	SystemAccountID                 string
	ProviderCode                    string
	ProviderProtocolProfileID       string
	ProtocolCode                    string
	ProtocolVersion                 string
	Name                            string
	Type                            string
	Status                          string
	CredentialsEncrypted            string
	CredentialFingerprint           pgtype.Text
	CredentialMask                  string
	ConcurrencyLimit                int32
	Priority                        int32
	SuperPriorityEnabled            bool
	FallbackEnabled                 bool
	ClientCompatibility             string
	Schedulable                     bool
	AvailabilityScheduleJson        pgtype.Text
	AvailabilityScheduleNextCheckAt pgtype.Timestamptz
	Notes                           pgtype.Text
	AccountExpiresAt                pgtype.Timestamptz
	LastUsedAt                      pgtype.Timestamptz
	CooldownUntil                   pgtype.Timestamptz
	LastErrorCode                   pgtype.Text
	LastErrorMessage                pgtype.Text
	DeletedAt                       pgtype.Timestamptz
	DeletedBy                       pgtype.Text
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
}

type JuheBusinessAccountSupportedModel struct {
	AccountID    string
	ProviderCode string
	Model        string
	CreatedAt    pgtype.Timestamptz
}

type JuheBusinessApiKey struct {
	ID                              string
	SystemAccountID                 string
	RouteStrategyID                 string
	Name                            string
	Description                     pgtype.Text
	KeyHash                         string
	KeyPrefix                       string
	KeySuffix                       string
	Status                          string
	IsDefault                       bool
	ExpiresAt                       pgtype.Timestamptz
	QuotaLimitsJson                 pgtype.Text
	AvailabilityScheduleJson        pgtype.Text
	AvailabilityScheduleNextCheckAt pgtype.Timestamptz
	LastUsedAt                      pgtype.Timestamptz
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
}

type JuheBusinessExternalIntegrationSource struct {
	ID             string
	Name           string
	Status         string
	ScopesJson     string
	RateLimitsJson string
	ExpiresAt      pgtype.Timestamptz
	Notes          pgtype.Text
	LastUsedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type JuheBusinessExternalIntegrationSourceToken struct {
	ID                   string
	SourceRefID          string
	Name                 string
	TokenHash            string
	TokenSecretEncrypted string
	TokenPrefix          string
	TokenSuffix          string
	Status               string
	ScopesJson           string
	ExpiresAt            pgtype.Timestamptz
	LastUsedAt           pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
}

type JuheBusinessGlobalSetting struct {
	Key       string
	ValueJson string
	UpdatedAt pgtype.Timestamptz
}

type JuheBusinessGroup struct {
	ID                   string
	SystemAccountID      string
	Name                 string
	ProviderCode         string
	Description          pgtype.Text
	Enabled              bool
	IsDefault            bool
	GroupType            string
	SchedulingPolicyJson pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type JuheBusinessGroupAccount struct {
	SystemAccountID           string
	GroupID                   string
	AccountID                 string
	AccountAuthorizationID    pgtype.Text
	LocalPriority             int32
	LocalSuperPriorityEnabled bool
	LocalFallbackEnabled      bool
	Enabled                   bool
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

type JuheBusinessProtocol struct {
	ID          string
	Code        string
	Version     string
	Name        string
	Description pgtype.Text
	Enabled     bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type JuheBusinessProvider struct {
	ID                         string
	Code                       string
	Name                       string
	Description                pgtype.Text
	ParentCode                 pgtype.Text
	Enabled                    bool
	DefaultSupportedModelsJson string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

type JuheBusinessProviderProtocolProfile struct {
	ID               string
	ProviderCode     string
	Name             string
	Description      pgtype.Text
	Enabled          bool
	ProtocolCode     string
	ProtocolVersion  string
	BaseUrl          string
	DefaultTestModel string
	AccountTypesJson string
	CapabilitiesJson string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type JuheBusinessProxyProfile struct {
	ID                string
	SystemAccountID   string
	Name              string
	Description       pgtype.Text
	Type              string
	Host              string
	Port              int32
	Username          pgtype.Text
	PasswordEncrypted pgtype.Text
	Enabled           bool
	TestStatus        string
	LatencyMs         pgtype.Int4
	OutboundIp        pgtype.Text
	OutboundRegion    pgtype.Text
	LastTestMessage   pgtype.Text
	LastTestedAt      pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type JuheBusinessRouteStrategy struct {
	ID              string
	SystemAccountID string
	Name            string
	Description     pgtype.Text
	Mode            string
	Status          string
	IsDefault       bool
	ConfigJson      pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type JuheBusinessRouteStrategyGroup struct {
	ID              string
	RouteStrategyID string
	SystemAccountID string
	GroupID         string
	Priority        int32
	Weight          int32
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type JuheBusinessSystemAccount struct {
	ID                     string
	Username               string
	DisplayName            string
	Description            pgtype.Text
	Role                   string
	Status                 string
	PasswordHash           string
	MustChangePassword     bool
	ImageGenerationEnabled bool
	LastLoginAt            pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type JuheBusinessSystemSetting struct {
	SystemAccountID string
	Key             string
	ValueJson       string
	UpdatedAt       pgtype.Timestamptz
}

type JuheDatasetPublicApiLog struct {
	ID                    string
	TraceID               pgtype.Text
	SourceRefID           pgtype.Text
	SourceName            pgtype.Text
	TokenID               pgtype.Text
	TokenName             pgtype.Text
	TokenPrefix           pgtype.Text
	IsTestToken           bool
	Method                string
	Path                  string
	QueryString           pgtype.Text
	ClientIp              pgtype.Text
	UserAgent             pgtype.Text
	StatusCode            pgtype.Int4
	Success               bool
	DurationMs            pgtype.Int8
	RequestSizeBytes      int64
	ResponseSizeBytes     int64
	RequestCaptureStatus  string
	ResponseCaptureStatus string
	RequestDataJson       string
	ResponseDataJson      string
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	StartedAt             pgtype.Timestamptz
	EndedAt               pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
}
