// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresqueries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type JuheBusinessAccount struct {
	ID                                        string
	SystemAccountID                           string
	ProviderCode                              string
	ProviderProtocolProfileID                 string
	ProtocolCode                              string
	ProtocolVersion                           string
	Name                                      string
	Type                                      string
	Status                                    string
	CredentialsEncrypted                      string
	CredentialFingerprint                     pgtype.Text
	CredentialMask                            string
	ConcurrencyLimit                          int32
	Priority                                  int32
	SuperPriorityEnabled                      bool
	FallbackEnabled                           bool
	ClientCompatibility                       string
	Schedulable                               bool
	AvailabilityScheduleJson                  pgtype.Text
	AvailabilityScheduleNextCheckAt           pgtype.Timestamptz
	Notes                                     pgtype.Text
	AccountExpiresAt                          pgtype.Timestamptz
	LastUsedAt                                pgtype.Timestamptz
	CooldownUntil                             pgtype.Timestamptz
	LastErrorCode                             pgtype.Text
	LastErrorMessage                          pgtype.Text
	HealthCheckModel                          string
	HealthCheckEndpointMode                   string
	DeletedAt                                 pgtype.Timestamptz
	DeletedBy                                 pgtype.Text
	CreatedAt                                 pgtype.Timestamptz
	UpdatedAt                                 pgtype.Timestamptz
	AuthorizationInstanceSourceAccountID      pgtype.Text
	AuthorizationInstanceAuthorizationID      pgtype.Text
	AuthorizationInstanceOwnerSystemAccountID pgtype.Text
	ProxyProfileID                            pgtype.Text
	NextHealthCheckAt                         pgtype.Timestamptz
	HealthCheckFailureCount                   int32
	LastHealthCheckStatusCode                 pgtype.Int4
	LastHealthCheckErrorCode                  pgtype.Text
	LastHealthCheckErrorMessage               pgtype.Text
	ConfigRevision                            int32
	HealthCheckFailureStartedAt               pgtype.Timestamptz
}

type JuheBusinessAccountModelMapping struct {
	AccountID              string
	ProviderCode           string
	SourceModel            string
	SourceEndpointFamily   string
	UpstreamModel          string
	UpstreamEndpointFamily string
	Enabled                bool
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type JuheBusinessAccountNameSearchDocument struct {
	AccountID       string
	SystemAccountID string
	NormalizedName  string
	UpdatedAt       pgtype.Timestamptz
}

type JuheBusinessAccountNameSearchTerm struct {
	AccountID       string
	SystemAccountID string
	Term            string
	CreatedAt       pgtype.Timestamptz
}

type JuheBusinessAccountSupportedModel struct {
	AccountID    string
	ProviderCode string
	Model        string
	CreatedAt    pgtype.Timestamptz
}

type JuheBusinessAccountTag struct {
	ID              string
	SystemAccountID string
	Name            string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type JuheBusinessAccountTagBinding struct {
	AccountID       string
	TagID           string
	SystemAccountID string
	CreatedAt       pgtype.Timestamptz
}

type JuheBusinessApiKey struct {
	ID                              string
	SystemAccountID                 string
	RouteStrategyID                 string
	Name                            string
	Description                     pgtype.Text
	KeyHash                         string
	KeyPrefix                       string
	KeySuffix                       string
	Status                          string
	IsDefault                       bool
	ExpiresAt                       pgtype.Timestamptz
	QuotaLimitsJson                 pgtype.Text
	AvailabilityScheduleJson        pgtype.Text
	AvailabilityScheduleNextCheckAt pgtype.Timestamptz
	LastUsedAt                      pgtype.Timestamptz
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
	KeySecretEncrypted              pgtype.Text
}

type JuheBusinessCustomProviderModel struct {
	ID                            string
	ProviderCode                  string
	Model                         string
	Scope                         string
	SystemAccountID               pgtype.Text
	Status                        string
	Mode                          pgtype.Text
	SupportedApiProtocolsJson     string
	ReleaseDate                   pgtype.Text
	ShutdownDate                  pgtype.Text
	ContextWindowTokens           pgtype.Int4
	MaxOutputTokens               pgtype.Int4
	InputUsdPer1m                 pgtype.Float8
	OutputUsdPer1m                pgtype.Float8
	CachedInputUsdPer1m           pgtype.Float8
	CacheWriteUsdPer1m            pgtype.Float8
	ImageInputUsdPer1m            pgtype.Float8
	ImageOutputUsdPer1m           pgtype.Float8
	AudioInputUsdPer1m            pgtype.Float8
	AudioOutputUsdPer1m           pgtype.Float8
	OutputUsdPerImage             pgtype.Float8
	Currency                      string
	PricingNotes                  pgtype.Text
	CapabilityNotes               pgtype.Text
	Notes                         pgtype.Text
	CreatedBy                     string
	UpdatedBy                     pgtype.Text
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	SupportedServiceTiersJson     string
	SupportedReasoningEffortsJson string
	DefaultReasoningEffort        pgtype.Text
	CacheWrite1hUsdPer1m          pgtype.Float8
	ServiceTierPricesJson         string
}

type JuheBusinessExternalIntegrationSource struct {
	ID             string
	Name           string
	Status         string
	ScopesJson     string
	RateLimitsJson string
	ExpiresAt      pgtype.Timestamptz
	Notes          pgtype.Text
	LastUsedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type JuheBusinessExternalIntegrationSourceToken struct {
	ID                   string
	SourceRefID          string
	Name                 string
	TokenHash            string
	TokenSecretEncrypted string
	TokenPrefix          string
	TokenSuffix          string
	Status               string
	ScopesJson           string
	ExpiresAt            pgtype.Timestamptz
	LastUsedAt           pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	RevokedAt            pgtype.Timestamptz
}

type JuheBusinessGlobalSetting struct {
	Key       string
	ValueJson string
	UpdatedAt pgtype.Timestamptz
}

type JuheBusinessGroup struct {
	ID                   string
	SystemAccountID      string
	Name                 string
	ProviderCode         string
	Description          pgtype.Text
	Enabled              bool
	IsDefault            bool
	GroupType            string
	SchedulingPolicyJson pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type JuheBusinessGroupAccount struct {
	SystemAccountID           string
	GroupID                   string
	AccountID                 string
	AccountAuthorizationID    pgtype.Text
	LocalPriority             int32
	LocalSuperPriorityEnabled bool
	LocalFallbackEnabled      bool
	Enabled                   bool
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

type JuheBusinessGroupAccountStatsDirty struct {
	GroupID   string
	Reason    pgtype.Text
	UpdatedAt pgtype.Timestamptz
}

type JuheBusinessGroupAuthorizationSetting struct {
	AuthorizationID      string
	SystemAccountID      string
	GroupID              string
	Enabled              bool
	GroupType            string
	SchedulingPolicyJson pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type JuheBusinessProtocol struct {
	ID          string
	Code        string
	Version     string
	Name        string
	Description pgtype.Text
	Enabled     bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type JuheBusinessProtocolEndpointFamily struct {
	ID              string
	ProtocolCode    string
	ProtocolVersion string
	FamilyCode      string
	Name            string
	Description     pgtype.Text
	Enabled         bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type JuheBusinessProvider struct {
	ID                         string
	Code                       string
	Name                       string
	Description                pgtype.Text
	ParentCode                 pgtype.Text
	Enabled                    bool
	DefaultSupportedModelsJson string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

type JuheBusinessProviderDefaultHealthCheckModel struct {
	SystemAccountID string
	ProviderCode    string
	Model           string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type JuheBusinessProviderModelCatalog struct {
	ID                                string
	ProviderCode                      string
	Model                             string
	Status                            string
	Mode                              pgtype.Text
	CatalogOrder                      pgtype.Int4
	ReleaseDate                       pgtype.Text
	ShutdownDate                      pgtype.Text
	SupportedApiProtocolsJson         string
	ContextWindowTokens               pgtype.Int4
	InputUsdPer1m                     pgtype.Float8
	OutputUsdPer1m                    pgtype.Float8
	CachedInputUsdPer1m               pgtype.Float8
	CacheWriteUsdPer1m                pgtype.Float8
	CacheWrite1hUsdPer1m              pgtype.Float8
	ImageInputUsdPer1m                pgtype.Float8
	ImageOutputUsdPer1m               pgtype.Float8
	AudioInputUsdPer1m                pgtype.Float8
	AudioOutputUsdPer1m               pgtype.Float8
	OutputUsdPerImage                 pgtype.Float8
	MaxInputTokens                    pgtype.Int4
	MaxOutputTokens                   pgtype.Int4
	MaxTokens                         pgtype.Int4
	SupportsPromptCaching             bool
	CatalogVisible                    bool
	Source                            string
	CreatedAt                         pgtype.Timestamptz
	UpdatedAt                         pgtype.Timestamptz
	SupportedServiceTiersJson         string
	SupportedReasoningEffortsJson     string
	DefaultReasoningEffort            pgtype.Text
	CodexSupportedReasoningLevelsJson string
	CodexDefaultReasoningLevel        pgtype.Text
	CodexMultiAgentVersion            pgtype.Text
	LongContextInputTokenThreshold    pgtype.Int4
	LongContextInputCostMultiplier    pgtype.Float8
	LongContextOutputCostMultiplier   pgtype.Float8
	ServiceTierPricesJson             string
}

type JuheBusinessProviderProtocolProfile struct {
	ID                      string
	ProviderCode            string
	Name                    string
	Description             pgtype.Text
	Enabled                 bool
	ProtocolCode            string
	ProtocolVersion         string
	BaseUrl                 string
	DefaultHealthCheckModel string
	AccountTypesJson        string
	CapabilitiesJson        string
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type JuheBusinessProviderProtocolProfileFamily struct {
	ProfileID               string
	FamilyCode              string
	Enabled                 bool
	DefaultHealthCheckModel pgtype.Text
	CapabilitiesJson        string
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type JuheBusinessProviderSystemDefaultHealthCheckModel struct {
	ProviderCode string
	Model        string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type JuheBusinessProxyProfile struct {
	ID                string
	SystemAccountID   string
	Name              string
	Description       pgtype.Text
	Type              string
	Host              string
	Port              int32
	Username          pgtype.Text
	PasswordEncrypted pgtype.Text
	Enabled           bool
	TestStatus        string
	LatencyMs         pgtype.Int4
	OutboundIp        pgtype.Text
	OutboundRegion    pgtype.Text
	LastTestMessage   pgtype.Text
	LastTestedAt      pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type JuheBusinessRequestQuotaHourlyWindowConfig struct {
	WindowHours int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type JuheBusinessResourceAuthorization struct {
	ID                           string
	ResourceType                 string
	ResourceID                   string
	ResourceOwnerSystemAccountID string
	GranteeSystemAccountID       string
	Scope                        string
	Status                       string
	EffectiveSourceType          pgtype.Text
	EffectiveSourceTeamID        pgtype.Text
	ActivatedAt                  pgtype.Timestamptz
	LastSourceChangedAt          pgtype.Timestamptz
	Remark                       pgtype.Text
	ExpiresAt                    pgtype.Timestamptz
	LimitsJson                   pgtype.Text
	CreatedBy                    string
	CreatedAt                    pgtype.Timestamptz
	RevokedBy                    pgtype.Text
	RevokedAt                    pgtype.Timestamptz
	RevokedReason                pgtype.Text
	UpdatedAt                    pgtype.Timestamptz
}

type JuheBusinessResourceAuthorizationGrant struct {
	ID                           string
	ResourceType                 string
	ResourceID                   string
	ResourceOwnerSystemAccountID string
	GranteeType                  string
	GranteeSystemAccountID       pgtype.Text
	GranteeTeamID                pgtype.Text
	Scope                        string
	Status                       string
	Remark                       pgtype.Text
	ExpiresAt                    pgtype.Timestamptz
	LimitsJson                   pgtype.Text
	CreatedBy                    string
	CreatedAt                    pgtype.Timestamptz
	RevokedBy                    pgtype.Text
	RevokedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
}

type JuheBusinessResourceAuthorizationSource struct {
	ID              string
	AuthorizationID string
	SourceType      string
	SourceTeamID    pgtype.Text
	Status          string
	ActivatedAt     pgtype.Timestamptz
	EndedAt         pgtype.Timestamptz
	EndedReason     pgtype.Text
	CreatedBy       string
	CreatedAt       pgtype.Timestamptz
	RevokedBy       pgtype.Text
	RevokedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type JuheBusinessRouteStrategy struct {
	ID              string
	SystemAccountID string
	Name            string
	Description     pgtype.Text
	Mode            string
	Status          string
	IsDefault       bool
	ConfigJson      pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type JuheBusinessRouteStrategyGroup struct {
	ID              string
	RouteStrategyID string
	SystemAccountID string
	GroupID         string
	Priority        int32
	Weight          int32
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type JuheBusinessSystemAccount struct {
	ID                     string
	Username               string
	DisplayName            string
	Description            pgtype.Text
	Role                   string
	Status                 string
	PasswordHash           string
	MustChangePassword     bool
	ImageGenerationEnabled bool
	LastLoginAt            pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type JuheBusinessSystemSession struct {
	ID              string
	SystemAccountID string
	TokenHash       string
	ExpiresAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	LastSeenAt      pgtype.Timestamptz
}

type JuheBusinessSystemSetting struct {
	SystemAccountID string
	Key             string
	ValueJson       string
	UpdatedAt       pgtype.Timestamptz
}

type JuheBusinessSystemTeam struct {
	ID          string
	Name        string
	Description pgtype.Text
	Status      string
	CreatedBy   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type JuheBusinessSystemTeamMember struct {
	ID              string
	TeamID          string
	SystemAccountID string
	MemberRole      string
	Status          string
	JoinedAt        pgtype.Timestamptz
	RemovedAt       pgtype.Timestamptz
	CreatedBy       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type JuheDatasetApiKeyRecordCleanupTarget struct {
	ApiKeyID          string
	SystemAccountID   string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	AttemptCount      int32
	LastAttemptAt     pgtype.Timestamptz
	LastBlockedReason pgtype.Text
	LastErrorMessage  pgtype.Text
}

type JuheDatasetOperationLog struct {
	ID                            string
	TraceID                       pgtype.Text
	ActorSystemAccountID          string
	ActorUsername                 pgtype.Text
	ActorDisplayName              pgtype.Text
	ActorRole                     string
	OperationScopeSystemAccountID pgtype.Text
	Mode                          string
	Module                        string
	Action                        string
	OperationKey                  string
	ResourceType                  string
	ResourceID                    pgtype.Text
	ResourceName                  pgtype.Text
	Summary                       string
	DetailLevel                   string
	VisibilityScope               string
	ChangesJson                   string
	MetadataJson                  string
	Method                        pgtype.Text
	Path                          pgtype.Text
	StatusCode                    pgtype.Int4
	ClientIp                      pgtype.Text
	UserAgent                     pgtype.Text
	CreatedAt                     pgtype.Timestamptz
}

type JuheDatasetOperationLogSummarySearchTerm struct {
	OperationLogID string
	Term           string
	CreatedAt      pgtype.Timestamptz
}

type JuheDatasetOperationLogTarget struct {
	ID                         string
	OperationLogID             string
	TargetType                 string
	TargetID                   pgtype.Text
	TargetName                 pgtype.Text
	TargetOwnerSystemAccountID pgtype.Text
	Relation                   string
	CreatedAt                  pgtype.Timestamptz
}

type JuheDatasetOperationLogViewer struct {
	OperationLogID   string
	SystemAccountID  string
	VisibilityReason string
	DetailLevel      string
	CreatedAt        pgtype.Timestamptz
}

type JuheDatasetPublicApiLog struct {
	ID                    string
	TraceID               pgtype.Text
	SourceRefID           pgtype.Text
	SourceName            pgtype.Text
	TokenID               pgtype.Text
	TokenName             pgtype.Text
	TokenPrefix           pgtype.Text
	IsTestToken           bool
	Method                string
	Path                  string
	QueryString           pgtype.Text
	ClientIp              pgtype.Text
	UserAgent             pgtype.Text
	StatusCode            pgtype.Int4
	Success               bool
	DurationMs            pgtype.Int8
	RequestSizeBytes      int64
	ResponseSizeBytes     int64
	RequestCaptureStatus  string
	ResponseCaptureStatus string
	RequestDataJson       string
	ResponseDataJson      string
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	StartedAt             pgtype.Timestamptz
	EndedAt               pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
}

type JuheDatasetRuntimeLog struct {
	ID           string
	LogFile      pgtype.Text
	LogOffset    pgtype.Int8
	LineNumber   pgtype.Int4
	Time         string
	Level        string
	TraceID      pgtype.Text
	Event        pgtype.Text
	Message      pgtype.Text
	ErrorMessage pgtype.Text
	RawJson      string
	CreatedAt    string
}

type JuheDatasetRuntimeLogEventFacet struct {
	BucketKey  string
	Event      string
	Count      int64
	LatestTime pgtype.Text
	UpdatedAt  string
}

type JuheDatasetRuntimeLogFacetSummary struct {
	BucketKey    string
	TotalCount   int64
	EarliestTime pgtype.Text
	LatestTime   pgtype.Text
	UpdatedAt    string
}

type JuheDatasetRuntimeLogFileCursor struct {
	LogFile          string
	FileIdentity     pgtype.Text
	CursorOffset     int64
	LineNumber       int32
	FileSize         int64
	FileMtimeMs      pgtype.Int8
	LastReadAt       pgtype.Text
	LastErrorMessage pgtype.Text
	CreatedAt        string
	UpdatedAt        string
}

type JuheDatasetRuntimeLogLevelFacet struct {
	BucketKey string
	Level     string
	Count     int64
	UpdatedAt string
}

type JuheStatsAuthorizationTeamUsageRangeWindow struct {
	SystemAccountID    string
	StartDate          string
	EndDate            string
	TeamFilterID       string
	ResourceFilterType string
	ResourceFilterID   string
	RequestCount       int64
	InputTokens        int64
	OutputTokens       int64
	CacheReadTokens    int64
	CacheReadCostUsd   pgtype.Numeric
	CacheWriteTokens   int64
	CacheWrite1hTokens int64
	CacheWriteCostUsd  pgtype.Numeric
	ThinkingTokens     int64
	InputImageTokens   int64
	OutputImageTokens  int64
	TotalCostUsd       pgtype.Numeric
	LastUsedAt         pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type JuheStatsAuthorizationTeamUsageSummaryDaily struct {
	SystemAccountID    string
	StatDate           string
	TeamFilterID       string
	ResourceFilterType string
	ResourceFilterID   string
	RowCount           int64
	RequestCount       int64
	SuccessCount       int64
	ErrorCount         int64
	InputTokens        int64
	OutputTokens       int64
	CacheReadTokens    int64
	CacheReadCostUsd   pgtype.Numeric
	CacheWriteTokens   int64
	CacheWrite1hTokens int64
	CacheWriteCostUsd  pgtype.Numeric
	ThinkingTokens     int64
	InputImageTokens   int64
	OutputImageTokens  int64
	TotalCostUsd       pgtype.Numeric
	DurationMsSum      int64
	DurationMsCount    int64
	DurationMsMax      int64
	FirstTokenMsSum    int64
	FirstTokenMsCount  int64
	FirstTokenMsMax    int64
	LastUsedAt         pgtype.Timestamptz
	LastErrorAt        pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type JuheStatsAuthorizationUserUsageRangeWindow struct {
	SystemAccountID              string
	StartDate                    string
	EndDate                      string
	TeamFilterID                 string
	GranteeFilterSystemAccountID string
	ResourceFilterType           string
	ResourceFilterID             string
	RequestCount                 int64
	InputTokens                  int64
	OutputTokens                 int64
	CacheReadTokens              int64
	CacheReadCostUsd             pgtype.Numeric
	CacheWriteTokens             int64
	CacheWrite1hTokens           int64
	CacheWriteCostUsd            pgtype.Numeric
	ThinkingTokens               int64
	InputImageTokens             int64
	OutputImageTokens            int64
	TotalCostUsd                 pgtype.Numeric
	LastUsedAt                   pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
}

type JuheStatsAuthorizationUserUsageSummaryDaily struct {
	SystemAccountID              string
	StatDate                     string
	TeamFilterID                 string
	GranteeFilterSystemAccountID string
	ResourceFilterType           string
	ResourceFilterID             string
	RowCount                     int64
	RequestCount                 int64
	SuccessCount                 int64
	ErrorCount                   int64
	InputTokens                  int64
	OutputTokens                 int64
	CacheReadTokens              int64
	CacheReadCostUsd             pgtype.Numeric
	CacheWriteTokens             int64
	CacheWrite1hTokens           int64
	CacheWriteCostUsd            pgtype.Numeric
	ThinkingTokens               int64
	InputImageTokens             int64
	OutputImageTokens            int64
	TotalCostUsd                 pgtype.Numeric
	DurationMsSum                int64
	DurationMsCount              int64
	DurationMsMax                int64
	FirstTokenMsSum              int64
	FirstTokenMsCount            int64
	FirstTokenMsMax              int64
	LastUsedAt                   pgtype.Timestamptz
	LastErrorAt                  pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
}

type JuheStatsClientIpAccountRangeWindowDirtyIp struct {
	IpHash    string
	UpdatedAt string
}

type JuheStatsClientIpAccountUsageRangeWindow struct {
	IpHash              string
	AccountID           string
	StartDate           string
	EndDate             string
	RequestCount        int64
	SuccessCount        int64
	ErrorCount          int64
	InputTokens         int64
	OutputTokens        int64
	CacheReadTokens     int64
	CacheReadCostUsd    float64
	CacheWriteTokens    int64
	CacheWrite1hTokens  int64
	CacheWriteCostUsd   float64
	ThinkingTokens      int64
	InputImageTokens    int64
	OutputImageTokens   int64
	TotalCostUsd        float64
	DurationMsSum       int64
	DurationMsCount     int64
	DurationMsMax       int64
	AverageDurationMs   pgtype.Float8
	FirstTokenMsSum     int64
	FirstTokenMsCount   int64
	AverageFirstTokenMs pgtype.Float8
	ActiveDays          int32
	LastUsedAt          pgtype.Text
	LastErrorAt         pgtype.Text
	UpdatedAt           string
}

type JuheStatsClientIpPolicy struct {
	ID                        string
	IpHash                    string
	PolicyType                string
	Status                    string
	Reason                    pgtype.Text
	ExpiresAt                 pgtype.Text
	CreatedBySystemAccountID  string
	CreatedAt                 string
	UpdatedAt                 string
	DisabledAt                pgtype.Text
	DisabledBySystemAccountID pgtype.Text
	DisabledReason            pgtype.Text
}

type JuheStatsClientIpRangeWindowDirtyIp struct {
	IpHash    string
	UpdatedAt string
}

type JuheStatsClientIpRegistry struct {
	IpHash         string
	BucketNo       int32
	AggregateIpKey string
	ClientIp       string
	IpVersion      int32
	FirstSeenAt    string
	LastSeenAt     string
	CreatedAt      string
	UpdatedAt      string
}

type JuheStatsClientIpUsageRangeWindow struct {
	IpHash              string
	StartDate           string
	EndDate             string
	RequestCount        int64
	SuccessCount        int64
	ErrorCount          int64
	InputTokens         int64
	OutputTokens        int64
	CacheReadTokens     int64
	CacheReadCostUsd    float64
	CacheWriteTokens    int64
	CacheWrite1hTokens  int64
	CacheWriteCostUsd   float64
	ThinkingTokens      int64
	InputImageTokens    int64
	OutputImageTokens   int64
	TotalCostUsd        float64
	DurationMsSum       int64
	DurationMsCount     int64
	DurationMsMax       int64
	AverageDurationMs   pgtype.Float8
	FirstTokenMsSum     int64
	FirstTokenMsCount   int64
	AverageFirstTokenMs pgtype.Float8
	ActiveDays          int32
	LastUsedAt          pgtype.Text
	LastErrorAt         pgtype.Text
	UpdatedAt           string
}

type JuheStatsGroupAccountStat struct {
	SystemAccountID    string
	GroupID            string
	Total              int32
	Available          int32
	Active             int32
	Disabled           int32
	Error              int32
	RateLimited        int32
	CurrentConcurrency int32
	ConcurrencyLimit   int32
	UpdatedAt          string
}

type JuheStatsStatsJobState struct {
	ScopeType        string
	ScopeID          string
	JobName          string
	CursorCreatedAt  pgtype.Text
	CursorID         pgtype.Text
	LastSuccessAt    pgtype.Text
	LastErrorMessage pgtype.Text
	LagSeconds       pgtype.Int4
	UpdatedAt        string
}

type JuheStatsUsageStatsDaily struct {
	SystemAccountID    string
	ScopeType          string
	ScopeID            string
	StatDate           string
	RequestCount       int64
	SuccessCount       int64
	ErrorCount         int64
	InputTokens        int64
	OutputTokens       int64
	CacheReadTokens    int64
	CacheReadCostUsd   float64
	CacheWriteTokens   int64
	CacheWrite1hTokens int64
	CacheWriteCostUsd  float64
	ThinkingTokens     int64
	InputImageTokens   int64
	OutputImageTokens  int64
	TotalCostUsd       float64
	DurationMsSum      int64
	DurationMsCount    int64
	DurationMsMax      int64
	FirstTokenMsSum    int64
	FirstTokenMsCount  int64
	FirstTokenMsMax    int64
	LastUsedAt         pgtype.Text
	LastErrorAt        pgtype.Text
	UpdatedAt          string
}

type JuheStatsUsageStatsTotal struct {
	SystemAccountID    string
	ScopeType          string
	ScopeID            string
	RequestCount       int64
	SuccessCount       int64
	ErrorCount         int64
	InputTokens        int64
	OutputTokens       int64
	CacheReadTokens    int64
	CacheReadCostUsd   float64
	CacheWriteTokens   int64
	CacheWrite1hTokens int64
	CacheWriteCostUsd  float64
	ThinkingTokens     int64
	InputImageTokens   int64
	OutputImageTokens  int64
	TotalCostUsd       float64
	DurationMsSum      int64
	DurationMsCount    int64
	DurationMsMax      int64
	FirstTokenMsSum    int64
	FirstTokenMsCount  int64
	FirstTokenMsMax    int64
	LastUsedAt         pgtype.Text
	LastErrorAt        pgtype.Text
	UpdatedAt          string
}
