// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w1b_public_groups.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPublicGroupAccounts = `-- name: CountPublicGroupAccounts :one
SELECT count(*)::bigint AS total
FROM juhe_business.group_accounts
WHERE group_id = $1
`

func (q *Queries) CountPublicGroupAccounts(ctx context.Context, groupID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicGroupAccounts, groupID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPublicGroupActiveRouteStrategyLoss = `-- name: CountPublicGroupActiveRouteStrategyLoss :one
SELECT count(DISTINCT route_strategies.id)::bigint AS total
FROM juhe_business.route_strategy_groups AS target_bindings
JOIN juhe_business.groups AS target_groups
  ON target_groups.id = target_bindings.group_id
  AND target_groups.system_account_id = target_bindings.system_account_id
JOIN juhe_business.route_strategies AS route_strategies
  ON route_strategies.id = target_bindings.route_strategy_id
  AND route_strategies.system_account_id = target_bindings.system_account_id
WHERE target_bindings.group_id = $1
  AND target_bindings.status = 'active'
  AND target_groups.enabled = true
  AND route_strategies.status = 'active'
  AND NOT EXISTS (
    SELECT 1
    FROM juhe_business.route_strategy_groups AS other_bindings
    JOIN juhe_business.groups AS other_groups
      ON other_groups.id = other_bindings.group_id
      AND other_groups.system_account_id = other_bindings.system_account_id
    WHERE other_bindings.route_strategy_id = target_bindings.route_strategy_id
      AND other_bindings.system_account_id = target_bindings.system_account_id
      AND other_bindings.group_id <> target_bindings.group_id
      AND other_bindings.status = 'active'
      AND other_groups.enabled = true
    LIMIT 1
  )
`

func (q *Queries) CountPublicGroupActiveRouteStrategyLoss(ctx context.Context, groupID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicGroupActiveRouteStrategyLoss, groupID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const deletePublicGroup = `-- name: DeletePublicGroup :execrows
DELETE FROM juhe_business.groups
WHERE id = $1
  AND system_account_id = $2
`

type DeletePublicGroupParams struct {
	ID              string
	SystemAccountID string
}

func (q *Queries) DeletePublicGroup(ctx context.Context, arg DeletePublicGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublicGroup, arg.ID, arg.SystemAccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findExistingPublicGroupByName = `-- name: FindExistingPublicGroupByName :one
SELECT
  id,
  system_account_id,
  name,
  provider_code,
  description,
  enabled,
  is_default,
  group_type,
  created_at,
  updated_at
FROM juhe_business.groups
WHERE system_account_id = $1
  AND provider_code = $2
  AND lower(name) = lower($3)
LIMIT 1
`

type FindExistingPublicGroupByNameParams struct {
	SystemAccountID string
	ProviderCode    string
	Name            string
}

type FindExistingPublicGroupByNameRow struct {
	ID              string
	SystemAccountID string
	Name            string
	ProviderCode    string
	Description     pgtype.Text
	Enabled         bool
	IsDefault       bool
	GroupType       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) FindExistingPublicGroupByName(ctx context.Context, arg FindExistingPublicGroupByNameParams) (FindExistingPublicGroupByNameRow, error) {
	row := q.db.QueryRow(ctx, findExistingPublicGroupByName, arg.SystemAccountID, arg.ProviderCode, arg.Name)
	var i FindExistingPublicGroupByNameRow
	err := row.Scan(
		&i.ID,
		&i.SystemAccountID,
		&i.Name,
		&i.ProviderCode,
		&i.Description,
		&i.Enabled,
		&i.IsDefault,
		&i.GroupType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPublicGroupByID = `-- name: FindPublicGroupByID :one
SELECT
  id,
  system_account_id,
  name,
  provider_code,
  description,
  enabled,
  is_default,
  group_type,
  created_at,
  updated_at
FROM juhe_business.groups
WHERE id = $1
LIMIT 1
`

type FindPublicGroupByIDRow struct {
	ID              string
	SystemAccountID string
	Name            string
	ProviderCode    string
	Description     pgtype.Text
	Enabled         bool
	IsDefault       bool
	GroupType       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) FindPublicGroupByID(ctx context.Context, id string) (FindPublicGroupByIDRow, error) {
	row := q.db.QueryRow(ctx, findPublicGroupByID, id)
	var i FindPublicGroupByIDRow
	err := row.Scan(
		&i.ID,
		&i.SystemAccountID,
		&i.Name,
		&i.ProviderCode,
		&i.Description,
		&i.Enabled,
		&i.IsDefault,
		&i.GroupType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPublicGroupByIDForUpdate = `-- name: FindPublicGroupByIDForUpdate :one
SELECT
  id,
  system_account_id,
  name,
  provider_code,
  description,
  enabled,
  is_default,
  group_type,
  created_at,
  updated_at
FROM juhe_business.groups
WHERE id = $1
LIMIT 1
FOR UPDATE
`

type FindPublicGroupByIDForUpdateRow struct {
	ID              string
	SystemAccountID string
	Name            string
	ProviderCode    string
	Description     pgtype.Text
	Enabled         bool
	IsDefault       bool
	GroupType       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) FindPublicGroupByIDForUpdate(ctx context.Context, id string) (FindPublicGroupByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, findPublicGroupByIDForUpdate, id)
	var i FindPublicGroupByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.SystemAccountID,
		&i.Name,
		&i.ProviderCode,
		&i.Description,
		&i.Enabled,
		&i.IsDefault,
		&i.GroupType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPublicGroupProviderByCode = `-- name: FindPublicGroupProviderByCode :one
SELECT code, enabled
FROM juhe_business.providers
WHERE code = $1
LIMIT 1
`

type FindPublicGroupProviderByCodeRow struct {
	Code    string
	Enabled bool
}

func (q *Queries) FindPublicGroupProviderByCode(ctx context.Context, code string) (FindPublicGroupProviderByCodeRow, error) {
	row := q.db.QueryRow(ctx, findPublicGroupProviderByCode, code)
	var i FindPublicGroupProviderByCodeRow
	err := row.Scan(&i.Code, &i.Enabled)
	return i, err
}

const findPublicGroupTargetByID = `-- name: FindPublicGroupTargetByID :one
SELECT id, username, display_name, status
FROM juhe_business.system_accounts
WHERE id = $1
LIMIT 1
`

type FindPublicGroupTargetByIDRow struct {
	ID          string
	Username    string
	DisplayName string
	Status      string
}

func (q *Queries) FindPublicGroupTargetByID(ctx context.Context, id string) (FindPublicGroupTargetByIDRow, error) {
	row := q.db.QueryRow(ctx, findPublicGroupTargetByID, id)
	var i FindPublicGroupTargetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Status,
	)
	return i, err
}

const findPublicGroupTargetByUsername = `-- name: FindPublicGroupTargetByUsername :one
SELECT id, username, display_name, status
FROM juhe_business.system_accounts
WHERE lower(username) = lower($1)
LIMIT 1
`

type FindPublicGroupTargetByUsernameRow struct {
	ID          string
	Username    string
	DisplayName string
	Status      string
}

func (q *Queries) FindPublicGroupTargetByUsername(ctx context.Context, lower string) (FindPublicGroupTargetByUsernameRow, error) {
	row := q.db.QueryRow(ctx, findPublicGroupTargetByUsername, lower)
	var i FindPublicGroupTargetByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Status,
	)
	return i, err
}

const insertPublicGroup = `-- name: InsertPublicGroup :one
INSERT INTO juhe_business.groups (
  id, system_account_id, name, provider_code, description, enabled, is_default, group_type, scheduling_policy_json,
  created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5,
  $6, false, $7, NULL, $8, $9
)
RETURNING
  id,
  system_account_id,
  name,
  provider_code,
  description,
  enabled,
  is_default,
  group_type,
  created_at,
  updated_at
`

type InsertPublicGroupParams struct {
	ID              string
	SystemAccountID string
	Name            string
	ProviderCode    string
	Description     pgtype.Text
	Enabled         bool
	GroupType       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type InsertPublicGroupRow struct {
	ID              string
	SystemAccountID string
	Name            string
	ProviderCode    string
	Description     pgtype.Text
	Enabled         bool
	IsDefault       bool
	GroupType       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertPublicGroup(ctx context.Context, arg InsertPublicGroupParams) (InsertPublicGroupRow, error) {
	row := q.db.QueryRow(ctx, insertPublicGroup,
		arg.ID,
		arg.SystemAccountID,
		arg.Name,
		arg.ProviderCode,
		arg.Description,
		arg.Enabled,
		arg.GroupType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i InsertPublicGroupRow
	err := row.Scan(
		&i.ID,
		&i.SystemAccountID,
		&i.Name,
		&i.ProviderCode,
		&i.Description,
		&i.Enabled,
		&i.IsDefault,
		&i.GroupType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPublicGroupSystemAccount = `-- name: InsertPublicGroupSystemAccount :exec
INSERT INTO juhe_business.system_accounts (
  id, username, display_name, description, role, status, password_hash,
  must_change_password, image_generation_enabled, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, 'user', 'active', $5,
  true, false, $6, $7
)
`

type InsertPublicGroupSystemAccountParams struct {
	ID           string
	Username     string
	DisplayName  string
	Description  pgtype.Text
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertPublicGroupSystemAccount(ctx context.Context, arg InsertPublicGroupSystemAccountParams) error {
	_, err := q.db.Exec(ctx, insertPublicGroupSystemAccount,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Description,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listPublicGroups = `-- name: ListPublicGroups :many
SELECT
  id,
  system_account_id,
  name,
  provider_code,
  description,
  enabled,
  is_default,
  group_type,
  created_at,
  updated_at
FROM juhe_business.groups
WHERE system_account_id = $1
  AND ($2::text = '' OR provider_code = $2)
  AND (
    $3::boolean = false
    OR (name COLLATE "C" >= $4::text AND name COLLATE "C" < $5::text)
    OR (provider_code COLLATE "C" >= $4::text AND provider_code COLLATE "C" < $5::text)
  )
ORDER BY updated_at DESC, id DESC
LIMIT $7::int
OFFSET $6::int
`

type ListPublicGroupsParams struct {
	SystemAccountID string
	ProviderCode    string
	HasKeyword      bool
	Keyword         string
	KeywordUpper    string
	RowOffset       int32
	RowLimit        int32
}

type ListPublicGroupsRow struct {
	ID              string
	SystemAccountID string
	Name            string
	ProviderCode    string
	Description     pgtype.Text
	Enabled         bool
	IsDefault       bool
	GroupType       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListPublicGroups(ctx context.Context, arg ListPublicGroupsParams) ([]ListPublicGroupsRow, error) {
	rows, err := q.db.Query(ctx, listPublicGroups,
		arg.SystemAccountID,
		arg.ProviderCode,
		arg.HasKeyword,
		arg.Keyword,
		arg.KeywordUpper,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicGroupsRow
	for rows.Next() {
		var i ListPublicGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.SystemAccountID,
			&i.Name,
			&i.ProviderCode,
			&i.Description,
			&i.Enabled,
			&i.IsDefault,
			&i.GroupType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPublicGroupActiveRouteStrategies = `-- name: LockPublicGroupActiveRouteStrategies :many
SELECT route_strategies.id
FROM juhe_business.route_strategy_groups AS target_bindings
JOIN juhe_business.groups AS target_groups
  ON target_groups.id = target_bindings.group_id
  AND target_groups.system_account_id = target_bindings.system_account_id
JOIN juhe_business.route_strategies AS route_strategies
  ON route_strategies.id = target_bindings.route_strategy_id
  AND route_strategies.system_account_id = target_bindings.system_account_id
WHERE target_bindings.group_id = $1
  AND target_bindings.status = 'active'
  AND target_groups.enabled = true
  AND route_strategies.status = 'active'
ORDER BY route_strategies.id
FOR UPDATE OF route_strategies
`

func (q *Queries) LockPublicGroupActiveRouteStrategies(ctx context.Context, groupID string) ([]string, error) {
	rows, err := q.db.Query(ctx, lockPublicGroupActiveRouteStrategies, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePublicGroupAllFields = `-- name: UpdatePublicGroupAllFields :one
UPDATE juhe_business.groups
SET name = $1,
    provider_code = $2,
    description = $3,
    enabled = $4,
    group_type = $5,
    updated_at = $6
WHERE id = $7
  AND system_account_id = $8
RETURNING
  id,
  system_account_id,
  name,
  provider_code,
  description,
  enabled,
  is_default,
  group_type,
  created_at,
  updated_at
`

type UpdatePublicGroupAllFieldsParams struct {
	Name            string
	ProviderCode    string
	Description     pgtype.Text
	Enabled         bool
	GroupType       string
	UpdatedAt       pgtype.Timestamptz
	ID              string
	SystemAccountID string
}

type UpdatePublicGroupAllFieldsRow struct {
	ID              string
	SystemAccountID string
	Name            string
	ProviderCode    string
	Description     pgtype.Text
	Enabled         bool
	IsDefault       bool
	GroupType       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdatePublicGroupAllFields(ctx context.Context, arg UpdatePublicGroupAllFieldsParams) (UpdatePublicGroupAllFieldsRow, error) {
	row := q.db.QueryRow(ctx, updatePublicGroupAllFields,
		arg.Name,
		arg.ProviderCode,
		arg.Description,
		arg.Enabled,
		arg.GroupType,
		arg.UpdatedAt,
		arg.ID,
		arg.SystemAccountID,
	)
	var i UpdatePublicGroupAllFieldsRow
	err := row.Scan(
		&i.ID,
		&i.SystemAccountID,
		&i.Name,
		&i.ProviderCode,
		&i.Description,
		&i.Enabled,
		&i.IsDefault,
		&i.GroupType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
