// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w1b_public_api.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupPublicAPILogsBefore = `-- name: CleanupPublicAPILogsBefore :execrows
WITH stale_public_api_logs AS (
  SELECT id
  FROM juhe_dataset.public_api_logs
  WHERE created_at < $1::timestamptz
  ORDER BY created_at ASC, id ASC
  LIMIT $2::int
)
DELETE FROM juhe_dataset.public_api_logs
WHERE id IN (SELECT id FROM stale_public_api_logs)
`

type CleanupPublicAPILogsBeforeParams struct {
	CutoffCreatedAt pgtype.Timestamptz
	RowLimit        int32
}

func (q *Queries) CleanupPublicAPILogsBefore(ctx context.Context, arg CleanupPublicAPILogsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupPublicAPILogsBefore, arg.CutoffCreatedAt, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findPublicAPIAuthTokenByHash = `-- name: FindPublicAPIAuthTokenByHash :one
SELECT
  sources.id AS source_ref_id,
  sources.name AS source_name,
  sources.status AS source_status,
  sources.scopes_json AS source_scopes_json,
  sources.rate_limits_json AS source_rate_limits_json,
  sources.expires_at AS source_expires_at,
  sources.last_used_at AS source_last_used_at,
  tokens.id AS token_id,
  tokens.name AS token_name,
  tokens.token_prefix AS token_prefix,
  tokens.status AS token_status,
  tokens.scopes_json AS token_scopes_json,
  tokens.expires_at AS token_expires_at,
  tokens.last_used_at AS token_last_used_at
FROM juhe_business.external_integration_source_tokens AS tokens
JOIN juhe_business.external_integration_sources AS sources ON sources.id = tokens.source_ref_id
WHERE tokens.token_hash = $1
LIMIT 1
`

type FindPublicAPIAuthTokenByHashRow struct {
	SourceRefID          string
	SourceName           string
	SourceStatus         string
	SourceScopesJson     string
	SourceRateLimitsJson string
	SourceExpiresAt      pgtype.Timestamptz
	SourceLastUsedAt     pgtype.Timestamptz
	TokenID              string
	TokenName            string
	TokenPrefix          string
	TokenStatus          string
	TokenScopesJson      string
	TokenExpiresAt       pgtype.Timestamptz
	TokenLastUsedAt      pgtype.Timestamptz
}

func (q *Queries) FindPublicAPIAuthTokenByHash(ctx context.Context, tokenHash string) (FindPublicAPIAuthTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, findPublicAPIAuthTokenByHash, tokenHash)
	var i FindPublicAPIAuthTokenByHashRow
	err := row.Scan(
		&i.SourceRefID,
		&i.SourceName,
		&i.SourceStatus,
		&i.SourceScopesJson,
		&i.SourceRateLimitsJson,
		&i.SourceExpiresAt,
		&i.SourceLastUsedAt,
		&i.TokenID,
		&i.TokenName,
		&i.TokenPrefix,
		&i.TokenStatus,
		&i.TokenScopesJson,
		&i.TokenExpiresAt,
		&i.TokenLastUsedAt,
	)
	return i, err
}

const getPublicAPILogRetentionDays = `-- name: GetPublicAPILogRetentionDays :one
SELECT value_json
FROM juhe_business.system_settings
WHERE system_account_id = 'sys_admin'
  AND key = 'publicApiLogRetentionDays'
LIMIT 1
`

func (q *Queries) GetPublicAPILogRetentionDays(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getPublicAPILogRetentionDays)
	var value_json string
	err := row.Scan(&value_json)
	return value_json, err
}

const insertPublicAPILog = `-- name: InsertPublicAPILog :exec
INSERT INTO juhe_dataset.public_api_logs (
  id, trace_id, source_ref_id, source_name, token_id, token_name, token_prefix, is_test_token,
  method, path, query_string, client_ip, user_agent, status_code, success, duration_ms,
  request_size_bytes, response_size_bytes, request_capture_status, response_capture_status,
  request_data_json, response_data_json, error_code, error_message, started_at, ended_at, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8,
  $9, $10, $11, $12, $13, $14, $15, $16,
  $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27
)
ON CONFLICT(id) DO NOTHING
`

type InsertPublicAPILogParams struct {
	ID                    string
	TraceID               pgtype.Text
	SourceRefID           pgtype.Text
	SourceName            pgtype.Text
	TokenID               pgtype.Text
	TokenName             pgtype.Text
	TokenPrefix           pgtype.Text
	IsTestToken           bool
	Method                string
	Path                  string
	QueryString           pgtype.Text
	ClientIp              pgtype.Text
	UserAgent             pgtype.Text
	StatusCode            pgtype.Int4
	Success               bool
	DurationMs            pgtype.Int8
	RequestSizeBytes      int64
	ResponseSizeBytes     int64
	RequestCaptureStatus  string
	ResponseCaptureStatus string
	RequestDataJson       string
	ResponseDataJson      string
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	StartedAt             pgtype.Timestamptz
	EndedAt               pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) InsertPublicAPILog(ctx context.Context, arg InsertPublicAPILogParams) error {
	_, err := q.db.Exec(ctx, insertPublicAPILog,
		arg.ID,
		arg.TraceID,
		arg.SourceRefID,
		arg.SourceName,
		arg.TokenID,
		arg.TokenName,
		arg.TokenPrefix,
		arg.IsTestToken,
		arg.Method,
		arg.Path,
		arg.QueryString,
		arg.ClientIp,
		arg.UserAgent,
		arg.StatusCode,
		arg.Success,
		arg.DurationMs,
		arg.RequestSizeBytes,
		arg.ResponseSizeBytes,
		arg.RequestCaptureStatus,
		arg.ResponseCaptureStatus,
		arg.RequestDataJson,
		arg.ResponseDataJson,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.EndedAt,
		arg.CreatedAt,
	)
	return err
}

const touchPublicAPIAuthSourceLastUsed = `-- name: TouchPublicAPIAuthSourceLastUsed :exec
UPDATE juhe_business.external_integration_sources
SET last_used_at = $2,
    updated_at = $2
WHERE id = $1
`

type TouchPublicAPIAuthSourceLastUsedParams struct {
	ID         string
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) TouchPublicAPIAuthSourceLastUsed(ctx context.Context, arg TouchPublicAPIAuthSourceLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchPublicAPIAuthSourceLastUsed, arg.ID, arg.LastUsedAt)
	return err
}

const touchPublicAPIAuthTokenLastUsed = `-- name: TouchPublicAPIAuthTokenLastUsed :exec
UPDATE juhe_business.external_integration_source_tokens
SET last_used_at = $2,
    updated_at = $2
WHERE id = $1
`

type TouchPublicAPIAuthTokenLastUsedParams struct {
	ID         string
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) TouchPublicAPIAuthTokenLastUsed(ctx context.Context, arg TouchPublicAPIAuthTokenLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchPublicAPIAuthTokenLastUsed, arg.ID, arg.LastUsedAt)
	return err
}
