// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w2_management_account_test_session.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createManagementAccountTestSession = `-- name: CreateManagementAccountTestSession :one
INSERT INTO juhe_business.account_test_sessions (id, request_system_account_id, request_role, request_system_account_filter_id, status, last_heartbeat_at, created_at, updated_at)
VALUES ($1::text, $2::text, $3::text, NULLIF($4::text, ''), 'running', now(), now(), now())
RETURNING id, status, cancel_reason, last_heartbeat_at, cancel_requested_at, finished_at, created_at, updated_at
`

type CreateManagementAccountTestSessionParams struct {
	ID       string
	ActorID  string
	Role     string
	FilterID string
}

type CreateManagementAccountTestSessionRow struct {
	ID                string
	Status            string
	CancelReason      pgtype.Text
	LastHeartbeatAt   pgtype.Timestamptz
	CancelRequestedAt pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

// First-pass account test session/task contract. The Go worker is intentionally
// not part of this migration; these queries operate on the existing Node tables.
func (q *Queries) CreateManagementAccountTestSession(ctx context.Context, arg CreateManagementAccountTestSessionParams) (CreateManagementAccountTestSessionRow, error) {
	row := q.db.QueryRow(ctx, createManagementAccountTestSession,
		arg.ID,
		arg.ActorID,
		arg.Role,
		arg.FilterID,
	)
	var i CreateManagementAccountTestSessionRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CancelReason,
		&i.LastHeartbeatAt,
		&i.CancelRequestedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
