// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w2_management_auth.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeManagementLogin = `-- name: CompleteManagementLogin :one
WITH updated_account AS (
  UPDATE juhe_business.system_accounts
  SET
    last_login_at = $1::timestamptz,
    updated_at = $1::timestamptz
  WHERE id = $2::text
    AND status = 'active'
    AND password_hash = $3::text
  RETURNING
    id,
    username,
    display_name,
    description,
    role,
    status,
    must_change_password,
    image_generation_enabled,
    last_login_at,
    created_at,
    updated_at
), inserted_session AS (
  INSERT INTO juhe_business.system_sessions (
    id,
    system_account_id,
    token_hash,
    expires_at,
    created_at,
    last_seen_at
  )
  SELECT
    $4::text,
    updated_account.id,
    $5::text,
    $6::timestamptz,
    $1::timestamptz,
    $1::timestamptz
  FROM updated_account
  RETURNING
    id AS session_id,
    expires_at AS session_expires_at
)
SELECT
  updated_account.id,
  updated_account.username,
  updated_account.display_name,
  updated_account.description,
  updated_account.role,
  updated_account.status,
  updated_account.must_change_password,
  updated_account.image_generation_enabled,
  updated_account.last_login_at,
  updated_account.created_at,
  updated_account.updated_at,
  inserted_session.session_id,
  inserted_session.session_expires_at
FROM updated_account
CROSS JOIN inserted_session
`

type CompleteManagementLoginParams struct {
	LoggedInAt           pgtype.Timestamptz
	SystemAccountID      string
	VerifiedPasswordHash string
	SessionID            string
	TokenHash            string
	ExpiresAt            pgtype.Timestamptz
}

type CompleteManagementLoginRow struct {
	ID                     string
	Username               string
	DisplayName            string
	Description            pgtype.Text
	Role                   string
	Status                 string
	MustChangePassword     bool
	ImageGenerationEnabled bool
	LastLoginAt            pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	SessionID              string
	SessionExpiresAt       pgtype.Timestamptz
}

func (q *Queries) CompleteManagementLogin(ctx context.Context, arg CompleteManagementLoginParams) (CompleteManagementLoginRow, error) {
	row := q.db.QueryRow(ctx, completeManagementLogin,
		arg.LoggedInAt,
		arg.SystemAccountID,
		arg.VerifiedPasswordHash,
		arg.SessionID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i CompleteManagementLoginRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Description,
		&i.Role,
		&i.Status,
		&i.MustChangePassword,
		&i.ImageGenerationEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionID,
		&i.SessionExpiresAt,
	)
	return i, err
}

const findManagementSessionByTokenHash = `-- name: FindManagementSessionByTokenHash :one
SELECT
  ss.id,
  ss.token_hash,
  ss.expires_at,
  ss.last_seen_at,
  sa.id AS account_id,
  sa.username,
  sa.display_name,
  sa.role,
  sa.status,
  sa.must_change_password
FROM juhe_business.system_sessions AS ss
INNER JOIN juhe_business.system_accounts AS sa
  ON sa.id = ss.system_account_id
WHERE ss.token_hash = $1
LIMIT 1
`

type FindManagementSessionByTokenHashRow struct {
	ID                 string
	TokenHash          string
	ExpiresAt          pgtype.Timestamptz
	LastSeenAt         pgtype.Timestamptz
	AccountID          string
	Username           string
	DisplayName        string
	Role               string
	Status             string
	MustChangePassword bool
}

func (q *Queries) FindManagementSessionByTokenHash(ctx context.Context, tokenHash string) (FindManagementSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findManagementSessionByTokenHash, tokenHash)
	var i FindManagementSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.AccountID,
		&i.Username,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.MustChangePassword,
	)
	return i, err
}

const findManagementSystemAccountPasswordByUsername = `-- name: FindManagementSystemAccountPasswordByUsername :one
SELECT
  id,
  username,
  status,
  password_hash
FROM juhe_business.system_accounts
WHERE lower(username) = lower($1::text)
LIMIT 1
`

type FindManagementSystemAccountPasswordByUsernameRow struct {
	ID           string
	Username     string
	Status       string
	PasswordHash string
}

func (q *Queries) FindManagementSystemAccountPasswordByUsername(ctx context.Context, username string) (FindManagementSystemAccountPasswordByUsernameRow, error) {
	row := q.db.QueryRow(ctx, findManagementSystemAccountPasswordByUsername, username)
	var i FindManagementSystemAccountPasswordByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Status,
		&i.PasswordHash,
	)
	return i, err
}

const listManagementSessionsForAccount = `-- name: ListManagementSessionsForAccount :many
SELECT
  id,
  expires_at,
  created_at,
  last_seen_at
FROM juhe_business.system_sessions
WHERE system_account_id = $1::text
  AND expires_at > $2::timestamptz
ORDER BY last_seen_at DESC, created_at DESC, id DESC
LIMIT $4::int
OFFSET $3::int
`

type ListManagementSessionsForAccountParams struct {
	SystemAccountID string
	NowAt           pgtype.Timestamptz
	OffsetRows      int32
	LimitRows       int32
}

type ListManagementSessionsForAccountRow struct {
	ID         string
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

func (q *Queries) ListManagementSessionsForAccount(ctx context.Context, arg ListManagementSessionsForAccountParams) ([]ListManagementSessionsForAccountRow, error) {
	rows, err := q.db.Query(ctx, listManagementSessionsForAccount,
		arg.SystemAccountID,
		arg.NowAt,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementSessionsForAccountRow
	for rows.Next() {
		var i ListManagementSessionsForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeManagementSessionByTokenHash = `-- name: RevokeManagementSessionByTokenHash :exec
DELETE FROM juhe_business.system_sessions
WHERE token_hash = $1
`

func (q *Queries) RevokeManagementSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeManagementSessionByTokenHash, tokenHash)
	return err
}

const revokeManagementSessionForAccount = `-- name: RevokeManagementSessionForAccount :execrows
DELETE FROM juhe_business.system_sessions
WHERE system_account_id = $1::text
  AND id = $2::text
`

type RevokeManagementSessionForAccountParams struct {
	SystemAccountID string
	SessionID       string
}

func (q *Queries) RevokeManagementSessionForAccount(ctx context.Context, arg RevokeManagementSessionForAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeManagementSessionForAccount, arg.SystemAccountID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOtherManagementSessionsForAccount = `-- name: RevokeOtherManagementSessionsForAccount :exec
DELETE FROM juhe_business.system_sessions
WHERE system_account_id = $1
  AND id <> $2
`

type RevokeOtherManagementSessionsForAccountParams struct {
	SystemAccountID string
	ID              string
}

func (q *Queries) RevokeOtherManagementSessionsForAccount(ctx context.Context, arg RevokeOtherManagementSessionsForAccountParams) error {
	_, err := q.db.Exec(ctx, revokeOtherManagementSessionsForAccount, arg.SystemAccountID, arg.ID)
	return err
}

const touchManagementSession = `-- name: TouchManagementSession :exec
UPDATE juhe_business.system_sessions
SET last_seen_at = $1::timestamptz
WHERE id = $2::text
  AND last_seen_at < $3::timestamptz
`

type TouchManagementSessionParams struct {
	LastSeenAt pgtype.Timestamptz
	SessionID  string
	Cutoff     pgtype.Timestamptz
}

func (q *Queries) TouchManagementSession(ctx context.Context, arg TouchManagementSessionParams) error {
	_, err := q.db.Exec(ctx, touchManagementSession, arg.LastSeenAt, arg.SessionID, arg.Cutoff)
	return err
}

const updateManagementCurrentUserPassword = `-- name: UpdateManagementCurrentUserPassword :one
UPDATE juhe_business.system_accounts
SET
  password_hash = $1::text,
  must_change_password = false,
  updated_at = $2::timestamptz
WHERE id = $3::text
  AND status = 'active'
RETURNING
  id,
  username,
  display_name,
  description,
  role,
  status,
  must_change_password,
  image_generation_enabled,
  last_login_at,
  created_at,
  updated_at
`

type UpdateManagementCurrentUserPasswordParams struct {
	PasswordHash    string
	UpdatedAt       pgtype.Timestamptz
	SystemAccountID string
}

type UpdateManagementCurrentUserPasswordRow struct {
	ID                     string
	Username               string
	DisplayName            string
	Description            pgtype.Text
	Role                   string
	Status                 string
	MustChangePassword     bool
	ImageGenerationEnabled bool
	LastLoginAt            pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) UpdateManagementCurrentUserPassword(ctx context.Context, arg UpdateManagementCurrentUserPasswordParams) (UpdateManagementCurrentUserPasswordRow, error) {
	row := q.db.QueryRow(ctx, updateManagementCurrentUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.SystemAccountID)
	var i UpdateManagementCurrentUserPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Description,
		&i.Role,
		&i.Status,
		&i.MustChangePassword,
		&i.ImageGenerationEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateManagementCurrentUserProfile = `-- name: UpdateManagementCurrentUserProfile :one
WITH current_account AS (
  SELECT
    id,
    display_name,
    status,
    role,
    must_change_password
  FROM juhe_business.system_accounts
  WHERE id = $1::text
  FOR UPDATE
), updated_account AS (
  UPDATE juhe_business.system_accounts AS system_accounts
  SET
    display_name = $2::text,
    updated_at = $3::timestamptz
  FROM current_account
  WHERE system_accounts.id = current_account.id
    AND current_account.status = 'active'
    AND (
      current_account.role IN ('super_admin', 'admin')
      OR current_account.must_change_password = false
    )
  RETURNING
    current_account.display_name AS previous_display_name,
    system_accounts.id,
    system_accounts.username,
    system_accounts.display_name,
    system_accounts.role,
    system_accounts.must_change_password
)
SELECT
  previous_display_name,
  id,
  username,
  display_name,
  role,
  must_change_password
FROM updated_account
`

type UpdateManagementCurrentUserProfileParams struct {
	SystemAccountID string
	DisplayName     string
	UpdatedAt       pgtype.Timestamptz
}

type UpdateManagementCurrentUserProfileRow struct {
	PreviousDisplayName string
	ID                  string
	Username            string
	DisplayName         string
	Role                string
	MustChangePassword  bool
}

func (q *Queries) UpdateManagementCurrentUserProfile(ctx context.Context, arg UpdateManagementCurrentUserProfileParams) (UpdateManagementCurrentUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateManagementCurrentUserProfile, arg.SystemAccountID, arg.DisplayName, arg.UpdatedAt)
	var i UpdateManagementCurrentUserProfileRow
	err := row.Scan(
		&i.PreviousDisplayName,
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Role,
		&i.MustChangePassword,
	)
	return i, err
}
