// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w2_management_account_test_options.sql

package postgresqueries

import (
	"context"
)

const getManagementAccountTestModelCapabilitiesSource = `-- name: GetManagementAccountTestModelCapabilitiesSource :one
WITH test_model_capability_sources AS (
  SELECT
    accounts.id,
    accounts.system_account_id AS owner_system_account_id,
    accounts.id AS model_mapping_account_id,
    accounts.provider_code,
    accounts.provider_protocol_profile_id,
    accounts.protocol_code,
    accounts.protocol_version,
    accounts.type,
    accounts.client_compatibility,
    accounts.health_check_model,
    accounts.health_check_endpoint_mode,
    accounts.credentials_encrypted
  FROM juhe_business.accounts AS accounts
  WHERE accounts.id = $1::text
    AND accounts.deleted_at IS NULL
    AND accounts.authorization_instance_source_account_id IS NULL
    AND accounts.authorization_instance_authorization_id IS NULL
    AND accounts.authorization_instance_owner_system_account_id IS NULL
    AND (
      $2::text = ''
      OR accounts.system_account_id = $2::text
    )

  UNION ALL

  SELECT
    accounts.id,
    COALESCE(
      accounts.authorization_instance_owner_system_account_id,
      resource_authorizations.resource_owner_system_account_id
    ) AS owner_system_account_id,
    source_accounts.id AS model_mapping_account_id,
    source_accounts.provider_code,
    source_accounts.provider_protocol_profile_id,
    source_accounts.protocol_code,
    source_accounts.protocol_version,
    source_accounts.type,
    source_accounts.client_compatibility,
    source_accounts.health_check_model,
    source_accounts.health_check_endpoint_mode,
    source_accounts.credentials_encrypted
  FROM juhe_business.accounts AS accounts
  INNER JOIN juhe_business.accounts AS source_accounts
    ON source_accounts.id = accounts.authorization_instance_source_account_id
    AND source_accounts.deleted_at IS NULL
    AND source_accounts.authorization_instance_source_account_id IS NULL
    AND source_accounts.authorization_instance_authorization_id IS NULL
    AND source_accounts.authorization_instance_owner_system_account_id IS NULL
  INNER JOIN juhe_business.resource_authorizations AS resource_authorizations
    ON resource_authorizations.id = accounts.authorization_instance_authorization_id
    AND resource_authorizations.resource_type = 'account'
    AND resource_authorizations.resource_id = accounts.authorization_instance_source_account_id
    AND resource_authorizations.resource_owner_system_account_id = source_accounts.system_account_id
    AND (
      accounts.authorization_instance_owner_system_account_id IS NULL
      OR accounts.authorization_instance_owner_system_account_id = resource_authorizations.resource_owner_system_account_id
    )
    AND resource_authorizations.grantee_system_account_id = accounts.system_account_id
    AND resource_authorizations.status IN ('active', 'paused', 'expired')
  WHERE accounts.id = $1::text
    AND accounts.deleted_at IS NULL
    AND (
      $2::text = ''
      OR accounts.system_account_id = $2::text
    )
)
SELECT
  test_model_capability_sources.id,
  test_model_capability_sources.owner_system_account_id,
  test_model_capability_sources.model_mapping_account_id,
  test_model_capability_sources.provider_code,
  test_model_capability_sources.provider_protocol_profile_id,
  test_model_capability_sources.protocol_code,
  test_model_capability_sources.protocol_version,
  test_model_capability_sources.type,
  test_model_capability_sources.client_compatibility,
  test_model_capability_sources.health_check_model,
  test_model_capability_sources.health_check_endpoint_mode,
  test_model_capability_sources.credentials_encrypted
FROM test_model_capability_sources
`

type GetManagementAccountTestModelCapabilitiesSourceParams struct {
	AccountID       string
	SystemAccountID string
}

type GetManagementAccountTestModelCapabilitiesSourceRow struct {
	ID                        string
	OwnerSystemAccountID      string
	ModelMappingAccountID     string
	ProviderCode              string
	ProviderProtocolProfileID string
	ProtocolCode              string
	ProtocolVersion           string
	Type                      string
	ClientCompatibility       string
	HealthCheckModel          string
	HealthCheckEndpointMode   string
	CredentialsEncrypted      string
}

func (q *Queries) GetManagementAccountTestModelCapabilitiesSource(ctx context.Context, arg GetManagementAccountTestModelCapabilitiesSourceParams) (GetManagementAccountTestModelCapabilitiesSourceRow, error) {
	row := q.db.QueryRow(ctx, getManagementAccountTestModelCapabilitiesSource, arg.AccountID, arg.SystemAccountID)
	var i GetManagementAccountTestModelCapabilitiesSourceRow
	err := row.Scan(
		&i.ID,
		&i.OwnerSystemAccountID,
		&i.ModelMappingAccountID,
		&i.ProviderCode,
		&i.ProviderProtocolProfileID,
		&i.ProtocolCode,
		&i.ProtocolVersion,
		&i.Type,
		&i.ClientCompatibility,
		&i.HealthCheckModel,
		&i.HealthCheckEndpointMode,
		&i.CredentialsEncrypted,
	)
	return i, err
}

const getManagementAccountTestOptionListSource = `-- name: GetManagementAccountTestOptionListSource :one
WITH test_option_list_sources AS (
  SELECT
    accounts.id,
    accounts.system_account_id AS owner_system_account_id,
    accounts.provider_code,
    accounts.provider_protocol_profile_id,
    accounts.protocol_code,
    accounts.protocol_version,
    accounts.type,
    accounts.client_compatibility,
    accounts.health_check_model
  FROM juhe_business.accounts AS accounts
  WHERE accounts.id = $1::text
    AND accounts.deleted_at IS NULL
    AND accounts.authorization_instance_source_account_id IS NULL
    AND accounts.authorization_instance_authorization_id IS NULL
    AND accounts.authorization_instance_owner_system_account_id IS NULL
    AND (
      $2::text = ''
      OR accounts.system_account_id = $2::text
    )

  UNION ALL

  SELECT
    accounts.id,
    COALESCE(
      accounts.authorization_instance_owner_system_account_id,
      resource_authorizations.resource_owner_system_account_id
    ) AS owner_system_account_id,
    source_accounts.provider_code,
    source_accounts.provider_protocol_profile_id,
    source_accounts.protocol_code,
    source_accounts.protocol_version,
    source_accounts.type,
    source_accounts.client_compatibility,
    source_accounts.health_check_model
  FROM juhe_business.accounts AS accounts
  INNER JOIN juhe_business.accounts AS source_accounts
    ON source_accounts.id = accounts.authorization_instance_source_account_id
    AND source_accounts.deleted_at IS NULL
    AND source_accounts.authorization_instance_source_account_id IS NULL
    AND source_accounts.authorization_instance_authorization_id IS NULL
    AND source_accounts.authorization_instance_owner_system_account_id IS NULL
  INNER JOIN juhe_business.resource_authorizations AS resource_authorizations
    ON resource_authorizations.id = accounts.authorization_instance_authorization_id
    AND resource_authorizations.resource_type = 'account'
    AND resource_authorizations.resource_id = accounts.authorization_instance_source_account_id
    AND resource_authorizations.resource_owner_system_account_id = source_accounts.system_account_id
    AND (
      accounts.authorization_instance_owner_system_account_id IS NULL
      OR accounts.authorization_instance_owner_system_account_id = resource_authorizations.resource_owner_system_account_id
    )
    AND resource_authorizations.grantee_system_account_id = accounts.system_account_id
    AND resource_authorizations.status IN ('active', 'paused', 'expired')
  WHERE accounts.id = $1::text
    AND accounts.deleted_at IS NULL
    AND (
      $2::text = ''
      OR accounts.system_account_id = $2::text
    )
)
SELECT
  test_option_list_sources.id,
  test_option_list_sources.owner_system_account_id,
  test_option_list_sources.provider_code,
  test_option_list_sources.provider_protocol_profile_id,
  test_option_list_sources.protocol_code,
  test_option_list_sources.protocol_version,
  test_option_list_sources.type,
  test_option_list_sources.client_compatibility,
  test_option_list_sources.health_check_model
FROM test_option_list_sources
`

type GetManagementAccountTestOptionListSourceParams struct {
	AccountID       string
	SystemAccountID string
}

type GetManagementAccountTestOptionListSourceRow struct {
	ID                        string
	OwnerSystemAccountID      string
	ProviderCode              string
	ProviderProtocolProfileID string
	ProtocolCode              string
	ProtocolVersion           string
	Type                      string
	ClientCompatibility       string
	HealthCheckModel          string
}

func (q *Queries) GetManagementAccountTestOptionListSource(ctx context.Context, arg GetManagementAccountTestOptionListSourceParams) (GetManagementAccountTestOptionListSourceRow, error) {
	row := q.db.QueryRow(ctx, getManagementAccountTestOptionListSource, arg.AccountID, arg.SystemAccountID)
	var i GetManagementAccountTestOptionListSourceRow
	err := row.Scan(
		&i.ID,
		&i.OwnerSystemAccountID,
		&i.ProviderCode,
		&i.ProviderProtocolProfileID,
		&i.ProtocolCode,
		&i.ProtocolVersion,
		&i.Type,
		&i.ClientCompatibility,
		&i.HealthCheckModel,
	)
	return i, err
}

const getManagementAccountTestOptionsSource = `-- name: GetManagementAccountTestOptionsSource :one
WITH test_options_sources AS (
  SELECT
    accounts.id,
    accounts.system_account_id AS owner_system_account_id,
    accounts.id AS model_mapping_account_id,
    accounts.provider_code,
    accounts.provider_protocol_profile_id,
    accounts.protocol_code,
    accounts.protocol_version,
    accounts.type,
    accounts.client_compatibility,
    accounts.health_check_model,
    accounts.health_check_endpoint_mode,
    accounts.credentials_encrypted
  FROM juhe_business.accounts AS accounts
  WHERE accounts.id = $1::text
    AND accounts.deleted_at IS NULL
    AND accounts.authorization_instance_source_account_id IS NULL
    AND accounts.authorization_instance_authorization_id IS NULL
    AND accounts.authorization_instance_owner_system_account_id IS NULL
    AND (
      $2::text = ''
      OR accounts.system_account_id = $2::text
    )

  UNION ALL

  SELECT
    accounts.id,
    COALESCE(
      accounts.authorization_instance_owner_system_account_id,
      resource_authorizations.resource_owner_system_account_id
    ) AS owner_system_account_id,
    source_accounts.id AS model_mapping_account_id,
    source_accounts.provider_code,
    source_accounts.provider_protocol_profile_id,
    source_accounts.protocol_code,
    source_accounts.protocol_version,
    source_accounts.type,
    source_accounts.client_compatibility,
    source_accounts.health_check_model,
    source_accounts.health_check_endpoint_mode,
    source_accounts.credentials_encrypted
  FROM juhe_business.accounts AS accounts
  INNER JOIN juhe_business.accounts AS source_accounts
    ON source_accounts.id = accounts.authorization_instance_source_account_id
    AND source_accounts.deleted_at IS NULL
    AND source_accounts.authorization_instance_source_account_id IS NULL
    AND source_accounts.authorization_instance_authorization_id IS NULL
    AND source_accounts.authorization_instance_owner_system_account_id IS NULL
  INNER JOIN juhe_business.resource_authorizations AS resource_authorizations
    ON resource_authorizations.id = accounts.authorization_instance_authorization_id
    AND resource_authorizations.resource_type = 'account'
    AND resource_authorizations.resource_id = accounts.authorization_instance_source_account_id
    AND resource_authorizations.resource_owner_system_account_id = source_accounts.system_account_id
    AND (
      accounts.authorization_instance_owner_system_account_id IS NULL
      OR accounts.authorization_instance_owner_system_account_id = resource_authorizations.resource_owner_system_account_id
    )
    AND resource_authorizations.grantee_system_account_id = accounts.system_account_id
    AND resource_authorizations.status IN ('active', 'paused', 'expired')
  WHERE accounts.id = $1::text
    AND accounts.deleted_at IS NULL
    AND (
      $2::text = ''
      OR accounts.system_account_id = $2::text
    )
)
SELECT
  test_options_sources.id,
  test_options_sources.owner_system_account_id,
  test_options_sources.model_mapping_account_id,
  test_options_sources.provider_code,
  test_options_sources.provider_protocol_profile_id,
  test_options_sources.protocol_code,
  test_options_sources.protocol_version,
  test_options_sources.type,
  test_options_sources.client_compatibility,
  test_options_sources.health_check_model,
  test_options_sources.health_check_endpoint_mode,
  test_options_sources.credentials_encrypted
FROM test_options_sources
`

type GetManagementAccountTestOptionsSourceParams struct {
	AccountID       string
	SystemAccountID string
}

type GetManagementAccountTestOptionsSourceRow struct {
	ID                        string
	OwnerSystemAccountID      string
	ModelMappingAccountID     string
	ProviderCode              string
	ProviderProtocolProfileID string
	ProtocolCode              string
	ProtocolVersion           string
	Type                      string
	ClientCompatibility       string
	HealthCheckModel          string
	HealthCheckEndpointMode   string
	CredentialsEncrypted      string
}

func (q *Queries) GetManagementAccountTestOptionsSource(ctx context.Context, arg GetManagementAccountTestOptionsSourceParams) (GetManagementAccountTestOptionsSourceRow, error) {
	row := q.db.QueryRow(ctx, getManagementAccountTestOptionsSource, arg.AccountID, arg.SystemAccountID)
	var i GetManagementAccountTestOptionsSourceRow
	err := row.Scan(
		&i.ID,
		&i.OwnerSystemAccountID,
		&i.ModelMappingAccountID,
		&i.ProviderCode,
		&i.ProviderProtocolProfileID,
		&i.ProtocolCode,
		&i.ProtocolVersion,
		&i.Type,
		&i.ClientCompatibility,
		&i.HealthCheckModel,
		&i.HealthCheckEndpointMode,
		&i.CredentialsEncrypted,
	)
	return i, err
}

const listManagementAccountTestModelCatalog = `-- name: ListManagementAccountTestModelCatalog :many
WITH source_provider_codes AS (
  SELECT $4::text AS code
  WHERE $4::text NOT IN ('openai', 'hybrid')

  UNION

  SELECT providers.code
  FROM juhe_business.providers AS providers
  WHERE $4::text = 'openai'
    AND providers.enabled = true
    AND EXISTS (
      SELECT 1
      FROM juhe_business.provider_protocol_profiles AS profiles
      WHERE profiles.provider_code = providers.code
        AND profiles.enabled = true
        AND profiles.protocol_code = 'openai'
        AND profiles.protocol_version = 'v1'
    )

  UNION

  SELECT providers.code
  FROM juhe_business.providers AS providers
  WHERE $4::text = 'hybrid'
    AND providers.enabled = true
    AND providers.code <> 'hybrid'
    AND EXISTS (
      SELECT 1
      FROM juhe_business.provider_protocol_profiles AS profiles
      WHERE profiles.provider_code = providers.code
        AND profiles.enabled = true
        AND (
          (profiles.protocol_code = 'openai' AND profiles.protocol_version = 'v1')
          OR (profiles.protocol_code = 'anthropic' AND profiles.protocol_version = 'v1')
          OR (profiles.protocol_code = 'gemini' AND profiles.protocol_version = 'v1beta')
        )
    )
), candidate_models AS (
  SELECT
    catalog.id,
    catalog.provider_code,
    catalog.model,
    'built_in'::text AS scope,
    COALESCE(catalog.mode, '')::text AS mode,
    catalog.supported_api_protocols_json
  FROM juhe_business.provider_model_catalog AS catalog
  INNER JOIN source_provider_codes AS sources ON sources.code = catalog.provider_code
  WHERE ($4::text <> 'openai' OR catalog.provider_code <> 'openai')
    AND catalog.status = 'active'
    AND catalog.catalog_visible = true
    AND (
      catalog.shutdown_date IS NULL
      OR btrim(catalog.shutdown_date) = ''
      OR catalog.shutdown_date > CURRENT_DATE::text
    )
    AND (
      cardinality($1::text[]) = 0
      OR catalog.model = ANY($1::text[])
    )
    AND (
      $5::text = ''
      OR strpos(lower(catalog.model), lower($5::text)) > 0
      OR catalog.model = ANY($3::text[])
    )

  UNION ALL

  SELECT
    custom_models.id,
    custom_models.provider_code,
    custom_models.model,
    custom_models.scope,
    COALESCE(custom_models.mode, '')::text AS mode,
    custom_models.supported_api_protocols_json
  FROM juhe_business.custom_provider_models AS custom_models
  INNER JOIN source_provider_codes AS sources ON sources.code = custom_models.provider_code
  WHERE custom_models.status = 'active'
    AND custom_models.catalog_visible = true
    AND (
      custom_models.shutdown_date IS NULL
      OR btrim(custom_models.shutdown_date) = ''
      OR custom_models.shutdown_date > CURRENT_DATE::text
    )
    AND (
      (custom_models.scope = 'global' AND custom_models.system_account_id IS NULL)
      OR (
        $6::text <> ''
        AND custom_models.scope = 'personal'
        AND custom_models.system_account_id = $6::text
      )
    )
    AND (
      cardinality($1::text[]) = 0
      OR custom_models.model = ANY($1::text[])
    )
    AND (
      $5::text = ''
      OR strpos(lower(custom_models.model), lower($5::text)) > 0
      OR custom_models.model = ANY($3::text[])
    )
), ranked_models AS (
  SELECT
    candidate_models.id, candidate_models.provider_code, candidate_models.model, candidate_models.scope, candidate_models.mode, candidate_models.supported_api_protocols_json,
    row_number() OVER (
      PARTITION BY
        CASE
          WHEN $4::text = 'hybrid'
          THEN candidate_models.provider_code
          ELSE ''
        END,
        candidate_models.model
      ORDER BY
        CASE candidate_models.scope
          WHEN 'personal' THEN 3
          WHEN 'global' THEN 2
          ELSE 1
        END DESC,
        candidate_models.provider_code ASC,
        candidate_models.id ASC
    ) AS scope_rank
  FROM candidate_models
), windowed_models AS (
  SELECT
    ranked_models.id, ranked_models.provider_code, ranked_models.model, ranked_models.scope, ranked_models.mode, ranked_models.supported_api_protocols_json, ranked_models.scope_rank,
    row_number() OVER (
      PARTITION BY
        CASE
          WHEN $4::text = 'hybrid'
          THEN ranked_models.provider_code
          ELSE ''
        END
      ORDER BY
        (ranked_models.model = ANY($3::text[])) DESC,
        ranked_models.model COLLATE "C" ASC,
        ranked_models.provider_code ASC,
        ranked_models.id ASC
    ) AS provider_window_rank
  FROM ranked_models
  WHERE ranked_models.scope_rank = 1
)
SELECT
  windowed_models.id,
  windowed_models.provider_code,
  windowed_models.model,
  windowed_models.scope,
  windowed_models.mode,
  windowed_models.supported_api_protocols_json
FROM windowed_models
WHERE windowed_models.provider_window_rank <=
  CASE
    WHEN cardinality($1::text[]) > 0
      THEN LEAST(500, GREATEST(1, cardinality($1::text[]) * 50))
    ELSE $2::integer + cardinality($3::text[])
  END
ORDER BY
  (windowed_models.model = ANY($3::text[])) DESC,
  windowed_models.model COLLATE "C" ASC,
  windowed_models.provider_code ASC,
  windowed_models.id ASC
`

type ListManagementAccountTestModelCatalogParams struct {
	ModelIds             []string
	ResultLimit          int32
	SelectedIds          []string
	ProviderCode         string
	Keyword              string
	OwnerSystemAccountID string
}

type ListManagementAccountTestModelCatalogRow struct {
	ID                        string
	ProviderCode              string
	Model                     string
	Scope                     string
	Mode                      string
	SupportedApiProtocolsJson string
}

func (q *Queries) ListManagementAccountTestModelCatalog(ctx context.Context, arg ListManagementAccountTestModelCatalogParams) ([]ListManagementAccountTestModelCatalogRow, error) {
	rows, err := q.db.Query(ctx, listManagementAccountTestModelCatalog,
		arg.ModelIds,
		arg.ResultLimit,
		arg.SelectedIds,
		arg.ProviderCode,
		arg.Keyword,
		arg.OwnerSystemAccountID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementAccountTestModelCatalogRow
	for rows.Next() {
		var i ListManagementAccountTestModelCatalogRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderCode,
			&i.Model,
			&i.Scope,
			&i.Mode,
			&i.SupportedApiProtocolsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagementAccountTestOptionModelMappings = `-- name: ListManagementAccountTestOptionModelMappings :many
SELECT
  account_model_mappings.source_model,
  account_model_mappings.source_endpoint_family,
  account_model_mappings.upstream_model,
  account_model_mappings.upstream_endpoint_family,
  account_model_mappings.enabled
FROM juhe_business.account_model_mappings AS account_model_mappings
WHERE account_model_mappings.account_id = $1::text
ORDER BY
  account_model_mappings.source_model ASC,
  account_model_mappings.source_endpoint_family ASC
`

type ListManagementAccountTestOptionModelMappingsRow struct {
	SourceModel            string
	SourceEndpointFamily   string
	UpstreamModel          string
	UpstreamEndpointFamily string
	Enabled                bool
}

func (q *Queries) ListManagementAccountTestOptionModelMappings(ctx context.Context, accountID string) ([]ListManagementAccountTestOptionModelMappingsRow, error) {
	rows, err := q.db.Query(ctx, listManagementAccountTestOptionModelMappings, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementAccountTestOptionModelMappingsRow
	for rows.Next() {
		var i ListManagementAccountTestOptionModelMappingsRow
		if err := rows.Scan(
			&i.SourceModel,
			&i.SourceEndpointFamily,
			&i.UpstreamModel,
			&i.UpstreamEndpointFamily,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagementAccountTestOptionModelMappingsBySourceModel = `-- name: ListManagementAccountTestOptionModelMappingsBySourceModel :many
SELECT
  account_model_mappings.source_model,
  account_model_mappings.source_endpoint_family,
  account_model_mappings.upstream_model,
  account_model_mappings.upstream_endpoint_family,
  account_model_mappings.enabled
FROM juhe_business.account_model_mappings AS account_model_mappings
WHERE account_model_mappings.account_id = $1::text
  AND account_model_mappings.source_model = $2::text
ORDER BY account_model_mappings.source_endpoint_family ASC
`

type ListManagementAccountTestOptionModelMappingsBySourceModelParams struct {
	AccountID   string
	SourceModel string
}

type ListManagementAccountTestOptionModelMappingsBySourceModelRow struct {
	SourceModel            string
	SourceEndpointFamily   string
	UpstreamModel          string
	UpstreamEndpointFamily string
	Enabled                bool
}

func (q *Queries) ListManagementAccountTestOptionModelMappingsBySourceModel(ctx context.Context, arg ListManagementAccountTestOptionModelMappingsBySourceModelParams) ([]ListManagementAccountTestOptionModelMappingsBySourceModelRow, error) {
	rows, err := q.db.Query(ctx, listManagementAccountTestOptionModelMappingsBySourceModel, arg.AccountID, arg.SourceModel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementAccountTestOptionModelMappingsBySourceModelRow
	for rows.Next() {
		var i ListManagementAccountTestOptionModelMappingsBySourceModelRow
		if err := rows.Scan(
			&i.SourceModel,
			&i.SourceEndpointFamily,
			&i.UpstreamModel,
			&i.UpstreamEndpointFamily,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
