// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w2_management_account_update.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateManagementAccount = `-- name: UpdateManagementAccount :one
WITH current_target AS MATERIALIZED (
  SELECT accounts.id, accounts.system_account_id, accounts.provider_code, accounts.provider_protocol_profile_id, accounts.protocol_code, accounts.protocol_version, accounts.name, accounts.type, accounts.status, accounts.credentials_encrypted, accounts.credential_fingerprint, accounts.credential_mask, accounts.concurrency_limit, accounts.priority, accounts.super_priority_enabled, accounts.fallback_enabled, accounts.client_compatibility, accounts.schedulable, accounts.availability_schedule_json, accounts.availability_schedule_next_check_at, accounts.notes, accounts.account_expires_at, accounts.last_used_at, accounts.cooldown_until, accounts.last_error_code, accounts.last_error_message, accounts.health_check_model, accounts.health_check_endpoint_mode, accounts.deleted_at, accounts.deleted_by, accounts.created_at, accounts.updated_at, accounts.authorization_instance_source_account_id, accounts.authorization_instance_authorization_id, accounts.authorization_instance_owner_system_account_id, accounts.proxy_profile_id, accounts.next_health_check_at, accounts.health_check_failure_count, accounts.last_health_check_status_code, accounts.last_health_check_error_code, accounts.last_health_check_error_message, accounts.config_revision, accounts.health_check_failure_started_at, accounts.last_error_trace_id, accounts.last_health_check_trace_id, accounts.temporary_unavailable_continuous_probe_enabled, accounts.cooldown_retest_failure_count, accounts.cooldown_retest_observation_started_at, accounts.cooldown_retest_last_at, accounts.cooldown_retest_last_status_code, accounts.last_health_check_at, accounts.last_health_success_at, accounts.stream_failure_count, accounts.stream_failure_window_started_at, accounts.balance_query_enabled, accounts.balance_query_config_json, accounts.balance_query_next_refresh_at
  FROM juhe_business.accounts AS accounts
  INNER JOIN juhe_business.providers AS providers
    ON providers.code = accounts.provider_code AND providers.enabled = true
  INNER JOIN juhe_business.provider_protocol_profiles AS profiles
    ON profiles.id = accounts.provider_protocol_profile_id
    AND profiles.provider_code = accounts.provider_code
    AND profiles.enabled = true
  WHERE accounts.id = $4::text
    AND accounts.system_account_id = $5::text
    AND accounts.config_revision = $6::int
    AND accounts.deleted_at IS NULL
    AND accounts.authorization_instance_authorization_id IS NULL
  FOR UPDATE OF accounts
)
UPDATE juhe_business.accounts AS accounts
SET credentials_encrypted = CASE
      WHEN $1::boolean THEN $2::text
      ELSE accounts.credentials_encrypted
    END,
    config_revision = config_revision + 1,
    updated_at = $3::timestamptz
FROM current_target
WHERE accounts.id = current_target.id
RETURNING accounts.id, accounts.system_account_id, accounts.config_revision
`

type UpdateManagementAccountParams struct {
	HasCredentials         bool
	CredentialsEncrypted   string
	UpdatedAt              pgtype.Timestamptz
	AccountID              string
	SystemAccountID        string
	ExpectedConfigRevision int32
}

type UpdateManagementAccountRow struct {
	ID              string
	SystemAccountID string
	ConfigRevision  int32
}

// First-pass account PATCH query. The Go adapter executes the equivalent CTE in
// managementaccountupdate.go so this slice can remain independent of router wiring.
func (q *Queries) UpdateManagementAccount(ctx context.Context, arg UpdateManagementAccountParams) (UpdateManagementAccountRow, error) {
	row := q.db.QueryRow(ctx, updateManagementAccount,
		arg.HasCredentials,
		arg.CredentialsEncrypted,
		arg.UpdatedAt,
		arg.AccountID,
		arg.SystemAccountID,
		arg.ExpectedConfigRevision,
	)
	var i UpdateManagementAccountRow
	err := row.Scan(&i.ID, &i.SystemAccountID, &i.ConfigRevision)
	return i, err
}
