// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w2_management_account_tags.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listManagementAccountTags = `-- name: ListManagementAccountTags :many
SELECT
  account_tags.id,
  account_tags.name,
  count(accounts.id)::bigint AS account_count,
  account_tags.created_at,
  account_tags.updated_at
FROM juhe_business.account_tags AS account_tags
LEFT JOIN juhe_business.account_tag_bindings AS account_tag_bindings
  ON account_tag_bindings.tag_id = account_tags.id
  AND account_tag_bindings.system_account_id = account_tags.system_account_id
LEFT JOIN juhe_business.accounts AS accounts
  ON accounts.id = account_tag_bindings.account_id
  AND accounts.system_account_id = account_tag_bindings.system_account_id
  AND accounts.deleted_at IS NULL
WHERE account_tags.system_account_id = $1::text
GROUP BY
  account_tags.id,
  account_tags.name,
  account_tags.created_at,
  account_tags.updated_at
ORDER BY account_tags.name ASC, account_tags.id ASC
`

type ListManagementAccountTagsRow struct {
	ID           string
	Name         string
	AccountCount int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListManagementAccountTags(ctx context.Context, systemAccountID string) ([]ListManagementAccountTagsRow, error) {
	rows, err := q.db.Query(ctx, listManagementAccountTags, systemAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementAccountTagsRow
	for rows.Next() {
		var i ListManagementAccountTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AccountCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
