// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w2_management_account_options.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listManagementAccountOptions = `-- name: ListManagementAccountOptions :many
WITH owner_account_rows AS (
  SELECT
    accounts.id,
    accounts.system_account_id,
    COALESCE(NULLIF(system_accounts.display_name, ''), NULLIF(system_accounts.username, ''), system_accounts.id) AS system_account_name,
    accounts.provider_code,
    accounts.provider_protocol_profile_id,
    accounts.protocol_code,
    accounts.protocol_version,
    accounts.name,
    accounts.type,
    (CASE
      WHEN accounts.last_error_code = 'account_expired'
        OR (accounts.account_expires_at IS NOT NULL AND accounts.account_expires_at <= now())
      THEN 'disabled'
      WHEN accounts.status IN ('pending_test', 'disabled', 'error', 'rate_limited', 'temporary_unavailable') THEN accounts.status
      WHEN accounts.cooldown_until IS NOT NULL AND accounts.cooldown_until > now() THEN 'temporary_unavailable'
      WHEN accounts.schedulable = false THEN 'disabled'
      ELSE accounts.status
    END)::text AS effective_status,
    CASE
      WHEN accounts.status = 'active'
        AND accounts.schedulable = true
        AND (accounts.cooldown_until IS NULL OR accounts.cooldown_until <= now())
        AND (accounts.account_expires_at IS NULL OR accounts.account_expires_at > now())
        AND (accounts.last_error_code IS NULL OR accounts.last_error_code <> 'account_expired')
      THEN true
      ELSE false
    END AS effective_schedulable,
    CASE
      WHEN accounts.status IN ('rate_limited', 'temporary_unavailable')
        OR (accounts.cooldown_until IS NOT NULL AND accounts.cooldown_until > now())
      THEN true
      ELSE false
    END AS is_cooling,
    accounts.account_expires_at,
    accounts.priority,
    accounts.created_at
  FROM juhe_business.accounts AS accounts
  LEFT JOIN juhe_business.system_accounts AS system_accounts
    ON system_accounts.id = accounts.system_account_id
  WHERE accounts.deleted_at IS NULL
    AND (
      $5::text = ''
      OR accounts.system_account_id = $5::text
    )
    AND (
      coalesce(array_length($6::text[], 1), 0) = 0
      OR accounts.id = ANY($6::text[])
    )
    AND (
      $7::text = ''
      OR accounts.provider_code = $7::text
    )
    AND (
      $8::text = ''
      OR EXISTS (
        SELECT 1
        FROM juhe_business.group_accounts AS group_accounts
        WHERE group_accounts.account_id = accounts.id
          AND group_accounts.system_account_id = accounts.system_account_id
          AND group_accounts.group_id = $8::text
          AND group_accounts.enabled = true
      )
    )
    AND (
      $9::text = ''
      OR accounts.type = $9::text
    )
    AND (
      $10::boolean = false
      OR (
        accounts.name COLLATE "C" >= $11::text
        AND accounts.name COLLATE "C" < $12::text
      )
    )
)
SELECT
  id,
  system_account_id,
  system_account_name,
  provider_code,
  provider_protocol_profile_id,
  protocol_code,
  protocol_version,
  name,
  type,
  effective_status AS status,
  account_expires_at
FROM owner_account_rows
WHERE (
    coalesce(array_length($1::text[], 1), 0) = 0
    OR effective_status = ANY($1::text[])
  )
  AND (
    $2::text = ''
    OR $2::text = 'all'
    OR ($2::text = 'enabled' AND effective_schedulable = true)
    OR ($2::text = 'disabled' AND effective_schedulable = false AND is_cooling = false)
    OR ($2::text = 'cooling' AND is_cooling = true)
  )
ORDER BY priority ASC, created_at ASC, id ASC
LIMIT $4::int
OFFSET $3::int
`

type ListManagementAccountOptionsParams struct {
	Statuses        []string
	Schedulable     string
	RowOffset       int32
	RowLimit        int32
	SystemAccountID string
	Ids             []string
	ProviderCode    string
	GroupID         string
	AccountType     string
	HasKeyword      bool
	Keyword         string
	KeywordUpper    string
}

type ListManagementAccountOptionsRow struct {
	ID                        string
	SystemAccountID           string
	SystemAccountName         string
	ProviderCode              string
	ProviderProtocolProfileID string
	ProtocolCode              string
	ProtocolVersion           string
	Name                      string
	Type                      string
	Status                    string
	AccountExpiresAt          pgtype.Timestamptz
}

func (q *Queries) ListManagementAccountOptions(ctx context.Context, arg ListManagementAccountOptionsParams) ([]ListManagementAccountOptionsRow, error) {
	rows, err := q.db.Query(ctx, listManagementAccountOptions,
		arg.Statuses,
		arg.Schedulable,
		arg.RowOffset,
		arg.RowLimit,
		arg.SystemAccountID,
		arg.Ids,
		arg.ProviderCode,
		arg.GroupID,
		arg.AccountType,
		arg.HasKeyword,
		arg.Keyword,
		arg.KeywordUpper,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementAccountOptionsRow
	for rows.Next() {
		var i ListManagementAccountOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SystemAccountID,
			&i.SystemAccountName,
			&i.ProviderCode,
			&i.ProviderProtocolProfileID,
			&i.ProtocolCode,
			&i.ProtocolVersion,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.AccountExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
