// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w2_management_authorization_options.sql

package postgresqueries

import (
	"context"
)

const listManagementAuthorizationGranteeAccounts = `-- name: ListManagementAuthorizationGranteeAccounts :many
SELECT id, username, display_name, status
FROM juhe_business.system_accounts
WHERE (
    $1::boolean = false
    OR id = ANY($2::text[])
  )
  AND (
    $3::boolean = false
    OR (
      username COLLATE "C" >= $4::text
      AND username COLLATE "C" < $5::text
      AND starts_with(username, $4::text)
    )
    OR (
      display_name COLLATE "C" >= $4::text
      AND display_name COLLATE "C" < $5::text
      AND starts_with(display_name, $4::text)
    )
  )
ORDER BY status ASC, display_name ASC, username ASC, id ASC
LIMIT $6::int
`

type ListManagementAuthorizationGranteeAccountsParams struct {
	HasIds       bool
	Ids          []string
	HasKeyword   bool
	Keyword      string
	KeywordUpper string
	RowLimit     int32
}

type ListManagementAuthorizationGranteeAccountsRow struct {
	ID          string
	Username    string
	DisplayName string
	Status      string
}

func (q *Queries) ListManagementAuthorizationGranteeAccounts(ctx context.Context, arg ListManagementAuthorizationGranteeAccountsParams) ([]ListManagementAuthorizationGranteeAccountsRow, error) {
	rows, err := q.db.Query(ctx, listManagementAuthorizationGranteeAccounts,
		arg.HasIds,
		arg.Ids,
		arg.HasKeyword,
		arg.Keyword,
		arg.KeywordUpper,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementAuthorizationGranteeAccountsRow
	for rows.Next() {
		var i ListManagementAuthorizationGranteeAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagementAuthorizationGranteeGroups = `-- name: ListManagementAuthorizationGranteeGroups :many
WITH active_grantee AS (
  SELECT id
  FROM juhe_business.system_accounts
  WHERE id = $8::text
    AND status = 'active'
  LIMIT 1
)
SELECT
  groups.id,
  groups.name
FROM juhe_business.groups AS groups
INNER JOIN active_grantee
  ON active_grantee.id = groups.system_account_id
WHERE groups.enabled = true
  AND (
    coalesce(array_length($1::text[], 1), 0) = 0
    OR groups.id = ANY($1::text[])
  )
  AND (
    $2::text = ''
    OR groups.provider_code = $2::text
  )
  AND (
    $3::boolean = false
    OR (
      groups.name COLLATE "C" >= $4::text
      AND groups.name COLLATE "C" < $5::text
      AND starts_with(groups.name, $4::text)
    )
  )
ORDER BY
  CASE WHEN $6::boolean THEN groups.is_default ELSE false END DESC,
  groups.updated_at DESC,
  groups.id DESC
LIMIT $7::int
`

type ListManagementAuthorizationGranteeGroupsParams struct {
	Ids                    []string
	ProviderCode           string
	HasKeyword             bool
	Keyword                string
	KeywordUpper           string
	PreferDefault          bool
	RowLimit               int32
	GranteeSystemAccountID string
}

type ListManagementAuthorizationGranteeGroupsRow struct {
	ID   string
	Name string
}

func (q *Queries) ListManagementAuthorizationGranteeGroups(ctx context.Context, arg ListManagementAuthorizationGranteeGroupsParams) ([]ListManagementAuthorizationGranteeGroupsRow, error) {
	rows, err := q.db.Query(ctx, listManagementAuthorizationGranteeGroups,
		arg.Ids,
		arg.ProviderCode,
		arg.HasKeyword,
		arg.Keyword,
		arg.KeywordUpper,
		arg.PreferDefault,
		arg.RowLimit,
		arg.GranteeSystemAccountID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementAuthorizationGranteeGroupsRow
	for rows.Next() {
		var i ListManagementAuthorizationGranteeGroupsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagementAuthorizationGranteeTeams = `-- name: ListManagementAuthorizationGranteeTeams :many
SELECT id, name, status
FROM juhe_business.system_teams
WHERE (
    $1::boolean = false
    OR id = ANY($2::text[])
  )
  AND (
    $3::boolean = false
    OR (
      name COLLATE "C" >= $4::text
      AND name COLLATE "C" < $5::text
      AND starts_with(name, $4::text)
    )
  )
ORDER BY status ASC, name ASC, id ASC
LIMIT $6::int
`

type ListManagementAuthorizationGranteeTeamsParams struct {
	HasIds       bool
	Ids          []string
	HasKeyword   bool
	Keyword      string
	KeywordUpper string
	RowLimit     int32
}

type ListManagementAuthorizationGranteeTeamsRow struct {
	ID     string
	Name   string
	Status string
}

func (q *Queries) ListManagementAuthorizationGranteeTeams(ctx context.Context, arg ListManagementAuthorizationGranteeTeamsParams) ([]ListManagementAuthorizationGranteeTeamsRow, error) {
	rows, err := q.db.Query(ctx, listManagementAuthorizationGranteeTeams,
		arg.HasIds,
		arg.Ids,
		arg.HasKeyword,
		arg.Keyword,
		arg.KeywordUpper,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementAuthorizationGranteeTeamsRow
	for rows.Next() {
		var i ListManagementAuthorizationGranteeTeamsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
