// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w3_account_balance_refresh_job.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAccountBalanceRefreshDueCandidates = `-- name: ListAccountBalanceRefreshDueCandidates :many
SELECT id, system_account_id, config_revision, credentials_encrypted,
       balance_query_config_json::text, balance_query_next_refresh_at,
       updated_at, proxy_profile_id
FROM juhe_business.accounts
WHERE status = 'active'
  AND schedulable = true
  AND type = 'api_key'
  AND balance_query_enabled = true
  AND balance_query_next_refresh_at IS NOT NULL
  AND balance_query_next_refresh_at <= $1
  AND deleted_at IS NULL
  AND authorization_instance_authorization_id IS NULL
ORDER BY balance_query_next_refresh_at ASC, id ASC
LIMIT $2
`

type ListAccountBalanceRefreshDueCandidatesParams struct {
	BalanceQueryNextRefreshAt pgtype.Timestamptz
	Limit                     int32
}

type ListAccountBalanceRefreshDueCandidatesRow struct {
	ID                        string
	SystemAccountID           string
	ConfigRevision            int32
	CredentialsEncrypted      string
	BalanceQueryConfigJson    string
	BalanceQueryNextRefreshAt pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	ProxyProfileID            pgtype.Text
}

func (q *Queries) ListAccountBalanceRefreshDueCandidates(ctx context.Context, arg ListAccountBalanceRefreshDueCandidatesParams) ([]ListAccountBalanceRefreshDueCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAccountBalanceRefreshDueCandidates, arg.BalanceQueryNextRefreshAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountBalanceRefreshDueCandidatesRow
	for rows.Next() {
		var i ListAccountBalanceRefreshDueCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.SystemAccountID,
			&i.ConfigRevision,
			&i.CredentialsEncrypted,
			&i.BalanceQueryConfigJson,
			&i.BalanceQueryNextRefreshAt,
			&i.UpdatedAt,
			&i.ProxyProfileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountBalanceRefreshRecoveryCandidates = `-- name: ListAccountBalanceRefreshRecoveryCandidates :many
SELECT id, system_account_id, config_revision, credentials_encrypted,
       balance_query_config_json::text, balance_query_next_refresh_at,
       updated_at, proxy_profile_id
FROM juhe_business.accounts
WHERE status = 'active'
  AND schedulable = true
  AND type = 'api_key'
  AND balance_query_enabled = true
  AND balance_query_next_refresh_at IS NULL
  AND deleted_at IS NULL
  AND authorization_instance_authorization_id IS NULL
ORDER BY id ASC
LIMIT $1
`

type ListAccountBalanceRefreshRecoveryCandidatesRow struct {
	ID                        string
	SystemAccountID           string
	ConfigRevision            int32
	CredentialsEncrypted      string
	BalanceQueryConfigJson    string
	BalanceQueryNextRefreshAt pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	ProxyProfileID            pgtype.Text
}

func (q *Queries) ListAccountBalanceRefreshRecoveryCandidates(ctx context.Context, limit int32) ([]ListAccountBalanceRefreshRecoveryCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAccountBalanceRefreshRecoveryCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountBalanceRefreshRecoveryCandidatesRow
	for rows.Next() {
		var i ListAccountBalanceRefreshRecoveryCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.SystemAccountID,
			&i.ConfigRevision,
			&i.CredentialsEncrypted,
			&i.BalanceQueryConfigJson,
			&i.BalanceQueryNextRefreshAt,
			&i.UpdatedAt,
			&i.ProxyProfileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
