// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w3_management_account_group_binding.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteManagementAccountGroupBindings = `-- name: DeleteManagementAccountGroupBindings :exec
DELETE FROM juhe_business.group_accounts
WHERE account_id = $1::text
  AND system_account_id = $2::text
`

type DeleteManagementAccountGroupBindingsParams struct {
	AccountID       string
	SystemAccountID string
}

func (q *Queries) DeleteManagementAccountGroupBindings(ctx context.Context, arg DeleteManagementAccountGroupBindingsParams) error {
	_, err := q.db.Exec(ctx, deleteManagementAccountGroupBindings, arg.AccountID, arg.SystemAccountID)
	return err
}

const lockManagementAccountGroupBindingTarget = `-- name: LockManagementAccountGroupBindingTarget :one
SELECT
  accounts.id,
  accounts.system_account_id,
  accounts.name,
  accounts.provider_code,
  accounts.provider_protocol_profile_id,
  accounts.protocol_code,
  accounts.protocol_version,
  accounts.type,
  accounts.status,
  accounts.client_compatibility,
  accounts.schedulable,
  accounts.concurrency_limit,
  accounts.priority,
  accounts.super_priority_enabled,
  accounts.fallback_enabled,
  accounts.health_check_model,
  groups.id AS group_id,
  groups.name AS group_name,
  COALESCE(previous_binding.group_id, '') AS previous_group_id
FROM juhe_business.groups AS groups
INNER JOIN juhe_business.accounts AS accounts
  ON accounts.id = $1::text
  AND accounts.system_account_id = groups.system_account_id
  AND accounts.provider_code = groups.provider_code
  AND accounts.deleted_at IS NULL
  AND accounts.authorization_instance_authorization_id IS NULL
LEFT JOIN LATERAL (
  SELECT group_accounts.group_id
  FROM juhe_business.group_accounts AS group_accounts
  WHERE group_accounts.account_id = accounts.id
    AND group_accounts.system_account_id = accounts.system_account_id
    AND group_accounts.enabled = true
  ORDER BY group_accounts.updated_at DESC, group_accounts.group_id ASC
  LIMIT 1
) AS previous_binding ON true
WHERE groups.id = $2::text
  AND (
    $3::boolean
    OR groups.system_account_id = $4::text
  )
FOR UPDATE OF groups, accounts
`

type LockManagementAccountGroupBindingTargetParams struct {
	AccountID                string
	GroupID                  string
	CanAccessAll             bool
	EffectiveSystemAccountID string
}

type LockManagementAccountGroupBindingTargetRow struct {
	ID                        string
	SystemAccountID           string
	Name                      string
	ProviderCode              string
	ProviderProtocolProfileID string
	ProtocolCode              string
	ProtocolVersion           string
	Type                      string
	Status                    string
	ClientCompatibility       string
	Schedulable               bool
	ConcurrencyLimit          int32
	Priority                  int32
	SuperPriorityEnabled      bool
	FallbackEnabled           bool
	HealthCheckModel          string
	GroupID                   string
	GroupName                 string
	PreviousGroupID           string
}

func (q *Queries) LockManagementAccountGroupBindingTarget(ctx context.Context, arg LockManagementAccountGroupBindingTargetParams) (LockManagementAccountGroupBindingTargetRow, error) {
	row := q.db.QueryRow(ctx, lockManagementAccountGroupBindingTarget,
		arg.AccountID,
		arg.GroupID,
		arg.CanAccessAll,
		arg.EffectiveSystemAccountID,
	)
	var i LockManagementAccountGroupBindingTargetRow
	err := row.Scan(
		&i.ID,
		&i.SystemAccountID,
		&i.Name,
		&i.ProviderCode,
		&i.ProviderProtocolProfileID,
		&i.ProtocolCode,
		&i.ProtocolVersion,
		&i.Type,
		&i.Status,
		&i.ClientCompatibility,
		&i.Schedulable,
		&i.ConcurrencyLimit,
		&i.Priority,
		&i.SuperPriorityEnabled,
		&i.FallbackEnabled,
		&i.HealthCheckModel,
		&i.GroupID,
		&i.GroupName,
		&i.PreviousGroupID,
	)
	return i, err
}

const upsertManagementAccountGroupBinding = `-- name: UpsertManagementAccountGroupBinding :exec
INSERT INTO juhe_business.group_accounts (
  system_account_id,
  group_id,
  account_id,
  account_authorization_id,
  local_priority,
  local_super_priority_enabled,
  local_fallback_enabled,
  enabled,
  created_at,
  updated_at
) VALUES (
  $1::text,
  $2::text,
  $3::text,
  NULL,
  $4::int,
  $5::boolean,
  $6::boolean,
  true,
  $7::timestamptz,
  $7::timestamptz
)
ON CONFLICT (group_id, account_id) DO UPDATE SET
  system_account_id = EXCLUDED.system_account_id,
  account_authorization_id = NULL,
  local_priority = EXCLUDED.local_priority,
  local_super_priority_enabled = EXCLUDED.local_super_priority_enabled,
  local_fallback_enabled = EXCLUDED.local_fallback_enabled,
  enabled = true,
  updated_at = EXCLUDED.updated_at
`

type UpsertManagementAccountGroupBindingParams struct {
	SystemAccountID           string
	GroupID                   string
	AccountID                 string
	LocalPriority             int32
	LocalSuperPriorityEnabled bool
	LocalFallbackEnabled      bool
	UpdatedAt                 pgtype.Timestamptz
}

func (q *Queries) UpsertManagementAccountGroupBinding(ctx context.Context, arg UpsertManagementAccountGroupBindingParams) error {
	_, err := q.db.Exec(ctx, upsertManagementAccountGroupBinding,
		arg.SystemAccountID,
		arg.GroupID,
		arg.AccountID,
		arg.LocalPriority,
		arg.LocalSuperPriorityEnabled,
		arg.LocalFallbackEnabled,
		arg.UpdatedAt,
	)
	return err
}
