// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w3_management_account_traffic_migration.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockManagementAccountTrafficMigrationAccount = `-- name: LockManagementAccountTrafficMigrationAccount :one
SELECT
  accounts.id,
  accounts.system_account_id,
  COALESCE(source_accounts.system_account_id, accounts.system_account_id) AS owner_system_account_id,
  accounts.name,
  COALESCE(source_accounts.provider_code, accounts.provider_code) AS provider_code,
  COALESCE(source_accounts.type, accounts.type) AS type,
  accounts.status,
  accounts.schedulable,
  accounts.cooldown_until,
  group_accounts.group_id,
  group_accounts.account_authorization_id,
  accounts.authorization_instance_authorization_id,
  CASE WHEN accounts.authorization_instance_authorization_id IS NULL THEN 'owner' ELSE 'authorized' END AS access_type,
  CASE
    WHEN accounts.authorization_instance_authorization_id IS NULL THEN
      accounts.status = 'active'
      AND accounts.schedulable = true
      AND (accounts.account_expires_at IS NULL OR accounts.account_expires_at > $1::timestamptz)
      AND (accounts.cooldown_until IS NULL OR accounts.cooldown_until <= $1::timestamptz)
    ELSE
      resource_authorizations.status = 'active'
      AND (resource_authorizations.expires_at IS NULL OR resource_authorizations.expires_at > $1::timestamptz)
      AND source_accounts.status = 'active'
      AND source_accounts.schedulable = true
      AND (source_accounts.account_expires_at IS NULL OR source_accounts.account_expires_at > $1::timestamptz)
      AND (source_accounts.cooldown_until IS NULL OR source_accounts.cooldown_until <= $1::timestamptz)
      AND accounts.status = 'active'
      AND accounts.schedulable = true
      AND (accounts.account_expires_at IS NULL OR accounts.account_expires_at > $1::timestamptz)
      AND (accounts.cooldown_until IS NULL OR accounts.cooldown_until <= $1::timestamptz)
  END AS effective_available
FROM juhe_business.accounts AS accounts
LEFT JOIN juhe_business.accounts AS source_accounts
  ON source_accounts.id = accounts.authorization_instance_source_account_id
  AND source_accounts.deleted_at IS NULL
LEFT JOIN juhe_business.resource_authorizations AS resource_authorizations
  ON resource_authorizations.id = accounts.authorization_instance_authorization_id
  AND resource_authorizations.resource_type = 'account'
  AND resource_authorizations.resource_id = source_accounts.id
  AND resource_authorizations.resource_owner_system_account_id = source_accounts.system_account_id
  AND resource_authorizations.grantee_system_account_id = accounts.system_account_id
INNER JOIN LATERAL (
  SELECT bindings.group_id, bindings.account_authorization_id
  FROM juhe_business.group_accounts AS bindings
  WHERE bindings.account_id = accounts.id
    AND bindings.system_account_id = accounts.system_account_id
    AND bindings.enabled = true
    -- Equivalent to the projected group_accounts authorization binding guard.
    -- group_accounts.account_authorization_id IS NOT DISTINCT FROM accounts.authorization_instance_authorization_id
    AND bindings.account_authorization_id IS NOT DISTINCT FROM accounts.authorization_instance_authorization_id
  ORDER BY bindings.updated_at DESC, bindings.group_id ASC
  LIMIT 1
) AS group_accounts ON true
WHERE accounts.id = $2::text
  AND accounts.deleted_at IS NULL
  AND ($3::boolean OR accounts.system_account_id = $4::text)
  AND (
    (accounts.authorization_instance_authorization_id IS NULL
      AND accounts.authorization_instance_source_account_id IS NULL
      AND accounts.authorization_instance_owner_system_account_id IS NULL)
    OR
    (accounts.authorization_instance_authorization_id IS NOT NULL
      AND source_accounts.id IS NOT NULL
      AND resource_authorizations.id IS NOT NULL
      AND resource_authorizations.status = 'active'
      AND (resource_authorizations.expires_at IS NULL OR resource_authorizations.expires_at > $1::timestamptz))
  )
FOR UPDATE OF accounts
`

type LockManagementAccountTrafficMigrationAccountParams struct {
	NowAt                    pgtype.Timestamptz
	AccountID                string
	CanAccessAll             bool
	EffectiveSystemAccountID string
}

type LockManagementAccountTrafficMigrationAccountRow struct {
	ID                                   string
	SystemAccountID                      string
	OwnerSystemAccountID                 string
	Name                                 string
	ProviderCode                         string
	Type                                 string
	Status                               string
	Schedulable                          bool
	CooldownUntil                        pgtype.Timestamptz
	GroupID                              string
	AccountAuthorizationID               pgtype.Text
	AuthorizationInstanceAuthorizationID pgtype.Text
	AccessType                           string
	EffectiveAvailable                   interface{}
}

func (q *Queries) LockManagementAccountTrafficMigrationAccount(ctx context.Context, arg LockManagementAccountTrafficMigrationAccountParams) (LockManagementAccountTrafficMigrationAccountRow, error) {
	row := q.db.QueryRow(ctx, lockManagementAccountTrafficMigrationAccount,
		arg.NowAt,
		arg.AccountID,
		arg.CanAccessAll,
		arg.EffectiveSystemAccountID,
	)
	var i LockManagementAccountTrafficMigrationAccountRow
	err := row.Scan(
		&i.ID,
		&i.SystemAccountID,
		&i.OwnerSystemAccountID,
		&i.Name,
		&i.ProviderCode,
		&i.Type,
		&i.Status,
		&i.Schedulable,
		&i.CooldownUntil,
		&i.GroupID,
		&i.AccountAuthorizationID,
		&i.AuthorizationInstanceAuthorizationID,
		&i.AccessType,
		&i.EffectiveAvailable,
	)
	return i, err
}

const markManagementAccountTrafficMigrationStatsDirty = `-- name: MarkManagementAccountTrafficMigrationStatsDirty :exec
INSERT INTO juhe_business.group_account_stats_dirty (group_id, reason, updated_at)
VALUES ($1::text, 'traffic_migration', $2::timestamptz)
ON CONFLICT (group_id) DO UPDATE
SET reason = EXCLUDED.reason, updated_at = EXCLUDED.updated_at
`

type MarkManagementAccountTrafficMigrationStatsDirtyParams struct {
	GroupID   string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) MarkManagementAccountTrafficMigrationStatsDirty(ctx context.Context, arg MarkManagementAccountTrafficMigrationStatsDirtyParams) error {
	_, err := q.db.Exec(ctx, markManagementAccountTrafficMigrationStatsDirty, arg.GroupID, arg.UpdatedAt)
	return err
}

const updateManagementAccountTrafficMigrationSource = `-- name: UpdateManagementAccountTrafficMigrationSource :execrows
UPDATE juhe_business.accounts
SET status = $1::text,
    schedulable = $2::boolean,
    cooldown_until = $3::timestamptz,
    last_error_code = NULL,
    last_error_message = '手动迁移流量',
    last_error_trace_id = NULL,
    cooldown_retest_failure_count = 0,
    cooldown_retest_observation_started_at = $4::timestamptz,
    cooldown_retest_last_at = NULL,
    cooldown_retest_last_status_code = NULL,
    stream_failure_count = 0,
    stream_failure_window_started_at = NULL,
    updated_at = $5::timestamptz
WHERE id = $6::text
  AND system_account_id = $7::text
  AND authorization_instance_authorization_id IS NOT DISTINCT FROM $8::text
  AND deleted_at IS NULL
`

type UpdateManagementAccountTrafficMigrationSourceParams struct {
	Status                 string
	Schedulable            bool
	CooldownUntil          pgtype.Timestamptz
	ObservationStartedAt   pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	AccountID              string
	SystemAccountID        string
	AccountAuthorizationID pgtype.Text
}

func (q *Queries) UpdateManagementAccountTrafficMigrationSource(ctx context.Context, arg UpdateManagementAccountTrafficMigrationSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateManagementAccountTrafficMigrationSource,
		arg.Status,
		arg.Schedulable,
		arg.CooldownUntil,
		arg.ObservationStartedAt,
		arg.UpdatedAt,
		arg.AccountID,
		arg.SystemAccountID,
		arg.AccountAuthorizationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
