// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w4_management_system_teams.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createManagementSystemTeam = `-- name: CreateManagementSystemTeam :one
INSERT INTO juhe_business.system_teams (
  id, name, description, status, created_by, created_at, updated_at
) VALUES (
  $1::text,
  $2::text,
  $3::text,
  $4::text,
  $5::text,
  $6::timestamptz,
  $7::timestamptz
)
RETURNING
  id,
  name,
  description,
  status,
  created_by,
  created_at,
  updated_at
`

type CreateManagementSystemTeamParams struct {
	ID          string
	Name        string
	Description pgtype.Text
	Status      string
	CreatedBy   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateManagementSystemTeam(ctx context.Context, arg CreateManagementSystemTeamParams) (JuheBusinessSystemTeam, error) {
	row := q.db.QueryRow(ctx, createManagementSystemTeam,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i JuheBusinessSystemTeam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findActiveManagementSystemTeamForUpdate = `-- name: FindActiveManagementSystemTeamForUpdate :one
SELECT
  teams.id,
  teams.name,
  teams.description,
  teams.status,
  teams.created_by,
  teams.created_at,
  teams.updated_at
FROM juhe_business.system_teams AS teams
WHERE teams.id = $1::text
  AND teams.status = 'active'
  AND (
    $2::text = ''
    OR EXISTS (
      SELECT 1
      FROM juhe_business.system_team_members AS scoped_members
      WHERE scoped_members.team_id = teams.id
        AND scoped_members.system_account_id = $2::text
        AND scoped_members.status = 'active'
    )
  )
LIMIT 1
FOR UPDATE OF teams
`

type FindActiveManagementSystemTeamForUpdateParams struct {
	TeamID          string
	SystemAccountID string
}

func (q *Queries) FindActiveManagementSystemTeamForUpdate(ctx context.Context, arg FindActiveManagementSystemTeamForUpdateParams) (JuheBusinessSystemTeam, error) {
	row := q.db.QueryRow(ctx, findActiveManagementSystemTeamForUpdate, arg.TeamID, arg.SystemAccountID)
	var i JuheBusinessSystemTeam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findManagementSystemTeam = `-- name: FindManagementSystemTeam :one
SELECT
  teams.id,
  teams.name,
  teams.description,
  teams.status,
  teams.created_by,
  teams.created_at,
  teams.updated_at,
  COALESCE(counts.active_member_count, 0)::bigint AS active_member_count
FROM juhe_business.system_teams AS teams
LEFT JOIN (
  SELECT
    team_id,
    COUNT(*) FILTER (WHERE status = 'active') AS active_member_count
  FROM juhe_business.system_team_members
  WHERE team_id = $1::text
  GROUP BY team_id
) AS counts ON counts.team_id = teams.id
WHERE teams.id = $1::text
  AND (
    $2::text = ''
    OR EXISTS (
      SELECT 1
      FROM juhe_business.system_team_members AS scoped_members
      WHERE scoped_members.team_id = teams.id
        AND scoped_members.system_account_id = $2::text
        AND scoped_members.status = 'active'
    )
  )
LIMIT 1
`

type FindManagementSystemTeamParams struct {
	TeamID          string
	SystemAccountID string
}

type FindManagementSystemTeamRow struct {
	ID                string
	Name              string
	Description       pgtype.Text
	Status            string
	CreatedBy         string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ActiveMemberCount int64
}

func (q *Queries) FindManagementSystemTeam(ctx context.Context, arg FindManagementSystemTeamParams) (FindManagementSystemTeamRow, error) {
	row := q.db.QueryRow(ctx, findManagementSystemTeam, arg.TeamID, arg.SystemAccountID)
	var i FindManagementSystemTeamRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveMemberCount,
	)
	return i, err
}

const findManagementSystemTeamForUpdate = `-- name: FindManagementSystemTeamForUpdate :one
SELECT
  teams.id,
  teams.name,
  teams.description,
  teams.status,
  teams.created_by,
  teams.created_at,
  teams.updated_at
FROM juhe_business.system_teams AS teams
WHERE teams.id = $1::text
  AND (
    $2::text = ''
    OR EXISTS (
      SELECT 1
      FROM juhe_business.system_team_members AS scoped_members
      WHERE scoped_members.team_id = teams.id
        AND scoped_members.system_account_id = $2::text
        AND scoped_members.status = 'active'
    )
  )
LIMIT 1
FOR UPDATE OF teams
`

type FindManagementSystemTeamForUpdateParams struct {
	TeamID          string
	SystemAccountID string
}

func (q *Queries) FindManagementSystemTeamForUpdate(ctx context.Context, arg FindManagementSystemTeamForUpdateParams) (JuheBusinessSystemTeam, error) {
	row := q.db.QueryRow(ctx, findManagementSystemTeamForUpdate, arg.TeamID, arg.SystemAccountID)
	var i JuheBusinessSystemTeam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listManagementSystemTeamMemberCounts = `-- name: ListManagementSystemTeamMemberCounts :many
SELECT
  team_id,
  COUNT(*) FILTER (WHERE status = 'active')::bigint AS active_member_count
FROM juhe_business.system_team_members
WHERE team_id = ANY($1::text[])
GROUP BY team_id
ORDER BY team_id ASC
`

type ListManagementSystemTeamMemberCountsRow struct {
	TeamID            string
	ActiveMemberCount int64
}

func (q *Queries) ListManagementSystemTeamMemberCounts(ctx context.Context, teamIds []string) ([]ListManagementSystemTeamMemberCountsRow, error) {
	rows, err := q.db.Query(ctx, listManagementSystemTeamMemberCounts, teamIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementSystemTeamMemberCountsRow
	for rows.Next() {
		var i ListManagementSystemTeamMemberCountsRow
		if err := rows.Scan(&i.TeamID, &i.ActiveMemberCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagementSystemTeamMembers = `-- name: ListManagementSystemTeamMembers :many
SELECT
  id,
  team_id,
  system_account_id,
  system_account_name,
  username,
  member_role,
  status,
  joined_at,
  removed_at,
  created_at,
  updated_at
FROM (
  SELECT
    members.id,
    members.team_id,
    members.system_account_id,
    accounts.display_name AS system_account_name,
    accounts.username,
    members.member_role,
    members.status,
    members.joined_at,
    members.removed_at,
    members.created_at,
    members.updated_at,
    ROW_NUMBER() OVER (
      PARTITION BY members.team_id
      ORDER BY members.status ASC, members.joined_at ASC, members.id ASC
    ) AS team_member_rank
  FROM juhe_business.system_team_members AS members
  INNER JOIN juhe_business.system_accounts AS accounts
    ON accounts.id = members.system_account_id
  WHERE members.team_id = $1::text
    AND members.status = 'active'
) AS ranked_team_members
WHERE team_member_rank <= 500
ORDER BY status ASC, joined_at ASC, id ASC
`

type ListManagementSystemTeamMembersRow struct {
	ID                string
	TeamID            string
	SystemAccountID   string
	SystemAccountName string
	Username          string
	MemberRole        string
	Status            string
	JoinedAt          pgtype.Timestamptz
	RemovedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) ListManagementSystemTeamMembers(ctx context.Context, teamID string) ([]ListManagementSystemTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listManagementSystemTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementSystemTeamMembersRow
	for rows.Next() {
		var i ListManagementSystemTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.SystemAccountID,
			&i.SystemAccountName,
			&i.Username,
			&i.MemberRole,
			&i.Status,
			&i.JoinedAt,
			&i.RemovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagementSystemTeams = `-- name: ListManagementSystemTeams :many
SELECT
  teams.id,
  teams.name,
  teams.description,
  teams.status,
  teams.created_by,
  teams.created_at,
  teams.updated_at
FROM juhe_business.system_teams AS teams
WHERE (
    $1::text = ''
    OR EXISTS (
      SELECT 1
      FROM juhe_business.system_team_members AS scoped_members
      WHERE scoped_members.team_id = teams.id
        AND scoped_members.system_account_id = $1::text
        AND scoped_members.status = 'active'
    )
  )
  AND (
    $2::text = ''
    OR (
      teams.name COLLATE "C" >= $2::text
      AND teams.name COLLATE "C" < $3::text
      AND starts_with(teams.name, $2::text)
    )
  )
ORDER BY teams.status ASC, teams.updated_at DESC, teams.name ASC, teams.id ASC
LIMIT $5::int
OFFSET $4::int
`

type ListManagementSystemTeamsParams struct {
	SystemAccountID string
	Keyword         string
	KeywordUpper    string
	RowOffset       int32
	RowLimit        int32
}

func (q *Queries) ListManagementSystemTeams(ctx context.Context, arg ListManagementSystemTeamsParams) ([]JuheBusinessSystemTeam, error) {
	rows, err := q.db.Query(ctx, listManagementSystemTeams,
		arg.SystemAccountID,
		arg.Keyword,
		arg.KeywordUpper,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JuheBusinessSystemTeam
	for rows.Next() {
		var i JuheBusinessSystemTeam
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateManagementSystemTeam = `-- name: UpdateManagementSystemTeam :one
UPDATE juhe_business.system_teams
SET
  name = CASE WHEN $1::bool THEN $2::text ELSE name END,
  description = CASE
    WHEN $3::bool THEN $4::text
    ELSE description
  END,
  status = CASE WHEN $5::bool THEN $6::text ELSE status END,
  updated_at = $7::timestamptz
WHERE id = $8::text
RETURNING
  id,
  name,
  description,
  status,
  created_by,
  created_at,
  updated_at
`

type UpdateManagementSystemTeamParams struct {
	HasName        bool
	Name           string
	HasDescription bool
	Description    pgtype.Text
	HasStatus      bool
	Status         string
	UpdatedAt      pgtype.Timestamptz
	TeamID         string
}

func (q *Queries) UpdateManagementSystemTeam(ctx context.Context, arg UpdateManagementSystemTeamParams) (JuheBusinessSystemTeam, error) {
	row := q.db.QueryRow(ctx, updateManagementSystemTeam,
		arg.HasName,
		arg.Name,
		arg.HasDescription,
		arg.Description,
		arg.HasStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.TeamID,
	)
	var i JuheBusinessSystemTeam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
