// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w5_management_group_delete.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countManagementGroupDeleteRouteStrategyLoss = `-- name: CountManagementGroupDeleteRouteStrategyLoss :one
SELECT count(DISTINCT route_strategies.id)::bigint AS total
FROM juhe_business.route_strategy_groups AS target_bindings
INNER JOIN juhe_business.route_strategies AS route_strategies
  ON route_strategies.id = target_bindings.route_strategy_id
  AND route_strategies.system_account_id = target_bindings.system_account_id
INNER JOIN juhe_business.groups AS target_groups
  ON target_groups.id = target_bindings.group_id
LEFT JOIN juhe_business.resource_authorizations AS target_authorization
  ON target_authorization.resource_type = 'group'
  AND target_authorization.resource_id = target_groups.id
  AND target_authorization.resource_owner_system_account_id = target_groups.system_account_id
  AND target_authorization.grantee_system_account_id = target_bindings.system_account_id
  AND target_authorization.status = 'active'
  AND (
    target_authorization.expires_at IS NULL
    OR target_authorization.expires_at > $1::timestamptz
  )
LEFT JOIN juhe_business.group_authorization_settings AS target_settings
  ON target_settings.authorization_id = target_authorization.id
  AND target_settings.system_account_id = target_bindings.system_account_id
  AND target_settings.group_id = target_groups.id
WHERE target_bindings.group_id = $2::text
  AND route_strategies.id = ANY($3::text[])
  AND target_bindings.status = 'active'
  AND route_strategies.status = 'active'
  AND target_groups.enabled = true
  AND (
    target_groups.system_account_id = target_bindings.system_account_id
    OR (
      target_authorization.id IS NOT NULL
      AND coalesce(target_settings.enabled, true) = true
    )
  )
  AND NOT EXISTS (
    SELECT 1
    FROM juhe_business.route_strategy_groups AS other_bindings
    INNER JOIN juhe_business.groups AS other_groups
      ON other_groups.id = other_bindings.group_id
    LEFT JOIN juhe_business.resource_authorizations AS other_authorization
      ON other_authorization.resource_type = 'group'
      AND other_authorization.resource_id = other_groups.id
      AND other_authorization.resource_owner_system_account_id = other_groups.system_account_id
      AND other_authorization.grantee_system_account_id = other_bindings.system_account_id
      AND other_authorization.status = 'active'
      AND (
        other_authorization.expires_at IS NULL
        OR other_authorization.expires_at > $1::timestamptz
      )
    LEFT JOIN juhe_business.group_authorization_settings AS other_settings
      ON other_settings.authorization_id = other_authorization.id
      AND other_settings.system_account_id = other_bindings.system_account_id
      AND other_settings.group_id = other_groups.id
    WHERE other_bindings.route_strategy_id = target_bindings.route_strategy_id
      AND other_bindings.system_account_id = target_bindings.system_account_id
      AND other_bindings.group_id <> target_bindings.group_id
      AND other_bindings.status = 'active'
      AND other_groups.enabled = true
      AND (
        other_groups.system_account_id = other_bindings.system_account_id
        OR (
          other_authorization.id IS NOT NULL
          AND coalesce(other_settings.enabled, true) = true
        )
      )
  )
`

type CountManagementGroupDeleteRouteStrategyLossParams struct {
	NowAt            pgtype.Timestamptz
	GroupID          string
	RouteStrategyIds []string
}

func (q *Queries) CountManagementGroupDeleteRouteStrategyLoss(ctx context.Context, arg CountManagementGroupDeleteRouteStrategyLossParams) (int64, error) {
	row := q.db.QueryRow(ctx, countManagementGroupDeleteRouteStrategyLoss, arg.NowAt, arg.GroupID, arg.RouteStrategyIds)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const hardDeleteManagementGroup = `-- name: HardDeleteManagementGroup :one
DELETE FROM juhe_business.groups
WHERE id = $1::text
  AND system_account_id = $2::text
RETURNING id
`

type HardDeleteManagementGroupParams struct {
	GroupID              string
	OwnerSystemAccountID string
}

func (q *Queries) HardDeleteManagementGroup(ctx context.Context, arg HardDeleteManagementGroupParams) (string, error) {
	row := q.db.QueryRow(ctx, hardDeleteManagementGroup, arg.GroupID, arg.OwnerSystemAccountID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockManagementGroupDeleteRouteStrategies = `-- name: LockManagementGroupDeleteRouteStrategies :many
SELECT
  route_strategies.id,
  route_strategies.name
FROM juhe_business.route_strategy_groups AS target_bindings
INNER JOIN juhe_business.route_strategies AS route_strategies
  ON route_strategies.id = target_bindings.route_strategy_id
  AND route_strategies.system_account_id = target_bindings.system_account_id
INNER JOIN juhe_business.groups AS target_groups
  ON target_groups.id = target_bindings.group_id
LEFT JOIN juhe_business.resource_authorizations AS target_authorization
  ON target_authorization.resource_type = 'group'
  AND target_authorization.resource_id = target_groups.id
  AND target_authorization.resource_owner_system_account_id = target_groups.system_account_id
  AND target_authorization.grantee_system_account_id = target_bindings.system_account_id
  AND target_authorization.status = 'active'
  AND (
    target_authorization.expires_at IS NULL
    OR target_authorization.expires_at > $1::timestamptz
  )
LEFT JOIN juhe_business.group_authorization_settings AS target_settings
  ON target_settings.authorization_id = target_authorization.id
  AND target_settings.system_account_id = target_bindings.system_account_id
  AND target_settings.group_id = target_groups.id
WHERE target_bindings.group_id = $2::text
  AND target_bindings.status = 'active'
  AND route_strategies.status = 'active'
  AND target_groups.enabled = true
  AND (
    target_groups.system_account_id = target_bindings.system_account_id
    OR (
      target_authorization.id IS NOT NULL
      AND coalesce(target_settings.enabled, true) = true
    )
  )
ORDER BY route_strategies.id ASC
LIMIT 101
FOR UPDATE OF route_strategies
`

type LockManagementGroupDeleteRouteStrategiesParams struct {
	NowAt   pgtype.Timestamptz
	GroupID string
}

type LockManagementGroupDeleteRouteStrategiesRow struct {
	ID   string
	Name string
}

func (q *Queries) LockManagementGroupDeleteRouteStrategies(ctx context.Context, arg LockManagementGroupDeleteRouteStrategiesParams) ([]LockManagementGroupDeleteRouteStrategiesRow, error) {
	rows, err := q.db.Query(ctx, lockManagementGroupDeleteRouteStrategies, arg.NowAt, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockManagementGroupDeleteRouteStrategiesRow
	for rows.Next() {
		var i LockManagementGroupDeleteRouteStrategiesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockManagementGroupDeleteTarget = `-- name: LockManagementGroupDeleteTarget :one
SELECT
  groups.id,
  groups.system_account_id,
  groups.name,
  groups.provider_code,
  groups.description,
  groups.enabled,
  groups.is_default,
  groups.group_type,
  groups.scheduling_policy_json
FROM juhe_business.groups AS groups
WHERE groups.id = $1::text
  AND (
    (
      $2::boolean
      AND $3::text = ''
    )
    OR groups.system_account_id = $3::text
  )
FOR UPDATE OF groups
`

type LockManagementGroupDeleteTargetParams struct {
	GroupID                  string
	CanAccessAll             bool
	EffectiveSystemAccountID string
}

type LockManagementGroupDeleteTargetRow struct {
	ID                   string
	SystemAccountID      string
	Name                 string
	ProviderCode         string
	Description          pgtype.Text
	Enabled              bool
	IsDefault            bool
	GroupType            string
	SchedulingPolicyJson pgtype.Text
}

func (q *Queries) LockManagementGroupDeleteTarget(ctx context.Context, arg LockManagementGroupDeleteTargetParams) (LockManagementGroupDeleteTargetRow, error) {
	row := q.db.QueryRow(ctx, lockManagementGroupDeleteTarget, arg.GroupID, arg.CanAccessAll, arg.EffectiveSystemAccountID)
	var i LockManagementGroupDeleteTargetRow
	err := row.Scan(
		&i.ID,
		&i.SystemAccountID,
		&i.Name,
		&i.ProviderCode,
		&i.Description,
		&i.Enabled,
		&i.IsDefault,
		&i.GroupType,
		&i.SchedulingPolicyJson,
	)
	return i, err
}

const markManagementGroupDeletedStatsDirty = `-- name: MarkManagementGroupDeletedStatsDirty :exec
INSERT INTO juhe_business.group_account_stats_dirty (
  group_id,
  reason,
  updated_at
) VALUES (
  $1::text,
  'group_deleted',
  $2::timestamptz
)
ON CONFLICT (group_id) DO UPDATE SET
  reason = excluded.reason,
  updated_at = excluded.updated_at
`

type MarkManagementGroupDeletedStatsDirtyParams struct {
	GroupID   string
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) MarkManagementGroupDeletedStatsDirty(ctx context.Context, arg MarkManagementGroupDeletedStatsDirtyParams) error {
	_, err := q.db.Exec(ctx, markManagementGroupDeletedStatsDirty, arg.GroupID, arg.DeletedAt)
	return err
}
