// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w5_management_settings.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockManagementGlobalSettings = `-- name: LockManagementGlobalSettings :many
SELECT key, value_json
FROM juhe_business.global_settings
WHERE key IN ('appName', 'appIcon')
ORDER BY key ASC
FOR UPDATE
`

type LockManagementGlobalSettingsRow struct {
	Key       string
	ValueJson string
}

func (q *Queries) LockManagementGlobalSettings(ctx context.Context) ([]LockManagementGlobalSettingsRow, error) {
	rows, err := q.db.Query(ctx, lockManagementGlobalSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockManagementGlobalSettingsRow
	for rows.Next() {
		var i LockManagementGlobalSettingsRow
		if err := rows.Scan(&i.Key, &i.ValueJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateManagementGlobalSetting = `-- name: UpdateManagementGlobalSetting :one
UPDATE juhe_business.global_settings
SET
  value_json = $1::text,
  updated_at = $2::timestamptz
WHERE key = $3::text
RETURNING key, value_json
`

type UpdateManagementGlobalSettingParams struct {
	ValueJson string
	UpdatedAt pgtype.Timestamptz
	Key       string
}

type UpdateManagementGlobalSettingRow struct {
	Key       string
	ValueJson string
}

func (q *Queries) UpdateManagementGlobalSetting(ctx context.Context, arg UpdateManagementGlobalSettingParams) (UpdateManagementGlobalSettingRow, error) {
	row := q.db.QueryRow(ctx, updateManagementGlobalSetting, arg.ValueJson, arg.UpdatedAt, arg.Key)
	var i UpdateManagementGlobalSettingRow
	err := row.Scan(&i.Key, &i.ValueJson)
	return i, err
}
