// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w5_management_api_key_secret.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findManagementAPIKeySecret = `-- name: FindManagementAPIKeySecret :one
SELECT
  api_keys.id,
  api_keys.system_account_id,
  api_keys.name,
  api_keys.key_prefix,
  api_keys.key_suffix,
  api_keys.key_secret_encrypted
FROM juhe_business.api_keys AS api_keys
WHERE api_keys.id = $1::text
  AND (
    $2::text = ''
    OR api_keys.system_account_id = $2::text
  )
`

type FindManagementAPIKeySecretParams struct {
	ApiKeyID        string
	SystemAccountID string
}

type FindManagementAPIKeySecretRow struct {
	ID                 string
	SystemAccountID    string
	Name               string
	KeyPrefix          string
	KeySuffix          string
	KeySecretEncrypted pgtype.Text
}

func (q *Queries) FindManagementAPIKeySecret(ctx context.Context, arg FindManagementAPIKeySecretParams) (FindManagementAPIKeySecretRow, error) {
	row := q.db.QueryRow(ctx, findManagementAPIKeySecret, arg.ApiKeyID, arg.SystemAccountID)
	var i FindManagementAPIKeySecretRow
	err := row.Scan(
		&i.ID,
		&i.SystemAccountID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeySuffix,
		&i.KeySecretEncrypted,
	)
	return i, err
}

const lockManagementAPIKeySecretRefreshTarget = `-- name: LockManagementAPIKeySecretRefreshTarget :one
SELECT
  api_keys.id,
  api_keys.system_account_id,
  system_accounts.display_name AS system_account_name,
  api_keys.name,
  api_keys.description,
  api_keys.key_prefix,
  api_keys.key_suffix,
  api_keys.status,
  api_keys.is_default,
  api_keys.purpose,
  api_keys.route_strategy_id,
  route_strategies.name AS route_strategy_name,
  route_strategies.mode AS route_strategy_mode,
  route_strategies.status AS route_strategy_status,
  api_keys.expires_at,
  api_keys.quota_limits_json,
  api_keys.availability_schedule_json
FROM juhe_business.api_keys AS api_keys
INNER JOIN juhe_business.system_accounts AS system_accounts
  ON system_accounts.id = api_keys.system_account_id
INNER JOIN juhe_business.route_strategies AS route_strategies
  ON route_strategies.id = api_keys.route_strategy_id
  AND route_strategies.system_account_id = api_keys.system_account_id
WHERE api_keys.id = $1::text
  AND (
    $2::text = ''
    OR api_keys.system_account_id = $2::text
  )
FOR UPDATE OF api_keys
`

type LockManagementAPIKeySecretRefreshTargetParams struct {
	ApiKeyID        string
	SystemAccountID string
}

type LockManagementAPIKeySecretRefreshTargetRow struct {
	ID                       string
	SystemAccountID          string
	SystemAccountName        string
	Name                     string
	Description              pgtype.Text
	KeyPrefix                string
	KeySuffix                string
	Status                   string
	IsDefault                bool
	Purpose                  string
	RouteStrategyID          string
	RouteStrategyName        string
	RouteStrategyMode        string
	RouteStrategyStatus      string
	ExpiresAt                pgtype.Timestamptz
	QuotaLimitsJson          pgtype.Text
	AvailabilityScheduleJson pgtype.Text
}

func (q *Queries) LockManagementAPIKeySecretRefreshTarget(ctx context.Context, arg LockManagementAPIKeySecretRefreshTargetParams) (LockManagementAPIKeySecretRefreshTargetRow, error) {
	row := q.db.QueryRow(ctx, lockManagementAPIKeySecretRefreshTarget, arg.ApiKeyID, arg.SystemAccountID)
	var i LockManagementAPIKeySecretRefreshTargetRow
	err := row.Scan(
		&i.ID,
		&i.SystemAccountID,
		&i.SystemAccountName,
		&i.Name,
		&i.Description,
		&i.KeyPrefix,
		&i.KeySuffix,
		&i.Status,
		&i.IsDefault,
		&i.Purpose,
		&i.RouteStrategyID,
		&i.RouteStrategyName,
		&i.RouteStrategyMode,
		&i.RouteStrategyStatus,
		&i.ExpiresAt,
		&i.QuotaLimitsJson,
		&i.AvailabilityScheduleJson,
	)
	return i, err
}

const updateManagementAPIKeySecret = `-- name: UpdateManagementAPIKeySecret :one
UPDATE juhe_business.api_keys
SET key_hash = $1::text,
    key_prefix = $2::text,
    key_suffix = $3::text,
    key_secret_encrypted = $4::text,
    updated_at = $5::timestamptz
WHERE id = $6::text
  AND system_account_id = $7::text
RETURNING id
`

type UpdateManagementAPIKeySecretParams struct {
	KeyHash            string
	KeyPrefix          string
	KeySuffix          string
	KeySecretEncrypted string
	UpdatedAt          pgtype.Timestamptz
	ApiKeyID           string
	SystemAccountID    string
}

func (q *Queries) UpdateManagementAPIKeySecret(ctx context.Context, arg UpdateManagementAPIKeySecretParams) (string, error) {
	row := q.db.QueryRow(ctx, updateManagementAPIKeySecret,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.KeySuffix,
		arg.KeySecretEncrypted,
		arg.UpdatedAt,
		arg.ApiKeyID,
		arg.SystemAccountID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
