// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w5_management_group_list.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listManagementGroupAccountStats = `-- name: ListManagementGroupAccountStats :many
SELECT
  system_account_id,
  group_id,
  total,
  available,
  active,
  disabled,
  error,
  rate_limited,
  current_concurrency,
  concurrency_limit
FROM juhe_stats.group_account_stats
WHERE group_id = ANY($1::text[])
ORDER BY group_id ASC, system_account_id ASC
`

type ListManagementGroupAccountStatsRow struct {
	SystemAccountID    string
	GroupID            string
	Total              int32
	Available          int32
	Active             int32
	Disabled           int32
	Error              int32
	RateLimited        int32
	CurrentConcurrency int32
	ConcurrencyLimit   int32
}

func (q *Queries) ListManagementGroupAccountStats(ctx context.Context, groupIds []string) ([]ListManagementGroupAccountStatsRow, error) {
	rows, err := q.db.Query(ctx, listManagementGroupAccountStats, groupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementGroupAccountStatsRow
	for rows.Next() {
		var i ListManagementGroupAccountStatsRow
		if err := rows.Scan(
			&i.SystemAccountID,
			&i.GroupID,
			&i.Total,
			&i.Available,
			&i.Active,
			&i.Disabled,
			&i.Error,
			&i.RateLimited,
			&i.CurrentConcurrency,
			&i.ConcurrencyLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagementGroupAuthorizationSources = `-- name: ListManagementGroupAuthorizationSources :many
SELECT
  authorization_sources.authorization_id,
  authorization_sources.source_type,
  authorization_sources.status,
  coalesce(system_teams.name, '')::text AS source_team_name
FROM juhe_business.resource_authorization_sources AS authorization_sources
LEFT JOIN juhe_business.system_teams AS system_teams
  ON system_teams.id = authorization_sources.source_team_id
WHERE authorization_sources.authorization_id = ANY($1::text[])
ORDER BY
  authorization_sources.authorization_id ASC,
  authorization_sources.created_at ASC,
  authorization_sources.id ASC
`

type ListManagementGroupAuthorizationSourcesRow struct {
	AuthorizationID string
	SourceType      string
	Status          string
	SourceTeamName  string
}

func (q *Queries) ListManagementGroupAuthorizationSources(ctx context.Context, authorizationIds []string) ([]ListManagementGroupAuthorizationSourcesRow, error) {
	rows, err := q.db.Query(ctx, listManagementGroupAuthorizationSources, authorizationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementGroupAuthorizationSourcesRow
	for rows.Next() {
		var i ListManagementGroupAuthorizationSourcesRow
		if err := rows.Scan(
			&i.AuthorizationID,
			&i.SourceType,
			&i.Status,
			&i.SourceTeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagementGroupUsageDaily = `-- name: ListManagementGroupUsageDaily :many
WITH requested_scopes AS MATERIALIZED (
  SELECT
    requested.lookup_key::text AS lookup_key,
    ($2::text[])[requested.ordinality::int] AS system_account_id,
    ($3::text[])[requested.ordinality::int] AS scope_type,
    ($4::text[])[requested.ordinality::int] AS scope_id,
    requested.ordinality
  FROM unnest($5::text[])
    WITH ORDINALITY AS requested(lookup_key, ordinality)
)
SELECT
  requested_scopes.lookup_key,
  usage_stats.system_account_id,
  usage_stats.scope_type,
  usage_stats.scope_id,
  usage_stats.request_count,
  usage_stats.input_tokens,
  usage_stats.output_tokens,
  usage_stats.cache_read_tokens,
  usage_stats.cache_read_cost_usd,
  usage_stats.cache_write_tokens,
  usage_stats.cache_write_1h_tokens,
  usage_stats.cache_write_cost_usd,
  usage_stats.thinking_tokens,
  usage_stats.input_image_tokens,
  usage_stats.output_image_tokens,
  usage_stats.total_cost_usd,
  usage_stats.last_used_at
FROM requested_scopes
INNER JOIN juhe_stats.usage_stats_daily AS usage_stats
  ON usage_stats.system_account_id = requested_scopes.system_account_id
  AND usage_stats.scope_type = requested_scopes.scope_type
  AND usage_stats.scope_id = requested_scopes.scope_id
  AND usage_stats.stat_date = $1::text
ORDER BY requested_scopes.ordinality ASC
`

type ListManagementGroupUsageDailyParams struct {
	StatDate         string
	SystemAccountIds []string
	ScopeTypes       []string
	ScopeIds         []string
	LookupKeys       []string
}

type ListManagementGroupUsageDailyRow struct {
	LookupKey          string
	SystemAccountID    string
	ScopeType          string
	ScopeID            string
	RequestCount       int64
	InputTokens        int64
	OutputTokens       int64
	CacheReadTokens    int64
	CacheReadCostUsd   float64
	CacheWriteTokens   int64
	CacheWrite1hTokens int64
	CacheWriteCostUsd  float64
	ThinkingTokens     int64
	InputImageTokens   int64
	OutputImageTokens  int64
	TotalCostUsd       float64
	LastUsedAt         pgtype.Text
}

func (q *Queries) ListManagementGroupUsageDaily(ctx context.Context, arg ListManagementGroupUsageDailyParams) ([]ListManagementGroupUsageDailyRow, error) {
	rows, err := q.db.Query(ctx, listManagementGroupUsageDaily,
		arg.StatDate,
		arg.SystemAccountIds,
		arg.ScopeTypes,
		arg.ScopeIds,
		arg.LookupKeys,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementGroupUsageDailyRow
	for rows.Next() {
		var i ListManagementGroupUsageDailyRow
		if err := rows.Scan(
			&i.LookupKey,
			&i.SystemAccountID,
			&i.ScopeType,
			&i.ScopeID,
			&i.RequestCount,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheReadCostUsd,
			&i.CacheWriteTokens,
			&i.CacheWrite1hTokens,
			&i.CacheWriteCostUsd,
			&i.ThinkingTokens,
			&i.InputImageTokens,
			&i.OutputImageTokens,
			&i.TotalCostUsd,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagementGroupUsageTotals = `-- name: ListManagementGroupUsageTotals :many
WITH requested_scopes AS MATERIALIZED (
  SELECT
    requested.lookup_key::text AS lookup_key,
    ($1::text[])[requested.ordinality::int] AS system_account_id,
    ($2::text[])[requested.ordinality::int] AS scope_type,
    ($3::text[])[requested.ordinality::int] AS scope_id,
    requested.ordinality
  FROM unnest($4::text[])
    WITH ORDINALITY AS requested(lookup_key, ordinality)
)
SELECT
  requested_scopes.lookup_key,
  usage_stats.system_account_id,
  usage_stats.scope_type,
  usage_stats.scope_id,
  usage_stats.request_count,
  usage_stats.input_tokens,
  usage_stats.output_tokens,
  usage_stats.cache_read_tokens,
  usage_stats.cache_read_cost_usd,
  usage_stats.cache_write_tokens,
  usage_stats.cache_write_1h_tokens,
  usage_stats.cache_write_cost_usd,
  usage_stats.thinking_tokens,
  usage_stats.input_image_tokens,
  usage_stats.output_image_tokens,
  usage_stats.total_cost_usd,
  usage_stats.last_used_at
FROM requested_scopes
INNER JOIN juhe_stats.usage_stats_totals AS usage_stats
  ON usage_stats.system_account_id = requested_scopes.system_account_id
  AND usage_stats.scope_type = requested_scopes.scope_type
  AND usage_stats.scope_id = requested_scopes.scope_id
ORDER BY requested_scopes.ordinality ASC
`

type ListManagementGroupUsageTotalsParams struct {
	SystemAccountIds []string
	ScopeTypes       []string
	ScopeIds         []string
	LookupKeys       []string
}

type ListManagementGroupUsageTotalsRow struct {
	LookupKey          string
	SystemAccountID    string
	ScopeType          string
	ScopeID            string
	RequestCount       int64
	InputTokens        int64
	OutputTokens       int64
	CacheReadTokens    int64
	CacheReadCostUsd   float64
	CacheWriteTokens   int64
	CacheWrite1hTokens int64
	CacheWriteCostUsd  float64
	ThinkingTokens     int64
	InputImageTokens   int64
	OutputImageTokens  int64
	TotalCostUsd       float64
	LastUsedAt         pgtype.Text
}

func (q *Queries) ListManagementGroupUsageTotals(ctx context.Context, arg ListManagementGroupUsageTotalsParams) ([]ListManagementGroupUsageTotalsRow, error) {
	rows, err := q.db.Query(ctx, listManagementGroupUsageTotals,
		arg.SystemAccountIds,
		arg.ScopeTypes,
		arg.ScopeIds,
		arg.LookupKeys,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementGroupUsageTotalsRow
	for rows.Next() {
		var i ListManagementGroupUsageTotalsRow
		if err := rows.Scan(
			&i.LookupKey,
			&i.SystemAccountID,
			&i.ScopeType,
			&i.ScopeID,
			&i.RequestCount,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheReadCostUsd,
			&i.CacheWriteTokens,
			&i.CacheWrite1hTokens,
			&i.CacheWriteCostUsd,
			&i.ThinkingTokens,
			&i.InputImageTokens,
			&i.OutputImageTokens,
			&i.TotalCostUsd,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagementGroups = `-- name: ListManagementGroups :many
WITH group_rows AS (
  SELECT
    groups.id,
    groups.system_account_id,
    system_accounts.display_name AS system_account_name,
    groups.name,
    groups.provider_code,
    groups.description,
    groups.enabled,
    groups.is_default,
    groups.group_type,
    groups.scheduling_policy_json,
    'owner'::text AS access_type,
    NULL::text AS group_authorization_id,
    NULL::text AS authorization_status,
    NULL::timestamptz AS authorization_expires_at,
    NULL::text AS authorization_limits_json,
    groups.updated_at AS effective_updated_at
  FROM juhe_business.groups AS groups
  INNER JOIN juhe_business.system_accounts AS system_accounts
    ON system_accounts.id = groups.system_account_id
  WHERE (
    $3::text = ''
    OR groups.system_account_id = $3::text
  )

  UNION ALL

  SELECT
    groups.id,
    groups.system_account_id,
    system_accounts.display_name AS system_account_name,
    groups.name,
    groups.provider_code,
    groups.description,
    CASE
      WHEN groups.enabled THEN coalesce(group_authorization_settings.enabled, true)
      ELSE false
    END AS enabled,
    false AS is_default,
    coalesce(group_authorization_settings.group_type, groups.group_type) AS group_type,
    CASE
      WHEN coalesce(group_authorization_settings.group_type, groups.group_type) = 'high_concurrency'
        THEN coalesce(group_authorization_settings.scheduling_policy_json, groups.scheduling_policy_json)
      ELSE NULL
    END AS scheduling_policy_json,
    'authorized'::text AS access_type,
    resource_authorizations.id AS group_authorization_id,
    resource_authorizations.status AS authorization_status,
    resource_authorizations.expires_at AS authorization_expires_at,
    resource_authorizations.limits_json AS authorization_limits_json,
    coalesce(group_authorization_settings.updated_at, groups.updated_at) AS effective_updated_at
  FROM juhe_business.resource_authorizations AS resource_authorizations
  INNER JOIN juhe_business.groups AS groups
    ON groups.id = resource_authorizations.resource_id
    AND groups.system_account_id = resource_authorizations.resource_owner_system_account_id
  INNER JOIN juhe_business.system_accounts AS system_accounts
    ON system_accounts.id = groups.system_account_id
  LEFT JOIN juhe_business.group_authorization_settings AS group_authorization_settings
    ON group_authorization_settings.authorization_id = resource_authorizations.id
    AND group_authorization_settings.system_account_id = resource_authorizations.grantee_system_account_id
    AND group_authorization_settings.group_id = resource_authorizations.resource_id
  WHERE $3::text <> ''
    AND resource_authorizations.resource_type = 'group'
    AND resource_authorizations.grantee_system_account_id = $3::text
    AND resource_authorizations.status IN ('active', 'paused', 'expired')
    AND groups.system_account_id <> $3::text
)
SELECT
  group_rows.id,
  group_rows.system_account_id,
  group_rows.system_account_name,
  group_rows.name,
  group_rows.provider_code,
  group_rows.description,
  group_rows.enabled,
  group_rows.is_default,
  group_rows.group_type,
  group_rows.scheduling_policy_json,
  group_rows.access_type,
  group_rows.group_authorization_id,
  group_rows.authorization_status,
  group_rows.authorization_expires_at,
  group_rows.authorization_limits_json,
  group_rows.effective_updated_at
FROM group_rows
ORDER BY group_rows.effective_updated_at DESC, group_rows.id DESC
LIMIT $2::int
OFFSET $1::int
`

type ListManagementGroupsParams struct {
	RowOffset       int32
	RowLimit        int32
	SystemAccountID string
}

type ListManagementGroupsRow struct {
	ID                      string
	SystemAccountID         string
	SystemAccountName       string
	Name                    string
	ProviderCode            string
	Description             pgtype.Text
	Enabled                 bool
	IsDefault               bool
	GroupType               string
	SchedulingPolicyJson    pgtype.Text
	AccessType              string
	GroupAuthorizationID    pgtype.Text
	AuthorizationStatus     pgtype.Text
	AuthorizationExpiresAt  pgtype.Timestamptz
	AuthorizationLimitsJson pgtype.Text
	EffectiveUpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListManagementGroups(ctx context.Context, arg ListManagementGroupsParams) ([]ListManagementGroupsRow, error) {
	rows, err := q.db.Query(ctx, listManagementGroups, arg.RowOffset, arg.RowLimit, arg.SystemAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementGroupsRow
	for rows.Next() {
		var i ListManagementGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.SystemAccountID,
			&i.SystemAccountName,
			&i.Name,
			&i.ProviderCode,
			&i.Description,
			&i.Enabled,
			&i.IsDefault,
			&i.GroupType,
			&i.SchedulingPolicyJson,
			&i.AccessType,
			&i.GroupAuthorizationID,
			&i.AuthorizationStatus,
			&i.AuthorizationExpiresAt,
			&i.AuthorizationLimitsJson,
			&i.EffectiveUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
