// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: w6_management_client_ip_stats_detail.sql

package postgresqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getManagementClientIPStatsRegistry = `-- name: GetManagementClientIPStatsRegistry :one
SELECT
  ip_hash,
  aggregate_ip_key,
  last_seen_at
FROM juhe_stats.client_ip_registry
WHERE ip_hash = $1::text
LIMIT 1
`

type GetManagementClientIPStatsRegistryRow struct {
	IpHash         string
	AggregateIpKey string
	LastSeenAt     string
}

func (q *Queries) GetManagementClientIPStatsRegistry(ctx context.Context, ipHash string) (GetManagementClientIPStatsRegistryRow, error) {
	row := q.db.QueryRow(ctx, getManagementClientIPStatsRegistry, ipHash)
	var i GetManagementClientIPStatsRegistryRow
	err := row.Scan(&i.IpHash, &i.AggregateIpKey, &i.LastSeenAt)
	return i, err
}

const listManagementClientIPAccountUsage = `-- name: ListManagementClientIPAccountUsage :many
SELECT
  range_stats.account_id,
  accounts.name AS account_name,
  accounts.system_account_id AS account_owner_system_account_id,
  system_accounts.display_name AS account_owner_system_account_name,
  range_stats.request_count,
  range_stats.success_count,
  range_stats.error_count,
  range_stats.input_tokens,
  range_stats.output_tokens,
  range_stats.cache_read_tokens,
  range_stats.cache_read_cost_usd,
  range_stats.cache_write_tokens,
  range_stats.cache_write_1h_tokens,
  range_stats.cache_write_cost_usd,
  range_stats.thinking_tokens,
  range_stats.input_image_tokens,
  range_stats.output_image_tokens,
  range_stats.total_cost_usd,
  range_stats.duration_ms_sum,
  range_stats.duration_ms_count,
  range_stats.duration_ms_max,
  range_stats.average_duration_ms,
  range_stats.first_token_ms_sum,
  range_stats.first_token_ms_count,
  range_stats.average_first_token_ms,
  range_stats.active_days,
  range_stats.last_used_at,
  range_stats.last_error_at
FROM juhe_stats.client_ip_account_usage_range_windows AS range_stats
LEFT JOIN juhe_business.accounts AS accounts
  ON accounts.id = range_stats.account_id
LEFT JOIN juhe_business.system_accounts AS system_accounts
  ON system_accounts.id = accounts.system_account_id
WHERE range_stats.ip_hash = $1::text
  AND range_stats.start_date = $2::text
  AND range_stats.end_date = $3::text
ORDER BY
  CASE WHEN $4::text = 'requestCount' AND $5::text = 'asc' THEN range_stats.request_count END ASC,
  CASE WHEN $4::text = 'requestCount' AND $5::text = 'desc' THEN range_stats.request_count END DESC,
  CASE WHEN $4::text = 'successCount' AND $5::text = 'asc' THEN range_stats.success_count END ASC,
  CASE WHEN $4::text = 'successCount' AND $5::text = 'desc' THEN range_stats.success_count END DESC,
  CASE WHEN $4::text = 'errorCount' AND $5::text = 'asc' THEN range_stats.error_count END ASC,
  CASE WHEN $4::text = 'errorCount' AND $5::text = 'desc' THEN range_stats.error_count END DESC,
  CASE WHEN $4::text = 'errorRate' AND $5::text = 'asc' THEN CASE WHEN range_stats.request_count > 0 THEN range_stats.error_count::double precision / range_stats.request_count ELSE 0::double precision END END ASC,
  CASE WHEN $4::text = 'errorRate' AND $5::text = 'desc' THEN CASE WHEN range_stats.request_count > 0 THEN range_stats.error_count::double precision / range_stats.request_count ELSE 0::double precision END END DESC,
  CASE WHEN $4::text = 'totalTokens' AND $5::text = 'asc' THEN range_stats.input_tokens + range_stats.output_tokens END ASC,
  CASE WHEN $4::text = 'totalTokens' AND $5::text = 'desc' THEN range_stats.input_tokens + range_stats.output_tokens END DESC,
  CASE WHEN $4::text = 'totalCost' AND $5::text = 'asc' THEN range_stats.total_cost_usd END ASC,
  CASE WHEN $4::text = 'totalCost' AND $5::text = 'desc' THEN range_stats.total_cost_usd END DESC,
  CASE WHEN $4::text = 'activeDays' AND $5::text = 'asc' THEN range_stats.active_days END ASC,
  CASE WHEN $4::text = 'activeDays' AND $5::text = 'desc' THEN range_stats.active_days END DESC,
  CASE WHEN $4::text = 'lastUsedAt' AND $5::text = 'asc' THEN range_stats.last_used_at END ASC,
  CASE WHEN $4::text = 'lastUsedAt' AND $5::text = 'desc' THEN range_stats.last_used_at END DESC,
  CASE WHEN $5::text = 'asc' THEN range_stats.account_id END DESC,
  range_stats.account_id ASC
LIMIT $7::int
OFFSET $6::int
`

type ListManagementClientIPAccountUsageParams struct {
	IpHash    string
	StartDate string
	EndDate   string
	SortField string
	SortOrder string
	RowOffset int32
	RowLimit  int32
}

type ListManagementClientIPAccountUsageRow struct {
	AccountID                     string
	AccountName                   pgtype.Text
	AccountOwnerSystemAccountID   pgtype.Text
	AccountOwnerSystemAccountName pgtype.Text
	RequestCount                  int64
	SuccessCount                  int64
	ErrorCount                    int64
	InputTokens                   int64
	OutputTokens                  int64
	CacheReadTokens               int64
	CacheReadCostUsd              float64
	CacheWriteTokens              int64
	CacheWrite1hTokens            int64
	CacheWriteCostUsd             float64
	ThinkingTokens                int64
	InputImageTokens              int64
	OutputImageTokens             int64
	TotalCostUsd                  float64
	DurationMsSum                 int64
	DurationMsCount               int64
	DurationMsMax                 int64
	AverageDurationMs             pgtype.Float8
	FirstTokenMsSum               int64
	FirstTokenMsCount             int64
	AverageFirstTokenMs           pgtype.Float8
	ActiveDays                    int32
	LastUsedAt                    pgtype.Text
	LastErrorAt                   pgtype.Text
}

func (q *Queries) ListManagementClientIPAccountUsage(ctx context.Context, arg ListManagementClientIPAccountUsageParams) ([]ListManagementClientIPAccountUsageRow, error) {
	rows, err := q.db.Query(ctx, listManagementClientIPAccountUsage,
		arg.IpHash,
		arg.StartDate,
		arg.EndDate,
		arg.SortField,
		arg.SortOrder,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementClientIPAccountUsageRow
	for rows.Next() {
		var i ListManagementClientIPAccountUsageRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountName,
			&i.AccountOwnerSystemAccountID,
			&i.AccountOwnerSystemAccountName,
			&i.RequestCount,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheReadCostUsd,
			&i.CacheWriteTokens,
			&i.CacheWrite1hTokens,
			&i.CacheWriteCostUsd,
			&i.ThinkingTokens,
			&i.InputImageTokens,
			&i.OutputImageTokens,
			&i.TotalCostUsd,
			&i.DurationMsSum,
			&i.DurationMsCount,
			&i.DurationMsMax,
			&i.AverageDurationMs,
			&i.FirstTokenMsSum,
			&i.FirstTokenMsCount,
			&i.AverageFirstTokenMs,
			&i.ActiveDays,
			&i.LastUsedAt,
			&i.LastErrorAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagementClientIPAccountUsageRequestCountDesc = `-- name: ListManagementClientIPAccountUsageRequestCountDesc :many
SELECT
  range_stats.account_id,
  accounts.name AS account_name,
  accounts.system_account_id AS account_owner_system_account_id,
  system_accounts.display_name AS account_owner_system_account_name,
  range_stats.request_count,
  range_stats.success_count,
  range_stats.error_count,
  range_stats.input_tokens,
  range_stats.output_tokens,
  range_stats.cache_read_tokens,
  range_stats.cache_read_cost_usd,
  range_stats.cache_write_tokens,
  range_stats.cache_write_1h_tokens,
  range_stats.cache_write_cost_usd,
  range_stats.thinking_tokens,
  range_stats.input_image_tokens,
  range_stats.output_image_tokens,
  range_stats.total_cost_usd,
  range_stats.duration_ms_sum,
  range_stats.duration_ms_count,
  range_stats.duration_ms_max,
  range_stats.average_duration_ms,
  range_stats.first_token_ms_sum,
  range_stats.first_token_ms_count,
  range_stats.average_first_token_ms,
  range_stats.active_days,
  range_stats.last_used_at,
  range_stats.last_error_at
FROM juhe_stats.client_ip_account_usage_range_windows AS range_stats
LEFT JOIN juhe_business.accounts AS accounts
  ON accounts.id = range_stats.account_id
LEFT JOIN juhe_business.system_accounts AS system_accounts
  ON system_accounts.id = accounts.system_account_id
WHERE range_stats.ip_hash = $1::text
  AND range_stats.start_date = $2::text
  AND range_stats.end_date = $3::text
ORDER BY range_stats.request_count DESC, range_stats.account_id ASC
LIMIT $5::int
OFFSET $4::int
`

type ListManagementClientIPAccountUsageRequestCountDescParams struct {
	IpHash    string
	StartDate string
	EndDate   string
	RowOffset int32
	RowLimit  int32
}

type ListManagementClientIPAccountUsageRequestCountDescRow struct {
	AccountID                     string
	AccountName                   pgtype.Text
	AccountOwnerSystemAccountID   pgtype.Text
	AccountOwnerSystemAccountName pgtype.Text
	RequestCount                  int64
	SuccessCount                  int64
	ErrorCount                    int64
	InputTokens                   int64
	OutputTokens                  int64
	CacheReadTokens               int64
	CacheReadCostUsd              float64
	CacheWriteTokens              int64
	CacheWrite1hTokens            int64
	CacheWriteCostUsd             float64
	ThinkingTokens                int64
	InputImageTokens              int64
	OutputImageTokens             int64
	TotalCostUsd                  float64
	DurationMsSum                 int64
	DurationMsCount               int64
	DurationMsMax                 int64
	AverageDurationMs             pgtype.Float8
	FirstTokenMsSum               int64
	FirstTokenMsCount             int64
	AverageFirstTokenMs           pgtype.Float8
	ActiveDays                    int32
	LastUsedAt                    pgtype.Text
	LastErrorAt                   pgtype.Text
}

func (q *Queries) ListManagementClientIPAccountUsageRequestCountDesc(ctx context.Context, arg ListManagementClientIPAccountUsageRequestCountDescParams) ([]ListManagementClientIPAccountUsageRequestCountDescRow, error) {
	rows, err := q.db.Query(ctx, listManagementClientIPAccountUsageRequestCountDesc,
		arg.IpHash,
		arg.StartDate,
		arg.EndDate,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManagementClientIPAccountUsageRequestCountDescRow
	for rows.Next() {
		var i ListManagementClientIPAccountUsageRequestCountDescRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountName,
			&i.AccountOwnerSystemAccountID,
			&i.AccountOwnerSystemAccountName,
			&i.RequestCount,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheReadCostUsd,
			&i.CacheWriteTokens,
			&i.CacheWrite1hTokens,
			&i.CacheWriteCostUsd,
			&i.ThinkingTokens,
			&i.InputImageTokens,
			&i.OutputImageTokens,
			&i.TotalCostUsd,
			&i.DurationMsSum,
			&i.DurationMsCount,
			&i.DurationMsMax,
			&i.AverageDurationMs,
			&i.FirstTokenMsSum,
			&i.FirstTokenMsCount,
			&i.AverageFirstTokenMs,
			&i.ActiveDays,
			&i.LastUsedAt,
			&i.LastErrorAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
