// Curated from official Anthropic model, pricing, and deprecation docs on 2026-07-15.
// Values follow LiteLLM/model-price-repo field names: token prices are USD per token.

export const anthropicModelPricingData = [
  {
    model: 'best',
    catalog_order: 210,
    catalog_visible: false,
    input_cost_per_token: 10 / 1_000_000,
    output_cost_per_token: 50 / 1_000_000,
    cache_creation_input_token_cost: 12.5 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 20 / 1_000_000,
    cache_read_input_token_cost: 1 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 128_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","xhigh","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'fable',
    catalog_order: 220,
    catalog_visible: false,
    input_cost_per_token: 10 / 1_000_000,
    output_cost_per_token: 50 / 1_000_000,
    cache_creation_input_token_cost: 12.5 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 20 / 1_000_000,
    cache_read_input_token_cost: 1 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 128_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","xhigh","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'opus',
    catalog_order: 230,
    catalog_visible: false,
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 128_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","xhigh","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'opus[1m]',
    catalog_order: 240,
    catalog_visible: false,
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 128_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","xhigh","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'opusplan',
    catalog_order: 250,
    catalog_visible: false,
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 128_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","xhigh","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'sonnet',
    catalog_order: 260,
    catalog_visible: false,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'sonnet[1m]',
    catalog_order: 270,
    catalog_visible: false,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'haiku',
    catalog_order: 280,
    catalog_visible: false,
    input_cost_per_token: 1 / 1_000_000,
    output_cost_per_token: 5 / 1_000_000,
    cache_creation_input_token_cost: 1.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 2 / 1_000_000,
    cache_read_input_token_cost: 0.1 / 1_000_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"]
  },
  {
    model: 'claude-fable-5',
    catalog_order: 10,
    input_cost_per_token: 10 / 1_000_000,
    output_cost_per_token: 50 / 1_000_000,
    cache_creation_input_token_cost: 12.5 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 20 / 1_000_000,
    cache_read_input_token_cost: 1 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 128_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","xhigh","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'claude-mythos-5',
    catalog_order: 20,
    input_cost_per_token: 10 / 1_000_000,
    output_cost_per_token: 50 / 1_000_000,
    cache_creation_input_token_cost: 12.5 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 20 / 1_000_000,
    cache_read_input_token_cost: 1 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 128_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","xhigh","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'claude-sonnet-5',
    catalog_order: 25,
    input_cost_per_token: 2 / 1_000_000,
    output_cost_per_token: 10 / 1_000_000,
    cache_creation_input_token_cost: 2.5 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 4 / 1_000_000,
    cache_read_input_token_cost: 0.2 / 1_000_000,
    context_window_tokens: 200_000,
    max_output_tokens: 128_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","xhigh","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'claude-mythos-preview',
    catalog_order: 30,
    shutdown_date: '2026-06-30',
    input_cost_per_token: 10 / 1_000_000,
    output_cost_per_token: 50 / 1_000_000,
    cache_creation_input_token_cost: 12.5 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 20 / 1_000_000,
    cache_read_input_token_cost: 1 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 128_000,
    supported_api_protocols: ['messages', 'message_token_counting'],
    supports_prompt_caching: true,
    supports_service_tier: true
  },
  {
    model: 'claude-opus-4-8',
    catalog_order: 40,
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 128_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","xhigh","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'claude-opus-4-7',
    catalog_order: 50,
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 128_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","xhigh","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'claude-opus-4-6',
    catalog_order: 60,
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 128_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'claude-opus-4-6-thinking',
    catalog_order: 70,
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'antigravity-claude-opus-4-6-thinking',
    catalog_order: 900,
    catalog_visible: false,
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'antigravity/claude-opus-4-6-thinking',
    catalog_order: 901,
    catalog_visible: false,
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'google/antigravity-claude-opus-4-6-thinking',
    catalog_order: 902,
    catalog_visible: false,
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'google-antigravity/claude-opus-4-6-thinking',
    catalog_order: 903,
    catalog_visible: false,
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'google-antigravity:claude-opus-4-6-thinking',
    catalog_order: 904,
    catalog_visible: false,
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'claude-opus-4-6-antigravity',
    catalog_order: 905,
    catalog_visible: false,
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'claude-opus-4-5',
    catalog_order: 80,
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"]
  },
  {
    model: 'claude-opus-4-5-20251101',
    catalog_order: 90,
    release_date: '2025-11-01',
    input_cost_per_token: 5 / 1_000_000,
    output_cost_per_token: 25 / 1_000_000,
    cache_creation_input_token_cost: 6.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 10 / 1_000_000,
    cache_read_input_token_cost: 0.5 / 1_000_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"]
  },
  {
    model: 'claude-opus-4-1',
    catalog_order: 100,
    release_date: '2025-08-05',
    shutdown_date: '2026-08-05',
    input_cost_per_token: 15 / 1_000_000,
    output_cost_per_token: 75 / 1_000_000,
    cache_creation_input_token_cost: 18.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 30 / 1_000_000,
    cache_read_input_token_cost: 1.5 / 1_000_000,
    max_input_tokens: 200_000,
    max_output_tokens: 32_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"]
  },
  {
    model: 'claude-opus-4-1-20250805',
    catalog_order: 110,
    release_date: '2025-08-05',
    shutdown_date: '2026-08-05',
    input_cost_per_token: 15 / 1_000_000,
    output_cost_per_token: 75 / 1_000_000,
    cache_creation_input_token_cost: 18.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 30 / 1_000_000,
    cache_read_input_token_cost: 1.5 / 1_000_000,
    max_input_tokens: 200_000,
    max_output_tokens: 32_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"]
  },
  {
    model: 'claude-sonnet-4-6',
    catalog_order: 120,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'claude-sonnet-4-6-antigravity',
    catalog_order: 920,
    catalog_visible: false,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'antigravity-claude-sonnet-4-6',
    catalog_order: 921,
    catalog_visible: false,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'antigravity/claude-sonnet-4-6',
    catalog_order: 922,
    catalog_visible: false,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'google/antigravity-claude-sonnet-4-6',
    catalog_order: 923,
    catalog_visible: false,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'google-antigravity/claude-sonnet-4-6',
    catalog_order: 924,
    catalog_visible: false,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'google-antigravity:claude-sonnet-4-6',
    catalog_order: 925,
    catalog_visible: false,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'claude-sonnet-4-6-thinking',
    catalog_order: 130,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'antigravity-claude-sonnet-4-6-thinking',
    catalog_order: 930,
    catalog_visible: false,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'antigravity/claude-sonnet-4-6-thinking',
    catalog_order: 931,
    catalog_visible: false,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'google/antigravity-claude-sonnet-4-6-thinking',
    catalog_order: 932,
    catalog_visible: false,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'google-antigravity/claude-sonnet-4-6-thinking',
    catalog_order: 933,
    catalog_visible: false,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'google-antigravity:claude-sonnet-4-6-thinking',
    catalog_order: 934,
    catalog_visible: false,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 64_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"],
    supported_reasoning_efforts: ["low","medium","high","max"],
    default_reasoning_effort: "medium"
  },
  {
    model: 'claude-sonnet-4-5',
    catalog_order: 140,
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"]
  },
  {
    model: 'claude-sonnet-4-5-20250929',
    catalog_order: 150,
    release_date: '2025-09-29',
    input_cost_per_token: 3 / 1_000_000,
    output_cost_per_token: 15 / 1_000_000,
    cache_creation_input_token_cost: 3.75 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 6 / 1_000_000,
    cache_read_input_token_cost: 0.3 / 1_000_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"]
  },
  {
    model: 'claude-haiku-4-5',
    catalog_order: 160,
    input_cost_per_token: 1 / 1_000_000,
    output_cost_per_token: 5 / 1_000_000,
    cache_creation_input_token_cost: 1.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 2 / 1_000_000,
    cache_read_input_token_cost: 0.1 / 1_000_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"]
  },
  {
    model: 'claude-haiku-4-5-20251001',
    catalog_order: 170,
    release_date: '2025-10-01',
    input_cost_per_token: 1 / 1_000_000,
    output_cost_per_token: 5 / 1_000_000,
    cache_creation_input_token_cost: 1.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 2 / 1_000_000,
    cache_read_input_token_cost: 0.1 / 1_000_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"]
  },
  {
    model: 'claude-fake-5',
    catalog_order: 999,
    catalog_visible: false,
    input_cost_per_token: 1 / 1_000_000,
    output_cost_per_token: 5 / 1_000_000,
    cache_creation_input_token_cost: 1.25 / 1_000_000,
    cache_creation_input_token_cost_above_1hr: 2 / 1_000_000,
    cache_read_input_token_cost: 0.1 / 1_000_000,
    supported_api_protocols: ["messages","message_token_counting"],
    supports_prompt_caching: true,
    supports_service_tier: true
  ,
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","code_execution"]
  }
]
