// Curated from official Z.ai / BigModel GLM text model and pricing docs on 2026-06-22.
// Values follow LiteLLM/model-price-repo field names: token prices are USD per token.

export const glmModelPricingData = [
  {
    model: 'glm-5.2',
    mode: 'chat',
    catalog_order: 10,
    input_cost_per_token: 1.4 / 1_000_000,
    cache_read_input_token_cost: 0.26 / 1_000_000,
    output_cost_per_token: 4.4 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 131_072,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: true,
    supports_service_tier: false
  },
  {
    model: 'glm-5.1',
    mode: 'chat',
    catalog_order: 20,
    input_cost_per_token: 1.4 / 1_000_000,
    cache_read_input_token_cost: 0.26 / 1_000_000,
    output_cost_per_token: 4.4 / 1_000_000,
    max_input_tokens: 200_000,
    max_output_tokens: 98_304,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: true,
    supports_service_tier: false
  },
  {
    model: 'glm-5',
    mode: 'chat',
    catalog_order: 30,
    input_cost_per_token: 1.0 / 1_000_000,
    cache_read_input_token_cost: 0.2 / 1_000_000,
    output_cost_per_token: 3.2 / 1_000_000,
    max_input_tokens: 128_000,
    max_output_tokens: 98_304,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: true,
    supports_service_tier: false
  },
  {
    model: 'glm-5-turbo',
    mode: 'chat',
    catalog_order: 40,
    input_cost_per_token: 1.2 / 1_000_000,
    cache_read_input_token_cost: 0.24 / 1_000_000,
    output_cost_per_token: 4.0 / 1_000_000,
    max_input_tokens: 200_000,
    max_output_tokens: 98_304,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: true,
    supports_service_tier: false
  },
  {
    model: 'glm-4.7',
    mode: 'chat',
    catalog_order: 50,
    input_cost_per_token: 0.6 / 1_000_000,
    cache_read_input_token_cost: 0.11 / 1_000_000,
    output_cost_per_token: 2.2 / 1_000_000,
    max_input_tokens: 200_000,
    max_output_tokens: 131_072,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: true,
    supports_service_tier: false
  },
  {
    model: 'glm-4.7-flashx',
    mode: 'chat',
    catalog_order: 60,
    input_cost_per_token: 0.07 / 1_000_000,
    cache_read_input_token_cost: 0.01 / 1_000_000,
    output_cost_per_token: 0.4 / 1_000_000,
    max_input_tokens: 200_000,
    max_output_tokens: 131_072,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: true,
    supports_service_tier: false
  },
  {
    model: 'glm-4.7-flash',
    mode: 'chat',
    catalog_order: 70,
    input_cost_per_token: 0,
    output_cost_per_token: 0,
    max_input_tokens: 200_000,
    max_output_tokens: 131_072,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: false,
    supports_service_tier: false
  },
  {
    model: 'glm-4.6',
    mode: 'chat',
    catalog_order: 80,
    input_cost_per_token: 0.6 / 1_000_000,
    cache_read_input_token_cost: 0.11 / 1_000_000,
    output_cost_per_token: 2.2 / 1_000_000,
    max_input_tokens: 200_000,
    max_output_tokens: 131_072,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: true,
    supports_service_tier: false
  },
  {
    model: 'glm-4.5',
    mode: 'chat',
    catalog_order: 90,
    input_cost_per_token: 0.6 / 1_000_000,
    cache_read_input_token_cost: 0.11 / 1_000_000,
    output_cost_per_token: 2.2 / 1_000_000,
    max_input_tokens: 128_000,
    max_output_tokens: 98_304,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: true,
    supports_service_tier: false
  },
  {
    model: 'glm-4.5-x',
    mode: 'chat',
    catalog_order: 100,
    input_cost_per_token: 2.2 / 1_000_000,
    cache_read_input_token_cost: 0.45 / 1_000_000,
    output_cost_per_token: 8.9 / 1_000_000,
    max_input_tokens: 128_000,
    max_output_tokens: 98_304,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: true,
    supports_service_tier: false
  },
  {
    model: 'glm-4.5-air',
    mode: 'chat',
    catalog_order: 110,
    input_cost_per_token: 0.2 / 1_000_000,
    cache_read_input_token_cost: 0.03 / 1_000_000,
    output_cost_per_token: 1.1 / 1_000_000,
    max_input_tokens: 128_000,
    max_output_tokens: 98_304,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: true,
    supports_service_tier: false
  },
  {
    model: 'glm-4.5-airx',
    mode: 'chat',
    catalog_order: 120,
    input_cost_per_token: 1.1 / 1_000_000,
    cache_read_input_token_cost: 0.22 / 1_000_000,
    output_cost_per_token: 4.5 / 1_000_000,
    max_input_tokens: 128_000,
    max_output_tokens: 98_304,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: true,
    supports_service_tier: false
  },
  {
    model: 'glm-4.5-flash',
    mode: 'chat',
    catalog_order: 130,
    input_cost_per_token: 0,
    output_cost_per_token: 0,
    max_input_tokens: 128_000,
    max_output_tokens: 98_304,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: false,
    supports_service_tier: false
  },
  {
    model: 'glm-4-32b-0414-128k',
    mode: 'chat',
    catalog_order: 140,
    input_cost_per_token: 0.1 / 1_000_000,
    output_cost_per_token: 0.1 / 1_000_000,
    max_input_tokens: 128_000,
    max_output_tokens: 8_192,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: false,
    supports_service_tier: false
  },
  {
    model: 'glm-4-long',
    mode: 'chat',
    catalog_order: 150,
    input_cost_per_token: 0.14 / 1_000_000,
    output_cost_per_token: 0.14 / 1_000_000,
    max_input_tokens: 1_000_000,
    max_output_tokens: 8_192,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: false,
    supports_service_tier: false
  },
  {
    model: 'glm-4-flashx-250414',
    mode: 'chat',
    catalog_order: 160,
    input_cost_per_token: 0,
    output_cost_per_token: 0,
    max_input_tokens: 128_000,
    max_output_tokens: 8_192,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: false,
    supports_service_tier: false
  },
  {
    model: 'glm-4-flash-250414',
    mode: 'chat',
    catalog_order: 170,
    input_cost_per_token: 0,
    output_cost_per_token: 0,
    max_input_tokens: 128_000,
    max_output_tokens: 8_192,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: false,
    supports_service_tier: false
  },
  {
    model: 'glm-5.2-free',
    mode: 'chat',
    catalog_order: 999,
    input_cost_per_token: 0,
    output_cost_per_token: 0,
    max_input_tokens: 1_000_000,
    max_output_tokens: 131_072,
    supported_api_protocols: ['chat_completions'],
    supports_prompt_caching: false,
    supports_service_tier: false,
    catalog_visible: false
  }
] as const
