// Curated from official OpenAI model and pricing docs, including the 2026-07-30 pricing changelog.
// Values follow LiteLLM/model-price-repo field names: token prices are USD per token.
// Current GPT-5 family model prices.

export const openAIGPT5ModelPricingData = [
  {
    model: "gpt-5.6-sol",
    litellm_provider: "openai",
    mode: "chat",
    catalog_order: 0,
    release_date: "2026-06-26",
    context_window_tokens: 1050000,
    max_input_tokens: 922000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.000005,
    input_cost_per_token_priority: 0.00001,
    input_cost_per_token_flex: 0.0000025,
    output_cost_per_token: 0.00003,
    output_cost_per_token_priority: 0.00006,
    output_cost_per_token_flex: 0.000015,
    cache_creation_input_token_cost: 0.00000625,
    cache_creation_input_token_cost_priority: 0.0000125,
    cache_creation_input_token_cost_flex: 0.000003125,
    cache_read_input_token_cost: 5e-7,
    cache_read_input_token_cost_priority: 0.000001,
    cache_read_input_token_cost_flex: 2.5e-7,
    long_context_input_token_threshold: 272000,
    long_context_input_cost_multiplier: 2,
    long_context_output_cost_multiplier: 1.5,
    supports_prompt_caching: true,
    supported_service_tiers: ["priority", "flex"],
    supported_reasoning_efforts: ["none","low","medium","high","xhigh","max"],
    codex_supported_reasoning_levels: ["low", "medium", "high", "xhigh", "max", "ultra"],
    codex_default_reasoning_level: "low",
    codex_multi_agent_version: "v2"
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","hosted_shell","apply_patch","skills","computer_use","mcp","tool_search"],
  },
  {
    model: "gpt-5.6-terra",
    litellm_provider: "openai",
    mode: "chat",
    catalog_order: 1,
    release_date: "2026-06-26",
    context_window_tokens: 1050000,
    max_input_tokens: 922000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.000002,
    input_cost_per_token_priority: 0.000004,
    input_cost_per_token_flex: 0.000001,
    output_cost_per_token: 0.000012,
    output_cost_per_token_priority: 0.000024,
    output_cost_per_token_flex: 0.000006,
    cache_creation_input_token_cost: 0.0000025,
    cache_creation_input_token_cost_priority: 0.000005,
    cache_creation_input_token_cost_flex: 0.00000125,
    cache_read_input_token_cost: 2e-7,
    cache_read_input_token_cost_priority: 4e-7,
    cache_read_input_token_cost_flex: 1e-7,
    long_context_input_token_threshold: 272000,
    long_context_input_cost_multiplier: 2,
    long_context_output_cost_multiplier: 1.5,
    supports_prompt_caching: true,
    supported_service_tiers: ["priority", "flex"],
    supported_reasoning_efforts: ["none","low","medium","high","xhigh","max"],
    codex_supported_reasoning_levels: ["low", "medium", "high", "xhigh", "max", "ultra"],
    codex_default_reasoning_level: "medium",
    codex_multi_agent_version: "v2"
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","hosted_shell","apply_patch","skills","computer_use","mcp","tool_search"],
  },
  {
    model: "gpt-5.6-luna",
    litellm_provider: "openai",
    mode: "chat",
    catalog_order: 2,
    release_date: "2026-06-26",
    context_window_tokens: 1050000,
    max_input_tokens: 922000,
    max_output_tokens: 128000,
    input_cost_per_token: 2e-7,
    input_cost_per_token_priority: 4e-7,
    input_cost_per_token_flex: 1e-7,
    output_cost_per_token: 0.0000012,
    output_cost_per_token_priority: 0.0000024,
    output_cost_per_token_flex: 6e-7,
    cache_creation_input_token_cost: 2.5e-7,
    cache_creation_input_token_cost_priority: 5e-7,
    cache_creation_input_token_cost_flex: 1.25e-7,
    cache_read_input_token_cost: 2e-8,
    cache_read_input_token_cost_priority: 4e-8,
    cache_read_input_token_cost_flex: 1e-8,
    long_context_input_token_threshold: 272000,
    long_context_input_cost_multiplier: 2,
    long_context_output_cost_multiplier: 1.5,
    supports_prompt_caching: true,
    supported_service_tiers: ["priority", "flex"],
    supported_reasoning_efforts: ["none","low","medium","high","xhigh","max"],
    codex_supported_reasoning_levels: ["low", "medium", "high", "xhigh", "max"],
    codex_default_reasoning_level: "medium"
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","hosted_shell","apply_patch","skills","computer_use","mcp","tool_search"],
  },
  {
    model: "gpt-5.5",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    context_window_tokens: 1050000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.000005,
    input_cost_per_token_priority: 0.0000125,
    input_cost_per_token_flex: 0.0000025,
    output_cost_per_token: 0.00003,
    output_cost_per_token_priority: 0.000075,
    output_cost_per_token_flex: 0.000015,
    cache_read_input_token_cost: 5e-7,
    cache_read_input_token_cost_priority: 0.00000125,
    cache_read_input_token_cost_flex: 2.5e-7,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["none","low","medium","high","xhigh"],
    supported_service_tiers: ["priority", "flex"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","tool_search","image_generation","code_interpreter","hosted_shell","apply_patch","skills","computer_use","mcp"],
  },
  {
    model: "gpt-5.5-2026-04-23",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    context_window_tokens: 1050000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.000005,
    input_cost_per_token_priority: 0.0000125,
    input_cost_per_token_flex: 0.0000025,
    output_cost_per_token: 0.00003,
    output_cost_per_token_priority: 0.000075,
    output_cost_per_token_flex: 0.000015,
    cache_read_input_token_cost: 5e-7,
    cache_read_input_token_cost_priority: 0.00000125,
    cache_read_input_token_cost_flex: 2.5e-7,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["none","low","medium","high","xhigh"],
    supported_service_tiers: ["priority", "flex"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","tool_search","image_generation","code_interpreter","hosted_shell","apply_patch","skills","computer_use","mcp"],
  },
  {
    model: "gpt-5.5-pro",
    litellm_provider: "openai",
    mode: "responses",
    max_tokens: 128000,
    context_window_tokens: 1050000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00003,
    input_cost_per_token_flex: 0.000015,
    output_cost_per_token: 0.00018,
    output_cost_per_token_flex: 0.00009,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["medium","high","xhigh"],
    supported_service_tiers: ["flex"]
  ,
    supported_api_protocols: ["responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","hosted_shell","mcp"],
  },
  {
    model: "gpt-5.5-pro-2026-04-23",
    litellm_provider: "openai",
    mode: "responses",
    max_tokens: 128000,
    context_window_tokens: 1050000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00003,
    input_cost_per_token_flex: 0.000015,
    output_cost_per_token: 0.00018,
    output_cost_per_token_flex: 0.00009,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["medium","high","xhigh"],
    supported_service_tiers: ["flex"]
  ,
    supported_api_protocols: ["responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","hosted_shell","mcp"],
  },
  {
    model: "gpt-5.4",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    context_window_tokens: 1050000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.0000025,
    input_cost_per_token_priority: 0.000005,
    input_cost_per_token_flex: 0.00000125,
    output_cost_per_token: 0.000015,
    output_cost_per_token_priority: 0.00003,
    output_cost_per_token_flex: 0.0000075,
    cache_read_input_token_cost: 2.5e-7,
    cache_read_input_token_cost_priority: 5e-7,
    cache_read_input_token_cost_flex: 1.3e-7,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["none","low","medium","high","xhigh"],
    supported_service_tiers: ["priority", "flex"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","tool_search","image_generation","code_interpreter","hosted_shell","apply_patch","skills","computer_use","mcp"],
  },
  {
    model: "gpt-5.4-2026-03-05",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    context_window_tokens: 1050000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.0000025,
    input_cost_per_token_priority: 0.000005,
    input_cost_per_token_flex: 0.00000125,
    output_cost_per_token: 0.000015,
    output_cost_per_token_priority: 0.00003,
    output_cost_per_token_flex: 0.0000075,
    cache_read_input_token_cost: 2.5e-7,
    cache_read_input_token_cost_priority: 5e-7,
    cache_read_input_token_cost_flex: 1.3e-7,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["none","low","medium","high","xhigh"],
    supported_service_tiers: ["priority", "flex"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","tool_search","image_generation","code_interpreter","hosted_shell","apply_patch","skills","computer_use","mcp"],
  },
  {
    model: "gpt-5.4-mini",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    context_window_tokens: 400000,
    max_input_tokens: 272000,
    max_output_tokens: 128000,
    input_cost_per_token: 7.5e-7,
    input_cost_per_token_priority: 0.0000015,
    input_cost_per_token_flex: 3.75e-7,
    output_cost_per_token: 0.0000045,
    output_cost_per_token_priority: 0.000009,
    output_cost_per_token_flex: 0.00000225,
    cache_read_input_token_cost: 7.5e-8,
    cache_read_input_token_cost_priority: 1.5e-7,
    cache_read_input_token_cost_flex: 3.75e-8,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["none","low","medium","high","xhigh"],
    supported_service_tiers: ["priority", "flex"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","tool_search","image_generation","code_interpreter","hosted_shell","apply_patch","skills","computer_use","mcp"],
  },
  {
    model: "gpt-5.4-mini-2026-03-17",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    context_window_tokens: 400000,
    max_input_tokens: 272000,
    max_output_tokens: 128000,
    input_cost_per_token: 7.5e-7,
    input_cost_per_token_priority: 0.0000015,
    input_cost_per_token_flex: 3.75e-7,
    output_cost_per_token: 0.0000045,
    output_cost_per_token_priority: 0.000009,
    output_cost_per_token_flex: 0.00000225,
    cache_read_input_token_cost: 7.5e-8,
    cache_read_input_token_cost_priority: 1.5e-7,
    cache_read_input_token_cost_flex: 3.75e-8,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["none","low","medium","high","xhigh"],
    supported_service_tiers: ["priority", "flex"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","tool_search","image_generation","code_interpreter","hosted_shell","apply_patch","skills","computer_use","mcp"],
  },
  {
    model: "gpt-5.4-nano",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    context_window_tokens: 400000,
    max_input_tokens: 272000,
    max_output_tokens: 128000,
    input_cost_per_token: 2e-7,
    input_cost_per_token_flex: 1e-7,
    output_cost_per_token: 0.00000125,
    output_cost_per_token_flex: 6.25e-7,
    cache_read_input_token_cost: 2e-8,
    cache_read_input_token_cost_flex: 1e-8,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["none","low","medium","high","xhigh"],
    supported_service_tiers: ["flex"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","hosted_shell","apply_patch","skills","mcp"],
  },
  {
    model: "gpt-5.4-nano-2026-03-17",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    context_window_tokens: 400000,
    max_input_tokens: 272000,
    max_output_tokens: 128000,
    input_cost_per_token: 2e-7,
    input_cost_per_token_flex: 1e-7,
    output_cost_per_token: 0.00000125,
    output_cost_per_token_flex: 6.25e-7,
    cache_read_input_token_cost: 2e-8,
    cache_read_input_token_cost_flex: 1e-8,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["none","low","medium","high","xhigh"],
    supported_service_tiers: ["flex"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","hosted_shell","apply_patch","skills","mcp"],
  },
  {
    model: "gpt-5.4-pro",
    litellm_provider: "openai",
    mode: "responses",
    max_tokens: 128000,
    context_window_tokens: 1050000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00003,
    input_cost_per_token_flex: 0.000015,
    output_cost_per_token: 0.00018,
    output_cost_per_token_flex: 0.00009,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["medium","high","xhigh"],
    supported_service_tiers: ["flex"]
  ,
    supported_api_protocols: ["responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","tool_search","image_generation","apply_patch","computer_use","mcp"],
  },
  {
    model: "gpt-5.4-pro-2026-03-05",
    litellm_provider: "openai",
    mode: "responses",
    max_tokens: 128000,
    context_window_tokens: 1050000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00003,
    input_cost_per_token_flex: 0.000015,
    output_cost_per_token: 0.00018,
    output_cost_per_token_flex: 0.00009,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["medium","high","xhigh"],
    supported_service_tiers: ["flex"]
  ,
    supported_api_protocols: ["responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","tool_search","image_generation","apply_patch","computer_use","mcp"],
  },
  {
    model: "gpt-5.3-chat-latest",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 16384,
    max_input_tokens: 128000,
    max_output_tokens: 16384,
    input_cost_per_token: 0.00000175,
    input_cost_per_token_priority: 0.0000035,
    output_cost_per_token: 0.000014,
    output_cost_per_token_priority: 0.000028,
    cache_read_input_token_cost: 1.75e-7,
    cache_read_input_token_cost_priority: 3.5e-7,
    shutdown_date: "2026-08-10",
    supports_prompt_caching: true
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","mcp"]
  },
  {
    model: "gpt-5.3-codex",
    litellm_provider: "openai",
    mode: "responses",
    max_tokens: 128000,
    context_window_tokens: 400000,
    max_input_tokens: 272000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00000175,
    input_cost_per_token_priority: 0.0000035,
    output_cost_per_token: 0.000014,
    output_cost_per_token_priority: 0.000028,
    cache_read_input_token_cost: 1.75e-7,
    cache_read_input_token_cost_priority: 3.5e-7,
    supports_prompt_caching: true,
    supported_service_tiers: ["priority"]
  ,
    supported_api_protocols: ["responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","hosted_shell","skills"],
    supported_reasoning_efforts: ["low","medium","high","xhigh"]
  },
  {
    model: "gpt-5.2",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    max_input_tokens: 400000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00000175,
    input_cost_per_token_priority: 0.0000035,
    output_cost_per_token: 0.000014,
    output_cost_per_token_priority: 0.000028,
    cache_read_input_token_cost: 1.75e-7,
    cache_read_input_token_cost_priority: 3.5e-7,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["none","low","medium","high","xhigh"],
    supported_service_tiers: ["priority"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","hosted_shell","apply_patch","skills","mcp"],
  },
  {
    model: "gpt-5.2-2025-12-11",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    max_input_tokens: 400000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00000175,
    input_cost_per_token_priority: 0.0000035,
    output_cost_per_token: 0.000014,
    output_cost_per_token_priority: 0.000028,
    cache_read_input_token_cost: 1.75e-7,
    cache_read_input_token_cost_priority: 3.5e-7,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["none","low","medium","high","xhigh"],
    supported_service_tiers: ["priority"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","hosted_shell","apply_patch","skills","mcp"],
  },
  {
    model: "gpt-5.2-pro",
    litellm_provider: "openai",
    mode: "responses",
    max_tokens: 128000,
    max_input_tokens: 400000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.000021,
    output_cost_per_token: 0.000168,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["medium","high","xhigh"],
    supported_service_tiers: ["priority"]
  ,
    supported_api_protocols: ["responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","file_search","image_generation","mcp","web_search"]
  },
  {
    model: "gpt-5.2-pro-2025-12-11",
    litellm_provider: "openai",
    mode: "responses",
    max_tokens: 128000,
    max_input_tokens: 400000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.000021,
    output_cost_per_token: 0.000168,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["medium","high","xhigh"],
    supported_service_tiers: ["priority"]
  ,
    supported_api_protocols: ["responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","file_search","image_generation","mcp","web_search"]
  },
  {
    model: "gpt-5.2-chat-latest",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 16384,
    max_input_tokens: 128000,
    max_output_tokens: 16384,
    input_cost_per_token: 0.00000175,
    output_cost_per_token: 0.000014,
    cache_read_input_token_cost: 1.75e-7,
    shutdown_date: "2026-08-10",
    supports_prompt_caching: true
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","mcp"]
  },
  {
    model: "gpt-5.2-codex",
    litellm_provider: "openai",
    mode: "responses",
    max_tokens: 128000,
    max_input_tokens: 400000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00000175,
    input_cost_per_token_priority: 0.0000035,
    output_cost_per_token: 0.000014,
    output_cost_per_token_priority: 0.000028,
    cache_read_input_token_cost: 1.75e-7,
    cache_read_input_token_cost_priority: 3.5e-7,
    shutdown_date: "2026-07-23",
    supports_prompt_caching: true,
    supported_service_tiers: ["priority"]
  ,
    supported_api_protocols: ["responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","hosted_shell","skills"],
    supported_reasoning_efforts: ["low","medium","high","xhigh"]
  },
  {
    model: "gpt-5.1",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    max_input_tokens: 400000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00000125,
    input_cost_per_token_priority: 0.0000025,
    output_cost_per_token: 0.00001,
    output_cost_per_token_priority: 0.00002,
    cache_read_input_token_cost: 1.25e-7,
    cache_read_input_token_cost_priority: 2.5e-7,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["none","low","medium","high"],
    supported_service_tiers: ["priority"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","apply_patch","mcp"],
  },
  {
    model: "gpt-5.1-2025-11-13",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    max_input_tokens: 400000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00000125,
    input_cost_per_token_priority: 0.0000025,
    output_cost_per_token: 0.00001,
    output_cost_per_token_priority: 0.00002,
    cache_read_input_token_cost: 1.25e-7,
    cache_read_input_token_cost_priority: 2.5e-7,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["none","low","medium","high"],
    supported_service_tiers: ["priority"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","apply_patch","mcp"],
  },
  {
    model: "gpt-5.1-chat-latest",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 16384,
    max_input_tokens: 128000,
    max_output_tokens: 16384,
    input_cost_per_token: 0.00000125,
    output_cost_per_token: 0.00001,
    cache_read_input_token_cost: 1.25e-7,
    shutdown_date: "2026-07-23",
    supports_prompt_caching: true
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","mcp"]
  },
  {
    model: "gpt-5.1-codex",
    litellm_provider: "openai",
    mode: "responses",
    max_tokens: 128000,
    max_input_tokens: 400000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00000125,
    input_cost_per_token_priority: 0.0000025,
    output_cost_per_token: 0.00001,
    output_cost_per_token_priority: 0.00002,
    cache_read_input_token_cost: 1.25e-7,
    cache_read_input_token_cost_priority: 2.5e-7,
    shutdown_date: "2026-07-23",
    supports_prompt_caching: true,
    supported_service_tiers: ["priority"]
  ,
    supported_api_protocols: ["responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search"]
  },
  {
    model: "gpt-5.1-codex-max",
    litellm_provider: "openai",
    mode: "responses",
    max_tokens: 128000,
    max_input_tokens: 400000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00000125,
    input_cost_per_token_priority: 0.0000025,
    output_cost_per_token: 0.00001,
    output_cost_per_token_priority: 0.00002,
    cache_read_input_token_cost: 1.25e-7,
    cache_read_input_token_cost_priority: 2.5e-7,
    shutdown_date: "2026-07-23",
    supports_prompt_caching: true,
    supported_service_tiers: ["priority"]
  ,
    supported_api_protocols: ["responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search"]
  },
  {
    model: "gpt-5.1-codex-mini",
    litellm_provider: "openai",
    mode: "responses",
    max_tokens: 128000,
    max_input_tokens: 400000,
    max_output_tokens: 128000,
    input_cost_per_token: 2.5e-7,
    output_cost_per_token: 0.000002,
    cache_read_input_token_cost: 2.5e-8,
    shutdown_date: "2026-07-23",
    supports_prompt_caching: true,
    supported_service_tiers: ["priority"]
  ,
    supported_api_protocols: ["responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search"]
  },
  {
    model: "gpt-5",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    context_window_tokens: 400000,
    max_input_tokens: 272000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00000125,
    input_cost_per_token_priority: 0.0000025,
    output_cost_per_token: 0.00001,
    output_cost_per_token_priority: 0.00002,
    cache_read_input_token_cost: 1.25e-7,
    cache_read_input_token_cost_priority: 2.5e-7,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["minimal","low","medium","high"],
    supported_service_tiers: ["priority", "flex"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","mcp"],
  },
  {
    model: "gpt-5-2025-08-07",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    context_window_tokens: 400000,
    max_input_tokens: 272000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00000125,
    input_cost_per_token_priority: 0.0000025,
    output_cost_per_token: 0.00001,
    output_cost_per_token_priority: 0.00002,
    cache_read_input_token_cost: 1.25e-7,
    cache_read_input_token_cost_priority: 2.5e-7,
    supports_prompt_caching: true,
    supported_reasoning_efforts: ["minimal","low","medium","high"],
    supported_service_tiers: ["priority", "flex"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","mcp"],
  },
  {
    model: "gpt-5-chat-latest",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 16384,
    max_input_tokens: 128000,
    max_output_tokens: 16384,
    input_cost_per_token: 0.00000125,
    output_cost_per_token: 0.00001,
    cache_read_input_token_cost: 1.25e-7,
    shutdown_date: "2026-07-23",
    supports_prompt_caching: true
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","mcp"]
  },
  {
    model: "gpt-5-codex",
    litellm_provider: "openai",
    mode: "responses",
    max_tokens: 128000,
    max_input_tokens: 400000,
    max_output_tokens: 128000,
    input_cost_per_token: 0.00000125,
    input_cost_per_token_priority: 0.0000025,
    output_cost_per_token: 0.00001,
    output_cost_per_token_priority: 0.00002,
    cache_read_input_token_cost: 1.25e-7,
    cache_read_input_token_cost_priority: 2.5e-7,
    shutdown_date: "2026-07-23",
    supports_prompt_caching: true,
    supported_service_tiers: ["priority"]
  ,
    supported_api_protocols: ["responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search"]
  },
  {
    model: "gpt-5-mini",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    context_window_tokens: 400000,
    max_input_tokens: 272000,
    max_output_tokens: 128000,
    input_cost_per_token: 2.5e-7,
    input_cost_per_token_priority: 4.5e-7,
    output_cost_per_token: 0.000002,
    output_cost_per_token_priority: 0.0000036,
    cache_read_input_token_cost: 2.5e-8,
    cache_read_input_token_cost_priority: 4.5e-8,
    supports_prompt_caching: true,
    supported_service_tiers: ["priority", "flex"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","code_interpreter","mcp"],
    supported_reasoning_efforts: ["minimal","low","medium","high"],
  },
  {
    model: "gpt-5-mini-2025-08-07",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    context_window_tokens: 400000,
    max_input_tokens: 272000,
    max_output_tokens: 128000,
    input_cost_per_token: 2.5e-7,
    input_cost_per_token_priority: 4.5e-7,
    output_cost_per_token: 0.000002,
    output_cost_per_token_priority: 0.0000036,
    cache_read_input_token_cost: 2.5e-8,
    cache_read_input_token_cost_priority: 4.5e-8,
    supports_prompt_caching: true,
    supported_service_tiers: ["priority", "flex"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","code_interpreter","mcp"],
    supported_reasoning_efforts: ["minimal","low","medium","high"],
  },
  {
    model: "gpt-5-nano",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    context_window_tokens: 400000,
    max_input_tokens: 272000,
    max_output_tokens: 128000,
    input_cost_per_token: 5e-8,
    input_cost_per_token_priority: 2e-7,
    output_cost_per_token: 4e-7,
    output_cost_per_token_priority: 8e-7,
    cache_read_input_token_cost: 5e-9,
    cache_read_input_token_cost_priority: 5e-8,
    supports_prompt_caching: true,
    supported_service_tiers: ["priority", "flex"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","mcp"],
    supported_reasoning_efforts: ["minimal","low","medium","high"],
  },
  {
    model: "gpt-5-nano-2025-08-07",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 128000,
    context_window_tokens: 400000,
    max_input_tokens: 272000,
    max_output_tokens: 128000,
    input_cost_per_token: 5e-8,
    input_cost_per_token_priority: 2e-7,
    output_cost_per_token: 4e-7,
    output_cost_per_token_priority: 8e-7,
    cache_read_input_token_cost: 5e-9,
    cache_read_input_token_cost_priority: 5e-8,
    supports_prompt_caching: true,
    supported_service_tiers: ["priority", "flex"]
  ,
    supported_api_protocols: ["chat_completions","responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","web_search","file_search","image_generation","code_interpreter","mcp"],
    supported_reasoning_efforts: ["minimal","low","medium","high"],
  },
  {
    model: "gpt-5-pro",
    litellm_provider: "openai",
    mode: "responses",
    max_tokens: 128000,
    context_window_tokens: 400000,
    max_output_tokens: 272000,
    input_cost_per_token: 0.000015,
    output_cost_per_token: 0.00012,
    supports_prompt_caching: true,
    supported_service_tiers: ["priority"]
  ,
    supported_api_protocols: ["responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","file_search","image_generation","mcp","web_search"],
    supported_reasoning_efforts: ["high"],
  },
  {
    model: "gpt-5-pro-2025-10-06",
    litellm_provider: "openai",
    mode: "responses",
    max_tokens: 128000,
    context_window_tokens: 400000,
    max_output_tokens: 272000,
    input_cost_per_token: 0.000015,
    output_cost_per_token: 0.00012,
    supports_prompt_caching: true,
    supported_service_tiers: ["priority"]
  ,
    supported_api_protocols: ["responses"],
    input_modalities: ["text","image"],
    output_modalities: ["text"],
    supported_tools: ["function_calling","file_search","image_generation","mcp","web_search"],
    supported_reasoning_efforts: ["high"],
  }
] as const
