// Generated from https://raw.githubusercontent.com/Wei-Shaw/model-price-repo/main/model_prices_and_context_window.json at 2026-05-01T17:12:56Z.
// Values follow LiteLLM/model-price-repo field names: token prices are USD per token.

export const openAIModelPricingData = [
  {
    "model": "gpt-3.5-turbo",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 16385,
    "max_output_tokens": 4096,
    "input_cost_per_token": 5E-07,
    "output_cost_per_token": 1.5E-06,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-3.5-turbo-0125",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 16385,
    "max_output_tokens": 4096,
    "input_cost_per_token": 5E-07,
    "output_cost_per_token": 1.5E-06,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-3.5-turbo-1106",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 16385,
    "max_output_tokens": 4096,
    "input_cost_per_token": 1E-06,
    "output_cost_per_token": 2E-06,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-3.5-turbo-16k",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 16385,
    "max_output_tokens": 4096,
    "input_cost_per_token": 3E-06,
    "output_cost_per_token": 4E-06,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-4",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 8192,
    "max_output_tokens": 4096,
    "input_cost_per_token": 3E-05,
    "output_cost_per_token": 6E-05,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-4-0125-preview",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 1E-05,
    "output_cost_per_token": 3E-05,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-4-0314",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 8192,
    "max_output_tokens": 4096,
    "input_cost_per_token": 3E-05,
    "output_cost_per_token": 6E-05
  },
  {
    "model": "gpt-4-0613",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 8192,
    "max_output_tokens": 4096,
    "input_cost_per_token": 3E-05,
    "output_cost_per_token": 6E-05,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-4-1106-preview",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 1E-05,
    "output_cost_per_token": 3E-05,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-4-turbo",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 1E-05,
    "output_cost_per_token": 3E-05,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-4-turbo-2024-04-09",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 1E-05,
    "output_cost_per_token": 3E-05,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-4-turbo-preview",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 1E-05,
    "output_cost_per_token": 3E-05,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-4.1",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 32768,
    "max_input_tokens": 1047576,
    "max_output_tokens": 32768,
    "input_cost_per_token": 2E-06,
    "input_cost_per_token_priority": 3.5E-06,
    "output_cost_per_token": 8E-06,
    "output_cost_per_token_priority": 1.4E-05,
    "cache_read_input_token_cost": 5E-07,
    "cache_read_input_token_cost_priority": 8.75E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-4.1-2025-04-14",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 32768,
    "max_input_tokens": 1047576,
    "max_output_tokens": 32768,
    "input_cost_per_token": 2E-06,
    "output_cost_per_token": 8E-06,
    "cache_read_input_token_cost": 5E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-4.1-mini",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 32768,
    "max_input_tokens": 1047576,
    "max_output_tokens": 32768,
    "input_cost_per_token": 4E-07,
    "input_cost_per_token_priority": 7E-07,
    "output_cost_per_token": 1.6E-06,
    "output_cost_per_token_priority": 2.8E-06,
    "cache_read_input_token_cost": 1E-07,
    "cache_read_input_token_cost_priority": 1.75E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-4.1-mini-2025-04-14",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 32768,
    "max_input_tokens": 1047576,
    "max_output_tokens": 32768,
    "input_cost_per_token": 4E-07,
    "output_cost_per_token": 1.6E-06,
    "cache_read_input_token_cost": 1E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-4.1-nano",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 32768,
    "max_input_tokens": 1047576,
    "max_output_tokens": 32768,
    "input_cost_per_token": 1E-07,
    "input_cost_per_token_priority": 2E-07,
    "output_cost_per_token": 4E-07,
    "output_cost_per_token_priority": 8E-07,
    "cache_read_input_token_cost": 2.5E-08,
    "cache_read_input_token_cost_priority": 5E-08,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-4.1-nano-2025-04-14",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 32768,
    "max_input_tokens": 1047576,
    "max_output_tokens": 32768,
    "input_cost_per_token": 1E-07,
    "output_cost_per_token": 4E-07,
    "cache_read_input_token_cost": 2.5E-08,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-4o",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 2.5E-06,
    "input_cost_per_token_priority": 4.25E-06,
    "output_cost_per_token": 1E-05,
    "output_cost_per_token_priority": 1.7E-05,
    "cache_read_input_token_cost": 1.25E-06,
    "cache_read_input_token_cost_priority": 2.125E-06,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-4o-2024-05-13",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 5E-06,
    "input_cost_per_token_priority": 8.75E-06,
    "output_cost_per_token": 1.5E-05,
    "output_cost_per_token_priority": 2.625E-05,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-4o-2024-08-06",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05,
    "cache_read_input_token_cost": 1.25E-06,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-4o-2024-11-20",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05,
    "cache_read_input_token_cost": 1.25E-06,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-4o-audio-preview",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05
  },
  {
    "model": "gpt-4o-audio-preview-2024-12-17",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05
  },
  {
    "model": "gpt-4o-audio-preview-2025-06-03",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05
  },
  {
    "model": "gpt-4o-mini",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 1.5E-07,
    "input_cost_per_token_priority": 2.5E-07,
    "output_cost_per_token": 6E-07,
    "output_cost_per_token_priority": 1E-06,
    "cache_read_input_token_cost": 7.5E-08,
    "cache_read_input_token_cost_priority": 1.25E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-4o-mini-2024-07-18",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 1.5E-07,
    "output_cost_per_token": 6E-07,
    "cache_read_input_token_cost": 7.5E-08,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-4o-mini-audio-preview",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 1.5E-07,
    "output_cost_per_token": 6E-07
  },
  {
    "model": "gpt-4o-mini-audio-preview-2024-12-17",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 1.5E-07,
    "output_cost_per_token": 6E-07
  },
  {
    "model": "gpt-4o-mini-realtime-preview",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 6E-07,
    "output_cost_per_token": 2.4E-06,
    "cache_read_input_token_cost": 3E-07
  },
  {
    "model": "gpt-4o-mini-realtime-preview-2024-12-17",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 6E-07,
    "output_cost_per_token": 2.4E-06,
    "cache_read_input_token_cost": 3E-07
  },
  {
    "model": "gpt-4o-mini-search-preview",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 1.5E-07,
    "output_cost_per_token": 6E-07,
    "cache_read_input_token_cost": 7.5E-08,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-4o-mini-search-preview-2025-03-11",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 1.5E-07,
    "output_cost_per_token": 6E-07,
    "cache_read_input_token_cost": 7.5E-08,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-4o-mini-transcribe",
    "litellm_provider": "openai",
    "mode": "audio_transcription",
    "max_input_tokens": 16000,
    "max_output_tokens": 2000,
    "input_cost_per_token": 1.25E-06,
    "output_cost_per_token": 5E-06
  },
  {
    "model": "gpt-4o-mini-transcribe-2025-03-20",
    "litellm_provider": "openai",
    "mode": "audio_transcription",
    "max_input_tokens": 16000,
    "max_output_tokens": 2000,
    "input_cost_per_token": 1.25E-06,
    "output_cost_per_token": 5E-06
  },
  {
    "model": "gpt-4o-mini-transcribe-2025-12-15",
    "litellm_provider": "openai",
    "mode": "audio_transcription",
    "max_input_tokens": 16000,
    "max_output_tokens": 2000,
    "input_cost_per_token": 1.25E-06,
    "output_cost_per_token": 5E-06
  },
  {
    "model": "gpt-4o-mini-tts",
    "litellm_provider": "openai",
    "mode": "audio_speech",
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05
  },
  {
    "model": "gpt-4o-mini-tts-2025-03-20",
    "litellm_provider": "openai",
    "mode": "audio_speech",
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05
  },
  {
    "model": "gpt-4o-mini-tts-2025-12-15",
    "litellm_provider": "openai",
    "mode": "audio_speech",
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05
  },
  {
    "model": "gpt-4o-realtime-preview",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 5E-06,
    "output_cost_per_token": 2E-05,
    "cache_read_input_token_cost": 2.5E-06
  },
  {
    "model": "gpt-4o-realtime-preview-2024-12-17",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 5E-06,
    "output_cost_per_token": 2E-05,
    "cache_read_input_token_cost": 2.5E-06
  },
  {
    "model": "gpt-4o-realtime-preview-2025-06-03",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 5E-06,
    "output_cost_per_token": 2E-05,
    "cache_read_input_token_cost": 2.5E-06
  },
  {
    "model": "gpt-4o-search-preview",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05,
    "cache_read_input_token_cost": 1.25E-06,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-4o-search-preview-2025-03-11",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05,
    "cache_read_input_token_cost": 1.25E-06,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-4o-transcribe",
    "litellm_provider": "openai",
    "mode": "audio_transcription",
    "max_input_tokens": 16000,
    "max_output_tokens": 2000,
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05
  },
  {
    "model": "gpt-4o-transcribe-diarize",
    "litellm_provider": "openai",
    "mode": "audio_transcription",
    "max_input_tokens": 16000,
    "max_output_tokens": 2000,
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05
  },
  {
    "model": "gpt-5",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 1.25E-06,
    "input_cost_per_token_priority": 2.5E-06,
    "output_cost_per_token": 1E-05,
    "output_cost_per_token_priority": 2E-05,
    "cache_read_input_token_cost": 1.25E-07,
    "cache_read_input_token_cost_priority": 2.5E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5-2025-08-07",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 1.25E-06,
    "input_cost_per_token_priority": 2.5E-06,
    "output_cost_per_token": 1E-05,
    "output_cost_per_token_priority": 2E-05,
    "cache_read_input_token_cost": 1.25E-07,
    "cache_read_input_token_cost_priority": 2.5E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5-chat",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 1.25E-06,
    "output_cost_per_token": 1E-05,
    "cache_read_input_token_cost": 1.25E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5-chat-latest",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 1.25E-06,
    "output_cost_per_token": 1E-05,
    "cache_read_input_token_cost": 1.25E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5-codex",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 1.25E-06,
    "output_cost_per_token": 1E-05,
    "cache_read_input_token_cost": 1.25E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5-mini",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 2.5E-07,
    "input_cost_per_token_priority": 4.5E-07,
    "output_cost_per_token": 2E-06,
    "output_cost_per_token_priority": 3.6E-06,
    "cache_read_input_token_cost": 2.5E-08,
    "cache_read_input_token_cost_priority": 4.5E-08,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5-mini-2025-08-07",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 2.5E-07,
    "input_cost_per_token_priority": 4.5E-07,
    "output_cost_per_token": 2E-06,
    "output_cost_per_token_priority": 3.6E-06,
    "cache_read_input_token_cost": 2.5E-08,
    "cache_read_input_token_cost_priority": 4.5E-08,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5-nano",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 5E-08,
    "input_cost_per_token_priority": 2.5E-06,
    "output_cost_per_token": 4E-07,
    "cache_read_input_token_cost": 5E-09,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5-nano-2025-08-07",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 5E-08,
    "output_cost_per_token": 4E-07,
    "cache_read_input_token_cost": 5E-09,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5-pro",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 272000,
    "max_input_tokens": 128000,
    "max_output_tokens": 272000,
    "input_cost_per_token": 1.5E-05,
    "output_cost_per_token": 0.00012,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5-pro-2025-10-06",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 272000,
    "max_input_tokens": 128000,
    "max_output_tokens": 272000,
    "input_cost_per_token": 1.5E-05,
    "output_cost_per_token": 0.00012,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5-search-api",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 1.25E-06,
    "output_cost_per_token": 1E-05,
    "cache_read_input_token_cost": 1.25E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5-search-api-2025-10-14",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 1.25E-06,
    "output_cost_per_token": 1E-05,
    "cache_read_input_token_cost": 1.25E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5.1",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 1.25E-06,
    "input_cost_per_token_priority": 2.5E-06,
    "output_cost_per_token": 1E-05,
    "output_cost_per_token_priority": 2E-05,
    "cache_read_input_token_cost": 1.25E-07,
    "cache_read_input_token_cost_priority": 2.5E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.1-2025-11-13",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 1.25E-06,
    "input_cost_per_token_priority": 2.5E-06,
    "output_cost_per_token": 1E-05,
    "output_cost_per_token_priority": 2E-05,
    "cache_read_input_token_cost": 1.25E-07,
    "cache_read_input_token_cost_priority": 2.5E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.1-chat-latest",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 1.25E-06,
    "input_cost_per_token_priority": 2.5E-06,
    "output_cost_per_token": 1E-05,
    "output_cost_per_token_priority": 2E-05,
    "cache_read_input_token_cost": 1.25E-07,
    "cache_read_input_token_cost_priority": 2.5E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5.1-codex",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 1.25E-06,
    "input_cost_per_token_priority": 2.5E-06,
    "output_cost_per_token": 1E-05,
    "output_cost_per_token_priority": 2E-05,
    "cache_read_input_token_cost": 1.25E-07,
    "cache_read_input_token_cost_priority": 2.5E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5.1-codex-max",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 1.25E-06,
    "output_cost_per_token": 1E-05,
    "cache_read_input_token_cost": 1.25E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5.1-codex-mini",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 2.5E-07,
    "input_cost_per_token_priority": 4.5E-07,
    "output_cost_per_token": 2E-06,
    "output_cost_per_token_priority": 3.6E-06,
    "cache_read_input_token_cost": 2.5E-08,
    "cache_read_input_token_cost_priority": 4.5E-08,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5.2",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 1.75E-06,
    "input_cost_per_token_priority": 3.5E-06,
    "output_cost_per_token": 1.4E-05,
    "output_cost_per_token_priority": 2.8E-05,
    "cache_read_input_token_cost": 1.75E-07,
    "cache_read_input_token_cost_priority": 3.5E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.2-2025-12-11",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 1.75E-06,
    "input_cost_per_token_priority": 3.5E-06,
    "output_cost_per_token": 1.4E-05,
    "output_cost_per_token_priority": 2.8E-05,
    "cache_read_input_token_cost": 1.75E-07,
    "cache_read_input_token_cost_priority": 3.5E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.2-chat-latest",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 1.75E-06,
    "input_cost_per_token_priority": 3.5E-06,
    "output_cost_per_token": 1.4E-05,
    "output_cost_per_token_priority": 2.8E-05,
    "cache_read_input_token_cost": 1.75E-07,
    "cache_read_input_token_cost_priority": 3.5E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5.2-codex",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 1.75E-06,
    "input_cost_per_token_priority": 3.5E-06,
    "output_cost_per_token": 1.4E-05,
    "output_cost_per_token_priority": 2.8E-05,
    "cache_read_input_token_cost": 1.75E-07,
    "cache_read_input_token_cost_priority": 3.5E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5.2-pro",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 2.1E-05,
    "output_cost_per_token": 0.000168,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5.2-pro-2025-12-11",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 2.1E-05,
    "output_cost_per_token": 0.000168,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5.3-chat-latest",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 1.75E-06,
    "input_cost_per_token_priority": 3.5E-06,
    "output_cost_per_token": 1.4E-05,
    "output_cost_per_token_priority": 2.8E-05,
    "cache_read_input_token_cost": 1.75E-07,
    "cache_read_input_token_cost_priority": 3.5E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5.3-codex",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 1.75E-06,
    "input_cost_per_token_priority": 3.5E-06,
    "output_cost_per_token": 1.4E-05,
    "output_cost_per_token_priority": 2.8E-05,
    "cache_read_input_token_cost": 1.75E-07,
    "cache_read_input_token_cost_priority": 3.5E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5.3-codex-spark",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 1.75E-06,
    "input_cost_per_token_priority": 3.5E-06,
    "output_cost_per_token": 1.4E-05,
    "output_cost_per_token_priority": 2.8E-05,
    "cache_read_input_token_cost": 1.75E-07,
    "cache_read_input_token_cost_priority": 3.5E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "gpt-5.4",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 1050000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 2.5E-06,
    "input_cost_per_token_priority": 5E-06,
    "output_cost_per_token": 1.5E-05,
    "output_cost_per_token_priority": 3E-05,
    "cache_read_input_token_cost": 2.5E-07,
    "cache_read_input_token_cost_priority": 5E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.4-2026-03-05",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 1050000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 2.5E-06,
    "input_cost_per_token_priority": 5E-06,
    "output_cost_per_token": 1.5E-05,
    "output_cost_per_token_priority": 3E-05,
    "cache_read_input_token_cost": 2.5E-07,
    "cache_read_input_token_cost_priority": 5E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.4-mini",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 400000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 7.5E-07,
    "input_cost_per_token_priority": 1.5E-06,
    "output_cost_per_token": 4.5E-06,
    "output_cost_per_token_priority": 9E-06,
    "cache_read_input_token_cost": 7.5E-08,
    "cache_read_input_token_cost_priority": 1.5E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.4-mini-2026-03-17",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 7.5E-07,
    "input_cost_per_token_priority": 1.5E-06,
    "output_cost_per_token": 4.5E-06,
    "output_cost_per_token_priority": 9E-06,
    "cache_read_input_token_cost": 7.5E-08,
    "cache_read_input_token_cost_priority": 1.5E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.4-nano",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 400000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 2E-07,
    "output_cost_per_token": 1.25E-06,
    "cache_read_input_token_cost": 2E-08,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.4-nano-2026-03-17",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 272000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 2E-07,
    "output_cost_per_token": 1.25E-06,
    "cache_read_input_token_cost": 2E-08,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.4-pro",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 128000,
    "max_input_tokens": 1050000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 3E-05,
    "output_cost_per_token": 0.00018,
    "cache_read_input_token_cost": 3E-06,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.4-pro-2026-03-05",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 128000,
    "max_input_tokens": 1050000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 3E-05,
    "output_cost_per_token": 0.00018,
    "cache_read_input_token_cost": 3E-06,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.5",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 1050000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 5E-06,
    "input_cost_per_token_priority": 1E-05,
    "output_cost_per_token": 3E-05,
    "output_cost_per_token_priority": 6E-05,
    "cache_read_input_token_cost": 5E-07,
    "cache_read_input_token_cost_priority": 1E-06,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.5-2026-04-23",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 128000,
    "max_input_tokens": 1050000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 5E-06,
    "input_cost_per_token_priority": 1E-05,
    "output_cost_per_token": 3E-05,
    "output_cost_per_token_priority": 6E-05,
    "cache_read_input_token_cost": 5E-07,
    "cache_read_input_token_cost_priority": 1E-06,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.5-pro",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 128000,
    "max_input_tokens": 1050000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 3E-05,
    "output_cost_per_token": 0.00018,
    "cache_read_input_token_cost": 3E-06,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-5.5-pro-2026-04-23",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 128000,
    "max_input_tokens": 1050000,
    "max_output_tokens": 128000,
    "input_cost_per_token": 3E-05,
    "output_cost_per_token": 0.00018,
    "cache_read_input_token_cost": 3E-06,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "gpt-audio",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05,
    "supports_prompt_caching": false
  },
  {
    "model": "gpt-audio-1.5",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05,
    "supports_prompt_caching": false
  },
  {
    "model": "gpt-audio-2025-08-28",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 2.5E-06,
    "output_cost_per_token": 1E-05,
    "supports_prompt_caching": false
  },
  {
    "model": "gpt-audio-mini",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 6E-07,
    "output_cost_per_token": 2.4E-06,
    "supports_prompt_caching": false
  },
  {
    "model": "gpt-audio-mini-2025-10-06",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 6E-07,
    "output_cost_per_token": 2.4E-06,
    "supports_prompt_caching": false
  },
  {
    "model": "gpt-audio-mini-2025-12-15",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 16384,
    "max_input_tokens": 128000,
    "max_output_tokens": 16384,
    "input_cost_per_token": 6E-07,
    "output_cost_per_token": 2.4E-06,
    "supports_prompt_caching": false
  },
  {
    "model": "gpt-image-1",
    "litellm_provider": "openai",
    "mode": "image_generation",
    "input_cost_per_token": 5E-06,
    "cache_read_input_token_cost": 1.25E-06,
    "output_cost_per_image_token": 4E-05
  },
  {
    "model": "gpt-image-1-mini",
    "litellm_provider": "openai",
    "mode": "image_generation",
    "input_cost_per_token": 2E-06,
    "cache_read_input_token_cost": 2E-07,
    "output_cost_per_image_token": 8E-06
  },
  {
    "model": "gpt-image-1.5",
    "litellm_provider": "openai",
    "mode": "image_generation",
    "input_cost_per_token": 5E-06,
    "output_cost_per_token": 1E-05,
    "cache_read_input_token_cost": 1.25E-06,
    "output_cost_per_image_token": 3.2E-05
  },
  {
    "model": "gpt-image-1.5-2025-12-16",
    "litellm_provider": "openai",
    "mode": "image_generation",
    "input_cost_per_token": 5E-06,
    "output_cost_per_token": 1E-05,
    "cache_read_input_token_cost": 1.25E-06,
    "output_cost_per_image_token": 3.2E-05
  },
  {
    "model": "gpt-image-2",
    "litellm_provider": "openai",
    "mode": "image_generation",
    "input_cost_per_token": 5E-06,
    "output_cost_per_token": 1E-05,
    "cache_read_input_token_cost": 1.25E-06,
    "output_cost_per_image_token": 3E-05
  },
  {
    "model": "gpt-image-2-2026-04-21",
    "litellm_provider": "openai",
    "mode": "image_generation",
    "input_cost_per_token": 5E-06,
    "output_cost_per_token": 1E-05,
    "cache_read_input_token_cost": 1.25E-06,
    "output_cost_per_image_token": 3E-05
  },
  {
    "model": "gpt-realtime",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 32000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 4E-06,
    "output_cost_per_token": 1.6E-05,
    "cache_read_input_token_cost": 4E-07
  },
  {
    "model": "gpt-realtime-1.5",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 32000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 4E-06,
    "output_cost_per_token": 1.6E-05,
    "cache_read_input_token_cost": 4E-07
  },
  {
    "model": "gpt-realtime-2025-08-28",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 32000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 4E-06,
    "output_cost_per_token": 1.6E-05,
    "cache_read_input_token_cost": 4E-07
  },
  {
    "model": "gpt-realtime-mini",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 6E-07,
    "output_cost_per_token": 2.4E-06
  },
  {
    "model": "gpt-realtime-mini-2025-10-06",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 6E-07,
    "output_cost_per_token": 2.4E-06,
    "cache_read_input_token_cost": 6E-08
  },
  {
    "model": "gpt-realtime-mini-2025-12-15",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 4096,
    "max_input_tokens": 128000,
    "max_output_tokens": 4096,
    "input_cost_per_token": 6E-07,
    "output_cost_per_token": 2.4E-06,
    "cache_read_input_token_cost": 6E-08
  },
  {
    "model": "o1-2024-12-17",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 1.5E-05,
    "output_cost_per_token": 6E-05,
    "cache_read_input_token_cost": 7.5E-06,
    "supports_prompt_caching": true
  },
  {
    "model": "o1-pro",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 0.00015,
    "output_cost_per_token": 0.0006,
    "supports_prompt_caching": true
  },
  {
    "model": "o1-pro-2025-03-19",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 0.00015,
    "output_cost_per_token": 0.0006,
    "supports_prompt_caching": true
  },
  {
    "model": "o3",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 2E-06,
    "input_cost_per_token_priority": 3.5E-06,
    "output_cost_per_token": 8E-06,
    "output_cost_per_token_priority": 1.4E-05,
    "cache_read_input_token_cost": 5E-07,
    "cache_read_input_token_cost_priority": 8.75E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "o3-2025-04-16",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 2E-06,
    "output_cost_per_token": 8E-06,
    "cache_read_input_token_cost": 5E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "o3-deep-research",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 1E-05,
    "output_cost_per_token": 4E-05,
    "cache_read_input_token_cost": 2.5E-06,
    "supports_prompt_caching": true
  },
  {
    "model": "o3-deep-research-2025-06-26",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 1E-05,
    "output_cost_per_token": 4E-05,
    "cache_read_input_token_cost": 2.5E-06,
    "supports_prompt_caching": true
  },
  {
    "model": "o3-mini",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 1.1E-06,
    "output_cost_per_token": 4.4E-06,
    "cache_read_input_token_cost": 5.5E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "o3-mini-2025-01-31",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 1.1E-06,
    "output_cost_per_token": 4.4E-06,
    "cache_read_input_token_cost": 5.5E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "o3-pro",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 2E-05,
    "output_cost_per_token": 8E-05,
    "supports_prompt_caching": true
  },
  {
    "model": "o3-pro-2025-06-10",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 2E-05,
    "output_cost_per_token": 8E-05,
    "supports_prompt_caching": true
  },
  {
    "model": "o4-mini",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 1.1E-06,
    "input_cost_per_token_priority": 2E-06,
    "output_cost_per_token": 4.4E-06,
    "output_cost_per_token_priority": 8E-06,
    "cache_read_input_token_cost": 2.75E-07,
    "cache_read_input_token_cost_priority": 5E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "o4-mini-2025-04-16",
    "litellm_provider": "openai",
    "mode": "chat",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 1.1E-06,
    "output_cost_per_token": 4.4E-06,
    "cache_read_input_token_cost": 2.75E-07,
    "supports_prompt_caching": true,
    "supports_service_tier": true
  },
  {
    "model": "o4-mini-deep-research",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 2E-06,
    "output_cost_per_token": 8E-06,
    "cache_read_input_token_cost": 5E-07,
    "supports_prompt_caching": true
  },
  {
    "model": "o4-mini-deep-research-2025-06-26",
    "litellm_provider": "openai",
    "mode": "responses",
    "max_tokens": 100000,
    "max_input_tokens": 200000,
    "max_output_tokens": 100000,
    "input_cost_per_token": 2E-06,
    "output_cost_per_token": 8E-06,
    "cache_read_input_token_cost": 5E-07,
    "supports_prompt_caching": true
  }
] as const
