// Curated from official OpenAI model, pricing, and deprecation docs on 2026-07-13.
// Values follow LiteLLM/model-price-repo field names: token prices are USD per token.
// Current OpenAI audio, image, and realtime model prices.

export const openAIMediaRealtimeModelPricingData = [
  {
    model: "gpt-audio",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 16384,
    context_window_tokens: 128000,
    max_output_tokens: 16384,
    input_modalities: ["text", "audio"],
    output_modalities: ["text", "audio"],
    supported_api_protocols: ["chat_completions"],
    supported_tools: ["function_calling"],
    input_cost_per_token: 0.0000025,
    output_cost_per_token: 0.00001,
    supports_prompt_caching: false
  },
  {
    model: "gpt-audio-1.5",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 16384,
    context_window_tokens: 128000,
    max_output_tokens: 16384,
    input_modalities: ["text", "audio"],
    output_modalities: ["text", "audio"],
    supported_api_protocols: ["chat_completions"],
    supported_tools: ["function_calling"],
    input_cost_per_token: 0.0000025,
    output_cost_per_token: 0.00001,
    supports_prompt_caching: false
  },
  {
    model: "gpt-audio-mini",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 16384,
    context_window_tokens: 128000,
    max_output_tokens: 16384,
    input_modalities: ["text", "audio"],
    output_modalities: ["text", "audio"],
    supported_api_protocols: ["chat_completions"],
    supported_tools: ["function_calling"],
    input_cost_per_token: 6e-7,
    output_cost_per_token: 0.0000024,
    supports_prompt_caching: true
  },
  {
    model: "gpt-image-2",
    litellm_provider: "openai",
    mode: "image_generation",
    input_modalities: ["text", "image"],
    output_modalities: ["image"],
    supported_api_protocols: ["images"],
    input_cost_per_token: 0.000005,
    output_cost_per_token: 0.00001,
    cache_read_input_token_cost: 0.00000125,
    input_cost_per_image_token: 0.000008,
    output_cost_per_image_token: 0.00003
  },
  {
    model: "gpt-image-2-2026-04-21",
    litellm_provider: "openai",
    mode: "image_generation",
    input_modalities: ["text", "image"],
    output_modalities: ["image"],
    supported_api_protocols: ["images"],
    input_cost_per_token: 0.000005,
    output_cost_per_token: 0.00001,
    cache_read_input_token_cost: 0.00000125,
    input_cost_per_image_token: 0.000008,
    output_cost_per_image_token: 0.00003
  },
  {
    model: "gpt-image-1.5",
    litellm_provider: "openai",
    mode: "image_generation",
    input_modalities: ["text", "image"],
    output_modalities: ["image", "text"],
    supported_api_protocols: ["images"],
    input_cost_per_token: 0.000005,
    output_cost_per_token: 0.00001,
    cache_read_input_token_cost: 0.00000125,
    input_cost_per_image_token: 0.000008,
    output_cost_per_image_token: 0.000032
  },
  {
    model: "gpt-image-1-mini",
    litellm_provider: "openai",
    mode: "image_generation",
    input_modalities: ["text", "image"],
    output_modalities: ["image"],
    supported_api_protocols: ["images"],
    input_cost_per_token: 0.000002,
    cache_read_input_token_cost: 2e-7,
    input_cost_per_image_token: 0.0000025,
    output_cost_per_image_token: 0.000008
  },
  {
    model: "gpt-image-1",
    litellm_provider: "openai",
    mode: "image_generation",
    input_modalities: ["text", "image"],
    output_modalities: ["image"],
    supported_api_protocols: ["images", "responses"],
    input_cost_per_token: 0.000005,
    output_cost_per_token: 0.00001,
    cache_read_input_token_cost: 0.00000125,
    input_cost_per_image_token: 0.00001,
    output_cost_per_image_token: 0.00004,
    shutdown_date: "2026-10-23"
  },
  {
    model: "gpt-realtime",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 4096,
    context_window_tokens: 32000,
    max_output_tokens: 4096,
    input_modalities: ["text", "audio", "image"],
    output_modalities: ["text", "audio"],
    supported_api_protocols: ["realtime"],
    supported_tools: ["function_calling"],
    input_cost_per_token: 0.000004,
    output_cost_per_token: 0.000016,
    cache_read_input_token_cost: 4e-7,
    supports_prompt_caching: true
  },
  {
    model: "gpt-realtime-1.5",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 4096,
    context_window_tokens: 32000,
    max_output_tokens: 4096,
    input_modalities: ["text", "audio", "image"],
    output_modalities: ["text", "audio"],
    supported_api_protocols: ["realtime"],
    supported_tools: ["function_calling"],
    input_cost_per_token: 0.000004,
    output_cost_per_token: 0.000016,
    cache_read_input_token_cost: 4e-7,
    supports_prompt_caching: true
  },
  {
    model: "gpt-realtime-mini",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 4096,
    context_window_tokens: 32000,
    max_output_tokens: 4096,
    input_modalities: ["text", "image", "audio"],
    output_modalities: ["text", "audio"],
    supported_api_protocols: ["realtime"],
    supported_tools: ["function_calling"],
    input_cost_per_token: 6e-7,
    output_cost_per_token: 0.0000024,
    cache_read_input_token_cost: 6e-8,
    supports_prompt_caching: true
  },
  {
    model: "gpt-realtime-mini-2025-12-15",
    litellm_provider: "openai",
    mode: "chat",
    max_tokens: 4096,
    context_window_tokens: 32000,
    max_output_tokens: 4096,
    input_modalities: ["text", "image", "audio"],
    output_modalities: ["text", "audio"],
    supported_api_protocols: ["realtime"],
    supported_tools: ["function_calling"],
    input_cost_per_token: 6e-7,
    output_cost_per_token: 0.0000024,
    cache_read_input_token_cost: 6e-8,
    supports_prompt_caching: true
  }
] as const
