ARG NODE_BUILDER_IMAGE
FROM ${NODE_BUILDER_IMAGE}

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG VITE_JUHE_AI_BUILD_ID
ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTPS_PROXY}
ENV NO_PROXY=${NO_PROXY}
ENV VITE_JUHE_AI_BUILD_ID=${VITE_JUHE_AI_BUILD_ID}

WORKDIR /source
COPY . .
RUN corepack enable \
  && corepack prepare pnpm@10.32.1 --activate \
  && pnpm install --frozen-lockfile \
  && pnpm build
