import type { BackgroundJobRegistryEntry } from './background-job-registry.js'

const scheduled = <const T extends BackgroundJobRegistryEntry>(entry: T & { category: 'scheduled' }) => entry
const entry = <const T extends BackgroundJobRegistryEntry>(value: T) => value

export const backgroundScheduledJobs = [
  scheduled({
    jobName: 'usage-record-first-page-prewarm',
    category: 'scheduled',
    kind: 'maintenance',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: false,
    writes: ['cache:usage_record_first_page'],
    notes: '仅 ingest/usage worker 的 replica 0 注册，避免 performance 多副本重复候选查询和首屏预热'
  }),
  scheduled({
    jobName: 'system-metrics-sample',
    category: 'scheduled',
    kind: 'sample',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: true,
    singleOwner: true,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: ['stats:system_metrics_samples', 'stats:process_event_loop_samples'],
    notes: '系统采样写入 stats 库，必须经 stats-worker 串行提交；其他进程事件循环样本通过 IPC 拉取'
  }),
  scheduled({
    jobName: 'system-metrics-trend-windows-refresh',
    category: 'scheduled',
    kind: 'snapshot',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['stats:system_metrics_trend_windows']
  }),
  scheduled({
    jobName: 'usage-stats-aggregation',
    category: 'scheduled',
    kind: 'stats',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['stats:usage_stats_*', 'stats:usage_model_*', 'stats:usage_error_*', 'stats:usage_latency_*']
  }),
  scheduled({
    jobName: 'usage-hot-window-refresh',
    category: 'scheduled',
    kind: 'snapshot',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: true,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['stats:usage_overview_summary_windows', 'stats:usage_overview_trend_windows', 'stats:usage_scope_range_windows'],
    notes: 'usage 增量聚合后由独立 scheduler job 合并刷新热窗口，不阻塞在线聚合主链路'
  }),
  scheduled({
    jobName: 'model-trust-observation-aggregation',
    category: 'scheduled',
    kind: 'stats',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['stats:model_token_integrity_windows', 'stats:model_token_integrity_rounds', 'stats:model_token_intercept_baseline_versions', 'stats:model_trust_window_sources', 'stats:model_identity_*', 'stats:model_paired_similarity_windows', 'stats:model_account_trust_results', 'stats:stats_job_state'],
    notes: '按 dataset observation 游标增量构建模型可信窗口和账号最新结果，API 只读结果表'
  }),
  scheduled({
    jobName: 'client-ip-stats-aggregation',
    category: 'scheduled',
    kind: 'stats',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: true,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['stats:client_ip_stats_daily', 'stats:client_ip_account_stats_daily', 'stats:client_ip_usage_range_windows', 'stats:client_ip_account_usage_range_windows'],
    notes: 'PostgreSQL 由单一 fencing lease 串行推进全局游标并刷新两类范围窗口；dirty generation CAS 保留并发新标记。'
  }),
  scheduled({
    jobName: 'group-account-stats-refresh',
    category: 'scheduled',
    kind: 'stats',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:group_account_stats_dirty', 'stats:group_account_stats']
  }),
  scheduled({
    jobName: 'usage-rank-snapshots-refresh',
    category: 'scheduled',
    kind: 'snapshot',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['stats:usage_rank_snapshots']
  }),
  scheduled({
    jobName: 'ai-performance-summary-windows-refresh',
    category: 'scheduled',
    kind: 'snapshot',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['stats:ai_performance_summary_windows', 'stats:ai_performance_summary_dirty_system_accounts'],
    notes: 'PostgreSQL 在线模式按 dirty system account 小批增量刷新；SQLite 保留在组合快照任务内。'
  }),
  scheduled({
    jobName: 'usage-overview-windows-refresh',
    category: 'scheduled',
    kind: 'snapshot',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['stats:usage_overview_summary_windows', 'stats:usage_overview_trend_windows']
  }),
  scheduled({
    jobName: 'usage-scope-range-windows-refresh',
    category: 'scheduled',
    kind: 'snapshot',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: true,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['stats:usage_scope_range_windows']
  }),
  scheduled({
    jobName: 'authorization-usage-range-windows-refresh',
    category: 'scheduled',
    kind: 'snapshot',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['stats:authorization_team_usage_range_windows', 'stats:authorization_user_usage_range_windows']
  }),
  scheduled({
    jobName: 'usage-stats-consistency-check',
    category: 'scheduled',
    kind: 'maintenance',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: []
  }),
  scheduled({
    jobName: 'background-task-run-reconcile',
    category: 'scheduled',
    kind: 'maintenance',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: false,
    writes: ['stats:background_task_runs', 'stats:background_job_leases'],
    notes: '启动后及低频周期回收无有效租约的临时维护任务陈旧状态；近期心跳和有效租约均阻止回收'
  }),
  scheduled({
    jobName: 'api-key-record-cleanup-retry',
    category: 'scheduled',
    kind: 'maintenance',
    lifecycle: 'hybrid',
    defaultRole: 'ingest-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:api_key_record_cleanup_targets', 'stats:usage_record_cleanup_deductions', 'usage-shards:usage_records']
  }),
  scheduled({
    jobName: 'account-record-cleanup-retry',
    category: 'scheduled',
    kind: 'maintenance',
    lifecycle: 'hybrid',
    defaultRole: 'ingest-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:account_record_cleanup_targets', 'stats:usage_record_cleanup_deductions', 'usage-shards:usage_records']
  }),
  scheduled({
    jobName: 'api-key-availability-schedule-status-sync',
    category: 'scheduled',
    kind: 'maintenance',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:api_keys']
  }),
  scheduled({
    jobName: 'account-availability-schedule-status-sync',
    category: 'scheduled',
    kind: 'maintenance',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:accounts']
  }),
  scheduled({
    jobName: 'resource-authorization-expiry-sweep',
    category: 'scheduled',
    kind: 'maintenance',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:resource_authorizations']
  }),
  scheduled({
    jobName: 'table-storage-monitor',
    category: 'scheduled',
    kind: 'maintenance',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['stats:database_storage_snapshots', 'stats:table_storage_snapshots']
  }),
  scheduled({
    jobName: 'proxy-latency-refresh',
    category: 'scheduled',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: true,
    shardable: true,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['business:proxies']
  }),
  scheduled({
    jobName: 'account-quality-refresh',
    category: 'scheduled',
    kind: 'stats',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['stats:account_quality_*']
  }),
  scheduled({
    jobName: 'account-balance-refresh',
    category: 'scheduled',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: false,
    shardable: true,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:accounts', 'stats:account_usage_snapshots'],
    notes: '按账户租约刷新物理单 API Key 上游余额，单轮有界且不影响账户健康状态'
  }),
  scheduled({
    jobName: 'openai-oauth-access-token-refresh',
    category: 'scheduled',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:accounts']
  }),
  scheduled({
    jobName: 'account-health-check',
    category: 'scheduled',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:accounts', 'usage-shards:usage_records', 'dataset:audit_logs']
  }),
  scheduled({
    jobName: 'model-quality-scheduled-check',
    category: 'scheduled',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:model_quality_schedules', 'business:accounts', 'business:account_quality_enforcements', 'dataset:model_check_runs', 'stats:account_quality_health_hourly']
  }),
  scheduled({
    jobName: 'model-quality-recovery',
    category: 'scheduled',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:accounts', 'business:account_quality_enforcements', 'dataset:model_check_runs', 'stats:account_quality_health_hourly']
  }),
  scheduled({
    jobName: 'model-quality-health-sync-retry',
    category: 'scheduled',
    kind: 'stats',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['dataset:model_check_runs', 'stats:account_quality_health_hourly'],
    notes: '有界重放质量判定中 healthSyncResult=failed 的 run；统计小时表和 run 决策更新均幂等'
  }),
  scheduled({
    jobName: 'cooldown-account-retest',
    category: 'scheduled',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:accounts', 'usage-shards:usage_records', 'dataset:audit_logs']
  }),
  scheduled({
    jobName: 'account-api-key-cooldown-retest',
    category: 'scheduled',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:account_api_key_runtime_states', 'usage-shards:usage_records', 'dataset:audit_logs']
  }),
  scheduled({
    jobName: 'normal-route-speed-first-recovery-probe',
    category: 'scheduled',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['runtime-state:gateway-normal-route-latency-degradation', 'usage-shards:usage_records', 'dataset:audit_logs']
  }),
  scheduled({
    jobName: 'account-circuit-control-plane-maintenance',
    category: 'scheduled',
    kind: 'maintenance',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:account_circuit_outbox', 'runtime:account_circuit'],
    notes: '投影 dispatch revision / incident outbox，并有界修复 Redis 状态与 due 索引孤儿'
  }),
  scheduled({
    jobName: 'account-circuit-recovery',
    category: 'scheduled',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: true,
    shardable: true,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['runtime:account_circuit']
  }),
  scheduled({
    jobName: 'runtime-log-index-maintenance',
    category: 'scheduled',
    kind: 'log',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:runtime_logs']
  }),
  scheduled({
    jobName: 'audit-hot-retention-cleanup',
    category: 'scheduled',
    kind: 'maintenance',
    lifecycle: 'hybrid',
    defaultRole: 'ingest-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:audit_logs', 'dataset:audit_payload_refs', 'dataset:audit_payload_blobs']
  }),
  scheduled({
    jobName: 'data-retention-cleanup',
    category: 'scheduled',
    kind: 'maintenance',
    lifecycle: 'hybrid',
    defaultRole: 'ingest-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:*', 'stats:*', 'usage-shards:usage_records']
  }),
  scheduled({
    jobName: 'chat-retention-cleanup',
    category: 'scheduled',
    kind: 'maintenance',
    lifecycle: 'hybrid',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['chat:*']
  }),
  scheduled({
    jobName: 'expired-deleted-account-cleanup',
    category: 'scheduled',
    kind: 'maintenance',
    lifecycle: 'hybrid',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['business:accounts', 'business:resource_authorizations']
  })
] as const

export const backgroundWorkerRegistry = [
  ...backgroundScheduledJobs,
  entry({
    jobName: 'background_worker_usage_records',
    category: 'ipc-queue',
    kind: 'ingest',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: ['usage-shards:usage_records']
  }),
  entry({
    jobName: 'background_worker_audit_logs',
    category: 'ipc-queue',
    kind: 'log',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: false,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:audit_logs', 'dataset:audit_payload_refs', 'dataset:audit_payload_blobs']
  }),
  entry({
    jobName: 'background_worker_operation_logs',
    category: 'ipc-queue',
    kind: 'log',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: false,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:operation_logs']
  }),
  entry({
    jobName: 'background_worker_public_api_logs',
    category: 'ipc-queue',
    kind: 'log',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: false,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:public_api_logs']
  }),
  entry({
    jobName: 'background_worker_record_maintenance',
    category: 'ipc-queue',
    kind: 'maintenance',
    lifecycle: 'hybrid',
    defaultRole: 'ingest-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:*', 'stats:*', 'usage-shards:usage_records'],
    notes: '队列在 ingest-worker 内串行执行；stats 写入继续投递 stats-writer'
  }),
  entry({
    jobName: 'background_worker_account_test_tasks',
    category: 'ipc-queue',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: false,
    shardable: true,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: ['business:account_test_tasks']
  }),
  entry({
    jobName: 'background_worker_account_test_cancel',
    category: 'control-ipc',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: false,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: ['business:account_test_tasks']
  }),
  entry({
    jobName: 'background_worker_account_health_check_trigger',
    category: 'control-ipc',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: false,
    shardable: true,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: ['business:accounts']
  }),
  entry({
    jobName: 'background_worker_status_request',
    category: 'control-ipc',
    kind: 'control',
    lifecycle: 'persistent',
    defaultRole: 'worker-control',
    hotspot: false,
    singleOwner: false,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: false,
    writes: []
  }),
  entry({
    jobName: 'background_worker_ready',
    category: 'control-ipc',
    kind: 'control',
    lifecycle: 'persistent',
    defaultRole: 'worker-control',
    hotspot: false,
    singleOwner: false,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: false,
    writes: []
  }),
  entry({
    jobName: 'background_worker_status_response',
    category: 'control-ipc',
    kind: 'control',
    lifecycle: 'persistent',
    defaultRole: 'worker-control',
    hotspot: false,
    singleOwner: false,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: false,
    writes: []
  }),
  entry({
    jobName: 'background_worker_ingest_status_request',
    category: 'control-ipc',
    kind: 'control',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: true,
    singleOwner: false,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: []
  }),
  entry({
    jobName: 'background_worker_ingest_status_response',
    category: 'control-ipc',
    kind: 'control',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: true,
    singleOwner: false,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: []
  }),
  entry({
    jobName: 'background_worker_db_service_request',
    category: 'control-ipc',
    kind: 'maintenance',
    lifecycle: 'persistent',
    defaultRole: 'worker-control',
    hotspot: false,
    singleOwner: false,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: ['business:typed_operation']
  }),
  entry({
    jobName: 'background_worker_db_service_response',
    category: 'control-ipc',
    kind: 'maintenance',
    lifecycle: 'persistent',
    defaultRole: 'worker-control',
    hotspot: false,
    singleOwner: false,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: []
  }),
  entry({
    jobName: 'background_worker_dataset_write_request',
    category: 'control-ipc',
    kind: 'ingest',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: true,
    singleOwner: true,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: ['dataset:typed_operation']
  }),
  entry({
    jobName: 'background_worker_dataset_write_response',
    category: 'control-ipc',
    kind: 'ingest',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: true,
    singleOwner: true,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: []
  }),
  entry({
    jobName: 'background_worker_stats_write_request',
    category: 'control-ipc',
    kind: 'stats',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: true,
    singleOwner: true,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: ['stats:typed_operation']
  }),
  entry({
    jobName: 'background_worker_stats_write_response',
    category: 'control-ipc',
    kind: 'stats',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: true,
    singleOwner: true,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: []
  }),
  entry({
    jobName: 'background_worker_process_event_loop_request',
    category: 'control-ipc',
    kind: 'sample',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: true,
    singleOwner: false,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: []
  }),
  entry({
    jobName: 'background_worker_process_event_loop_response',
    category: 'control-ipc',
    kind: 'sample',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: true,
    singleOwner: false,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: []
  }),
  entry({
    jobName: 'server_account_runtime_clear',
    category: 'control-ipc',
    kind: 'maintenance',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: false,
    singleOwner: false,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: ['server:gateway_runtime_cache']
  }),
  entry({
    jobName: 'gateway_runtime_cache_invalidate',
    category: 'control-ipc',
    kind: 'maintenance',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: false,
    singleOwner: false,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: ['server:gateway_runtime_cache']
  }),
  entry({
    jobName: 'gateway_quota_snapshot_update',
    category: 'control-ipc',
    kind: 'stats',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: false,
    singleOwner: false,
    shardable: false,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: ['server:gateway_quota_snapshot_cache']
  }),
  entry({
    jobName: 'runtime-log-file-import',
    category: 'entrypoint',
    kind: 'log',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: true,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:runtime_logs', 'dataset:runtime_log_file_cursors']
  }),
  entry({
    jobName: 'manual-account-test-queue',
    category: 'local-queue',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: false,
    shardable: true,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: ['business:account_test_tasks']
  }),
  entry({
    jobName: 'cooldown-account-retest-queue',
    category: 'local-queue',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:accounts', 'usage-shards:usage_records', 'dataset:audit_logs']
  }),
  entry({
    jobName: 'account-api-key-cooldown-retest-queue',
    category: 'local-queue',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:account_api_key_runtime_states', 'usage-shards:usage_records', 'dataset:audit_logs']
  }),
  entry({
    jobName: 'account-quality-failure-precheck-queue',
    category: 'local-queue',
    kind: 'probe',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: false,
    shardable: true,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:accounts']
  }),
  entry({
    jobName: 'public-api-log-queue',
    category: 'local-queue',
    kind: 'log',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: false,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:public_api_logs']
  }),
  entry({
    jobName: 'client-ip-policy-hit-buffer',
    category: 'local-queue',
    kind: 'stats',
    lifecycle: 'persistent',
    defaultRole: 'stats-worker',
    hotspot: true,
    singleOwner: false,
    shardable: true,
    leaseRequired: false,
    blocksUserVisibleFreshness: false,
    writes: ['stats:client_ip_policy_hits']
  }),
  entry({
    jobName: 'gateway-account-side-effects',
    category: 'local-queue',
    kind: 'maintenance',
    lifecycle: 'persistent',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: false,
    shardable: true,
    leaseRequired: true,
    blocksUserVisibleFreshness: true,
    writes: ['business:accounts']
  }),
  entry({
    jobName: 'record-maintenance:api_key_related_cleanup',
    category: 'maintenance-task',
    kind: 'maintenance',
    lifecycle: 'hybrid',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:api_key_record_cleanup_targets', 'stats:usage_record_cleanup_deductions', 'usage-shards:usage_records']
  }),
  entry({
    jobName: 'record-maintenance:account_related_cleanup',
    category: 'maintenance-task',
    kind: 'maintenance',
    lifecycle: 'hybrid',
    defaultRole: 'ops-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:account_record_cleanup_targets', 'stats:usage_record_cleanup_deductions', 'usage-shards:usage_records']
  }),
  entry({
    jobName: 'record-maintenance:usage_records_cleanup',
    category: 'maintenance-task',
    kind: 'maintenance',
    lifecycle: 'hybrid',
    defaultRole: 'ingest-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['usage-shards:usage_records']
  }),
  entry({
    jobName: 'record-maintenance:non_business_data_cleanup',
    category: 'maintenance-task',
    kind: 'maintenance',
    lifecycle: 'hybrid',
    defaultRole: 'ingest-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:*', 'stats:*', 'usage-shards:usage_records', 'audit-payload-files:*']
  }),
  entry({
    jobName: 'record-maintenance:audit_retained_data_cleanup',
    category: 'maintenance-task',
    kind: 'maintenance',
    lifecycle: 'hybrid',
    defaultRole: 'ingest-worker',
    hotspot: false,
    singleOwner: true,
    shardable: false,
    leaseRequired: true,
    blocksUserVisibleFreshness: false,
    writes: ['dataset:audit_logs', 'dataset:audit_log_attempts', 'dataset:audit_payload_refs', 'dataset:audit_error_groups', 'dataset:audit_payload_blobs', 'audit-payload-files:*']
  }),
  entry({
    jobName: 'record-maintenance:account_usage_snapshot_upsert',
    category: 'maintenance-task',
    kind: 'maintenance',
    lifecycle: 'persistent',
    defaultRole: 'ingest-worker',
    hotspot: false,
    singleOwner: false,
    shardable: true,
    leaseRequired: false,
    blocksUserVisibleFreshness: true,
    writes: ['stats:account_usage_snapshots'],
    notes: '同账号同来源任务可合并为最新快照；实际 stats 写入投递 stats-writer'
  })
] as const
