import {
  ANTHROPIC_ANTHROPIC_V1_PROFILE_ID,
  ANTHROPIC_PROVIDER_CODE,
  DEEPSEEK_ANTHROPIC_V1_PROFILE_ID,
  DEEPSEEK_OPENAI_V1_PROFILE_ID,
  DEEPSEEK_PROVIDER_CODE,
  GLM_CODING_ANTHROPIC_V1_PROFILE_ID,
  GLM_CODING_OPENAI_V1_PROFILE_ID,
  GLM_GENERAL_OPENAI_V1_PROFILE_ID,
  GLM_PROVIDER_CODE,
  GPT_OPENAI_V1_PROFILE_ID,
  GPT_VENDOR_CODE,
  HYBRID_OPENAI_CHAT_V1_PROFILE_ID,
  HYBRID_PROVIDER_CODE
} from '@/shared/providerProtocol'

export const importTemplate = JSON.stringify({
  type: 'juhe-ai-account-import',
  version: 1,
  proxies: [
    {
      ref: 'proxy-hk-1',
      name: '香港代理 1',
      type: 'http',
      host: '127.0.0.1',
      port: 7890,
      username: '',
      password: '',
      enabled: true
    }
  ],
  accounts: [
    {
      ref: 'gpt-key-001',
      name: 'GPT API Key 账号 1',
      providerCode: GPT_VENDOR_CODE,
      providerProtocolProfileId: GPT_OPENAI_V1_PROFILE_ID,
      type: 'api_key',
      status: 'active',
      groupName: '默认 GPT 分组',
      concurrencyLimit: 3,
      priority: 50,
      proxyRef: 'proxy-hk-1',
      credentials: {
        api_key: 'sk-xxx',
        base_url: 'https://api.openai.com/v1',
        supported_endpoint_modes: ['chat_json', 'chat_sse', 'responses_json', 'responses_sse']
      },
      notes: 'GPT API Key 账号'
    },
    {
      ref: 'gpt-oauth-001',
      name: 'GPT OAuth 账号 1',
      providerCode: GPT_VENDOR_CODE,
      providerProtocolProfileId: GPT_OPENAI_V1_PROFILE_ID,
      type: 'oauth',
      status: 'active',
      groupName: '默认 GPT 分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        refresh_token: 'refresh-token-xxx',
        access_token: 'access-token-xxx',
        id_token: 'id-token-xxx',
        base_url: 'https://api.openai.com/v1',
        supported_endpoint_modes: ['responses_json', 'responses_sse'],
        account_id: 'acct_xxx',
        email: 'user@example.com'
      },
      notes: 'OAuth 账号'
    },
    {
      ref: 'deepseek-key-001',
      name: 'DeepSeek API Key 账号 1',
      providerCode: DEEPSEEK_PROVIDER_CODE,
      providerProtocolProfileId: DEEPSEEK_OPENAI_V1_PROFILE_ID,
      type: 'api_key',
      status: 'active',
      groupName: '默认 DeepSeek 分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        api_key: 'sk-deepseek-xxx',
        base_url: 'https://api.deepseek.com',
        supported_endpoint_modes: ['chat_json', 'chat_sse']
      },
      notes: 'DeepSeek API Key 账号'
    },
    {
      ref: 'deepseek-claude-code-001',
      name: 'DeepSeek Claude Code 账号 1',
      providerCode: DEEPSEEK_PROVIDER_CODE,
      providerProtocolProfileId: DEEPSEEK_ANTHROPIC_V1_PROFILE_ID,
      type: 'api_key',
      status: 'active',
      groupName: '默认 DeepSeek 分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        api_key: 'sk-deepseek-claude-code-xxx',
        base_url: 'https://api.deepseek.com/anthropic',
        supported_endpoint_modes: ['messages_json', 'messages_sse']
      },
      notes: 'DeepSeek Anthropic v1 / Claude Code 账号'
    },
    {
      ref: 'glm-general-001',
      name: '智谱 GLM 通用账号 1',
      providerCode: GLM_PROVIDER_CODE,
      providerProtocolProfileId: GLM_GENERAL_OPENAI_V1_PROFILE_ID,
      type: 'api_key',
      status: 'active',
      groupName: '默认 GLM 分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        api_key: 'sk-glm-general-xxx',
        base_url: 'https://open.bigmodel.cn/api/paas/v4/',
        supported_endpoint_modes: ['chat_json', 'chat_sse']
      },
      notes: '智谱通用 GLM API Key 账号'
    },
    {
      ref: 'glm-coding-001',
      name: '智谱 GLM Coding 账号 1',
      providerCode: GLM_PROVIDER_CODE,
      providerProtocolProfileId: GLM_CODING_OPENAI_V1_PROFILE_ID,
      type: 'api_key',
      status: 'active',
      groupName: '默认 GLM 分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        api_key: 'sk-glm-coding-xxx',
        base_url: 'https://open.bigmodel.cn/api/coding/paas/v4',
        supported_endpoint_modes: ['chat_json', 'chat_sse']
      },
      notes: 'GLM Coding Plan Key 账号'
    },
    {
      ref: 'glm-coding-anthropic-001',
      name: '智谱 GLM Coding Anthropic 账号 1',
      providerCode: GLM_PROVIDER_CODE,
      providerProtocolProfileId: GLM_CODING_ANTHROPIC_V1_PROFILE_ID,
      type: 'api_key',
      status: 'active',
      groupName: '默认 GLM 分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        api_key: 'sk-glm-coding-anthropic-xxx',
        base_url: 'https://open.bigmodel.cn/api/anthropic',
        supported_endpoint_modes: ['messages_json', 'messages_sse']
      },
      notes: 'GLM Coding Anthropic v1 账号'
    },
    {
      ref: 'anthropic-key-001',
      name: 'Anthropic API Key 账号 1',
      providerCode: ANTHROPIC_PROVIDER_CODE,
      providerProtocolProfileId: ANTHROPIC_ANTHROPIC_V1_PROFILE_ID,
      type: 'api_key',
      status: 'active',
      groupName: '默认 Anthropic 分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        api_key: 'sk-ant-xxx',
        base_url: 'https://api.anthropic.com/v1',
        supported_endpoint_modes: ['messages_json', 'messages_sse', 'message_token_counting']
      },
      notes: 'Anthropic API Key 账号'
    },
    {
      ref: 'hybrid-glm-chat-001',
      name: '混合供应商 GLM Chat 上游账号 1',
      providerCode: HYBRID_PROVIDER_CODE,
      providerProtocolProfileId: HYBRID_OPENAI_CHAT_V1_PROFILE_ID,
      type: 'api_key',
      status: 'active',
      groupName: '默认混合供应商分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        api_key: 'sk-glm-coding-xxx',
        base_url: 'https://open.bigmodel.cn/api/coding/paas/v4',
        supported_endpoint_modes: ['chat_json', 'chat_sse']
      },
      modelMappings: [
        {
          sourceModel: 'claude-sonnet-4',
          sourceEndpointFamily: 'messages',
          upstreamModel: 'glm-5.2',
          upstreamEndpointFamily: 'chat_completions',
          enabled: true
        }
      ],
      notes: '真实上游是 GLM OpenAI Chat；下游 Anthropic Messages 模型通过混合供应商账户映射到 glm-5.2'
    }
  ]
}, null, 2)

export const aiConversionPrompt = [
  '请根据我附上的《juhe-ai AI 账户导入协议 v1》Markdown，把下面账号数据转换为 juhe-ai-account-import v1 JSON。',
  '',
  '要求：',
  '1. 协议文件优先于你的默认认知；字段名、必填项、枚举值和示例都按协议文件执行。',
  '2. 只输出合法 JSON，不要输出解释、Markdown 代码块或注释。',
  '3. 顶层 type 固定为 juhe-ai-account-import，version 固定为数字 1。',
  '4. 每个账户必须显式填写 name、providerCode、providerProtocolProfileId、type、status、credentials，以及 groupName 或 groupId。',
  '5. API Key 账号使用 type: api_key；GPT OAuth 使用 type: oauth；Gemini Google OAuth 使用 type: google_oauth。',
  '6. providerProtocolProfileId 是协议档案唯一入口；不要根据 base_url、供应商默认值或旧字段猜测档案。',
  '7. 普通 OpenAI v1 账户可以用 modelMappings 显式填写 Responses -> Chat Completions；其他跨协议映射只能写入 providerCode 为 hybrid 的混合供应商账户。',
  '8. 不要编造来源数据里不存在的 token、API Key、邮箱、账号 ID、代理密码或模型列表。',
  '9. 如果有代理，请放到 proxies 数组，并用账号的 proxyRef 引用代理 ref。',
  '10. 不确定的信息放到 notes；无法判断是否可立即调度时 status 填 pending_test 或 disabled。'
].join('\n')

export const accountImportProtocolMarkdown = [
  '# juhe-ai AI 账户导入协议 v1',
  '',
  '## 用途',
  '',
  '把其他系统、表格、文本或人工整理的 GPT / OpenAI v1 / DeepSeek / GLM / Anthropic v1 / Gemini / 混合供应商账户数据转换为 juhe-ai 可导入的 JSON。导入接口只接受 JSON，不接受 Markdown、注释、JSONL、CSV 或外部系统原始格式。',
  '',
  '## 转换约束',
  '',
  '- 输出必须是一个 JSON 对象，不能包在 Markdown 代码块里，不能附带解释文字。',
  '- 字段名严格使用本协议定义，不要把 `providerCode` 改成 `provider_code`，也不要把 `api_key` 改成 `apiKey`。',
  '- 顶层 `type` 固定为 `juhe-ai-account-import`，`version` 固定为数字 `1`。',
  '- `accounts` 至少 1 条；每个账户必须显式填写 `name`、`providerCode`、`providerProtocolProfileId`、`type`、`status`、`credentials`，以及 `groupId` 或 `groupName`。',
  '- 当前默认使用 `providerCode: "gpt"`；确需通用 OpenAI-compatible 供应商时才填 `openai`；xAI / Grok 直连填 `xai`；DeepSeek 直连填 `deepseek`；智谱 GLM 直连填 `glm`；官方 Anthropic Claude 直连填 `anthropic`；Google Gemini 直连填 `gemini`；跨协议真实上游账户填 `hybrid`。系统会按供应商和协议档案匹配内部配置；所有账户都必须显式填写 `providerProtocolProfileId`，真实上游协议由账户模型映射的目标协议和上游接口能力表达。',
  '- `providerProtocolProfileId` 是协议档案唯一入口；不要根据 `base_url`、供应商默认值或旧字段猜测档案。',
  '- 账号导入不填写 `clientCompatibility`。下游客户端画像由网关运行时自动识别；OpenAI v1 普通账户可用 `modelMappings` 显式声明 Responses 到 Chat Completions，Anthropic Messages 或 Gemini native 等其他跨协议转换必须通过混合供应商账户配置。',
  '- 不确定是否可立即调度时，`status` 填 `pending_test` 或 `disabled`，不要默认填 `active`。',
  '- 不要编造缺失的 token、API Key、邮箱、账号 ID、代理密码或模型列表；不确定的信息写入 `notes`。',
  '- 外部来源字段如果没有本协议对应字段，不要塞进 `credentials`，可以整理到 `notes`。',
  '',
  '## 顶层结构',
  '',
  '| 字段 | 必填 | 类型 | 说明 |',
  '| --- | --- | --- | --- |',
  '| `type` | 是 | string | 固定为 `juhe-ai-account-import`。 |',
  '| `version` | 是 | number | 当前固定为 `1`。 |',
  '| `accounts` | 是 | array | 账户数组，至少 1 条，单次最多 50 条。 |',
  '| `proxies` | 否 | array | 代理数组，单次最多 20 条；账户通过 `proxyRef` 引用 `proxies[].ref`。 |',
  '',
  '结构骨架：',
  '',
  '```json',
  '{',
  '  "type": "juhe-ai-account-import",',
  '  "version": 1,',
  '  "accounts": []',
  '}',
  '```',
  '',
  '## accounts 字段',
  '',
  '| 字段 | 必填 | 类型 | 说明 |',
  '| --- | --- | --- | --- |',
  '| `ref` | 否 | string | 导入预览和错误定位用，不写入数据库。 |',
  '| `name` | 是 | string | 账户名称，同一系统账户下不能重复。 |',
  '| `providerCode` | 是 | string | 默认填 `gpt`。当前支持 `gpt`、`openai`、`xai`、`deepseek`、`glm`、`anthropic`、`gemini` 和 `hybrid`；`xai` 表示官方 xAI / Grok 直连供应商，其余代码对应同名供应商或混合供应商真实上游账户。 |',
  '| `type` | 是 | string | `api_key`、`oauth` 或 `google_oauth`；具体可用值受协议档案约束。 |',
  '| `providerProtocolProfileId` | 是 | string | 显式内部协议档案；常用值包括 `profile_openai_openai_v1`、`profile_gpt_openai_v1`、`profile_xai_openai_v1`、`profile_anthropic_anthropic_v1`、`profile_glm_general_openai_v1`、`profile_glm_coding_openai_v1`、`profile_glm_coding_anthropic_v1`、`profile_deepseek_openai_v1`、`profile_deepseek_anthropic_v1`、`profile_gemini_native_v1beta`、`profile_gemini_openai_chat_v1beta` 和混合供应商档案。 |',
  '| `status` | 是 | string | `active`、`pending_test` 或 `disabled`。`active` 导入创建时会转为 `pending_test`；不确定时用 `pending_test` 或 `disabled`。 |',
  '| `groupId` | 二选一 | string | 绑定已有分组 ID；同时存在 `groupName` 时优先使用 `groupId`。 |',
  '| `groupName` | 二选一 | string | 绑定或自动创建同名分组。 |',
  '| `proxyRef` | 否 | string | 引用 `proxies[].ref` 或已有代理 ID。 |',
  '| `proxyProfileId` | 否 | string | 直接引用已有代理 ID；不能和 `proxyRef` 同时填写。 |',
  '| `concurrencyLimit` | 否 | number | 正整数，并发上限。 |',
  '| `priority` | 否 | number | 非负整数，调度优先级。 |',
  '| `superPriorityEnabled` | 否 | boolean | 超级优先开关。 |',
  '| `fallbackEnabled` | 否 | boolean | 降级备用开关。 |',
  '| `supportedModels` | 否 | string[] | 支持模型列表；省略时按供应商默认支持模型回填，最终必须非空。 |',
  '| `modelMappings` | 否 | object[] | 账号模型映射列表；普通供应商账户只允许当前账号供应商模型目录内的同协议模型名改写，以及 OpenAI v1 的 Responses 到 Chat Completions 显式 bridge；混合供应商账户允许用该字段声明其他下游模型 / 协议入口到真实上游模型 / 协议的跨协议映射。条目包含 `sourceModel`、`sourceEndpointFamily`、`upstreamModel`、`upstreamEndpointFamily`、`enabled`。 |',
  '| `tags` | 否 | string[] | 账户标签名称列表；不存在的标签按当前导入权限创建或报错。 |',
  '| `accountExpiresAt` | 否 | string | ISO 时间字符串。 |',
  '| `availabilitySchedule` | 否 | object | 时间计划；不确定时省略。 |',
  '| `credentials` | 是 | object | 按账户类型填写凭据。 |',
  '| `notes` | 否 | string | 备注；无法确定的信息写这里。 |',
  '',
  '字段规则：',
  '',
  '- `groupId` 和 `groupName` 同时存在时优先使用 `groupId`。',
  '- `proxyRef` 和 `proxyProfileId` 不能同时填写。',
  '- `concurrencyLimit` 必须是正整数；`priority` 必须是非负整数。',
  '- 导入创建时 `status: "active"` 会转为 `pending_test`，测试通过后才参与调度；明确不希望调度时填 `disabled`。',
  '- `supportedModels` 只填明确支持的模型名称；不确定时省略，系统会按供应商默认支持模型回填。',
  '- 通用 OpenAI-compatible 上游如需原生处理 OpenAI Responses 透传，请在 `credentials.supported_endpoint_modes` 的上游接口能力中包含 `responses_json` 或 `responses_sse`。',
  '- 普通供应商账户的 `modelMappings` 只做账号模型别名和 OpenAI v1 内部 bridge：OpenAI Chat 只能映射到 Chat Completions，OpenAI Responses 可映射到 Responses 或 Chat Completions，Anthropic Messages 只能映射到 Messages，Gemini native `streamGenerateContent` 可映射到 `generateContent`。其他跨协议方向不要写入普通账户导入数据。',
  '- 混合供应商账户的 `modelMappings` 用于声明跨协议入口，`upstreamEndpointFamily` 直接表示真实上游目标协议，可选 `chat_completions`、`messages` 或 `generate_content`；未列出的转换方向会被拒绝。',
  '- `modelMappings` 右侧 `upstreamEndpointFamily: "responses"` 只允许 `sourceEndpointFamily: "responses"` 的原生 Responses 别名，账号真实能力必须包含 `responses_json` 或 `responses_sse`。',
  '- 需要把 OpenAI / Gemini 转到 Anthropic Messages、Anthropic / OpenAI 转到 Gemini native，或 Gemini native 转到 OpenAI / Anthropic 时，请使用 `providerCode: "hybrid"` 的混合供应商账户配置；普通账户 `modelMappings` 只额外承接 OpenAI v1 Responses -> Chat Completions。',
  '- GLM Coding OpenAI Chat、DeepSeek OpenAI-compatible 和 Gemini OpenAI Chat 的 `credentials.supported_endpoint_modes` 仍按上游接口能力填写 `chat_json`、`chat_sse`；处理 Responses / Codex Responses 时必须同时配置 `responses -> chat_completions` 模型别名。',
  '- DeepSeek Claude Code 与 GLM Coding Anthropic 使用 Anthropic v1 Messages 原生协议，`credentials.supported_endpoint_modes` 填 `messages_json`、`messages_sse`，不要填 `message_token_counting`。',
  '- `modelMappings` 的 `sourceModel` 是客户端请求模型，`upstreamModel` 是该账户实际转发模型；普通供应商账户两者都必须来自当前账户供应商模型目录。OpenAI v1 `responses -> chat_completions` bridge 的左侧 `sourceModel` 是下游 Responses 别名，可选择当前供应商目录内的 Chat-only 模型；右侧 `upstreamModel` 仍必须支持 Chat Completions。通用 OpenAI-compatible 账号按 OpenAI-compatible 协议模型池处理，专用供应商不能引用其他供应商目录模型。混合供应商账户允许任意填写明确的下游模型名和真实上游模型名。',
  '- `supportedModels` 最终必须非空，限制的是映射右侧 `upstreamModel`，不是左侧 `sourceModel`；映射右侧只能选择账户支持模型。',
  '- `accountExpiresAt` 使用 ISO 时间字符串，例如 `2027-12-31T00:00:00.000Z`。',
  '',
  '## credentials 字段',
  '',
  'API Key 账户：',
  '',
  '```json',
  '{',
  '  "api_key": "sk-xxx",',
  '  "base_url": "https://api.openai.com/v1",',
  '  "supported_endpoint_modes": ["chat_json", "chat_sse"]',
  '}',
  '```',
  '',
  'Anthropic API Key 账户：',
  '',
  '```json',
  '{',
  '  "api_key": "sk-ant-xxx",',
  '  "base_url": "https://api.anthropic.com/v1",',
  '  "supported_endpoint_modes": ["messages_json", "messages_sse", "message_token_counting"]',
  '}',
  '```',
  '',
  'Gemini Google OAuth 账户：',
  '',
  '```json',
  '{',
  '  "refresh_token": "google-refresh-token-xxx",',
  '  "client_id": "google-client-id-xxx",',
  '  "client_secret": "google-client-secret-xxx",',
  '  "quota_project_id": "project-id",',
  '  "base_url": "https://generativelanguage.googleapis.com",',
  '  "supported_endpoint_modes": ["generate_content_json", "generate_content_sse", "interactions_json", "interactions_sse", "count_tokens", "embed_content"]',
  '}',
  '```',
  '',
  'DeepSeek OpenAI-compatible API Key 账户：',
  '',
  '```json',
  '{',
  '  "api_key": "sk-deepseek-xxx",',
  '  "base_url": "https://api.deepseek.com",',
  '  "supported_endpoint_modes": ["chat_json", "chat_sse"]',
  '}',
  '```',
  '',
  'DeepSeek Claude Code API Key 账户：',
  '',
  '```json',
  '{',
  '  "providerCode": "deepseek",',
  '  "providerProtocolProfileId": "profile_deepseek_anthropic_v1",',
  '  "type": "api_key",',
  '  "credentials": {',
  '    "api_key": "sk-deepseek-claude-code-xxx",',
  '    "base_url": "https://api.deepseek.com/anthropic",',
  '    "supported_endpoint_modes": ["messages_json", "messages_sse"]',
  '  }',
  '}',
  '```',
  '',
  '智谱 GLM 通用 API Key 账户：',
  '',
  '```json',
  '{',
  '  "providerCode": "glm",',
  '  "providerProtocolProfileId": "profile_glm_general_openai_v1",',
  '  "type": "api_key",',
  '  "credentials": {',
  '    "api_key": "sk-glm-general-xxx",',
  '    "base_url": "https://open.bigmodel.cn/api/paas/v4/",',
  '    "supported_endpoint_modes": ["chat_json", "chat_sse"]',
  '  }',
  '}',
  '```',
  '',
  'GLM Coding OpenAI Chat Key 账户：',
  '',
  '```json',
  '{',
  '  "providerCode": "glm",',
  '  "providerProtocolProfileId": "profile_glm_coding_openai_v1",',
  '  "type": "api_key",',
  '  "credentials": {',
  '    "api_key": "sk-glm-coding-xxx",',
  '    "base_url": "https://open.bigmodel.cn/api/coding/paas/v4",',
  '    "supported_endpoint_modes": ["chat_json", "chat_sse"]',
  '  }',
  '}',
  '```',
  '',
  'GLM Coding Anthropic Key 账户：',
  '',
  '```json',
  '{',
  '  "providerCode": "glm",',
  '  "providerProtocolProfileId": "profile_glm_coding_anthropic_v1",',
  '  "type": "api_key",',
  '  "credentials": {',
  '    "api_key": "sk-glm-coding-anthropic-xxx",',
  '    "base_url": "https://open.bigmodel.cn/api/anthropic",',
  '    "supported_endpoint_modes": ["messages_json", "messages_sse"]',
  '  }',
  '}',
  '```',
  '',
  '混合供应商账户：',
  '',
  '```json',
  '{',
  '  "providerCode": "hybrid",',
  '  "providerProtocolProfileId": "profile_hybrid_openai_chat_v1",',
  '  "type": "api_key",',
  '  "credentials": {',
  '    "api_key": "sk-glm-coding-xxx",',
  '    "base_url": "https://open.bigmodel.cn/api/coding/paas/v4",',
  '    "supported_endpoint_modes": ["chat_json", "chat_sse"]',
  '  },',
  '  "modelMappings": [',
  '    {',
  '      "sourceModel": "claude-sonnet-4",',
  '      "sourceEndpointFamily": "messages",',
  '      "upstreamModel": "glm-5.2",',
  '      "upstreamEndpointFamily": "chat_completions",',
  '      "enabled": true',
  '    }',
  '  ]',
  '}',
  '```',
  '',
  'OAuth 账户：',
  '',
  '```json',
  '{',
  '  "refresh_token": "refresh-token-xxx",',
  '  "access_token": "access-token-xxx",',
  '  "id_token": "id-token-xxx",',
  '  "base_url": "https://api.openai.com/v1",',
  '  "supported_endpoint_modes": ["responses_json", "responses_sse"],',
  '  "account_id": "acct_xxx",',
  '  "email": "user@example.com"',
  '}',
  '```',
  '',
  '凭据规则：',
  '',
  '- `api_key` 账户必须有 `credentials.api_key`。',
  '- `oauth` 账户必须有 `credentials.refresh_token` 或 `credentials.access_token`。`google_oauth` 必须填写可用 Access Token，或同时填写 Refresh Token、Client ID 与 Client Secret。只有 Access Token 的 Google OAuth 账户按静态 token 使用，不会自动刷新。',
  '- `credentials.base_url` 必须显式填写服务根地址或 `/v1` 版本根地址，OpenAI / GPT 通常为 `https://api.openai.com/v1`，xAI 为 `https://api.x.ai/v1`，DeepSeek OpenAI-compatible 通常为 `https://api.deepseek.com`，DeepSeek Claude Code 通常为 `https://api.deepseek.com/anthropic`，GLM 通用 API 通常为 `https://open.bigmodel.cn/api/paas/v4/`，GLM Coding OpenAI Chat 通常为 `https://open.bigmodel.cn/api/coding/paas/v4`，GLM Coding Anthropic 通常为 `https://open.bigmodel.cn/api/anthropic`，Anthropic 通常为 `https://api.anthropic.com/v1`，Gemini native 通常为 `https://generativelanguage.googleapis.com`，Gemini OpenAI Chat 通常为 `https://generativelanguage.googleapis.com/v1beta/openai`；混合供应商账户填写它自己的真实上游根地址；不要填写 `/chat/completions`、`/responses`、`/messages`、`/interactions` 或 `:generateContent` 等具体接口路径。',
  '- Anthropic API Key 不接受 `credentials.anthropic_version` 或 `credentials.anthropic_beta`；`anthropic-version` 是客户端请求头，缺省时由网关按当前协议默认 `2023-06-01` 补齐，`anthropic-beta` 只透传客户端显式 header。Claude Code 是客户端画像，不是账户类型；不要导入 Claude 订阅 OAuth / Setup Token。',
  '- 省略 `credentials.supported_endpoint_modes` 时，DeepSeek OpenAI-compatible 默认 Chat Completion (JSON/Streaming)，DeepSeek Claude Code 默认 Messages (JSON/Streaming)，GLM 通用 / Coding OpenAI Chat 默认 Chat JSON/SSE，GLM Coding Anthropic 默认 Messages JSON/SSE。',
  '- `credentials.supported_endpoint_modes` 用于声明上游接口能力，OpenAI / GPT / xAI 枚举为 `chat_json`、`chat_sse`、`responses_json`、`responses_sse`；Anthropic 枚举为 `messages_json`、`messages_sse`、`message_token_counting`；Gemini native 枚举为 `generate_content_json`、`generate_content_sse`、`interactions_json`、`interactions_sse`、`count_tokens`、`embed_content`；混合供应商账户可在这些枚举中按真实上游支持情况选择，省略时默认全量开放。字段名保持 snake_case，不要改成 camelCase。',
  '- 不要编造缺失 token，不确定的信息写入 `notes`。',
  '',
  '## proxies 字段',
  '',
  '| 字段 | 必填 | 类型 | 说明 |',
  '| --- | --- | --- | --- |',
  '| `ref` | 是 | string | 代理引用标识，供账户 `proxyRef` 使用。 |',
  '| `name` | 是 | string | 代理名称；已有同名启用代理时复用。 |',
  '| `type` | 是 | string | `http`、`https`、`socks5`、`socks5h`。 |',
  '| `host` | 是 | string | 代理主机。 |',
  '| `port` | 是 | number | 1 到 65535。 |',
  '| `username` | 否 | string | 代理用户名。 |',
  '| `password` | 否 | string | 代理密码。 |',
  '| `enabled` | 否 | boolean | 是否启用，默认 `true`。 |',
  '',
  '## 完整示例',
  '',
  '```json',
  importTemplate,
  '```',
  '',
  '## 常见失败原因',
  '',
  '- 顶层不是 JSON 对象，或者带了 Markdown 代码块。',
  '- `type` / `version` 不匹配当前协议。',
  '- `accounts` 为空、超过 50 条，或账户名称在同一系统账户下重复。',
  '- 账户缺少 `groupId` / `groupName`，或分组供应商和账户供应商不一致。',
  '- API Key 账户缺少 `credentials.api_key`。',
  '- OAuth 账户同时缺少 `credentials.refresh_token` 和 `credentials.access_token`，或 Google OAuth 缺少必填字段。',
  '- `proxyRef` 指向的代理不存在、未在 `proxies` 中声明，或普通用户尝试创建新代理。',
  '- 未知字段写入了错误层级，例如把外部系统字段直接放进 `credentials`。'
].join('\n')
