import { GPT_VENDOR_CODE } from '@/shared/providerProtocol'

export const importTemplate = JSON.stringify({
  type: 'juhe-ai-account-import',
  version: 1,
  proxies: [
    {
      ref: 'proxy-hk-1',
      name: '香港代理 1',
      type: 'http',
      host: '127.0.0.1',
      port: 7890,
      username: '',
      password: '',
      enabled: true
    }
  ],
  accounts: [
    {
      ref: 'gpt-key-001',
      name: 'GPT API Key 账号 1',
      providerCode: GPT_VENDOR_CODE,
      type: 'api_key',
      status: 'active',
      groupName: '默认 GPT 分组',
      concurrencyLimit: 3,
      priority: 50,
      proxyRef: 'proxy-hk-1',
      credentials: {
        api_key: 'sk-xxx',
        base_url: 'https://api.openai.com/v1'
      },
      notes: 'GPT API Key 账号'
    },
    {
      ref: 'gpt-oauth-001',
      name: 'GPT OAuth 账号 1',
      providerCode: GPT_VENDOR_CODE,
      type: 'oauth',
      status: 'active',
      groupName: '默认 GPT 分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        refresh_token: 'refresh-token-xxx',
        access_token: 'access-token-xxx',
        id_token: 'id-token-xxx',
        base_url: 'https://api.openai.com/v1',
        account_id: 'acct_xxx',
        email: 'user@example.com'
      },
      notes: 'OAuth 账号'
    }
  ]
}, null, 2)

export const aiConversionPrompt = [
  '请根据我附上的《juhe-ai AI 账户导入协议 v1》Markdown，把下面账号数据转换为 juhe-ai-account-import v1 JSON。',
  '',
  '要求：',
  '1. 协议文件优先于你的默认认知；字段名、必填项、枚举值和示例都按协议文件执行。',
  '2. 只输出合法 JSON，不要输出解释、Markdown 代码块或注释。',
  '3. 顶层 type 固定为 juhe-ai-account-import，version 固定为数字 1。',
  '4. 每个账户必须显式填写 name、providerCode、type、status、credentials，以及 groupName 或 groupId。',
  '5. API Key 账号使用 type: api_key；OAuth 账号使用 type: oauth。',
  '6. 不要编造来源数据里不存在的 token、API Key、邮箱、账号 ID、代理密码或模型列表。',
  '7. 如果有代理，请放到 proxies 数组，并用账号的 proxyRef 引用代理 ref。',
  '8. 不确定的信息放到 notes；无法判断是否可立即调度时 status 填 disabled。'
].join('\n')

export const accountImportProtocolMarkdown = [
  '# juhe-ai AI 账户导入协议 v1',
  '',
  '## 用途',
  '',
  '把其他系统、表格、文本或人工整理的 GPT / OpenAI v1 账户数据转换为 juhe-ai 可导入的 JSON。导入接口只接受 JSON，不接受 Markdown、注释、JSONL、CSV 或外部系统原始格式。',
  '',
  '## 转换约束',
  '',
  '- 输出必须是一个 JSON 对象，不能包在 Markdown 代码块里，不能附带解释文字。',
  '- 字段名严格使用本协议定义，不要把 `providerCode` 改成 `provider_code`，也不要把 `api_key` 改成 `apiKey`。',
  '- 顶层 `type` 固定为 `juhe-ai-account-import`，`version` 固定为数字 `1`。',
  '- `accounts` 至少 1 条；每个账户必须显式填写 `name`、`providerCode`、`type`、`status`、`credentials`，以及 `groupId` 或 `groupName`。',
  '- 当前默认使用 `providerCode: "gpt"`；确需通用 OpenAI-compatible 供应商时才填 `openai`。系统会按供应商自动匹配内部协议配置；通用 `openai` 供应商只填 `api_key`，`gpt` 供应商可填 `api_key` 或 `oauth`。',
  '- 不确定是否可立即调度时，`status` 填 `disabled`，不要默认填 `active`。',
  '- 不要编造缺失的 token、API Key、邮箱、账号 ID、代理密码或模型列表；不确定的信息写入 `notes`。',
  '- 外部来源字段如果没有本协议对应字段，不要塞进 `credentials`，可以整理到 `notes`。',
  '',
  '## 顶层结构',
  '',
  '| 字段 | 必填 | 类型 | 说明 |',
  '| --- | --- | --- | --- |',
  '| `type` | 是 | string | 固定为 `juhe-ai-account-import`。 |',
  '| `version` | 是 | number | 当前固定为 `1`。 |',
  '| `accounts` | 是 | array | 账户数组，至少 1 条，单次最多 50 条。 |',
  '| `proxies` | 否 | array | 代理数组，单次最多 20 条；账户通过 `proxyRef` 引用 `proxies[].ref`。 |',
  '',
  '结构骨架：',
  '',
  '```json',
  '{',
  '  "type": "juhe-ai-account-import",',
  '  "version": 1,',
  '  "accounts": []',
  '}',
  '```',
  '',
  '## accounts 字段',
  '',
  '| 字段 | 必填 | 类型 | 说明 |',
  '| --- | --- | --- | --- |',
  '| `ref` | 否 | string | 导入预览和错误定位用，不写入数据库。 |',
  '| `name` | 是 | string | 账户名称，同一系统账户下不能重复。 |',
  '| `providerCode` | 是 | string | 默认填 `gpt`。当前支持 `gpt` 和 `openai`；`gpt` 表示 GPT 专属供应商，`openai` 表示通用 OpenAI-compatible 供应商。 |',
  '| `type` | 是 | string | `api_key` 或 `oauth`。 |',
  '| `status` | 是 | string | `active` 或 `disabled`。不确定时用 `disabled`。 |',
  '| `groupId` | 二选一 | string | 绑定已有分组 ID；同时存在 `groupName` 时优先使用 `groupId`。 |',
  '| `groupName` | 二选一 | string | 绑定或自动创建同名分组。 |',
  '| `proxyRef` | 否 | string | 引用 `proxies[].ref` 或已有代理 ID。 |',
  '| `proxyProfileId` | 否 | string | 直接引用已有代理 ID；不能和 `proxyRef` 同时填写。 |',
  '| `concurrencyLimit` | 否 | number | 正整数，并发上限。 |',
  '| `priority` | 否 | number | 非负整数，调度优先级。 |',
  '| `superPriorityEnabled` | 否 | boolean | 超级优先开关。 |',
  '| `fallbackEnabled` | 否 | boolean | 降级备用开关。 |',
  '| `supportedModels` | 否 | string[] | 支持模型列表；不确定时省略。 |',
  '| `modelMappings` | 否 | object[] | 模型映射列表，条目包含 `sourceModel`、`upstreamModel`、`enabled`。 |',
  '| `accountExpiresAt` | 否 | string | ISO 时间字符串。 |',
  '| `availabilitySchedule` | 否 | object | 时间计划；不确定时省略。 |',
  '| `credentials` | 是 | object | 按账户类型填写凭据。 |',
  '| `notes` | 否 | string | 备注；无法确定的信息写这里。 |',
  '',
  '字段规则：',
  '',
  '- `groupId` 和 `groupName` 同时存在时优先使用 `groupId`。',
  '- `proxyRef` 和 `proxyProfileId` 不能同时填写。',
  '- `concurrencyLimit` 必须是正整数；`priority` 必须是非负整数。',
  '- `supportedModels` 只填明确支持的模型名称；不确定时省略。',
  '- `modelMappings` 的 sourceModel 是下游请求模型，upstreamModel 是该账户实际转发模型。',
  '- `accountExpiresAt` 使用 ISO 时间字符串，例如 `2027-12-31T00:00:00.000Z`。',
  '',
  '## credentials 字段',
  '',
  'API Key 账户：',
  '',
  '```json',
  '{',
  '  "api_key": "sk-xxx",',
  '  "base_url": "https://api.openai.com/v1"',
  '}',
  '```',
  '',
  'OAuth 账户：',
  '',
  '```json',
  '{',
  '  "refresh_token": "refresh-token-xxx",',
  '  "access_token": "access-token-xxx",',
  '  "id_token": "id-token-xxx",',
  '  "base_url": "https://api.openai.com/v1",',
  '  "account_id": "acct_xxx",',
  '  "email": "user@example.com"',
  '}',
  '```',
  '',
  '凭据规则：',
  '',
  '- `api_key` 账户必须有 `credentials.api_key`。',
  '- `oauth` 账户必须有 `credentials.refresh_token` 或 `credentials.access_token`。',
  '- `credentials.base_url` 必须显式填写服务根地址或 `/v1` 版本根地址，通常为 `https://api.openai.com/v1`；不要填写 `/responses` 等具体接口路径。',
  '- 字段名保持 snake_case，不要改成 camelCase。',
  '- 不要编造缺失 token，不确定的信息写入 `notes`。',
  '',
  '## proxies 字段',
  '',
  '| 字段 | 必填 | 类型 | 说明 |',
  '| --- | --- | --- | --- |',
  '| `ref` | 是 | string | 代理引用标识，供账户 `proxyRef` 使用。 |',
  '| `name` | 是 | string | 代理名称；已有同名启用代理时复用。 |',
  '| `type` | 是 | string | `http`、`https`、`socks5`、`socks5h`。 |',
  '| `host` | 是 | string | 代理主机。 |',
  '| `port` | 是 | number | 1 到 65535。 |',
  '| `username` | 否 | string | 代理用户名。 |',
  '| `password` | 否 | string | 代理密码。 |',
  '| `enabled` | 否 | boolean | 是否启用，默认 `true`。 |',
  '',
  '## 完整示例',
  '',
  '```json',
  importTemplate,
  '```',
  '',
  '## 常见失败原因',
  '',
  '- 顶层不是 JSON 对象，或者带了 Markdown 代码块。',
  '- `type` / `version` 不匹配当前协议。',
  '- `accounts` 为空、超过 50 条，或账户名称在同一系统账户下重复。',
  '- 账户缺少 `groupId` / `groupName`，或分组供应商和账户供应商不一致。',
  '- API Key 账户缺少 `credentials.api_key`。',
  '- OAuth 账户同时缺少 `credentials.refresh_token` 和 `credentials.access_token`。',
  '- `proxyRef` 指向的代理不存在、未在 `proxies` 中声明，或普通用户尝试创建新代理。',
  '- 未知字段写入了错误层级，例如把外部系统字段直接放进 `credentials`。'
].join('\n')
