import {
  ANTHROPIC_PROVIDER_CODE,
  DEEPSEEK_ANTHROPIC_V1_PROFILE_ID,
  DEEPSEEK_PROVIDER_CODE,
  GLM_CODING_ANTHROPIC_V1_PROFILE_ID,
  GLM_PROVIDER_CODE,
  GPT_VENDOR_CODE
} from '@/shared/providerProtocol'

export const importTemplate = JSON.stringify({
  type: 'juhe-ai-account-import',
  version: 1,
  proxies: [
    {
      ref: 'proxy-hk-1',
      name: '香港代理 1',
      type: 'http',
      host: '127.0.0.1',
      port: 7890,
      username: '',
      password: '',
      enabled: true
    }
  ],
  accounts: [
    {
      ref: 'gpt-key-001',
      name: 'GPT API Key 账号 1',
      providerCode: GPT_VENDOR_CODE,
      type: 'api_key',
      status: 'active',
      groupName: '默认 GPT 分组',
      concurrencyLimit: 3,
      priority: 50,
      proxyRef: 'proxy-hk-1',
      credentials: {
        api_key: 'sk-xxx',
        base_url: 'https://api.openai.com/v1',
        supported_endpoint_modes: ['chat_json', 'chat_sse', 'responses_json', 'responses_sse']
      },
      notes: 'GPT API Key 账号'
    },
    {
      ref: 'gpt-oauth-001',
      name: 'GPT OAuth 账号 1',
      providerCode: GPT_VENDOR_CODE,
      type: 'oauth',
      status: 'active',
      groupName: '默认 GPT 分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        refresh_token: 'refresh-token-xxx',
        access_token: 'access-token-xxx',
        id_token: 'id-token-xxx',
        base_url: 'https://api.openai.com/v1',
        supported_endpoint_modes: ['responses_json', 'responses_sse'],
        account_id: 'acct_xxx',
        email: 'user@example.com'
      },
      notes: 'OAuth 账号'
    },
    {
      ref: 'deepseek-key-001',
      name: 'DeepSeek API Key 账号 1',
      providerCode: DEEPSEEK_PROVIDER_CODE,
      type: 'api_key',
      status: 'active',
      groupName: '默认 DeepSeek 分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        api_key: 'sk-deepseek-xxx',
        base_url: 'https://api.deepseek.com',
        supported_endpoint_modes: ['chat_json', 'chat_sse']
      },
      notes: 'DeepSeek API Key 账号'
    },
    {
      ref: 'deepseek-claude-code-001',
      name: 'DeepSeek Claude Code 账号 1',
      providerCode: DEEPSEEK_PROVIDER_CODE,
      providerProtocolProfileId: DEEPSEEK_ANTHROPIC_V1_PROFILE_ID,
      type: 'api_key',
      status: 'active',
      groupName: '默认 DeepSeek Claude Code 分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        api_key: 'sk-deepseek-claude-code-xxx',
        base_url: 'https://api.deepseek.com/anthropic',
        supported_endpoint_modes: ['messages_json', 'messages_sse']
      },
      notes: 'DeepSeek Anthropic v1 / Claude Code 账号'
    },
    {
      ref: 'glm-general-001',
      name: '智谱 GLM 通用账号 1',
      providerCode: GLM_PROVIDER_CODE,
      connectionType: 'general_api_key',
      type: 'api_key',
      clientCompatibility: 'openai_standard',
      status: 'active',
      groupName: '默认 GLM 通用分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        api_key: 'sk-glm-general-xxx',
        base_url: 'https://open.bigmodel.cn/api/paas/v4/',
        supported_endpoint_modes: ['chat_json', 'chat_sse']
      },
      notes: '智谱通用 GLM API Key 账号'
    },
    {
      ref: 'glm-coding-001',
      name: '智谱 GLM Coding 账号 1',
      providerCode: GLM_PROVIDER_CODE,
      connectionType: 'coding_api_key',
      type: 'api_key',
      clientCompatibility: 'codex_responses',
      status: 'active',
      groupName: '默认 GLM Coding 分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        api_key: 'sk-glm-coding-xxx',
        base_url: 'https://open.bigmodel.cn/api/coding/paas/v4',
        supported_endpoint_modes: ['chat_json', 'chat_sse']
      },
      notes: 'GLM Coding Plan Key 账号'
    },
    {
      ref: 'glm-coding-claude-code-001',
      name: '智谱 GLM Coding Claude Code 账号 1',
      providerCode: GLM_PROVIDER_CODE,
      connectionType: 'coding_anthropic_api_key',
      type: 'api_key',
      status: 'active',
      groupName: '默认 GLM Coding Claude Code 分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        api_key: 'sk-glm-coding-claude-code-xxx',
        base_url: 'https://open.bigmodel.cn/api/anthropic',
        supported_endpoint_modes: ['messages_json', 'messages_sse']
      },
      notes: 'GLM Coding Anthropic v1 / Claude Code 账号'
    },
    {
      ref: 'anthropic-key-001',
      name: 'Anthropic API Key 账号 1',
      providerCode: ANTHROPIC_PROVIDER_CODE,
      type: 'api_key',
      status: 'active',
      groupName: '默认 Anthropic 分组',
      concurrencyLimit: 3,
      priority: 50,
      credentials: {
        api_key: 'sk-ant-xxx',
        base_url: 'https://api.anthropic.com/v1',
        supported_endpoint_modes: ['messages_json', 'messages_sse', 'message_token_counting']
      },
      notes: 'Anthropic API Key 账号'
    }
  ]
}, null, 2)

export const aiConversionPrompt = [
  '请根据我附上的《juhe-ai AI 账户导入协议 v1》Markdown，把下面账号数据转换为 juhe-ai-account-import v1 JSON。',
  '',
  '要求：',
  '1. 协议文件优先于你的默认认知；字段名、必填项、枚举值和示例都按协议文件执行。',
  '2. 只输出合法 JSON，不要输出解释、Markdown 代码块或注释。',
  '3. 顶层 type 固定为 juhe-ai-account-import，version 固定为数字 1。',
  '4. 每个账户必须显式填写 name、providerCode、type、status、credentials，以及 groupName 或 groupId。',
  '5. API Key 账号使用 type: api_key；OAuth 账号使用 type: oauth。',
  '6. providerCode 为 glm 时必须显式填写 connectionType：general_api_key 表示通用 GLM API Key，coding_api_key 表示 GLM Coding OpenAI Chat，coding_anthropic_api_key 表示 GLM Coding Claude Code；DeepSeek Claude Code 必须显式填写 providerProtocolProfileId: profile_deepseek_anthropic_v1。',
  '7. 不要编造来源数据里不存在的 token、API Key、邮箱、账号 ID、代理密码或模型列表。',
  '8. 如果有代理，请放到 proxies 数组，并用账号的 proxyRef 引用代理 ref。',
  '9. 不确定的信息放到 notes；无法判断是否可立即调度时 status 填 pending_test 或 disabled。'
].join('\n')

export const accountImportProtocolMarkdown = [
  '# juhe-ai AI 账户导入协议 v1',
  '',
  '## 用途',
  '',
  '把其他系统、表格、文本或人工整理的 GPT / OpenAI v1 / DeepSeek / GLM / Anthropic v1 账户数据转换为 juhe-ai 可导入的 JSON。导入接口只接受 JSON，不接受 Markdown、注释、JSONL、CSV 或外部系统原始格式。',
  '',
  '## 转换约束',
  '',
  '- 输出必须是一个 JSON 对象，不能包在 Markdown 代码块里，不能附带解释文字。',
  '- 字段名严格使用本协议定义，不要把 `providerCode` 改成 `provider_code`，也不要把 `api_key` 改成 `apiKey`。',
  '- 顶层 `type` 固定为 `juhe-ai-account-import`，`version` 固定为数字 `1`。',
  '- `accounts` 至少 1 条；每个账户必须显式填写 `name`、`providerCode`、`type`、`status`、`credentials`，以及 `groupId` 或 `groupName`。',
  '- 当前默认使用 `providerCode: "gpt"`；确需通用 OpenAI-compatible 供应商时才填 `openai`；DeepSeek 直连填 `deepseek`；智谱 GLM 直连填 `glm`；官方 Anthropic Claude 直连填 `anthropic`。系统会按供应商和协议档案匹配内部配置；通用 `openai` 供应商只填 `api_key`，`deepseek` 当前只填 `api_key` 但可选 OpenAI-compatible 或 Anthropic v1 档案，`glm` 当前只填 `api_key` 但必须用 `connectionType` 区分通用 API、Coding OpenAI Chat 与 Coding Claude Code，`gpt` 供应商可填 `api_key` 或 `oauth`，`anthropic` 当前只填 `api_key`。',
  '- `providerCode: "glm"` 时必须显式填写 `connectionType: "general_api_key"`、`connectionType: "coding_api_key"` 或 `connectionType: "coding_anthropic_api_key"`；不要根据 `base_url` 猜测接入类型。',
  '- DeepSeek OpenAI-compatible 可省略 `providerProtocolProfileId`；DeepSeek Claude Code 必须显式填写 `providerProtocolProfileId: "profile_deepseek_anthropic_v1"`。',
  '- `clientCompatibility` 可选填写 `openai_standard` 或 `codex_responses`；省略时按供应商默认值处理。GLM 通用 API 只填 `openai_standard` 或省略；GLM Coding OpenAI Chat、DeepSeek OpenAI-compatible 如需承接 Codex 客户端必须显式填写 `codex_responses`，否则只按 OpenAI-compatible 请求处理。DeepSeek Claude Code、GLM Coding Claude Code 和官方 Anthropic 走 Anthropic v1 Messages 原生协议，不填写 `clientCompatibility`。',
  '- 不确定是否可立即调度时，`status` 填 `pending_test` 或 `disabled`，不要默认填 `active`。',
  '- 不要编造缺失的 token、API Key、邮箱、账号 ID、代理密码或模型列表；不确定的信息写入 `notes`。',
  '- 外部来源字段如果没有本协议对应字段，不要塞进 `credentials`，可以整理到 `notes`。',
  '',
  '## 顶层结构',
  '',
  '| 字段 | 必填 | 类型 | 说明 |',
  '| --- | --- | --- | --- |',
  '| `type` | 是 | string | 固定为 `juhe-ai-account-import`。 |',
  '| `version` | 是 | number | 当前固定为 `1`。 |',
  '| `accounts` | 是 | array | 账户数组，至少 1 条，单次最多 50 条。 |',
  '| `proxies` | 否 | array | 代理数组，单次最多 20 条；账户通过 `proxyRef` 引用 `proxies[].ref`。 |',
  '',
  '结构骨架：',
  '',
  '```json',
  '{',
  '  "type": "juhe-ai-account-import",',
  '  "version": 1,',
  '  "accounts": []',
  '}',
  '```',
  '',
  '## accounts 字段',
  '',
  '| 字段 | 必填 | 类型 | 说明 |',
  '| --- | --- | --- | --- |',
  '| `ref` | 否 | string | 导入预览和错误定位用，不写入数据库。 |',
  '| `name` | 是 | string | 账户名称，同一系统账户下不能重复。 |',
  '| `providerCode` | 是 | string | 默认填 `gpt`。当前支持 `gpt`、`openai`、`deepseek`、`glm` 和 `anthropic`；`gpt` 表示 GPT 专属供应商，`openai` 表示通用 OpenAI-compatible 供应商，`deepseek` 表示 DeepSeek 直连供应商，`glm` 表示智谱 GLM 直连供应商，`anthropic` 表示官方 Anthropic Claude 直连供应商。 |',
  '| `connectionType` | 条件必填 | string | `glm` 必填 `general_api_key`、`coding_api_key` 或 `coding_anthropic_api_key`；其他供应商省略。 |',
  '| `type` | 是 | string | `api_key` 或 `oauth`。 |',
  '| `clientCompatibility` | 否 | string | `openai_standard` 或 `codex_responses`；GLM Coding OpenAI Chat、DeepSeek OpenAI-compatible 需要承接 Codex 客户端时必须填 `codex_responses`。Anthropic v1 / Claude Code 档案省略。 |',
  '| `providerProtocolProfileId` | 否 | string | 显式内部协议档案；省略时按供应商默认解析。DeepSeek Claude Code 填 `profile_deepseek_anthropic_v1`；GLM 优先使用 `connectionType` 区分通用 API、Coding OpenAI Chat 与 Coding Claude Code。 |',
  '| `status` | 是 | string | `active`、`pending_test` 或 `disabled`。`active` 导入创建时会转为 `pending_test`；不确定时用 `pending_test` 或 `disabled`。 |',
  '| `groupId` | 二选一 | string | 绑定已有分组 ID；同时存在 `groupName` 时优先使用 `groupId`。 |',
  '| `groupName` | 二选一 | string | 绑定或自动创建同名分组。 |',
  '| `proxyRef` | 否 | string | 引用 `proxies[].ref` 或已有代理 ID。 |',
  '| `proxyProfileId` | 否 | string | 直接引用已有代理 ID；不能和 `proxyRef` 同时填写。 |',
  '| `concurrencyLimit` | 否 | number | 正整数，并发上限。 |',
  '| `priority` | 否 | number | 非负整数，调度优先级。 |',
  '| `superPriorityEnabled` | 否 | boolean | 超级优先开关。 |',
  '| `fallbackEnabled` | 否 | boolean | 降级备用开关。 |',
  '| `supportedModels` | 否 | string[] | 支持模型列表；不确定时省略。 |',
  '| `modelMappings` | 否 | object[] | 模型映射列表，条目包含 `sourceModel`、`sourceEndpointFamily`、`upstreamModel`、`upstreamEndpointFamily`、`enabled`。 |',
  '| `tags` | 否 | string[] | 账户标签名称列表；不存在的标签按当前导入权限创建或报错。 |',
  '| `accountExpiresAt` | 否 | string | ISO 时间字符串。 |',
  '| `availabilitySchedule` | 否 | object | 时间计划；不确定时省略。 |',
  '| `credentials` | 是 | object | 按账户类型填写凭据。 |',
  '| `notes` | 否 | string | 备注；无法确定的信息写这里。 |',
  '',
  '字段规则：',
  '',
  '- `groupId` 和 `groupName` 同时存在时优先使用 `groupId`。',
  '- `proxyRef` 和 `proxyProfileId` 不能同时填写。',
  '- `concurrencyLimit` 必须是正整数；`priority` 必须是非负整数。',
  '- 导入创建时 `status: "active"` 会转为 `pending_test`，测试通过后才参与调度；明确不希望调度时填 `disabled`。',
  '- `supportedModels` 只填明确支持的模型名称；不确定时省略。',
  '- 通用 OpenAI-compatible 上游如需承接 OpenAI Responses 透传，请在 `credentials.supported_endpoint_modes` 中包含 `responses_json` 或 `responses_sse`。',
  '- 需要把 OpenAI Responses 请求转到 Chat Completions 上游时，在 `modelMappings` 中显式配置 `sourceEndpointFamily: "responses"` 和 `upstreamEndpointFamily: "chat_completions"`；不支持 `chat_completions` 转 `responses`。',
  '- GLM Coding OpenAI Chat 和 DeepSeek OpenAI-compatible 的 `credentials.supported_endpoint_modes` 仍填写真实上游能力 `chat_json`、`chat_sse`。',
  '- DeepSeek Claude Code 与 GLM Coding Claude Code 使用 Anthropic v1 Messages 原生协议，`credentials.supported_endpoint_modes` 填 `messages_json`、`messages_sse`，不要填 `message_token_counting`。',
  '- `modelMappings` 的 `sourceModel` 是客户端请求模型，必须来自 OpenAI 协议模型池；`upstreamModel` 是该账户实际转发模型，专用供应商必须来自当前供应商模型列表，通用 OpenAI-compatible 账号可来自 OpenAI 协议模型池。',
  '- `supportedModels` 非空时限制的是映射右侧 `upstreamModel`，不是左侧 `sourceModel`。',
  '- `accountExpiresAt` 使用 ISO 时间字符串，例如 `2027-12-31T00:00:00.000Z`。',
  '',
  '## credentials 字段',
  '',
  'API Key 账户：',
  '',
  '```json',
  '{',
  '  "api_key": "sk-xxx",',
  '  "base_url": "https://api.openai.com/v1",',
  '  "supported_endpoint_modes": ["chat_json", "chat_sse"]',
  '}',
  '```',
  '',
  'Anthropic API Key 账户：',
  '',
  '```json',
  '{',
  '  "api_key": "sk-ant-xxx",',
  '  "base_url": "https://api.anthropic.com/v1",',
  '  "supported_endpoint_modes": ["messages_json", "messages_sse", "message_token_counting"]',
  '}',
  '```',
  '',
  'DeepSeek OpenAI-compatible API Key 账户：',
  '',
  '```json',
  '{',
  '  "api_key": "sk-deepseek-xxx",',
  '  "base_url": "https://api.deepseek.com",',
  '  "supported_endpoint_modes": ["chat_json", "chat_sse"]',
  '}',
  '```',
  '',
  'DeepSeek Claude Code API Key 账户：',
  '',
  '```json',
  '{',
  '  "providerCode": "deepseek",',
  '  "providerProtocolProfileId": "profile_deepseek_anthropic_v1",',
  '  "type": "api_key",',
  '  "credentials": {',
  '    "api_key": "sk-deepseek-claude-code-xxx",',
  '    "base_url": "https://api.deepseek.com/anthropic",',
  '    "supported_endpoint_modes": ["messages_json", "messages_sse"]',
  '  }',
  '}',
  '```',
  '',
  '智谱 GLM 通用 API Key 账户：',
  '',
  '```json',
  '{',
  '  "providerCode": "glm",',
  '  "connectionType": "general_api_key",',
  '  "type": "api_key",',
  '  "clientCompatibility": "openai_standard",',
  '  "credentials": {',
  '    "api_key": "sk-glm-general-xxx",',
  '    "base_url": "https://open.bigmodel.cn/api/paas/v4/",',
  '    "supported_endpoint_modes": ["chat_json", "chat_sse"]',
  '  }',
  '}',
  '```',
  '',
  'GLM Coding OpenAI Chat Key 账户：',
  '',
  '```json',
  '{',
  '  "providerCode": "glm",',
  '  "connectionType": "coding_api_key",',
  '  "type": "api_key",',
  '  "clientCompatibility": "codex_responses",',
  '  "credentials": {',
  '    "api_key": "sk-glm-coding-xxx",',
  '    "base_url": "https://open.bigmodel.cn/api/coding/paas/v4",',
  '    "supported_endpoint_modes": ["chat_json", "chat_sse"]',
  '  }',
  '}',
  '```',
  '',
  'GLM Coding Claude Code Key 账户：',
  '',
  '```json',
  '{',
  '  "providerCode": "glm",',
  '  "connectionType": "coding_anthropic_api_key",',
  '  "type": "api_key",',
  '  "credentials": {',
  '    "api_key": "sk-glm-coding-claude-code-xxx",',
  '    "base_url": "https://open.bigmodel.cn/api/anthropic",',
  '    "supported_endpoint_modes": ["messages_json", "messages_sse"]',
  '  }',
  '}',
  '```',
  '',
  'OAuth 账户：',
  '',
  '```json',
  '{',
  '  "refresh_token": "refresh-token-xxx",',
  '  "access_token": "access-token-xxx",',
  '  "id_token": "id-token-xxx",',
  '  "base_url": "https://api.openai.com/v1",',
  '  "supported_endpoint_modes": ["responses_json", "responses_sse"],',
  '  "account_id": "acct_xxx",',
  '  "email": "user@example.com"',
  '}',
  '```',
  '',
  '凭据规则：',
  '',
  '- `api_key` 账户必须有 `credentials.api_key`。',
  '- `oauth` 账户必须有 `credentials.refresh_token` 或 `credentials.access_token`。',
  '- `credentials.base_url` 必须显式填写服务根地址或 `/v1` 版本根地址，OpenAI / GPT 通常为 `https://api.openai.com/v1`，DeepSeek OpenAI-compatible 通常为 `https://api.deepseek.com`，DeepSeek Claude Code 通常为 `https://api.deepseek.com/anthropic`，GLM 通用 API 通常为 `https://open.bigmodel.cn/api/paas/v4/`，GLM Coding OpenAI Chat 通常为 `https://open.bigmodel.cn/api/coding/paas/v4`，GLM Coding Claude Code 通常为 `https://open.bigmodel.cn/api/anthropic`，Anthropic 通常为 `https://api.anthropic.com/v1`；不要填写 `/chat/completions`、`/responses` 或 `/messages` 等具体接口路径。',
  '- Anthropic API Key 不接受 `credentials.anthropic_version` 或 `credentials.anthropic_beta`；`anthropic-version` 是客户端请求头，缺省时由网关按当前协议默认 `2023-06-01` 补齐，`anthropic-beta` 只透传客户端显式 header。Claude Code 是客户端画像，不是账户类型，不要导入 Claude Code OAuth / Setup Token。',
  '- `credentials.supported_endpoint_modes` 可限制接口能力，OpenAI / GPT 枚举为 `chat_json`、`chat_sse`、`responses_json`、`responses_sse`；DeepSeek OpenAI-compatible、GLM 通用、GLM Coding OpenAI Chat 只支持 `chat_json`、`chat_sse`；DeepSeek Claude Code、GLM Coding Claude Code 只支持 `messages_json`、`messages_sse`；官方 Anthropic 枚举为 `messages_json`、`messages_sse`、`message_token_counting`。省略时通用 `openai` API Key 默认 Chat Completions (JSON/Streaming)，DeepSeek OpenAI-compatible 默认 Chat Completion (JSON/Streaming)，DeepSeek Claude Code 默认 Messages (JSON/Streaming)，GLM 通用 API Key 默认对话补全 (JSON/Streaming)，GLM Coding OpenAI Chat 默认 OpenAI Chat Completions (JSON/Streaming)，GLM Coding Claude Code 默认 Messages (JSON/Streaming)，GLM Coding 和 DeepSeek 的 Codex bridge 也必须保存真实上游能力，GPT API Key 默认四项全开，GPT OAuth 默认 Responses API (JSON/Streaming)，官方 Anthropic API Key 默认 Messages API (JSON/Streaming) 和 Count tokens。',
  '- 字段名保持 snake_case，不要改成 camelCase。',
  '- 不要编造缺失 token，不确定的信息写入 `notes`。',
  '',
  '## proxies 字段',
  '',
  '| 字段 | 必填 | 类型 | 说明 |',
  '| --- | --- | --- | --- |',
  '| `ref` | 是 | string | 代理引用标识，供账户 `proxyRef` 使用。 |',
  '| `name` | 是 | string | 代理名称；已有同名启用代理时复用。 |',
  '| `type` | 是 | string | `http`、`https`、`socks5`、`socks5h`。 |',
  '| `host` | 是 | string | 代理主机。 |',
  '| `port` | 是 | number | 1 到 65535。 |',
  '| `username` | 否 | string | 代理用户名。 |',
  '| `password` | 否 | string | 代理密码。 |',
  '| `enabled` | 否 | boolean | 是否启用，默认 `true`。 |',
  '',
  '## 完整示例',
  '',
  '```json',
  importTemplate,
  '```',
  '',
  '## 常见失败原因',
  '',
  '- 顶层不是 JSON 对象，或者带了 Markdown 代码块。',
  '- `type` / `version` 不匹配当前协议。',
  '- `accounts` 为空、超过 50 条，或账户名称在同一系统账户下重复。',
  '- 账户缺少 `groupId` / `groupName`，或分组供应商和账户供应商不一致。',
  '- API Key 账户缺少 `credentials.api_key`。',
  '- OAuth 账户同时缺少 `credentials.refresh_token` 和 `credentials.access_token`。',
  '- `proxyRef` 指向的代理不存在、未在 `proxies` 中声明，或普通用户尝试创建新代理。',
  '- 未知字段写入了错误层级，例如把外部系统字段直接放进 `credentials`。'
].join('\n')
