package pricing

// OpenAI pricing snapshot, ported from backend/src/modules/model-pricing/
// openai-model-pricing.{data,gpt4,gpt5,image,reasoning}.data.ts. Token prices
// are USD per token literals identical to the Node snapshot rows.

// openAIModelPricingData = openAIGPT4 + openAIGPT5 + openAIImage +
// openAIReasoning (order preserved).
var openAIModelPricingData = func() []rawModel {
	out := make([]rawModel, 0, len(openAIGPT4ModelPricingData)+len(openAIGPT5ModelPricingData)+len(openAIImageModelPricingData)+len(openAIReasoningModelPricingData))
	out = append(out, openAIGPT4ModelPricingData...)
	out = append(out, openAIGPT5ModelPricingData...)
	out = append(out, openAIImageModelPricingData...)
	out = append(out, openAIReasoningModelPricingData...)
	return out
}()

// openAIGPT4ModelPricingData — curated 2026-07-13.
var openAIGPT4ModelPricingData = []rawModel{
	{
		Model: "gpt-4.1", Mode: "chat",
		MaxTokens: intp(32768), ContextWindowTokens: intp(1047576), MaxOutputTokens: intp(32768),
		InputModalities:       []string{"text", "image"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions", "responses"},
		SupportedTools:        []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "mcp"},
		InputCostPerToken:     f64p(0.000002), InputCostPerTokenPriority: f64p(0.0000035),
		OutputCostPerToken: f64p(0.000008), OutputCostPerTokenPriority: f64p(0.000014),
		CacheReadInputTokenCost: f64p(5e-7), CacheReadInputTokenCostPriority: f64p(8.75e-7),
		SupportsPromptCaching: true,
		SupportedServiceTiers: []string{"priority"},
	},
	{
		Model: "gpt-4.1-mini", Mode: "chat",
		MaxTokens: intp(32768), ContextWindowTokens: intp(1047576), MaxOutputTokens: intp(32768),
		InputModalities:       []string{"text", "image"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions", "responses"},
		SupportedTools:        []string{"function_calling", "web_search", "file_search", "code_interpreter", "mcp"},
		InputCostPerToken:     f64p(4e-7), InputCostPerTokenPriority: f64p(7e-7),
		OutputCostPerToken: f64p(0.0000016), OutputCostPerTokenPriority: f64p(0.0000028),
		CacheReadInputTokenCost: f64p(1e-7), CacheReadInputTokenCostPriority: f64p(1.75e-7),
		SupportsPromptCaching: true,
		SupportedServiceTiers: []string{"priority"},
	},
	{
		Model: "gpt-4.1-nano", Mode: "chat",
		MaxTokens: intp(32768), ContextWindowTokens: intp(1047576), MaxOutputTokens: intp(32768),
		InputModalities:       []string{"text", "image"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions", "responses"},
		SupportedTools:        []string{"function_calling", "file_search", "image_generation", "code_interpreter", "mcp"},
		InputCostPerToken:     f64p(1e-7), InputCostPerTokenPriority: f64p(2e-7),
		OutputCostPerToken: f64p(4e-7), OutputCostPerTokenPriority: f64p(8e-7),
		CacheReadInputTokenCost: f64p(2.5e-8), CacheReadInputTokenCostPriority: f64p(5e-8),
		ShutdownDate:          "2026-10-23",
		SupportsPromptCaching: true,
		SupportedServiceTiers: []string{"priority"},
	},
	{
		Model: "gpt-4o", Mode: "chat",
		MaxTokens: intp(16384), ContextWindowTokens: intp(128000), MaxOutputTokens: intp(16384),
		InputModalities:       []string{"text", "image"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions", "responses"},
		SupportedTools:        []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "mcp"},
		InputCostPerToken:     f64p(0.0000025), InputCostPerTokenPriority: f64p(0.00000425),
		OutputCostPerToken: f64p(0.00001), OutputCostPerTokenPriority: f64p(0.000017),
		CacheReadInputTokenCost: f64p(0.00000125), CacheReadInputTokenCostPriority: f64p(0.000002125),
		SupportsPromptCaching: true,
		SupportedServiceTiers: []string{"priority"},
	},
	{
		Model: "gpt-4o-mini", Mode: "chat",
		MaxTokens: intp(16384), ContextWindowTokens: intp(128000), MaxOutputTokens: intp(16384),
		InputModalities:       []string{"text", "image"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions", "responses"},
		SupportedTools:        []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "mcp"},
		InputCostPerToken:     f64p(1.5e-7), InputCostPerTokenPriority: f64p(2.5e-7),
		OutputCostPerToken: f64p(6e-7), OutputCostPerTokenPriority: f64p(0.000001),
		CacheReadInputTokenCost: f64p(7.5e-8), CacheReadInputTokenCostPriority: f64p(1.25e-7),
		SupportsPromptCaching: true,
		SupportedServiceTiers: []string{"priority"},
	},
	{
		Model: "gpt-4o-2024-05-13", Mode: "chat",
		MaxTokens: intp(4096), ContextWindowTokens: intp(128000), MaxOutputTokens: intp(4096),
		InputModalities:       []string{"text", "image"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions", "responses"},
		SupportedTools:        []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "mcp"},
		InputCostPerToken:     f64p(0.000005),
		OutputCostPerToken:    f64p(0.000015),
		ShutdownDate:          "2026-10-23",
	},
	{
		Model: "gpt-4-turbo", Mode: "chat",
		MaxTokens: intp(4096), ContextWindowTokens: intp(128000), MaxOutputTokens: intp(4096),
		InputModalities:       []string{"text", "image"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions", "responses"},
		InputCostPerToken:     f64p(0.00001),
		OutputCostPerToken:    f64p(0.00003),
		ShutdownDate:          "2026-10-23",
	},
	{
		Model: "gpt-4-turbo-2024-04-09", Mode: "chat",
		MaxTokens: intp(4096), ContextWindowTokens: intp(128000), MaxOutputTokens: intp(4096),
		InputModalities:       []string{"text", "image"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions", "responses"},
		InputCostPerToken:     f64p(0.00001),
		OutputCostPerToken:    f64p(0.00003),
		ShutdownDate:          "2026-10-23",
	},
	{
		Model: "gpt-4-1106-preview", Mode: "chat",
		MaxTokens: intp(4096), ContextWindowTokens: intp(128000), MaxOutputTokens: intp(4096),
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions"},
		InputCostPerToken:     f64p(0.00001),
		OutputCostPerToken:    f64p(0.00003),
		ShutdownDate:          "2026-10-23",
	},
	{
		Model: "gpt-4", Mode: "chat",
		MaxTokens: intp(8192), ContextWindowTokens: intp(8192), MaxOutputTokens: intp(4096),
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions"},
		InputCostPerToken:     f64p(0.00003),
		OutputCostPerToken:    f64p(0.00006),
		ShutdownDate:          "2026-10-23",
	},
	{
		Model: "gpt-4-0613", Mode: "chat",
		MaxTokens: intp(8192), ContextWindowTokens: intp(8192), MaxOutputTokens: intp(4096),
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions"},
		InputCostPerToken:     f64p(0.00003),
		OutputCostPerToken:    f64p(0.00006),
		ShutdownDate:          "2026-10-23",
	},
	{
		Model: "gpt-3.5-turbo", Mode: "chat",
		MaxTokens: intp(4096), ContextWindowTokens: intp(16385), MaxOutputTokens: intp(4096),
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions"},
		InputCostPerToken:     f64p(5e-7),
		OutputCostPerToken:    f64p(0.0000015),
		ShutdownDate:          "2026-10-23",
	},
	{
		Model: "gpt-3.5-turbo-0125", Mode: "chat",
		MaxTokens: intp(4096), ContextWindowTokens: intp(16385), MaxOutputTokens: intp(4096),
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions"},
		InputCostPerToken:     f64p(5e-7),
		OutputCostPerToken:    f64p(0.0000015),
		ShutdownDate:          "2026-10-23",
	},
	{
		Model: "gpt-3.5-turbo-1106", Mode: "chat",
		MaxTokens: intp(4096), ContextWindowTokens: intp(16385), MaxOutputTokens: intp(4096),
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions"},
		InputCostPerToken:     f64p(0.000001),
		OutputCostPerToken:    f64p(0.000002),
		ShutdownDate:          "2026-09-28",
	},
}

// gpt5ToolsGpt5Dot6 mirrors the shared supported_tools list of the GPT-5.6
// family rows.
var gpt5ToolsGpt5Dot6 = []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "hosted_shell", "apply_patch", "skills", "computer_use", "mcp", "tool_search"}

// gpt5ToolsGpt55 mirrors the GPT-5.5 family supported_tools list.
var gpt5ToolsGpt55 = []string{"function_calling", "web_search", "file_search", "tool_search", "image_generation", "code_interpreter", "hosted_shell", "apply_patch", "skills", "computer_use", "mcp"}

// gpt5ToolsGpt54Mini mirrors the GPT-5.4/mini family supported_tools list.
var gpt5ToolsGpt54Mini = gpt5ToolsGpt55

// gpt5ToolsGpt54Nano mirrors the GPT-5.4-nano supported_tools list.
var gpt5ToolsGpt54Nano = []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "hosted_shell", "apply_patch", "skills", "mcp"}

// gpt5ToolsProCodex mirrors the GPT-5 pro / codex supported_tools lists that
// share the same content.
var gpt5ToolsProCodex543 = []string{"function_calling", "web_search", "file_search", "tool_search", "image_generation", "apply_patch", "computer_use", "mcp"}

// openAIGPT5ModelPricingData — GPT-6/GPT-5 family, curated with the
// 2026-07-30 pricing changelog.
var openAIGPT5ModelPricingData = []rawModel{
	{
		Model: "gpt-6-astra", Mode: "chat", CatalogOrder: intp(-1), ReleaseDate: "2026-09-03",
		ContextWindowTokens: intp(1050000), MaxInputTokens: intp(922000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.00001), InputCostPerTokenPriority: f64p(0.00002), InputCostPerTokenFlex: f64p(0.000005),
		OutputCostPerToken: f64p(0.00005), OutputCostPerTokenPriority: f64p(0.0001), OutputCostPerTokenFlex: f64p(0.000025),
		CacheCreationInputTokenCost: f64p(0.0000125), CacheCreationInputTokenCostPriority: f64p(0.000025), CacheCreationInputTokenCostFlex: f64p(0.00000625),
		CacheReadInputTokenCost: f64p(0.000001), CacheReadInputTokenCostPriority: f64p(0.000002), CacheReadInputTokenCostFlex: f64p(0.0000005),
		LongContextInputTokenThreshold: intp(272000),
		LongContextInputCostMultiplier: f64p(2), LongContextOutputCostMultiplier: f64p(1.5),
		SupportsPromptCaching:     true,
		SupportedServiceTiers:     []string{"priority", "flex"},
		SupportedReasoningEfforts: []string{"low", "medium", "high", "xhigh", "max"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            gpt5ToolsGpt5Dot6,
	},
	{
		Model: "gpt-5.6-sol", Mode: "chat", CatalogOrder: intp(0), ReleaseDate: "2026-06-26",
		ContextWindowTokens: intp(1050000), MaxInputTokens: intp(922000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.000005), InputCostPerTokenPriority: f64p(0.00001), InputCostPerTokenFlex: f64p(0.0000025),
		OutputCostPerToken: f64p(0.00003), OutputCostPerTokenPriority: f64p(0.00006), OutputCostPerTokenFlex: f64p(0.000015),
		CacheCreationInputTokenCost: f64p(0.00000625), CacheCreationInputTokenCostPriority: f64p(0.0000125), CacheCreationInputTokenCostFlex: f64p(0.000003125),
		CacheReadInputTokenCost: f64p(5e-7), CacheReadInputTokenCostPriority: f64p(0.000001), CacheReadInputTokenCostFlex: f64p(2.5e-7),
		LongContextInputTokenThreshold: intp(272000),
		LongContextInputCostMultiplier: f64p(2), LongContextOutputCostMultiplier: f64p(1.5),
		SupportsPromptCaching:         true,
		SupportedServiceTiers:         []string{"priority", "flex"},
		SupportedReasoningEfforts:     []string{"none", "low", "medium", "high", "xhigh", "max"},
		CodexSupportedReasoningLevels: []string{"low", "medium", "high", "xhigh", "max", "ultra"},
		CodexDefaultReasoningLevel:    "low",
		CodexMultiAgentVersion:        "v2",
		SupportedAPIProtocols:         []string{"chat_completions", "responses"},
		InputModalities:               []string{"text", "image"},
		OutputModalities:              []string{"text"},
		SupportedTools:                gpt5ToolsGpt5Dot6,
	},
	{
		Model: "gpt-5.6-terra", Mode: "chat", CatalogOrder: intp(1), ReleaseDate: "2026-06-26",
		ContextWindowTokens: intp(1050000), MaxInputTokens: intp(922000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.000002), InputCostPerTokenPriority: f64p(0.000004), InputCostPerTokenFlex: f64p(0.000001),
		OutputCostPerToken: f64p(0.000012), OutputCostPerTokenPriority: f64p(0.000024), OutputCostPerTokenFlex: f64p(0.000006),
		CacheCreationInputTokenCost: f64p(0.0000025), CacheCreationInputTokenCostPriority: f64p(0.000005), CacheCreationInputTokenCostFlex: f64p(0.00000125),
		CacheReadInputTokenCost: f64p(2e-7), CacheReadInputTokenCostPriority: f64p(4e-7), CacheReadInputTokenCostFlex: f64p(1e-7),
		LongContextInputTokenThreshold: intp(272000),
		LongContextInputCostMultiplier: f64p(2), LongContextOutputCostMultiplier: f64p(1.5),
		SupportsPromptCaching:         true,
		SupportedServiceTiers:         []string{"priority", "flex"},
		SupportedReasoningEfforts:     []string{"none", "low", "medium", "high", "xhigh", "max"},
		CodexSupportedReasoningLevels: []string{"low", "medium", "high", "xhigh", "max", "ultra"},
		CodexDefaultReasoningLevel:    "medium",
		CodexMultiAgentVersion:        "v2",
		SupportedAPIProtocols:         []string{"chat_completions", "responses"},
		InputModalities:               []string{"text", "image"},
		OutputModalities:              []string{"text"},
		SupportedTools:                gpt5ToolsGpt5Dot6,
	},
	{
		Model: "gpt-5.6-luna", Mode: "chat", CatalogOrder: intp(2), ReleaseDate: "2026-06-26",
		ContextWindowTokens: intp(1050000), MaxInputTokens: intp(922000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(2e-7), InputCostPerTokenPriority: f64p(4e-7), InputCostPerTokenFlex: f64p(1e-7),
		OutputCostPerToken: f64p(0.0000012), OutputCostPerTokenPriority: f64p(0.0000024), OutputCostPerTokenFlex: f64p(6e-7),
		CacheCreationInputTokenCost: f64p(2.5e-7), CacheCreationInputTokenCostPriority: f64p(5e-7), CacheCreationInputTokenCostFlex: f64p(1.25e-7),
		CacheReadInputTokenCost: f64p(2e-8), CacheReadInputTokenCostPriority: f64p(4e-8), CacheReadInputTokenCostFlex: f64p(1e-8),
		LongContextInputTokenThreshold: intp(272000),
		LongContextInputCostMultiplier: f64p(2), LongContextOutputCostMultiplier: f64p(1.5),
		SupportsPromptCaching:         true,
		SupportedServiceTiers:         []string{"priority", "flex"},
		SupportedReasoningEfforts:     []string{"none", "low", "medium", "high", "xhigh", "max"},
		CodexSupportedReasoningLevels: []string{"low", "medium", "high", "xhigh", "max"},
		CodexDefaultReasoningLevel:    "medium",
		SupportedAPIProtocols:         []string{"chat_completions", "responses"},
		InputModalities:               []string{"text", "image"},
		OutputModalities:              []string{"text"},
		SupportedTools:                gpt5ToolsGpt5Dot6,
	},
	{
		Model: "gpt-5.5", Mode: "chat",
		MaxTokens: intp(128000), ContextWindowTokens: intp(1050000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.000005), InputCostPerTokenPriority: f64p(0.0000125), InputCostPerTokenFlex: f64p(0.0000025),
		OutputCostPerToken: f64p(0.00003), OutputCostPerTokenPriority: f64p(0.000075), OutputCostPerTokenFlex: f64p(0.000015),
		CacheReadInputTokenCost: f64p(5e-7), CacheReadInputTokenCostPriority: f64p(0.00000125), CacheReadInputTokenCostFlex: f64p(2.5e-7),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"none", "low", "medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"priority", "flex"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            gpt5ToolsGpt55,
	},
	{
		Model: "gpt-5.5-2026-04-23", Mode: "chat",
		MaxTokens: intp(128000), ContextWindowTokens: intp(1050000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.000005), InputCostPerTokenPriority: f64p(0.0000125), InputCostPerTokenFlex: f64p(0.0000025),
		OutputCostPerToken: f64p(0.00003), OutputCostPerTokenPriority: f64p(0.000075), OutputCostPerTokenFlex: f64p(0.000015),
		CacheReadInputTokenCost: f64p(5e-7), CacheReadInputTokenCostPriority: f64p(0.00000125), CacheReadInputTokenCostFlex: f64p(2.5e-7),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"none", "low", "medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"priority", "flex"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            gpt5ToolsGpt55,
	},
	{
		Model: "gpt-5.5-pro", Mode: "responses",
		MaxTokens: intp(128000), ContextWindowTokens: intp(1050000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.00003), InputCostPerTokenFlex: f64p(0.000015),
		OutputCostPerToken: f64p(0.00018), OutputCostPerTokenFlex: f64p(0.00009),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"flex"},
		SupportedAPIProtocols:     []string{"responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "hosted_shell", "mcp"},
	},
	{
		Model: "gpt-5.5-pro-2026-04-23", Mode: "responses",
		MaxTokens: intp(128000), ContextWindowTokens: intp(1050000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.00003), InputCostPerTokenFlex: f64p(0.000015),
		OutputCostPerToken: f64p(0.00018), OutputCostPerTokenFlex: f64p(0.00009),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"flex"},
		SupportedAPIProtocols:     []string{"responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "hosted_shell", "mcp"},
	},
	{
		Model: "gpt-5.4", Mode: "chat",
		MaxTokens: intp(128000), ContextWindowTokens: intp(1050000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.0000025), InputCostPerTokenPriority: f64p(0.000005), InputCostPerTokenFlex: f64p(0.00000125),
		OutputCostPerToken: f64p(0.000015), OutputCostPerTokenPriority: f64p(0.00003), OutputCostPerTokenFlex: f64p(0.0000075),
		CacheReadInputTokenCost: f64p(2.5e-7), CacheReadInputTokenCostPriority: f64p(5e-7), CacheReadInputTokenCostFlex: f64p(1.3e-7),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"none", "low", "medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"priority", "flex"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            gpt5ToolsGpt54Mini,
	},
	{
		Model: "gpt-5.4-2026-03-05", Mode: "chat",
		MaxTokens: intp(128000), ContextWindowTokens: intp(1050000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.0000025), InputCostPerTokenPriority: f64p(0.000005), InputCostPerTokenFlex: f64p(0.00000125),
		OutputCostPerToken: f64p(0.000015), OutputCostPerTokenPriority: f64p(0.00003), OutputCostPerTokenFlex: f64p(0.0000075),
		CacheReadInputTokenCost: f64p(2.5e-7), CacheReadInputTokenCostPriority: f64p(5e-7), CacheReadInputTokenCostFlex: f64p(1.3e-7),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"none", "low", "medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"priority", "flex"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            gpt5ToolsGpt54Mini,
	},
	{
		Model: "gpt-5.4-mini", Mode: "chat",
		MaxTokens: intp(128000), ContextWindowTokens: intp(400000), MaxInputTokens: intp(272000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(7.5e-7), InputCostPerTokenPriority: f64p(0.0000015), InputCostPerTokenFlex: f64p(3.75e-7),
		OutputCostPerToken: f64p(0.0000045), OutputCostPerTokenPriority: f64p(0.000009), OutputCostPerTokenFlex: f64p(0.00000225),
		CacheReadInputTokenCost: f64p(7.5e-8), CacheReadInputTokenCostPriority: f64p(1.5e-7), CacheReadInputTokenCostFlex: f64p(3.75e-8),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"none", "low", "medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"priority", "flex"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            gpt5ToolsGpt54Mini,
	},
	{
		Model: "gpt-5.4-mini-2026-03-17", Mode: "chat",
		MaxTokens: intp(128000), ContextWindowTokens: intp(400000), MaxInputTokens: intp(272000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(7.5e-7), InputCostPerTokenPriority: f64p(0.0000015), InputCostPerTokenFlex: f64p(3.75e-7),
		OutputCostPerToken: f64p(0.0000045), OutputCostPerTokenPriority: f64p(0.000009), OutputCostPerTokenFlex: f64p(0.00000225),
		CacheReadInputTokenCost: f64p(7.5e-8), CacheReadInputTokenCostPriority: f64p(1.5e-7), CacheReadInputTokenCostFlex: f64p(3.75e-8),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"none", "low", "medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"priority", "flex"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            gpt5ToolsGpt54Mini,
	},
	{
		Model: "gpt-5.4-nano", Mode: "chat",
		MaxTokens: intp(128000), ContextWindowTokens: intp(400000), MaxInputTokens: intp(272000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(2e-7), InputCostPerTokenFlex: f64p(1e-7),
		OutputCostPerToken: f64p(0.00000125), OutputCostPerTokenFlex: f64p(6.25e-7),
		CacheReadInputTokenCost: f64p(2e-8), CacheReadInputTokenCostFlex: f64p(1e-8),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"none", "low", "medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"flex"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            gpt5ToolsGpt54Nano,
	},
	{
		Model: "gpt-5.4-nano-2026-03-17", Mode: "chat",
		MaxTokens: intp(128000), ContextWindowTokens: intp(400000), MaxInputTokens: intp(272000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(2e-7), InputCostPerTokenFlex: f64p(1e-7),
		OutputCostPerToken: f64p(0.00000125), OutputCostPerTokenFlex: f64p(6.25e-7),
		CacheReadInputTokenCost: f64p(2e-8), CacheReadInputTokenCostFlex: f64p(1e-8),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"none", "low", "medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"flex"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            gpt5ToolsGpt54Nano,
	},
	{
		Model: "gpt-5.4-pro", Mode: "responses",
		MaxTokens: intp(128000), ContextWindowTokens: intp(1050000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.00003), InputCostPerTokenFlex: f64p(0.000015),
		OutputCostPerToken: f64p(0.00018), OutputCostPerTokenFlex: f64p(0.00009),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"flex"},
		SupportedAPIProtocols:     []string{"responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            gpt5ToolsProCodex543,
	},
	{
		Model: "gpt-5.4-pro-2026-03-05", Mode: "responses",
		MaxTokens: intp(128000), ContextWindowTokens: intp(1050000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.00003), InputCostPerTokenFlex: f64p(0.000015),
		OutputCostPerToken: f64p(0.00018), OutputCostPerTokenFlex: f64p(0.00009),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"flex"},
		SupportedAPIProtocols:     []string{"responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            gpt5ToolsProCodex543,
	},
	{
		Model: "gpt-5.3-codex", Mode: "responses",
		MaxTokens: intp(128000), ContextWindowTokens: intp(400000), MaxInputTokens: intp(272000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.00000175), InputCostPerTokenPriority: f64p(0.0000035),
		OutputCostPerToken: f64p(0.000014), OutputCostPerTokenPriority: f64p(0.000028),
		CacheReadInputTokenCost: f64p(1.75e-7), CacheReadInputTokenCostPriority: f64p(3.5e-7),
		SupportsPromptCaching:     true,
		SupportedServiceTiers:     []string{"priority"},
		SupportedAPIProtocols:     []string{"responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "web_search", "hosted_shell", "skills"},
		SupportedReasoningEfforts: []string{"low", "medium", "high", "xhigh"},
	},
	{
		Model: "gpt-5.2", Mode: "chat",
		MaxTokens: intp(128000), MaxInputTokens: intp(400000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.00000175), InputCostPerTokenPriority: f64p(0.0000035),
		OutputCostPerToken: f64p(0.000014), OutputCostPerTokenPriority: f64p(0.000028),
		CacheReadInputTokenCost: f64p(1.75e-7), CacheReadInputTokenCostPriority: f64p(3.5e-7),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"none", "low", "medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"priority"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "hosted_shell", "apply_patch", "skills", "mcp"},
	},
	{
		Model: "gpt-5.2-2025-12-11", Mode: "chat",
		MaxTokens: intp(128000), MaxInputTokens: intp(400000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.00000175), InputCostPerTokenPriority: f64p(0.0000035),
		OutputCostPerToken: f64p(0.000014), OutputCostPerTokenPriority: f64p(0.000028),
		CacheReadInputTokenCost: f64p(1.75e-7), CacheReadInputTokenCostPriority: f64p(3.5e-7),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"none", "low", "medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"priority"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "hosted_shell", "apply_patch", "skills", "mcp"},
	},
	{
		Model: "gpt-5.2-pro", Mode: "responses",
		MaxTokens: intp(128000), MaxInputTokens: intp(400000), MaxOutputTokens: intp(128000),
		InputCostPerToken:         f64p(0.000021),
		OutputCostPerToken:        f64p(0.000168),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"priority"},
		SupportedAPIProtocols:     []string{"responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "file_search", "image_generation", "mcp", "web_search"},
	},
	{
		Model: "gpt-5.2-pro-2025-12-11", Mode: "responses",
		MaxTokens: intp(128000), MaxInputTokens: intp(400000), MaxOutputTokens: intp(128000),
		InputCostPerToken:         f64p(0.000021),
		OutputCostPerToken:        f64p(0.000168),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"medium", "high", "xhigh"},
		SupportedServiceTiers:     []string{"priority"},
		SupportedAPIProtocols:     []string{"responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "file_search", "image_generation", "mcp", "web_search"},
	},
	{
		Model: "gpt-5.1", Mode: "chat",
		MaxTokens: intp(128000), MaxInputTokens: intp(400000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.00000125), InputCostPerTokenPriority: f64p(0.0000025),
		OutputCostPerToken: f64p(0.00001), OutputCostPerTokenPriority: f64p(0.00002),
		CacheReadInputTokenCost: f64p(1.25e-7), CacheReadInputTokenCostPriority: f64p(2.5e-7),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"none", "low", "medium", "high"},
		SupportedServiceTiers:     []string{"priority"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "apply_patch", "mcp"},
	},
	{
		Model: "gpt-5.1-2025-11-13", Mode: "chat",
		MaxTokens: intp(128000), MaxInputTokens: intp(400000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.00000125), InputCostPerTokenPriority: f64p(0.0000025),
		OutputCostPerToken: f64p(0.00001), OutputCostPerTokenPriority: f64p(0.00002),
		CacheReadInputTokenCost: f64p(1.25e-7), CacheReadInputTokenCostPriority: f64p(2.5e-7),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"none", "low", "medium", "high"},
		SupportedServiceTiers:     []string{"priority"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "apply_patch", "mcp"},
	},
	{
		Model: "gpt-5", Mode: "chat",
		MaxTokens: intp(128000), ContextWindowTokens: intp(400000), MaxInputTokens: intp(272000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.00000125), InputCostPerTokenPriority: f64p(0.0000025),
		OutputCostPerToken: f64p(0.00001), OutputCostPerTokenPriority: f64p(0.00002),
		CacheReadInputTokenCost: f64p(1.25e-7), CacheReadInputTokenCostPriority: f64p(2.5e-7),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"minimal", "low", "medium", "high"},
		SupportedServiceTiers:     []string{"priority", "flex"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "mcp"},
	},
	{
		Model: "gpt-5-2025-08-07", Mode: "chat",
		MaxTokens: intp(128000), ContextWindowTokens: intp(400000), MaxInputTokens: intp(272000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(0.00000125), InputCostPerTokenPriority: f64p(0.0000025),
		OutputCostPerToken: f64p(0.00001), OutputCostPerTokenPriority: f64p(0.00002),
		CacheReadInputTokenCost: f64p(1.25e-7), CacheReadInputTokenCostPriority: f64p(2.5e-7),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"minimal", "low", "medium", "high"},
		SupportedServiceTiers:     []string{"priority", "flex"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "mcp"},
	},
	{
		Model: "gpt-5-mini", Mode: "chat",
		MaxTokens: intp(128000), ContextWindowTokens: intp(400000), MaxInputTokens: intp(272000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(2.5e-7), InputCostPerTokenPriority: f64p(4.5e-7),
		OutputCostPerToken: f64p(0.000002), OutputCostPerTokenPriority: f64p(0.0000036),
		CacheReadInputTokenCost: f64p(2.5e-8), CacheReadInputTokenCostPriority: f64p(4.5e-8),
		SupportsPromptCaching:     true,
		SupportedServiceTiers:     []string{"priority", "flex"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "web_search", "file_search", "code_interpreter", "mcp"},
		SupportedReasoningEfforts: []string{"minimal", "low", "medium", "high"},
	},
	{
		Model: "gpt-5-mini-2025-08-07", Mode: "chat",
		MaxTokens: intp(128000), ContextWindowTokens: intp(400000), MaxInputTokens: intp(272000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(2.5e-7), InputCostPerTokenPriority: f64p(4.5e-7),
		OutputCostPerToken: f64p(0.000002), OutputCostPerTokenPriority: f64p(0.0000036),
		CacheReadInputTokenCost: f64p(2.5e-8), CacheReadInputTokenCostPriority: f64p(4.5e-8),
		SupportsPromptCaching:     true,
		SupportedServiceTiers:     []string{"priority", "flex"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "web_search", "file_search", "code_interpreter", "mcp"},
		SupportedReasoningEfforts: []string{"minimal", "low", "medium", "high"},
	},
	{
		Model: "gpt-5-nano", Mode: "chat",
		MaxTokens: intp(128000), ContextWindowTokens: intp(400000), MaxInputTokens: intp(272000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(5e-8), InputCostPerTokenPriority: f64p(2e-7),
		OutputCostPerToken: f64p(4e-7), OutputCostPerTokenPriority: f64p(8e-7),
		CacheReadInputTokenCost: f64p(5e-9), CacheReadInputTokenCostPriority: f64p(5e-8),
		SupportsPromptCaching:     true,
		SupportedServiceTiers:     []string{"priority", "flex"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "mcp"},
		SupportedReasoningEfforts: []string{"minimal", "low", "medium", "high"},
	},
	{
		Model: "gpt-5-nano-2025-08-07", Mode: "chat",
		MaxTokens: intp(128000), ContextWindowTokens: intp(400000), MaxInputTokens: intp(272000), MaxOutputTokens: intp(128000),
		InputCostPerToken: f64p(5e-8), InputCostPerTokenPriority: f64p(2e-7),
		OutputCostPerToken: f64p(4e-7), OutputCostPerTokenPriority: f64p(8e-7),
		CacheReadInputTokenCost: f64p(5e-9), CacheReadInputTokenCostPriority: f64p(5e-8),
		SupportsPromptCaching:     true,
		SupportedServiceTiers:     []string{"priority", "flex"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "web_search", "file_search", "image_generation", "code_interpreter", "mcp"},
		SupportedReasoningEfforts: []string{"minimal", "low", "medium", "high"},
	},
	{
		Model: "gpt-5-pro", Mode: "responses",
		MaxTokens: intp(128000), ContextWindowTokens: intp(400000), MaxOutputTokens: intp(272000),
		InputCostPerToken:         f64p(0.000015),
		OutputCostPerToken:        f64p(0.00012),
		SupportsPromptCaching:     true,
		SupportedServiceTiers:     []string{"priority"},
		SupportedAPIProtocols:     []string{"responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "file_search", "image_generation", "mcp", "web_search"},
		SupportedReasoningEfforts: []string{"high"},
	},
	{
		Model: "gpt-5-pro-2025-10-06", Mode: "responses",
		MaxTokens: intp(128000), ContextWindowTokens: intp(400000), MaxOutputTokens: intp(272000),
		InputCostPerToken:         f64p(0.000015),
		OutputCostPerToken:        f64p(0.00012),
		SupportsPromptCaching:     true,
		SupportedServiceTiers:     []string{"priority"},
		SupportedAPIProtocols:     []string{"responses"},
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedTools:            []string{"function_calling", "file_search", "image_generation", "mcp", "web_search"},
		SupportedReasoningEfforts: []string{"high"},
	},
}

// openAIImageModelPricingData — image generation models, curated 2026-07-24.
var openAIImageModelPricingData = []rawModel{
	{
		Model: "gpt-image-2", Mode: "image_generation",
		InputModalities:              []string{"text", "image"},
		OutputModalities:             []string{"image"},
		SupportedAPIProtocols:        []string{"images"},
		InputCostPerToken:            f64p(0.000005),
		CacheReadInputTokenCost:      f64p(0.00000125),
		InputCostPerImageToken:       f64p(0.000008),
		CacheReadInputImageTokenCost: f64p(0.000002),
		OutputCostPerImageToken:      f64p(0.00003),
		SupportsPromptCaching:        true,
	},
	{
		Model: "gpt-image-2-2026-04-21", Mode: "image_generation",
		InputModalities:              []string{"text", "image"},
		OutputModalities:             []string{"image"},
		SupportedAPIProtocols:        []string{"images"},
		InputCostPerToken:            f64p(0.000005),
		CacheReadInputTokenCost:      f64p(0.00000125),
		InputCostPerImageToken:       f64p(0.000008),
		CacheReadInputImageTokenCost: f64p(0.000002),
		OutputCostPerImageToken:      f64p(0.00003),
		SupportsPromptCaching:        true,
	},
	{
		Model: "gpt-image-1.5", Mode: "image_generation",
		InputModalities:              []string{"text", "image"},
		OutputModalities:             []string{"image", "text"},
		SupportedAPIProtocols:        []string{"images"},
		InputCostPerToken:            f64p(0.000005),
		OutputCostPerToken:           f64p(0.00001),
		CacheReadInputTokenCost:      f64p(0.00000125),
		InputCostPerImageToken:       f64p(0.000008),
		CacheReadInputImageTokenCost: f64p(0.000002),
		OutputCostPerImageToken:      f64p(0.000032),
		SupportsPromptCaching:        true,
		ShutdownDate:                 "2026-12-01",
	},
	{
		Model: "gpt-image-1-mini", Mode: "image_generation",
		InputModalities:              []string{"text", "image"},
		OutputModalities:             []string{"image", "text"},
		SupportedAPIProtocols:        []string{"images"},
		InputCostPerToken:            f64p(0.000002),
		CacheReadInputTokenCost:      f64p(2e-7),
		InputCostPerImageToken:       f64p(0.0000025),
		CacheReadInputImageTokenCost: f64p(2.5e-7),
		OutputCostPerImageToken:      f64p(0.000008),
		SupportsPromptCaching:        true,
		ShutdownDate:                 "2026-12-01",
	},
	{
		Model: "gpt-image-1", Mode: "image_generation",
		InputModalities:              []string{"text", "image"},
		OutputModalities:             []string{"image"},
		SupportedAPIProtocols:        []string{"images", "responses"},
		InputCostPerToken:            f64p(0.000005),
		CacheReadInputTokenCost:      f64p(0.00000125),
		InputCostPerImageToken:       f64p(0.00001),
		CacheReadInputImageTokenCost: f64p(0.0000025),
		OutputCostPerImageToken:      f64p(0.00004),
		SupportsPromptCaching:        true,
		ShutdownDate:                 "2026-10-23",
	},
}

// openAIReasoningModelPricingData — o-series models, curated 2026-07-13.
var openAIReasoningModelPricingData = []rawModel{
	{
		Model: "o1", Mode: "chat",
		MaxTokens: intp(100000), ContextWindowTokens: intp(200000), MaxOutputTokens: intp(100000),
		InputModalities:           []string{"text", "image"},
		OutputModalities:          []string{"text"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		SupportedTools:            []string{"function_calling", "file_search", "mcp"},
		InputCostPerToken:         f64p(0.000015),
		OutputCostPerToken:        f64p(0.00006),
		CacheReadInputTokenCost:   f64p(0.0000075),
		ShutdownDate:              "2026-10-23",
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"low", "medium", "high"},
	},
	{
		Model: "o1-pro", Mode: "responses",
		MaxTokens: intp(100000), ContextWindowTokens: intp(200000), MaxOutputTokens: intp(100000),
		InputModalities:       []string{"text", "image"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"responses"},
		SupportedTools:        []string{"function_calling", "file_search", "mcp"},
		InputCostPerToken:     f64p(0.00015),
		OutputCostPerToken:    f64p(0.0006),
		ShutdownDate:          "2026-10-23",
		SupportsPromptCaching: true,
	},
	{
		Model: "o3", Mode: "chat",
		MaxTokens: intp(100000), ContextWindowTokens: intp(200000), MaxOutputTokens: intp(100000),
		InputModalities:       []string{"text", "image"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions", "responses"},
		SupportedTools:        []string{"function_calling", "file_search", "image_generation", "code_interpreter", "mcp", "web_search"},
		InputCostPerToken:     f64p(0.000002), InputCostPerTokenPriority: f64p(0.0000035),
		OutputCostPerToken: f64p(0.000008), OutputCostPerTokenPriority: f64p(0.000014),
		CacheReadInputTokenCost: f64p(5e-7), CacheReadInputTokenCostPriority: f64p(8.75e-7),
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"low", "medium", "high"},
		SupportedServiceTiers:     []string{"priority", "flex"},
	},
	{
		Model: "o3-pro", Mode: "responses",
		MaxTokens: intp(100000), ContextWindowTokens: intp(200000), MaxOutputTokens: intp(100000),
		InputModalities:       []string{"text", "image"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"responses"},
		SupportedTools:        []string{"function_calling", "file_search", "image_generation", "mcp", "web_search"},
		InputCostPerToken:     f64p(0.00002),
		OutputCostPerToken:    f64p(0.00008),
		SupportsPromptCaching: true,
	},
	{
		Model: "o3-mini", Mode: "chat",
		MaxTokens: intp(100000), ContextWindowTokens: intp(200000), MaxOutputTokens: intp(100000),
		InputModalities:           []string{"text"},
		OutputModalities:          []string{"text"},
		SupportedAPIProtocols:     []string{"chat_completions", "responses"},
		SupportedTools:            []string{"function_calling", "file_search", "code_interpreter", "mcp", "image_generation"},
		InputCostPerToken:         f64p(0.0000011),
		OutputCostPerToken:        f64p(0.0000044),
		CacheReadInputTokenCost:   f64p(5.5e-7),
		ShutdownDate:              "2026-10-23",
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"low", "medium", "high"},
	},
	{
		Model: "o4-mini", Mode: "chat",
		MaxTokens: intp(100000), ContextWindowTokens: intp(200000), MaxOutputTokens: intp(100000),
		InputModalities:       []string{"text", "image"},
		OutputModalities:      []string{"text"},
		SupportedAPIProtocols: []string{"chat_completions", "responses"},
		SupportedTools:        []string{"function_calling", "file_search", "code_interpreter", "mcp", "web_search"},
		InputCostPerToken:     f64p(0.0000011), InputCostPerTokenPriority: f64p(0.000002),
		OutputCostPerToken: f64p(0.0000044), OutputCostPerTokenPriority: f64p(0.000008),
		CacheReadInputTokenCost: f64p(2.75e-7), CacheReadInputTokenCostPriority: f64p(5e-7),
		ShutdownDate:              "2026-10-23",
		SupportsPromptCaching:     true,
		SupportedReasoningEfforts: []string{"low", "medium", "high"},
		SupportedServiceTiers:     []string{"priority", "flex"},
	},
}
