package pricing

// GLM pricing snapshot, ported from
// backend/src/modules/model-pricing/glm-model-pricing.data.ts (curated
// 2026-08-26). Free models carry explicit zero prices, which stay real
// (non-undefined) prices in the billing semantics.
var glmModelPricingData = []rawModel{
	{
		Model: "glm-5.3", Mode: "chat", CatalogOrder: intp(0), ReleaseDate: "2026-08-18",
		InputCostPerToken: perToken(1.4), CacheReadInputTokenCost: perToken(0.26), OutputCostPerToken: perToken(4.4),
		ContextWindowTokens: intp(1_000_000), MaxOutputTokens: intp(128_000),
		SupportedAPIProtocols:     []string{"chat_completions"},
		SupportsPromptCaching:     true,
		InputModalities:           []string{"text"},
		OutputModalities:          []string{"text"},
		SupportedReasoningEfforts: []string{"low", "high", "max"},
		DefaultReasoningEffort:    "max",
	},
	{
		Model: "glm-5.2", Mode: "chat", CatalogOrder: intp(10), ReleaseDate: "2026-06-16",
		InputCostPerToken: perToken(1.4), CacheReadInputTokenCost: perToken(0.26), OutputCostPerToken: perToken(4.4),
		ContextWindowTokens: intp(1_000_000), MaxOutputTokens: intp(128_000),
		SupportedAPIProtocols:     []string{"chat_completions"},
		SupportsPromptCaching:     true,
		InputModalities:           []string{"text"},
		OutputModalities:          []string{"text"},
		SupportedReasoningEfforts: []string{"high", "max"},
		DefaultReasoningEffort:    "max",
	},
	{
		Model: "glm-5.1", Mode: "chat", CatalogOrder: intp(20), ReleaseDate: "2026-04-07",
		InputCostPerToken: perToken(1.4), CacheReadInputTokenCost: perToken(0.26), OutputCostPerToken: perToken(4.4),
		ContextWindowTokens: intp(200_000), MaxOutputTokens: intp(128_000),
		SupportedAPIProtocols: []string{"chat_completions"},
		SupportsPromptCaching: true,
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
	},
	{
		Model: "glm-5", Mode: "chat", CatalogOrder: intp(30), ReleaseDate: "2026-02-12",
		InputCostPerToken: perToken(1.0), CacheReadInputTokenCost: perToken(0.2), OutputCostPerToken: perToken(3.2),
		ContextWindowTokens: intp(200_000), MaxOutputTokens: intp(128_000),
		SupportedAPIProtocols: []string{"chat_completions"},
		SupportsPromptCaching: true,
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
	},
	{
		Model: "glm-5-turbo", Mode: "chat", CatalogOrder: intp(40), ReleaseDate: "2026-03-16",
		InputCostPerToken: perToken(1.2), CacheReadInputTokenCost: perToken(0.24), OutputCostPerToken: perToken(4.0),
		ContextWindowTokens: intp(200_000), MaxOutputTokens: intp(128_000),
		SupportedAPIProtocols: []string{"chat_completions"},
		SupportsPromptCaching: true,
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
	},
	{
		Model: "glm-4.7", Mode: "chat", CatalogOrder: intp(50), ReleaseDate: "2025-12-22",
		InputCostPerToken: perToken(0.6), CacheReadInputTokenCost: perToken(0.11), OutputCostPerToken: perToken(2.2),
		ContextWindowTokens: intp(200_000), MaxOutputTokens: intp(131_072),
		SupportedAPIProtocols: []string{"chat_completions"},
		SupportsPromptCaching: true,
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
	},
	{
		Model: "glm-4.7-flashx", Mode: "chat", CatalogOrder: intp(60), ReleaseDate: "2025-12-22",
		InputCostPerToken: perToken(0.07), CacheReadInputTokenCost: perToken(0.01), OutputCostPerToken: perToken(0.4),
		ContextWindowTokens: intp(200_000), MaxOutputTokens: intp(131_072),
		SupportedAPIProtocols: []string{"chat_completions"},
		SupportsPromptCaching: true,
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
	},
	{
		Model: "glm-4.7-flash", Mode: "chat", CatalogOrder: intp(70), ReleaseDate: "2025-12-22",
		InputCostPerToken: f64p(0), CacheReadInputTokenCost: f64p(0), OutputCostPerToken: f64p(0),
		ContextWindowTokens: intp(200_000), MaxOutputTokens: intp(131_072),
		SupportedAPIProtocols: []string{"chat_completions"},
		SupportsPromptCaching: true,
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
	},
	{
		Model: "glm-4.6", Mode: "chat", CatalogOrder: intp(80), ReleaseDate: "2025-09-30",
		InputCostPerToken: perToken(0.6), CacheReadInputTokenCost: perToken(0.11), OutputCostPerToken: perToken(2.2),
		ContextWindowTokens: intp(200_000), MaxOutputTokens: intp(131_072),
		SupportedAPIProtocols: []string{"chat_completions"},
		SupportsPromptCaching: true,
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
	},
	{
		Model: "glm-4.5", Mode: "chat", CatalogOrder: intp(90), ReleaseDate: "2025-07-28",
		InputCostPerToken: perToken(0.6), CacheReadInputTokenCost: perToken(0.11), OutputCostPerToken: perToken(2.2),
		ContextWindowTokens: intp(128_000), MaxOutputTokens: intp(98_304),
		SupportedAPIProtocols: []string{"chat_completions"},
		SupportsPromptCaching: true,
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
	},
	{
		Model: "glm-4.5-x", Mode: "chat", CatalogOrder: intp(100), ReleaseDate: "2025-07-28",
		InputCostPerToken: perToken(2.2), CacheReadInputTokenCost: perToken(0.45), OutputCostPerToken: perToken(8.9),
		ContextWindowTokens: intp(128_000), MaxOutputTokens: intp(98_304),
		SupportedAPIProtocols: []string{"chat_completions"},
		SupportsPromptCaching: true,
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
	},
	{
		Model: "glm-4.5-air", Mode: "chat", CatalogOrder: intp(110), ReleaseDate: "2025-07-28",
		InputCostPerToken: perToken(0.2), CacheReadInputTokenCost: perToken(0.03), OutputCostPerToken: perToken(1.1),
		ContextWindowTokens: intp(128_000), MaxOutputTokens: intp(98_304),
		SupportedAPIProtocols: []string{"chat_completions"},
		SupportsPromptCaching: true,
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
	},
	{
		Model: "glm-4.5-airx", Mode: "chat", CatalogOrder: intp(120), ReleaseDate: "2025-07-28",
		InputCostPerToken: perToken(1.1), CacheReadInputTokenCost: perToken(0.22), OutputCostPerToken: perToken(4.5),
		ContextWindowTokens: intp(128_000), MaxOutputTokens: intp(98_304),
		SupportedAPIProtocols: []string{"chat_completions"},
		SupportsPromptCaching: true,
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
	},
	{
		Model: "glm-4.5-flash", Mode: "chat", CatalogOrder: intp(130), ReleaseDate: "2025-07-28",
		InputCostPerToken: f64p(0), CacheReadInputTokenCost: f64p(0), OutputCostPerToken: f64p(0),
		ContextWindowTokens: intp(128_000), MaxOutputTokens: intp(98_304),
		SupportedAPIProtocols: []string{"chat_completions"},
		SupportsPromptCaching: true,
		InputModalities:       []string{"text"},
		OutputModalities:      []string{"text"},
	},
}
