package pricing

// seedgen —— 种子自动生成（计划-20261005T230500000Z 步骤 4）：catalogdata/
// *.json 是唯一数据源，本生成器经 toProviderModelPricing 投影输出
// maintenance 的 39 列种子 Go 源码（model_catalog_data_gen.go，Code
// generated 头）。跨模块不 import：生成的是文本，ID 列输出
// providerModelCatalogID("provider", "model") 调用表达式，由 maintenance
// 的同算法函数保证一致。受 JUHE_AI_GENERATE_SEED=1 触发（开发机一次性
// 工具，生产不参与）。
//
// 已知与手写种子的预期差异（切换时人工核对）：
//   - deepseek-v4-flash 手写残留行消失（计价层已删、种子漏删）
//   - xai 行 Source 统一为 entry 级 pricingSource（手写存在
//     xai-official-pricing-2026-07-18 行级双轨，顺带收敛）
import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"testing"
)

var seedGenProviders = []string{"gpt", "deepseek", "anthropic", "gemini", "glm", "minimax", "volcengine", "qwen", "xai"}

// seedTierKeyOrder 固定 tier JSON 键序（手写种子 priority 在前的既有口径）。
var seedTierKeyOrder = []string{"priority", "flex", "batch"}

func TestGenerateSeedCatalog(t *testing.T) {
	if os.Getenv("JUHE_AI_GENERATE_SEED") != "1" {
		t.Skip("set JUHE_AI_GENERATE_SEED=1 to regenerate model_catalog_data_gen.go")
	}
	type rowOut struct {
		model string
		line  string
	}
	var b strings.Builder
	b.WriteString(`// Code generated by pricing.TestGenerateSeedCatalog (JUHE_AI_GENERATE_SEED=1). DO NOT EDIT.
// 数据源：backend-go/projects/gateway/internal/pricing/catalogdata/*.json
// （模型目录 JSON 单一数据源，计划-20261005T230500000Z）。改价改 JSON 后重跑
// 生成器；本文件与 JSON 的漂移由种子一致性校验钉住。

package schema

var modelCatalogSeedRows = []modelCatalogSeedRow{
`)
	total := 0
	for _, provider := range seedGenProviders {
		entry := providerEntryFor(provider)
		if entry == nil {
			t.Fatalf("provider entry %q not found", provider)
		}
		// 行序 = nodeModelCatalogCompare（catalogOrder 升序 → releaseDate
		// 降序 → model 字典序），与排序门禁一致；纯字典序会错排日期后缀
		// 行（gpt-3.5-turbo vs gpt-3.5-turbo-0125 实证）。
		pricings := make([]*Pricing, 0, len(entry.rawModels))
		for index := range entry.rawModels {
			pricings = append(pricings, toProviderModelPricing(&entry.rawModels[index], entry, provider))
			total++
		}
		sort.SliceStable(pricings, func(left, right int) bool {
			return compareProviderModels(pricings[left], pricings[right]) < 0
		})
		for _, pricing := range pricings {
			b.WriteString("\t" + seedRowLiteral(provider, pricing) + "\n")
		}
	}
	b.WriteString("}\n")
	target := filepath.Join("..", "..", "..", "maintenance", "internal", "schema", "model_catalog_data_gen.go")
	if err := os.WriteFile(target, []byte(b.String()), 0o644); err != nil {
		t.Fatalf("write %s: %v", target, err)
	}
	t.Logf("wrote %s (%d rows)", target, total)
}

// seedRowLiteral 把一行 Pricing 投影文本化为 modelCatalogSeedRow 字面量
// （39 列；列序与手写种子一致）。
func seedRowLiteral(provider string, p *Pricing) string {
	strPtr := func(v string) string {
		if v == "" {
			return "nil"
		}
		return "seedStrPtr(" + strconv.Quote(v) + ")"
	}
	int64Ptr := func(v *int) string {
		if v == nil {
			return "nil"
		}
		return "seedInt64Ptr(" + strconv.Itoa(*v) + ")"
	}
	f64Ptr := func(v *float64) string {
		if v == nil {
			return "nil"
		}
		return "seedFloat64Ptr(" + formatSeedFloat(*v) + ")"
	}
	marshalJSON := func(value any) string {
		// nil 切片 JSON 序列化为 null；种子口径是显式空数组 "[]"。
		if value != nil {
			if rv := reflect.ValueOf(value); rv.Kind() == reflect.Slice && rv.IsNil() {
				return strconv.Quote("[]")
			}
		}
		encoded, err := jsonMarshalCompact(value)
		if err != nil {
			panic(err)
		}
		return strconv.Quote(encoded)
	}
	tierJSON := func() string {
		if len(p.ServiceTierPrices) == 0 {
			return `"{}"`
		}
		keys := make([]string, 0, len(p.ServiceTierPrices))
		for key := range p.ServiceTierPrices {
			keys = append(keys, key)
		}
		sort.Slice(keys, func(left, right int) bool {
			rank := func(k string) int {
				for index, known := range seedTierKeyOrder {
					if k == known {
						return index
					}
				}
				return len(seedTierKeyOrder)
			}
			return rank(keys[left]) < rank(keys[right])
		})
		segments := make([]string, 0, len(keys))
		for _, key := range keys {
			// tier 内字段 = PriceSet 非 null 全集（键名 = 字段名首字母小写；
			// 手写种子 gpt 行的 cacheWrite 与 gemini 行的 cacheStorage/
			// audioInput 同一规则），固定按 PriceSet 声明序输出。
			segments = append(segments, strconv.Quote(key)+":{"+priceSetJSONFields(p.ServiceTierPrices[key])+"}")
		}
		return strconv.Quote("{" + strings.Join(segments, ",") + "}")
	}
	fields := []string{
		"ID: " + fmt.Sprintf("providerModelCatalogID(%s, %s)", strconv.Quote(provider), strconv.Quote(p.Model)),
		"ProviderCode: " + strconv.Quote(provider),
		"Model: " + strconv.Quote(p.Model),
		"Mode: " + strPtr(p.Mode),
		"CatalogOrder: " + int64Ptr(p.CatalogOrder),
		"ReleaseDate: " + strPtr(p.ReleaseDate),
		"ShutdownDate: " + strPtr(p.ShutdownDate),
		"SupportedAPIProtocolsJSON: " + marshalJSON(p.SupportedAPIProtocols),
		"SupportedServiceTiersJSON: " + marshalJSON(p.SupportedServiceTiers),
		"SupportedReasoningEffortsJSON: " + marshalJSON(p.SupportedReasoningEfforts),
		"DefaultReasoningEffort: " + strPtr(p.DefaultReasoningEffort),
		"CodexSupportedReasoningLevelsJSON: " + marshalJSON(p.CodexSupportedReasoningLevels),
		"CodexDefaultReasoningLevel: " + strPtr(p.CodexDefaultReasoningLevel),
		"CodexMultiAgentVersion: " + strPtr(p.CodexMultiAgentVersion),
		"ContextWindowTokens: " + int64Ptr(p.ContextWindowTokens),
		"MaxInputTokens: " + int64Ptr(p.MaxInputTokens),
		"MaxOutputTokens: " + int64Ptr(p.MaxOutputTokens),
		"MaxTokens: " + int64Ptr(p.MaxTokens),
		"InputUsdPer1M: " + f64Ptr(p.InputUsdPer1M),
		"OutputUsdPer1M: " + f64Ptr(p.OutputUsdPer1M),
		"CachedInputUsdPer1M: " + f64Ptr(p.CachedInputUsdPer1M),
		"CacheWriteUsdPer1M: " + f64Ptr(p.CacheWriteUsdPer1M),
		"CacheWrite1HUsdPer1M: " + f64Ptr(p.CacheWrite1hUsdPer1M),
		"CacheStorageUsdPer1MPerHour: " + f64Ptr(p.CacheStorageUsdPer1MPerHour),
		"ServiceTierPricesJSON: " + tierJSON(),
		"LongContextInputTokenThreshold: " + int64Ptr(p.LongContextInputTokenThreshold),
		fmt.Sprintf("LongContextInputTokenThresholdInclusive: %v", p.LongContextInputTokenThresholdInclusive),
		"LongContextInputCostMultiplier: " + f64Ptr(p.LongContextInputCostMultiplier),
		"LongContextOutputCostMultiplier: " + f64Ptr(p.LongContextOutputCostMultiplier),
		"ImageInputUsdPer1M: " + f64Ptr(p.ImageInputUsdPer1M),
		"ImageOutputUsdPer1M: " + f64Ptr(p.ImageOutputUsdPer1M),
		"AudioInputUsdPer1M: " + f64Ptr(p.AudioInputUsdPer1M),
		"AudioOutputUsdPer1M: " + f64Ptr(p.AudioOutputUsdPer1M),
		"OutputUsdPerImage: " + f64Ptr(p.OutputUsdPerImage),
		fmt.Sprintf("SupportsPromptCaching: %v", p.SupportsPromptCaching),
		fmt.Sprintf("CatalogVisible: %v", p.CatalogVisible),
		"Source: " + strconv.Quote(p.Source),
	}
	return "{" + strings.Join(fields, ", ") + "},"
}

// priceSetJSONFields 输出 PriceSet 非 null 字段的 JSON 片段（按声明序）。
func priceSetJSONFields(set PriceSet) string {
	value := reflect.ValueOf(set)
	typ := value.Type()
	parts := make([]string, 0, typ.NumField())
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		if value.Field(i).IsNil() {
			continue
		}
		key := strings.ToLower(field.Name[:1]) + field.Name[1:]
		parts = append(parts, strconv.Quote(key)+":"+jsonNumber(value.Field(i).Interface().(*float64)))
	}
	return strings.Join(parts, ",")
}

func formatSeedFloat(v float64) string {
	return strconv.FormatFloat(v, 'f', -1, 64)
}

func jsonMarshalCompact(value any) (string, error) {
	encoded, err := json.Marshal(value)
	if err != nil {
		return "", err
	}
	return string(encoded), nil
}

// jsonNumber 输出 JSON 数字字面量（null 或最短 float 表示，JSON round-trip
// 与 float64 位精确一致）。
func jsonNumber(v *float64) string {
	if v == nil {
		return "null"
	}
	return formatSeedFloat(*v)
}
