// defaults.go mirrors storage/schema-defaults.ts DEFAULT_SYSTEM_SETTINGS
// (lines 585-655): the seeded system_settings key/value pairs the jobs read
// model falls back to when a row is missing or the store is not initialized.
// Numeric entries stay numbers (settingsNumber validates them as integers);
// usageStatsTimezone keeps its string value — Node seeds the host timezone
// (Intl.DateTimeFormat().resolvedOptions()) and deployments with a configured
// timezone always carry an explicit row, so UTC is the safe static fallback.
package jobssettings

// DefaultSystemSettings mirrors DEFAULT_SYSTEM_SETTINGS.
var DefaultSystemSettings = map[string]any{
	"gatewayTextRawBodyLimitMegabytes":           float64(16),
	"accountCircuitConfirmationFailuresRequired": float64(2),
	"gatewayUserRequestLimitPerMinute":           float64(0),
	"gatewayUserRequestLimitPerDay":              float64(0),
	"gatewayUserRequestLimitPerWeek":             float64(0),
	"gatewayUserRequestLimitPerMonth":            float64(0),
	"userAiAccountLimit":                         float64(100),
	"systemApiRateLimitIpReadPerMinute":          float64(600),
	"systemApiRateLimitIpReadBurstPer10Seconds":  float64(120),
	"systemApiRateLimitIpWritePerMinute":         float64(180),
	"systemApiRateLimitIpWriteBurstPer10Seconds": float64(40),
	"systemApiRateLimitUserReadPerMinute":        float64(300),
	"systemApiRateLimitUserWritePerMinute":       float64(120),
	"defaultTemporaryUnschedulableMinutes":       float64(2),
	"temporaryUnschedulableRetryIntervalSeconds": float64(3),
	"temporaryUnschedulableRetryAttempts":        float64(2),
	"textFirstResponseTimeoutSeconds":            float64(120),
	"textStreamIdleTimeoutSeconds":               float64(30),
	"textUncommittedAttemptMaxLifetimeSeconds":   float64(1800),
	"imageFirstResponseTimeoutSeconds":           float64(600),
	"imageStreamIdleTimeoutSeconds":              float64(120),
	"imageUncommittedAttemptMaxLifetimeSeconds":  float64(3600),
	"imageRequestWallTimeoutSeconds":             float64(3600),
	"chatImageGenerationTotalTimeoutSeconds":     float64(900),
	"noAvailableAccountWaitTimeoutSeconds":       float64(270),
	"streamFailureThresholdCount":                float64(3),
	"streamFailureThresholdWindowMinutes":        float64(5),
	"operationLogRetentionDays":                  float64(365),
	"operationLogMaxChangesPerRecord":            float64(100),
	"statsAggregationIntervalSeconds":            float64(60),
	"statsAggregationBatchSize":                  float64(2000),
	"statsAggregationMaxBatchesPerRun":           float64(5),
	"usageHotWindowRefreshIntervalSeconds":       float64(600),
	"groupAccountStatsRefreshIntervalSeconds":    float64(60),
	"systemMetricsSampleIntervalSeconds":         float64(30),
	"tableMonitorMaxTablesPerRun":                float64(4),
	"accountQualityRefreshIntervalSeconds":       float64(600),
	"accountQualityWindowMinutes":                float64(10),
	"accountHealthCheckIntervalHours":            float64(1),
	"accountHealthCheckJitterMinutes":            float64(10),
	"accountHealthCheckFailureThreshold":         float64(3),
	"cooldownAccountRetestIntervalSeconds":       float64(3),
	"cooldownAccountRetestMaxBackoffHours":       float64(12),
	"oauthAccessTokenRefreshIntervalSeconds":     float64(60),
	"oauthAccessTokenRefreshLeadSeconds":         float64(300),
	"oauthAccessTokenRefreshBatchSize":           float64(20),
	"oauthAccessTokenRefreshRetryBackoffSeconds": float64(300),
	"modelCheckRetentionDays":                    float64(30),
	"runtimeLogIndexRetentionDays":               float64(14),
	"publicApiLogRetentionDays":                  float64(30),
	"usageRecordRetentionDays":                   float64(30),
	"usageStatsTimezone":                         "UTC",
	"usageStatsMinuteRetentionHours":             float64(48),
	"usageStatsHourlyRetentionDays":              float64(60),
	"usageStatsDailyRetentionDays":               float64(400),
	"usageStatsWeeklyRetentionWeeks":             float64(104),
	"usageStatsMonthlyRetentionMonths":           float64(24),
	"usageRankSnapshotRetentionDays":             float64(30),
	"systemMetricsRetentionDays":                 float64(7),
	"systemMetricsHourlyRetentionDays":           float64(30),
}
