import { createHash } from 'node:crypto'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  listProviderModelPricing,
  type ProviderModelPricing
} from '../../backend/src/modules/model-pricing/model-pricing.service.js'

const providerCodes = ['gpt', 'anthropic', 'gemini', 'deepseek', 'glm'] as const
const scriptDirectory = dirname(fileURLToPath(import.meta.url))
const defaultOutputPath = resolve(
  scriptDirectory,
  '..',
  'db',
  'migrations',
  '000031_w2_sync_provider_model_catalog.sql'
)
const outputPath = process.argv[2] ? resolve(process.argv[2]) : defaultOutputPath

const rows = providerCodes.flatMap((providerCode) => listProviderModelPricing(providerCode))
const snapshot = JSON.stringify(rows)
const snapshotHash = createHash('sha256').update(snapshot).digest('hex')
const counts = providerCodes.map((providerCode) => {
  const providerRows = rows.filter((row) => row.providerCode === providerCode)
  const visibleCount = providerRows.filter((row) => row.catalogVisible).length
  return `${providerCode}=${providerRows.length}/${visibleCount}`
}).join(', ')

const sql = [
  '-- Code generated by backend-go/scripts/generate-provider-model-catalog.ts; DO NOT EDIT.',
  `-- Snapshot SHA-256: ${snapshotHash}`,
  `-- Provider row counts total/visible: ${counts}`,
  '-- Regenerate from the backend directory:',
  '--   pnpm exec tsx ../backend-go/scripts/generate-provider-model-catalog.ts',
  '',
  '-- +goose Up',
  'UPDATE juhe_business.provider_model_catalog',
  "SET status = 'disabled',",
  '    catalog_visible = false,',
  '    updated_at = now()',
  `WHERE provider_code IN (${providerCodes.map(sqlText).join(', ')});`,
  '',
  'INSERT INTO juhe_business.provider_model_catalog (',
  '  id, provider_code, model, status, mode, catalog_order, release_date, shutdown_date,',
  '  supported_api_protocols_json, supported_service_tiers_json, supported_reasoning_efforts_json,',
  '  default_reasoning_effort, codex_supported_reasoning_levels_json, codex_default_reasoning_level,',
  '  codex_multi_agent_version, pricing_model, context_window_tokens,',
  '  input_usd_per_1m, output_usd_per_1m, cached_input_usd_per_1m,',
  '  cache_write_usd_per_1m, cache_write_1h_usd_per_1m,',
  '  image_input_usd_per_1m, image_output_usd_per_1m,',
  '  audio_input_usd_per_1m, audio_output_usd_per_1m, output_usd_per_image,',
  '  max_input_tokens, max_output_tokens, max_tokens,',
  '  supports_prompt_caching, catalog_visible, source, created_at, updated_at',
  ') VALUES',
  rows.map((row, index) => `${catalogRowSQL(row)}${index === rows.length - 1 ? '' : ','}`).join('\n'),
  'ON CONFLICT (provider_code, model) DO UPDATE SET',
  "  status = 'active',",
  '  mode = EXCLUDED.mode,',
  '  catalog_order = EXCLUDED.catalog_order,',
  '  release_date = EXCLUDED.release_date,',
  '  shutdown_date = EXCLUDED.shutdown_date,',
  '  supported_api_protocols_json = EXCLUDED.supported_api_protocols_json,',
  '  supported_service_tiers_json = EXCLUDED.supported_service_tiers_json,',
  '  supported_reasoning_efforts_json = EXCLUDED.supported_reasoning_efforts_json,',
  '  default_reasoning_effort = EXCLUDED.default_reasoning_effort,',
  '  codex_supported_reasoning_levels_json = EXCLUDED.codex_supported_reasoning_levels_json,',
  '  codex_default_reasoning_level = EXCLUDED.codex_default_reasoning_level,',
  '  codex_multi_agent_version = EXCLUDED.codex_multi_agent_version,',
  '  pricing_model = EXCLUDED.pricing_model,',
  '  context_window_tokens = EXCLUDED.context_window_tokens,',
  '  input_usd_per_1m = EXCLUDED.input_usd_per_1m,',
  '  output_usd_per_1m = EXCLUDED.output_usd_per_1m,',
  '  cached_input_usd_per_1m = EXCLUDED.cached_input_usd_per_1m,',
  '  cache_write_usd_per_1m = EXCLUDED.cache_write_usd_per_1m,',
  '  cache_write_1h_usd_per_1m = EXCLUDED.cache_write_1h_usd_per_1m,',
  '  image_input_usd_per_1m = EXCLUDED.image_input_usd_per_1m,',
  '  image_output_usd_per_1m = EXCLUDED.image_output_usd_per_1m,',
  '  audio_input_usd_per_1m = EXCLUDED.audio_input_usd_per_1m,',
  '  audio_output_usd_per_1m = EXCLUDED.audio_output_usd_per_1m,',
  '  output_usd_per_image = EXCLUDED.output_usd_per_image,',
  '  max_input_tokens = EXCLUDED.max_input_tokens,',
  '  max_output_tokens = EXCLUDED.max_output_tokens,',
  '  max_tokens = EXCLUDED.max_tokens,',
  '  supports_prompt_caching = EXCLUDED.supports_prompt_caching,',
  '  catalog_visible = EXCLUDED.catalog_visible,',
  '  source = EXCLUDED.source,',
  '  updated_at = EXCLUDED.updated_at;',
  '',
  '-- +goose Down',
  '-- no-op: provider model catalog rows are current business metadata.',
  ''
].join('\n')

mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, sql, 'utf8')
console.log(`wrote ${rows.length} provider model rows to ${outputPath}`)

function catalogRowSQL(row: ProviderModelPricing): string {
  const values = [
    sqlText(catalogRowID(row)),
    sqlText(row.providerCode),
    sqlText(row.model),
    sqlText('active'),
    sqlNullableText(row.mode),
    sqlNullableNumber(row.catalogOrder),
    sqlNullableText(row.releaseDate),
    sqlNullableText(row.shutdownDate),
    sqlJSON(row.supportedApiProtocols),
    sqlJSON(row.supportedServiceTiers),
    sqlJSON(row.supportedReasoningEfforts),
    sqlNullableText(row.defaultReasoningEffort),
    sqlJSON(row.codexSupportedReasoningLevels),
    sqlNullableText(row.codexDefaultReasoningLevel),
    sqlNullableText(row.codexMultiAgentVersion),
    'NULL',
    'NULL',
    sqlNullableNumber(row.inputUsdPer1M),
    sqlNullableNumber(row.outputUsdPer1M),
    sqlNullableNumber(row.cachedInputUsdPer1M),
    sqlNullableNumber(row.cacheWriteUsdPer1M),
    sqlNullableNumber(row.cacheWrite1hUsdPer1M),
    sqlNullableNumber(row.imageInputUsdPer1M),
    sqlNullableNumber(row.imageOutputUsdPer1M),
    sqlNullableNumber(row.audioInputUsdPer1M),
    sqlNullableNumber(row.audioOutputUsdPer1M),
    sqlNullableNumber(row.outputUsdPerImage),
    sqlNullableNumber(row.maxInputTokens),
    sqlNullableNumber(row.maxOutputTokens),
    sqlNullableNumber(row.maxTokens),
    sqlBoolean(row.supportsPromptCaching),
    sqlBoolean(row.catalogVisible !== false),
    sqlText(row.source),
    'now()',
    'now()'
  ]

  return [
    '  (',
    `    ${values.slice(0, 8).join(', ')},`,
    `    ${values.slice(8, 15).join(', ')},`,
    `    ${values.slice(15, 22).join(', ')},`,
    `    ${values.slice(22, 29).join(', ')},`,
    `    ${values.slice(29).join(', ')}`,
    '  )'
  ].join('\n')
}

function catalogRowID(row: ProviderModelPricing): string {
  const slug = `${row.providerCode}_${row.model}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 72)
  const hash = createHash('sha256')
    .update(`${row.providerCode}\0${row.model}`)
    .digest('hex')
    .slice(0, 12)
  return `provider_model_${slug}_${hash}`
}

function sqlText(value: string): string {
  return `'${value.replaceAll("'", "''")}'`
}

function sqlNullableText(value: string | undefined): string {
  return value === undefined ? 'NULL' : sqlText(value)
}

function sqlNullableNumber(value: number | undefined): string {
  if (value === undefined) return 'NULL'
  if (!Number.isFinite(value)) {
    throw new Error(`provider model catalog contains a non-finite number: ${value}`)
  }
  return String(value)
}

function sqlBoolean(value: boolean): string {
  return value ? 'true' : 'false'
}

function sqlJSON(value: readonly string[]): string {
  return sqlText(JSON.stringify(value))
}
