// Code generated from the Node PostgreSQL storage sources. The statements
// in this file are a verbatim extract of one schema group from
// pg_schema.go's postgresSchemaStatements literal (see the header of
// pg_schema.go for the full provenance and execution model). The
// statements are data: do not hand-edit them and keep them byte-identical
// to the Node dump order.

package schema

// postgresSchemaStats holds the juhe_stats DDL statements in execution
// order.
var postgresSchemaStats = []PGStatement{
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS client_ip_range_window_dirty_ips (
      ip_hash text PRIMARY KEY,
      generation bigint NOT NULL DEFAULT 1,
      first_dirty_at text NOT NULL,
      updated_at text NOT NULL
    )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS client_ip_account_range_window_dirty_ips (
      ip_hash text PRIMARY KEY,
      generation bigint NOT NULL DEFAULT 1,
      first_dirty_at text NOT NULL,
      updated_at text NOT NULL
    )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS account_quality_minute_stats (
          account_id text NOT NULL,
          system_account_id text NOT NULL,
          provider_code text NOT NULL,
          stat_minute text NOT NULL,
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          last_sample_at text,
          last_success_at text,
          last_error_at text,
          last_error_message text,
          updated_at text NOT NULL,
          PRIMARY KEY (account_id, stat_minute)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS account_health_hourly (
          account_id text NOT NULL,
          system_account_id text NOT NULL,
          provider_code text NOT NULL,
          stat_hour text NOT NULL,
          status text NOT NULL CHECK (status IN ('success', 'failure')),
          last_observed_at text NOT NULL,
          last_record_id text NOT NULL,
          status_code integer,
          error_code text,
          error_message text,
          updated_at text NOT NULL,
          PRIMARY KEY (account_id, stat_hour)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS group_account_stats (
          system_account_id text NOT NULL,
          group_id text NOT NULL,
          total integer NOT NULL DEFAULT 0,
          available integer NOT NULL DEFAULT 0,
          active integer NOT NULL DEFAULT 0,
          disabled integer NOT NULL DEFAULT 0,
          error integer NOT NULL DEFAULT 0,
          rate_limited integer NOT NULL DEFAULT 0,
          current_concurrency integer NOT NULL DEFAULT 0,
          concurrency_limit integer NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, group_id)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS account_quality_scores (
          account_id text PRIMARY KEY,
          system_account_id text NOT NULL,
          provider_code text NOT NULL,
          quality_score integer NOT NULL DEFAULT 1000000,
          quality_state text NOT NULL DEFAULT 'unknown',
          recent_request_count integer NOT NULL DEFAULT 0,
          recent_success_count integer NOT NULL DEFAULT 0,
          recent_error_count integer NOT NULL DEFAULT 0,
          recent_first_token_sample_count integer NOT NULL DEFAULT 0,
          recent_avg_first_token_ms integer,
          ewma_first_token_ms integer,
          success_rate double precision,
          window_started_at text NOT NULL,
          window_ended_at text NOT NULL,
          last_sample_at text,
          last_success_at text,
          last_error_at text,
          last_error_message text,
          updated_at text NOT NULL
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS account_quality_dirty_accounts (
          account_id text PRIMARY KEY,
          first_dirty_at text NOT NULL,
          updated_at text NOT NULL
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS account_usage_snapshots (
          system_account_id text NOT NULL,
          account_id text NOT NULL,
          kind text NOT NULL CHECK (kind IN ('openai_codex', 'relay_balance', 'xai_grok')),
          source text,
          snapshot_json text NOT NULL,
          refresh_status text,
          last_attempt_at timestamptz,
          last_success_at timestamptz,
          next_refresh_after timestamptz,
          last_error_message text,
          updated_at timestamptz NOT NULL,
          created_at timestamptz NOT NULL,
          PRIMARY KEY (system_account_id, account_id, kind)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_stats_totals (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          duration_ms_max bigint NOT NULL DEFAULT 0,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          first_token_ms_max bigint NOT NULL DEFAULT 0,
          last_used_at text,
          last_error_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, scope_id)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_stats_minute (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          stat_minute text NOT NULL,
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          duration_ms_max bigint NOT NULL DEFAULT 0,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          first_token_ms_max bigint NOT NULL DEFAULT 0,
          last_used_at text,
          last_error_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, scope_id, stat_minute)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_stats_daily (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          stat_date text NOT NULL,
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          duration_ms_max bigint NOT NULL DEFAULT 0,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          first_token_ms_max bigint NOT NULL DEFAULT 0,
          last_used_at text,
          last_error_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, scope_id, stat_date)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_stats_hourly (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          stat_hour text NOT NULL,
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          duration_ms_max bigint NOT NULL DEFAULT 0,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          first_token_ms_max bigint NOT NULL DEFAULT 0,
          last_used_at text,
          last_error_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, scope_id, stat_hour)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_stats_weekly (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          stat_week text NOT NULL,
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          duration_ms_max bigint NOT NULL DEFAULT 0,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          first_token_ms_max bigint NOT NULL DEFAULT 0,
          last_used_at text,
          last_error_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, scope_id, stat_week)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_stats_monthly (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          stat_month text NOT NULL,
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          duration_ms_max bigint NOT NULL DEFAULT 0,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          first_token_ms_max bigint NOT NULL DEFAULT 0,
          last_used_at text,
          last_error_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, scope_id, stat_month)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS authorization_team_usage_summary_daily (
          system_account_id text NOT NULL,
          stat_date text NOT NULL,
          team_filter_id text NOT NULL DEFAULT '',
          resource_filter_type text NOT NULL DEFAULT 'all',
          resource_filter_id text NOT NULL DEFAULT '',
          row_count bigint NOT NULL DEFAULT 0,
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          duration_ms_max bigint NOT NULL DEFAULT 0,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          first_token_ms_max bigint NOT NULL DEFAULT 0,
          last_used_at text,
          last_error_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, stat_date, team_filter_id, resource_filter_type, resource_filter_id)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS authorization_team_usage_range_windows (
          system_account_id text NOT NULL,
          start_date text NOT NULL,
          end_date text NOT NULL,
          team_filter_id text NOT NULL DEFAULT '',
          resource_filter_type text NOT NULL DEFAULT 'all',
          resource_filter_id text NOT NULL DEFAULT '',
          request_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          last_used_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, start_date, end_date, team_filter_id, resource_filter_type, resource_filter_id)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS authorization_user_usage_summary_daily (
          system_account_id text NOT NULL,
          stat_date text NOT NULL,
          team_filter_id text NOT NULL DEFAULT '',
          grantee_filter_system_account_id text NOT NULL DEFAULT '',
          resource_filter_type text NOT NULL DEFAULT 'all',
          resource_filter_id text NOT NULL DEFAULT '',
          row_count bigint NOT NULL DEFAULT 0,
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          duration_ms_max bigint NOT NULL DEFAULT 0,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          first_token_ms_max bigint NOT NULL DEFAULT 0,
          last_used_at text,
          last_error_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, stat_date, team_filter_id, grantee_filter_system_account_id, resource_filter_type, resource_filter_id)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS authorization_user_usage_range_windows (
          system_account_id text NOT NULL,
          start_date text NOT NULL,
          end_date text NOT NULL,
          team_filter_id text NOT NULL DEFAULT '',
          grantee_filter_system_account_id text NOT NULL DEFAULT '',
          resource_filter_type text NOT NULL DEFAULT 'all',
          resource_filter_id text NOT NULL DEFAULT '',
          request_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          last_used_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, start_date, end_date, team_filter_id, grantee_filter_system_account_id, resource_filter_type, resource_filter_id)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_model_minute (
          system_account_id text NOT NULL,
          stat_minute text NOT NULL,
          provider_code text NOT NULL DEFAULT 'unknown',
          model text NOT NULL DEFAULT 'unknown',
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, stat_minute, provider_code, model)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_model_daily (
          system_account_id text NOT NULL,
          stat_date text NOT NULL,
          provider_code text NOT NULL DEFAULT 'unknown',
          model text NOT NULL DEFAULT 'unknown',
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, stat_date, provider_code, model)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_model_hourly (
          system_account_id text NOT NULL,
          stat_hour text NOT NULL,
          provider_code text NOT NULL DEFAULT 'unknown',
          model text NOT NULL DEFAULT 'unknown',
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, stat_hour, provider_code, model)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_model_weekly (
          system_account_id text NOT NULL,
          stat_week text NOT NULL,
          provider_code text NOT NULL DEFAULT 'unknown',
          model text NOT NULL DEFAULT 'unknown',
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, stat_week, provider_code, model)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_model_monthly (
          system_account_id text NOT NULL,
          stat_month text NOT NULL,
          provider_code text NOT NULL DEFAULT 'unknown',
          model text NOT NULL DEFAULT 'unknown',
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, stat_month, provider_code, model)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_error_minute (
          system_account_id text NOT NULL,
          stat_minute text NOT NULL,
          error_group text NOT NULL DEFAULT 'unknown',
          provider_code text NOT NULL DEFAULT 'unknown',
          error_code text NOT NULL DEFAULT 'unknown',
          status_code integer NOT NULL DEFAULT 0,
          error_message text,
          request_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, stat_minute, error_group, provider_code, error_code, status_code)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_error_daily (
          system_account_id text NOT NULL,
          stat_date text NOT NULL,
          error_group text NOT NULL DEFAULT 'unknown',
          provider_code text NOT NULL DEFAULT 'unknown',
          error_code text NOT NULL DEFAULT 'unknown',
          status_code integer NOT NULL DEFAULT 0,
          error_message text,
          request_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, stat_date, error_group, provider_code, error_code, status_code)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_error_hourly (
          system_account_id text NOT NULL,
          stat_hour text NOT NULL,
          error_group text NOT NULL DEFAULT 'unknown',
          provider_code text NOT NULL DEFAULT 'unknown',
          error_code text NOT NULL DEFAULT 'unknown',
          status_code integer NOT NULL DEFAULT 0,
          error_message text,
          request_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, stat_hour, error_group, provider_code, error_code, status_code)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_error_weekly (
          system_account_id text NOT NULL,
          stat_week text NOT NULL,
          error_group text NOT NULL DEFAULT 'unknown',
          provider_code text NOT NULL DEFAULT 'unknown',
          error_code text NOT NULL DEFAULT 'unknown',
          status_code integer NOT NULL DEFAULT 0,
          error_message text,
          request_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, stat_week, error_group, provider_code, error_code, status_code)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_error_monthly (
          system_account_id text NOT NULL,
          stat_month text NOT NULL,
          error_group text NOT NULL DEFAULT 'unknown',
          provider_code text NOT NULL DEFAULT 'unknown',
          error_code text NOT NULL DEFAULT 'unknown',
          status_code integer NOT NULL DEFAULT 0,
          error_message text,
          request_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, stat_month, error_group, provider_code, error_code, status_code)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_latency_minute (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          metric_type text NOT NULL,
          stat_minute text NOT NULL,
          bucket_upper_bound_ms integer NOT NULL,
          sample_count bigint NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, scope_id, metric_type, stat_minute, bucket_upper_bound_ms)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_latency_hourly (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          metric_type text NOT NULL,
          stat_hour text NOT NULL,
          bucket_upper_bound_ms integer NOT NULL,
          sample_count bigint NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, scope_id, metric_type, stat_hour, bucket_upper_bound_ms)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_latency_daily (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          metric_type text NOT NULL,
          stat_date text NOT NULL,
          bucket_upper_bound_ms integer NOT NULL,
          sample_count bigint NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, scope_id, metric_type, stat_date, bucket_upper_bound_ms)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_latency_weekly (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          metric_type text NOT NULL,
          stat_week text NOT NULL,
          bucket_upper_bound_ms integer NOT NULL,
          sample_count bigint NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, scope_id, metric_type, stat_week, bucket_upper_bound_ms)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_latency_monthly (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          metric_type text NOT NULL,
          stat_month text NOT NULL,
          bucket_upper_bound_ms integer NOT NULL,
          sample_count bigint NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, scope_id, metric_type, stat_month, bucket_upper_bound_ms)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_rank_snapshots (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          window_key text NOT NULL,
          metric text NOT NULL,
          snapshot_at text NOT NULL,
          rank integer NOT NULL,
          scope_id text NOT NULL,
          metric_value double precision NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, window_key, metric, snapshot_at, rank, scope_id)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_overview_summary_windows (
          system_account_id text NOT NULL,
          window_key text NOT NULL,
          start_date text NOT NULL DEFAULT '',
          end_date text NOT NULL DEFAULT '',
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          last_used_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, window_key)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_overview_trend_windows (
          system_account_id text NOT NULL,
          window_key text NOT NULL,
          start_date text NOT NULL DEFAULT '',
          end_date text NOT NULL DEFAULT '',
          bucket_key text NOT NULL,
          request_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, window_key, bucket_key)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_model_rank_windows (
          system_account_id text NOT NULL,
          window_key text NOT NULL,
          start_date text NOT NULL DEFAULT '',
          end_date text NOT NULL DEFAULT '',
          rank integer NOT NULL,
          provider_code text NOT NULL DEFAULT 'unknown',
          model text NOT NULL DEFAULT 'unknown',
          request_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, window_key, rank, provider_code, model)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_error_rank_windows (
          system_account_id text NOT NULL,
          window_key text NOT NULL,
          start_date text NOT NULL DEFAULT '',
          end_date text NOT NULL DEFAULT '',
          rank integer NOT NULL,
          provider_code text NOT NULL DEFAULT 'unknown',
          error_code text NOT NULL DEFAULT 'unknown',
          status_code integer NOT NULL DEFAULT 0,
          error_message text,
          error_count bigint NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, window_key, rank, provider_code, error_code, status_code)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS ai_performance_summary_windows (
          system_account_id text NOT NULL,
          window_key text NOT NULL,
          start_date text NOT NULL DEFAULT '',
          end_date text NOT NULL DEFAULT '',
          request_count bigint NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          duration_ms_max bigint NOT NULL DEFAULT 0,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          first_token_ms_max bigint NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, window_key)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_quota_hourly_windows (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          window_hours integer NOT NULL,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, scope_id, window_hours)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_quota_hourly_window_dirty_scopes (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          generation bigint NOT NULL DEFAULT 1,
          first_dirty_at text NOT NULL,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, scope_id)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_overview_dirty_scopes (
          system_account_id text PRIMARY KEY,
          scope_id text NOT NULL,
          min_changed_date text NOT NULL,
          generation bigint NOT NULL DEFAULT 1,
          first_dirty_at text NOT NULL,
          updated_at text NOT NULL
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS ai_performance_summary_dirty_system_accounts (
          system_account_id text PRIMARY KEY,
          min_stat_date text NOT NULL,
          max_stat_date text NOT NULL,
          generation bigint NOT NULL DEFAULT 1,
          first_dirty_at text NOT NULL,
          updated_at text NOT NULL
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_scope_range_windows (
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          start_date text NOT NULL,
          end_date text NOT NULL,
          window_key text GENERATED ALWAYS AS (start_date || ':' || end_date) STORED,
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          duration_ms_max bigint NOT NULL DEFAULT 0,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          first_token_ms_max bigint NOT NULL DEFAULT 0,
          active_days integer NOT NULL DEFAULT 0,
          last_used_at text,
          last_error_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (system_account_id, scope_type, scope_id, start_date, end_date)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_range_window_requests (
          id text PRIMARY KEY,
          domain text NOT NULL,
          system_account_id text NOT NULL,
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          start_date text NOT NULL,
          end_date text NOT NULL,
          window_key text GENERATED ALWAYS AS (start_date || ':' || end_date) STORED,
          status text NOT NULL DEFAULT 'pending',
          requested_count integer NOT NULL DEFAULT 1,
          last_requested_at text NOT NULL,
          last_processed_at text,
          error_message text,
          expires_at text NOT NULL,
          created_at text NOT NULL,
          updated_at text NOT NULL,
          UNIQUE (domain, system_account_id, scope_type, scope_id, start_date, end_date),
          CHECK (status IN ('pending', 'processing', 'completed', 'failed'))
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS client_ip_registry (
          ip_hash text PRIMARY KEY,
          bucket_no integer NOT NULL,
          aggregate_ip_key text NOT NULL,
          client_ip text NOT NULL,
          ip_version integer NOT NULL,
          first_seen_at text NOT NULL,
          last_seen_at text NOT NULL,
          created_at text NOT NULL,
          updated_at text NOT NULL
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS client_ip_stats_daily (
          ip_hash text NOT NULL,
          stat_date text NOT NULL,
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          duration_ms_max bigint NOT NULL DEFAULT 0,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          last_used_at text,
          last_error_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (ip_hash, stat_date)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS client_ip_usage_range_windows (
          ip_hash text NOT NULL,
          start_date text NOT NULL,
          end_date text NOT NULL,
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          duration_ms_max bigint NOT NULL DEFAULT 0,
          average_duration_ms double precision,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          average_first_token_ms double precision,
          active_days integer NOT NULL DEFAULT 0,
          last_used_at text,
          last_error_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (ip_hash, start_date, end_date)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS client_ip_range_window_dirty_ips (
          ip_hash text PRIMARY KEY,
          generation bigint NOT NULL DEFAULT 1,
          first_dirty_at text NOT NULL,
          updated_at text NOT NULL
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS client_ip_account_stats_daily (
          ip_hash text NOT NULL,
          account_id text NOT NULL,
          stat_date text NOT NULL,
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          duration_ms_max bigint NOT NULL DEFAULT 0,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          last_used_at text,
          last_error_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (ip_hash, account_id, stat_date)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS client_ip_account_usage_range_windows (
          ip_hash text NOT NULL,
          account_id text NOT NULL,
          start_date text NOT NULL,
          end_date text NOT NULL,
          request_count bigint NOT NULL DEFAULT 0,
          success_count bigint NOT NULL DEFAULT 0,
          error_count bigint NOT NULL DEFAULT 0,
          input_tokens bigint NOT NULL DEFAULT 0,
          output_tokens bigint NOT NULL DEFAULT 0,
          cache_read_tokens bigint NOT NULL DEFAULT 0,
          cache_read_cost_usd double precision NOT NULL DEFAULT 0,
          cache_write_tokens bigint NOT NULL DEFAULT 0,
          cache_write_1h_tokens bigint NOT NULL DEFAULT 0,
          cache_write_cost_usd double precision NOT NULL DEFAULT 0,
          thinking_tokens bigint NOT NULL DEFAULT 0,
          input_image_tokens bigint NOT NULL DEFAULT 0,
          output_image_tokens bigint NOT NULL DEFAULT 0,
          total_cost_usd double precision NOT NULL DEFAULT 0,
          duration_ms_sum bigint NOT NULL DEFAULT 0,
          duration_ms_count bigint NOT NULL DEFAULT 0,
          duration_ms_max bigint NOT NULL DEFAULT 0,
          average_duration_ms double precision,
          first_token_ms_sum bigint NOT NULL DEFAULT 0,
          first_token_ms_count bigint NOT NULL DEFAULT 0,
          average_first_token_ms double precision,
          active_days integer NOT NULL DEFAULT 0,
          last_used_at text,
          last_error_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (ip_hash, account_id, start_date, end_date)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS client_ip_account_range_window_dirty_ips (
          ip_hash text PRIMARY KEY,
          generation bigint NOT NULL DEFAULT 1,
          first_dirty_at text NOT NULL,
          updated_at text NOT NULL
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS client_ip_policies (
          id text PRIMARY KEY,
          ip_hash text NOT NULL,
          policy_type text NOT NULL,
          status text NOT NULL,
          reason text,
          expires_at text,
          created_by_system_account_id text NOT NULL,
          created_at text NOT NULL,
          updated_at text NOT NULL,
          disabled_at text,
          disabled_by_system_account_id text,
          disabled_reason text
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS client_ip_policy_hits (
          ip_hash text NOT NULL,
          stat_date text NOT NULL,
          policy_id text NOT NULL,
          hit_count bigint NOT NULL DEFAULT 0,
          last_hit_at text,
          updated_at text NOT NULL,
          PRIMARY KEY (ip_hash, stat_date, policy_id)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS stats_job_state (
          scope_type text NOT NULL,
          scope_id text NOT NULL DEFAULT '',
          job_name text NOT NULL,
          cursor_created_at text,
          cursor_id text,
          last_success_at text,
          last_error_message text,
          lag_seconds integer,
          updated_at text NOT NULL,
          PRIMARY KEY (scope_type, scope_id, job_name)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS background_task_runs (
          run_id text PRIMARY KEY,
          job_name text NOT NULL,
          job_type text NOT NULL,
          worker_role text NOT NULL,
          status text NOT NULL,
          lease_key text NOT NULL,
          owner_id text,
          params_json text NOT NULL DEFAULT '{}',
          result_json text NOT NULL DEFAULT '{}',
          error_message text,
          submitted_at text NOT NULL,
          started_at text,
          heartbeat_at text,
          finished_at text,
          duration_ms integer,
          exit_code integer,
          created_at text NOT NULL,
          updated_at text NOT NULL
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS background_job_leases (
          lease_key text PRIMARY KEY,
          job_name text NOT NULL,
          shard_key text NOT NULL DEFAULT '',
          owner_id text NOT NULL,
          run_id text,
          fencing_token bigint NOT NULL DEFAULT 0,
          lease_until text NOT NULL,
          heartbeat_at text NOT NULL,
          started_at text NOT NULL,
          updated_at text NOT NULL
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS usage_record_cleanup_deductions (
          usage_id text NOT NULL,
          api_key_id text NOT NULL,
          account_id text,
          system_account_id text NOT NULL,
          source_shard_key text NOT NULL,
          record_json text NOT NULL,
          stats_subtracted_at text,
          shard_deleted_at text,
          created_at text NOT NULL,
          updated_at text NOT NULL,
          PRIMARY KEY (usage_id, source_shard_key)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS system_metrics_samples (
          id text PRIMARY KEY,
          sampled_at text NOT NULL,
          cpu_percent double precision,
          memory_used_percent double precision,
          memory_total_bytes BIGINT,
          memory_free_bytes BIGINT,
          process_rss_bytes BIGINT,
          process_heap_used_bytes BIGINT,
          process_heap_total_bytes BIGINT,
          event_loop_lag_ms double precision,
          network_rx_bytes_per_sec double precision,
          network_tx_bytes_per_sec double precision,
          network_rx_total_bytes BIGINT,
          network_tx_total_bytes BIGINT,
          db_file_bytes BIGINT,
          stats_lag_seconds integer,
          created_at text NOT NULL
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS system_metrics_hourly (
          stat_hour text PRIMARY KEY,
          sample_count bigint NOT NULL DEFAULT 0,
          cpu_percent_sum double precision NOT NULL DEFAULT 0,
          cpu_percent_max double precision,
          memory_used_percent_sum double precision NOT NULL DEFAULT 0,
          memory_used_percent_max double precision,
          process_rss_bytes_sum BIGINT NOT NULL DEFAULT 0,
          process_rss_bytes_max BIGINT,
          process_heap_used_bytes_sum BIGINT NOT NULL DEFAULT 0,
          process_heap_used_bytes_max BIGINT,
          event_loop_lag_ms_sum double precision NOT NULL DEFAULT 0,
          event_loop_lag_ms_count bigint NOT NULL DEFAULT 0,
          event_loop_lag_ms_max double precision,
          network_rx_bytes_per_sec_sum double precision NOT NULL DEFAULT 0,
          network_rx_bytes_per_sec_max double precision,
          network_rx_bytes_per_sec_count bigint NOT NULL DEFAULT 0,
          network_tx_bytes_per_sec_sum double precision NOT NULL DEFAULT 0,
          network_tx_bytes_per_sec_max double precision,
          network_tx_bytes_per_sec_count bigint NOT NULL DEFAULT 0,
          network_rx_total_bytes_max BIGINT,
          network_tx_total_bytes_max BIGINT,
          db_file_bytes_max BIGINT,
          stats_lag_seconds_max integer,
          updated_at text NOT NULL
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS system_metrics_trend_windows (
          window_key text NOT NULL,
          start_date text NOT NULL DEFAULT '',
          end_date text NOT NULL DEFAULT '',
          bucket_key text NOT NULL,
          sample_count bigint NOT NULL DEFAULT 0,
          cpu_percent_sum double precision NOT NULL DEFAULT 0,
          cpu_percent_max double precision,
          memory_used_percent_sum double precision NOT NULL DEFAULT 0,
          memory_used_percent_max double precision,
          process_rss_bytes_sum BIGINT NOT NULL DEFAULT 0,
          process_rss_bytes_max BIGINT,
          process_heap_used_bytes_sum BIGINT NOT NULL DEFAULT 0,
          process_heap_used_bytes_max BIGINT,
          event_loop_lag_ms_sum double precision NOT NULL DEFAULT 0,
          event_loop_lag_ms_count bigint NOT NULL DEFAULT 0,
          event_loop_lag_ms_max double precision,
          network_rx_bytes_per_sec_sum double precision NOT NULL DEFAULT 0,
          network_rx_bytes_per_sec_max double precision,
          network_rx_bytes_per_sec_count bigint NOT NULL DEFAULT 0,
          network_tx_bytes_per_sec_sum double precision NOT NULL DEFAULT 0,
          network_tx_bytes_per_sec_max double precision,
          network_tx_bytes_per_sec_count bigint NOT NULL DEFAULT 0,
          network_rx_total_bytes_max BIGINT,
          network_tx_total_bytes_max BIGINT,
          db_file_bytes_max BIGINT,
          stats_lag_seconds_max integer,
          updated_at text NOT NULL,
          PRIMARY KEY (window_key, bucket_key)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS process_event_loop_samples (
          id text PRIMARY KEY,
          sampled_at text NOT NULL,
          process_role text NOT NULL,
          process_pid integer,
          event_loop_lag_ms double precision,
          process_rss_bytes BIGINT,
          process_heap_used_bytes BIGINT,
          process_heap_total_bytes BIGINT,
          process_external_bytes BIGINT,
          process_array_buffers_bytes BIGINT,
          created_at text NOT NULL
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS process_event_loop_hourly (
          stat_hour text NOT NULL,
          process_role text NOT NULL,
          sample_count bigint NOT NULL DEFAULT 0,
          event_loop_lag_ms_sum double precision NOT NULL DEFAULT 0,
          event_loop_lag_ms_count bigint NOT NULL DEFAULT 0,
          event_loop_lag_ms_max double precision,
          process_rss_bytes_sum BIGINT NOT NULL DEFAULT 0,
          process_rss_bytes_max BIGINT,
          process_heap_used_bytes_sum BIGINT NOT NULL DEFAULT 0,
          process_heap_used_bytes_max BIGINT,
          process_heap_total_bytes_sum BIGINT NOT NULL DEFAULT 0,
          process_heap_total_bytes_max BIGINT,
          process_external_bytes_sum BIGINT NOT NULL DEFAULT 0,
          process_external_bytes_max BIGINT,
          process_array_buffers_bytes_sum BIGINT NOT NULL DEFAULT 0,
          process_array_buffers_bytes_max BIGINT,
          updated_at text NOT NULL,
          PRIMARY KEY (stat_hour, process_role)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE TABLE IF NOT EXISTS process_event_loop_trend_windows (
          window_key text NOT NULL,
          start_date text NOT NULL DEFAULT '',
          end_date text NOT NULL DEFAULT '',
          bucket_key text NOT NULL,
          process_role text NOT NULL,
          sample_count bigint NOT NULL DEFAULT 0,
          event_loop_lag_ms_sum double precision NOT NULL DEFAULT 0,
          event_loop_lag_ms_count bigint NOT NULL DEFAULT 0,
          event_loop_lag_ms_max double precision,
          process_rss_bytes_sum BIGINT NOT NULL DEFAULT 0,
          process_rss_bytes_max BIGINT,
          process_heap_used_bytes_sum BIGINT NOT NULL DEFAULT 0,
          process_heap_used_bytes_max BIGINT,
          process_heap_total_bytes_sum BIGINT NOT NULL DEFAULT 0,
          process_heap_total_bytes_max BIGINT,
          process_external_bytes_sum BIGINT NOT NULL DEFAULT 0,
          process_external_bytes_max BIGINT,
          process_array_buffers_bytes_sum BIGINT NOT NULL DEFAULT 0,
          process_array_buffers_bytes_max BIGINT,
          updated_at text NOT NULL,
          PRIMARY KEY (window_key, bucket_key, process_role)
        )`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "account-list-projection-pg-quota-crossing-triggers",
		SQL: `
CREATE OR REPLACE FUNCTION account_list_availability_quota_crossing_trigger()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = juhe_business, public
AS $function$
DECLARE
  v_old_cost double precision;
  v_new_cost double precision;
BEGIN
  v_old_cost := CASE WHEN TG_OP = 'INSERT' THEN 0 ELSE COALESCE(OLD.total_cost_usd, 0) END;
  v_new_cost := CASE WHEN TG_OP = 'DELETE' THEN 0 ELSE COALESCE(NEW.total_cost_usd, 0) END;
  PERFORM juhe_business.account_list_availability_mark_dirty_quota_crossing(
    COALESCE(NEW.scope_type, OLD.scope_type),
    COALESCE(NEW.scope_id, OLD.scope_id),
    TG_ARGV[0], v_old_cost, v_new_cost
  );
  RETURN COALESCE(NEW, OLD);
END;
$function$;

DROP TRIGGER IF EXISTS account_list_availability_quota_total ON usage_stats_totals;
CREATE TRIGGER account_list_availability_quota_total
AFTER INSERT OR UPDATE OR DELETE ON usage_stats_totals
FOR EACH ROW EXECUTE FUNCTION account_list_availability_quota_crossing_trigger('total');
-- 注（2026-09-25）：触发器仍监听 total_cost_usd。展示/执法读点已切到
-- success_cost_usd（成功口径成本），失败尝试只改 total_cost_usd 时这里会
-- 多发通知、不会漏发（保守无害），故保持旧列监听不动。
DROP TRIGGER IF EXISTS account_list_availability_quota_daily ON usage_stats_daily;
CREATE TRIGGER account_list_availability_quota_daily
AFTER INSERT OR UPDATE OR DELETE ON usage_stats_daily
FOR EACH ROW EXECUTE FUNCTION account_list_availability_quota_crossing_trigger('daily');
DROP TRIGGER IF EXISTS account_list_availability_quota_weekly ON usage_stats_weekly;
CREATE TRIGGER account_list_availability_quota_weekly
AFTER INSERT OR UPDATE OR DELETE ON usage_stats_weekly
FOR EACH ROW EXECUTE FUNCTION account_list_availability_quota_crossing_trigger('weekly');
DROP TRIGGER IF EXISTS account_list_availability_quota_monthly ON usage_stats_monthly;
CREATE TRIGGER account_list_availability_quota_monthly
AFTER INSERT OR UPDATE OR DELETE ON usage_stats_monthly
FOR EACH ROW EXECUTE FUNCTION account_list_availability_quota_crossing_trigger('monthly');
DROP TRIGGER IF EXISTS account_list_availability_quota_hourly ON usage_quota_hourly_windows;
CREATE TRIGGER account_list_availability_quota_hourly
AFTER INSERT OR UPDATE OR DELETE ON usage_quota_hourly_windows
FOR EACH ROW EXECUTE FUNCTION account_list_availability_quota_crossing_trigger('hourly');
`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_background_task_runs_status_updated
      ON background_task_runs(status, updated_at DESC, run_id DESC)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_background_task_runs_job_created
      ON background_task_runs(job_name, created_at DESC, run_id DESC)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_background_job_leases_job
      ON background_job_leases(job_name, shard_key, lease_until)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_usage_record_cleanup_deductions_target
      ON usage_record_cleanup_deductions(api_key_id, system_account_id, shard_deleted_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_account_quality_minute_stats_minute ON account_quality_minute_stats(stat_minute, account_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_account_health_hourly_scope
      ON account_health_hourly(system_account_id, stat_hour, account_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_group_account_stats_group ON group_account_stats(group_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_account_quality_scores_sort ON account_quality_scores(provider_code, quality_score, quality_state)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_account_quality_scores_failure_precheck
      ON account_quality_scores(recent_error_count DESC, success_rate, updated_at DESC, account_id)
      WHERE recent_request_count >= 5 AND recent_error_count >= 2`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_account_quality_dirty_accounts_first_dirty ON account_quality_dirty_accounts(first_dirty_at, account_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_account_usage_snapshots_kind ON account_usage_snapshots(kind, updated_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_account_usage_snapshots_kind_account ON account_usage_snapshots(kind, account_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_stats_job_state_usage_shard_cursor_floor
      ON stats_job_state(scope_type, job_name, cursor_created_at, cursor_id)
      WHERE cursor_created_at IS NOT NULL
        AND cursor_id IS NOT NULL`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_stats_job_state_usage_shard_cursor_floor_any_job
      ON stats_job_state(scope_type, cursor_created_at, cursor_id, job_name)
      WHERE cursor_created_at IS NOT NULL
        AND cursor_id IS NOT NULL`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_totals_updated ON usage_stats_totals(updated_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_usage_stats_totals_scope_seed
      ON usage_stats_totals(scope_type, system_account_id, scope_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_minute_scope_minute ON usage_stats_minute(system_account_id, scope_type, scope_id, stat_minute)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_minute_minute ON usage_stats_minute(stat_minute)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_daily_scope_date ON usage_stats_daily(system_account_id, scope_type, scope_id, stat_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_usage_stats_daily_system_scope_date
      ON usage_stats_daily(system_account_id, scope_type, stat_date, scope_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_usage_stats_daily_system_account_top_activity
      ON usage_stats_daily(stat_date, request_count DESC, last_used_at DESC, system_account_id)
      WHERE scope_type = 'system_account'
        AND scope_id = system_account_id
        AND system_account_id <> 'global'`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_daily_date ON usage_stats_daily(stat_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_daily_updated ON usage_stats_daily(updated_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_hourly_scope_hour ON usage_stats_hourly(system_account_id, scope_type, scope_id, stat_hour)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_hourly_scope_stat_hour ON usage_stats_hourly(system_account_id, scope_type, stat_hour, scope_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_hourly_hour ON usage_stats_hourly(stat_hour)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_hourly_updated ON usage_stats_hourly(updated_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_weekly_scope_week ON usage_stats_weekly(system_account_id, scope_type, scope_id, stat_week)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_weekly_week ON usage_stats_weekly(stat_week)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_monthly_scope_month ON usage_stats_monthly(system_account_id, scope_type, scope_id, stat_month)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_monthly_month ON usage_stats_monthly(stat_month)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_stats_monthly_updated ON usage_stats_monthly(updated_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_authorization_team_usage_summary_daily_lookup ON authorization_team_usage_summary_daily(system_account_id, stat_date, team_filter_id, resource_filter_type, resource_filter_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_authorization_team_usage_summary_daily_updated ON authorization_team_usage_summary_daily(updated_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_authorization_team_usage_range_lookup ON authorization_team_usage_range_windows(system_account_id, start_date, end_date, team_filter_id, resource_filter_type, resource_filter_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_authorization_team_usage_range_sort ON authorization_team_usage_range_windows(system_account_id, start_date, end_date, total_cost_usd DESC, request_count DESC, last_used_at DESC, team_filter_id, resource_filter_type, resource_filter_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_authorization_team_usage_range_end ON authorization_team_usage_range_windows(end_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_authorization_user_usage_summary_daily_lookup ON authorization_user_usage_summary_daily(system_account_id, stat_date, team_filter_id, grantee_filter_system_account_id, resource_filter_type, resource_filter_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_authorization_user_usage_summary_daily_updated ON authorization_user_usage_summary_daily(updated_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_authorization_user_usage_range_lookup ON authorization_user_usage_range_windows(system_account_id, start_date, end_date, team_filter_id, grantee_filter_system_account_id, resource_filter_type, resource_filter_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_authorization_user_usage_range_sort ON authorization_user_usage_range_windows(system_account_id, start_date, end_date, team_filter_id, total_cost_usd DESC, request_count DESC, last_used_at DESC, grantee_filter_system_account_id, resource_filter_type, resource_filter_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_authorization_user_usage_range_end ON authorization_user_usage_range_windows(end_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_model_minute_minute ON usage_model_minute(system_account_id, stat_minute, model)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_model_minute_stat_minute ON usage_model_minute(stat_minute)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_model_daily_date ON usage_model_daily(system_account_id, stat_date, model)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_model_daily_stat_date ON usage_model_daily(stat_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_model_daily_updated ON usage_model_daily(updated_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE UNIQUE INDEX IF NOT EXISTS idx_usage_model_daily_account_date_provider_model ON usage_model_daily(system_account_id, stat_date, provider_code, model)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_model_hourly_hour ON usage_model_hourly(system_account_id, stat_hour, model)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_model_hourly_stat_hour ON usage_model_hourly(stat_hour)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_model_weekly_week ON usage_model_weekly(system_account_id, stat_week, model)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_model_weekly_stat_week ON usage_model_weekly(stat_week)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_model_monthly_month ON usage_model_monthly(system_account_id, stat_month, model)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_model_monthly_stat_month ON usage_model_monthly(stat_month)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_error_minute_minute ON usage_error_minute(system_account_id, stat_minute, error_code)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_error_minute_stat_minute ON usage_error_minute(stat_minute)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_error_daily_date ON usage_error_daily(system_account_id, stat_date, error_code)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_error_daily_stat_date ON usage_error_daily(stat_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_error_daily_updated ON usage_error_daily(updated_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_error_hourly_hour ON usage_error_hourly(system_account_id, stat_hour, error_code)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_error_hourly_stat_hour ON usage_error_hourly(stat_hour)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_error_weekly_week ON usage_error_weekly(system_account_id, stat_week, error_code)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_error_weekly_stat_week ON usage_error_weekly(stat_week)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_error_monthly_month ON usage_error_monthly(system_account_id, stat_month, error_code)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_error_monthly_stat_month ON usage_error_monthly(stat_month)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_latency_minute_minute ON usage_latency_minute(stat_minute)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_latency_hourly_hour ON usage_latency_hourly(stat_hour)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_latency_daily_date ON usage_latency_daily(stat_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_latency_weekly_week ON usage_latency_weekly(stat_week)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_latency_monthly_month ON usage_latency_monthly(stat_month)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_rank_snapshots_lookup ON usage_rank_snapshots(system_account_id, scope_type, window_key, metric, snapshot_at DESC, rank)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_rank_snapshots_snapshot ON usage_rank_snapshots(snapshot_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_overview_summary_windows_end ON usage_overview_summary_windows(end_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_usage_quota_hourly_window_dirty_updated
      ON usage_quota_hourly_window_dirty_scopes(first_dirty_at, system_account_id, scope_type, scope_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_usage_overview_dirty_first_dirty
      ON usage_overview_dirty_scopes(first_dirty_at, system_account_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_ai_performance_summary_dirty_first_dirty
      ON ai_performance_summary_dirty_system_accounts(first_dirty_at, system_account_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_usage_overview_summary_windows_prewarm_order
      ON usage_overview_summary_windows(window_key, request_count DESC, last_used_at DESC, system_account_id)
      WHERE request_count > 0
        AND system_account_id <> 'global'`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_overview_trend_windows_lookup ON usage_overview_trend_windows(system_account_id, window_key, bucket_key)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_overview_trend_windows_end ON usage_overview_trend_windows(end_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_model_rank_windows_lookup ON usage_model_rank_windows(system_account_id, window_key, rank)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_model_rank_windows_end ON usage_model_rank_windows(end_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_error_rank_windows_lookup ON usage_error_rank_windows(system_account_id, window_key, rank)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_error_rank_windows_end ON usage_error_rank_windows(end_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_ai_performance_summary_windows_lookup ON ai_performance_summary_windows(system_account_id, window_key)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_ai_performance_summary_windows_end ON ai_performance_summary_windows(end_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_quota_hourly_windows_lookup ON usage_quota_hourly_windows(system_account_id, scope_type, scope_id, window_hours)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_quota_hourly_windows_updated ON usage_quota_hourly_windows(updated_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_scope_range_windows_lookup ON usage_scope_range_windows(system_account_id, scope_type, scope_id, window_key)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_scope_range_windows_range_lookup ON usage_scope_range_windows(system_account_id, scope_type, window_key, scope_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_scope_range_windows_account_usage_order ON usage_scope_range_windows(system_account_id, scope_type, window_key, request_count DESC, total_cost_usd DESC, (input_tokens + output_tokens) DESC, last_used_at DESC, scope_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_scope_range_windows_end ON usage_scope_range_windows(end_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_scope_range_windows_end_start ON usage_scope_range_windows(end_date, start_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_range_window_requests_pending ON usage_range_window_requests(status, domain, updated_at, id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_usage_range_window_requests_expires ON usage_range_window_requests(expires_at, domain, status)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_registry_bucket ON client_ip_registry(bucket_no, ip_hash)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_registry_last_seen ON client_ip_registry(last_seen_at DESC, ip_hash)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_registry_ip ON client_ip_registry(aggregate_ip_key)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_registry_client_ip ON client_ip_registry(client_ip)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_stats_daily_date ON client_ip_stats_daily(stat_date, ip_hash)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_range_requests ON client_ip_usage_range_windows(start_date, end_date, request_count DESC, ip_hash)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_range_end ON client_ip_usage_range_windows(end_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_range_dirty_updated ON client_ip_range_window_dirty_ips(first_dirty_at ASC, ip_hash)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_account_daily_date ON client_ip_account_stats_daily(stat_date, ip_hash, account_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_account_daily_ip_date ON client_ip_account_stats_daily(ip_hash, stat_date, account_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_account_range_requests ON client_ip_account_usage_range_windows(ip_hash, start_date, end_date, request_count DESC, account_id)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_account_range_dirty_updated ON client_ip_account_range_window_dirty_ips(first_dirty_at ASC, ip_hash)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE UNIQUE INDEX IF NOT EXISTS idx_client_ip_policies_active_unique ON client_ip_policies(ip_hash) WHERE status = 'active'`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_policies_active ON client_ip_policies(status, policy_type, ip_hash, expires_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_policies_ip ON client_ip_policies(ip_hash, status, policy_type, created_at DESC)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_client_ip_policy_hits_date ON client_ip_policy_hits(stat_date DESC, ip_hash)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_account_usage_snapshots_updated ON account_usage_snapshots(updated_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_system_metrics_trend_windows_lookup ON system_metrics_trend_windows(window_key, bucket_key)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_system_metrics_trend_windows_end ON system_metrics_trend_windows(end_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_system_metrics_samples_sampled_at ON system_metrics_samples(sampled_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_system_metrics_samples_latest ON system_metrics_samples(sampled_at DESC, id DESC)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_system_metrics_hourly_updated ON system_metrics_hourly(updated_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_process_event_loop_samples_sampled_at ON process_event_loop_samples(sampled_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_process_event_loop_samples_role_latest ON process_event_loop_samples(process_role, sampled_at DESC, id DESC)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_process_event_loop_samples_role_peak
      ON process_event_loop_samples(process_role, event_loop_lag_ms DESC, sampled_at DESC, id DESC)
      WHERE event_loop_lag_ms IS NOT NULL`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_process_event_loop_hourly_lookup ON process_event_loop_hourly(stat_hour, process_role)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_process_event_loop_hourly_updated ON process_event_loop_hourly(updated_at)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_process_event_loop_trend_windows_lookup ON process_event_loop_trend_windows(window_key, bucket_key, process_role)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL:        `CREATE INDEX IF NOT EXISTS idx_process_event_loop_trend_windows_end ON process_event_loop_trend_windows(end_date)`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "stats",
		SQL: `CREATE INDEX IF NOT EXISTS idx_usage_record_cleanup_deductions_account
      ON usage_record_cleanup_deductions(account_id, shard_deleted_at)`,
	},
	// 成功口径成本列（配额/账单只计成功交付的尝试）：usage_stats 表族追加
	// success_cost_usd，失败尝试的成本只留在 total_cost_usd 供账号成本观测；
	// 消费方 gateway gatewayquota/costs.go 的配额读改读新列。usage_quota_hourly_windows
	// 不加列：其 total_cost_usd 单列即配额口径成本，由 statsagg 窗口刷新按
	// success_cost_usd 汇总重建，历史窗口行在下一次刷新自然收敛。
	// 回填策略（rerun-safe，可随 ensure 重复执行）：error_count = 0 的行
	// （无失败尝试，total 即成功成本）置为 total_cost_usd；error_count > 0 的
	// 混合历史行无法从聚合还原成功部分，保持 0 起算（业务口径：失败尝试不计
	// 配额），新聚合随后自然精确累积。WHERE 守卫保证对已回填/已切换后聚合的
	// 行为幂等（error_count = 0 且成功口径已累积时 success = total 恒成立）。
	{
		SchemaName: "juhe_stats",
		Source:     "success-cost-usd-pg-columns",
		SQL:        `ALTER TABLE usage_stats_totals ADD COLUMN IF NOT EXISTS success_cost_usd double precision NOT NULL DEFAULT 0`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "success-cost-usd-pg-columns",
		SQL:        `ALTER TABLE usage_stats_minute ADD COLUMN IF NOT EXISTS success_cost_usd double precision NOT NULL DEFAULT 0`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "success-cost-usd-pg-columns",
		SQL:        `ALTER TABLE usage_stats_hourly ADD COLUMN IF NOT EXISTS success_cost_usd double precision NOT NULL DEFAULT 0`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "success-cost-usd-pg-columns",
		SQL:        `ALTER TABLE usage_stats_daily ADD COLUMN IF NOT EXISTS success_cost_usd double precision NOT NULL DEFAULT 0`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "success-cost-usd-pg-columns",
		SQL:        `ALTER TABLE usage_stats_weekly ADD COLUMN IF NOT EXISTS success_cost_usd double precision NOT NULL DEFAULT 0`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "success-cost-usd-pg-columns",
		SQL:        `ALTER TABLE usage_stats_monthly ADD COLUMN IF NOT EXISTS success_cost_usd double precision NOT NULL DEFAULT 0`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "success-cost-usd-backfill",
		SQL:        `UPDATE usage_stats_totals SET success_cost_usd = total_cost_usd WHERE error_count = 0 AND success_cost_usd <> total_cost_usd`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "success-cost-usd-backfill",
		SQL:        `UPDATE usage_stats_minute SET success_cost_usd = total_cost_usd WHERE error_count = 0 AND success_cost_usd <> total_cost_usd`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "success-cost-usd-backfill",
		SQL:        `UPDATE usage_stats_hourly SET success_cost_usd = total_cost_usd WHERE error_count = 0 AND success_cost_usd <> total_cost_usd`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "success-cost-usd-backfill",
		SQL:        `UPDATE usage_stats_daily SET success_cost_usd = total_cost_usd WHERE error_count = 0 AND success_cost_usd <> total_cost_usd`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "success-cost-usd-backfill",
		SQL:        `UPDATE usage_stats_weekly SET success_cost_usd = total_cost_usd WHERE error_count = 0 AND success_cost_usd <> total_cost_usd`,
	},
	{
		SchemaName: "juhe_stats",
		Source:     "success-cost-usd-backfill",
		SQL:        `UPDATE usage_stats_monthly SET success_cost_usd = total_cost_usd WHERE error_count = 0 AND success_cost_usd <> total_cost_usd`,
	},
}
