package port

import (
	"context"
	"time"

	"juhe-ai/backend-go/internal/modelquality"
)

const (
	// ModelQualityScheduleClaimDefaultLimit and
	// ModelQualityScheduleClaimMaximumLimit retain Node's bounded durable
	// scheduler batch, while leaving scheduling execution outside this port.
	ModelQualityScheduleClaimDefaultLimit   = 3
	ModelQualityScheduleClaimMaximumLimit   = 20
	ModelQualityRecoveryClaimDefaultLimit   = 2
	ModelQualityRecoveryClaimMaximumLimit   = 10
	ModelQualityHealthSyncClaimDefaultLimit = 20
	ModelQualityHealthSyncClaimMaximumLimit = 100
	ModelQualityScheduleClaimDefaultLease   = 5 * time.Minute
	ModelQualityRecoveryClaimDefaultLease   = 6 * time.Minute
	ModelQualityHealthSyncClaimDefaultLease = 2 * time.Minute
	ModelQualityClaimMinimumLease           = time.Minute
	ModelQualityClaimMaximumLease           = 30 * time.Minute

	ModelQualityMinimumInterval = 10 * time.Minute
	ModelQualityMaximumInterval = 7 * 24 * time.Hour
)

// ModelQualityPolicyRecord represents either a persisted policy or the
// implicit default policy used when no policy row exists. The distinction is
// needed by an adapter so an optimistic write at revision zero can atomically
// create the first durable row instead of overwriting an existing one.
type ModelQualityPolicyRecord struct {
	Policy    modelquality.Policy
	Persisted bool
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

type ModelQualityPolicySaveInput struct {
	SystemAccountID string
	// ExpectedRevision is compared atomically with the durable policy revision.
	// Zero means the implicit default / first-row generation, not an omitted
	// fence.
	ExpectedRevision         modelquality.PolicyRevision
	Profile                  modelquality.Profile
	ManualEnforcementEnabled bool
	PenaltyThreshold         int
	PenaltyAction            modelquality.Action
	RecoveryInterval         time.Duration
	UpdatedAt                time.Time
}

type ModelQualityPolicySaveStatus string

const (
	ModelQualityPolicySaved    ModelQualityPolicySaveStatus = "saved"
	ModelQualityPolicyConflict ModelQualityPolicySaveStatus = "conflict"
)

type ModelQualityPolicySaveResult struct {
	Status ModelQualityPolicySaveStatus
	Policy ModelQualityPolicyRecord
}

// ModelQualityPolicyReader deliberately returns the effective policy: callers
// must never independently recreate a default and accidentally use different
// defaults from the durable adapter.
type ModelQualityPolicyReader interface {
	ReadModelQualityPolicy(context.Context, string) (ModelQualityPolicyRecord, error)
}

type ModelQualityPolicyWriter interface {
	SaveModelQualityPolicy(context.Context, ModelQualityPolicySaveInput) (ModelQualityPolicySaveResult, error)
}

// ModelQualityScheduleLease identifies an acquired schedule lease. ClaimToken
// is generated by the durable adapter and is distinct from OwnerID so a later
// claim by the same process cannot complete a stale prior lease.
type ModelQualityScheduleLease struct {
	OwnerID    ModelQualityClaimOwnerID
	ClaimToken ModelQualityScheduleClaimToken
	Until      time.Time
}

type ModelQualityClaimOwnerID string
type ModelQualityScheduleClaimToken string

type ModelQualitySchedule struct {
	ID              string
	SystemAccountID string
	AccountID       string
	Model           string
	Interval        time.Duration
	Enabled         bool
	Revision        modelquality.ScheduleRevision
	NextRunAt       time.Time
	LastRunID       string
	LastRunAt       *time.Time
	LastRunStatus   *modelquality.RunStatus
	Lease           *ModelQualityScheduleLease
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// ModelQualityScheduleUpsertInput changes the one schedule owned by the
// `(system_account_id, account_id)` relation. ExpectedRevision is optional only
// for the Node-compatible UI update path; a present zero explicitly requires
// that no durable schedule exists yet.
type ModelQualityScheduleUpsertInput struct {
	SystemAccountID  string
	AccountID        string
	Model            string
	Interval         time.Duration
	Enabled          bool
	ExpectedRevision *modelquality.ScheduleRevision
	UpdatedAt        time.Time
}

type ModelQualityScheduleDeleteInput struct {
	SystemAccountID string
	ScheduleID      string
	// ExpectedRevision is nil only for the legacy Node-compatible delete path.
	// New Go callers should provide it to avoid deleting a schedule edited after
	// it was displayed.
	ExpectedRevision *modelquality.ScheduleRevision
}

type ModelQualityScheduleWriteStatus string

const (
	ModelQualityScheduleWritten  ModelQualityScheduleWriteStatus = "written"
	ModelQualityScheduleConflict ModelQualityScheduleWriteStatus = "conflict"
	ModelQualityScheduleMissing  ModelQualityScheduleWriteStatus = "missing"
)

type ModelQualityScheduleWriteResult struct {
	Status   ModelQualityScheduleWriteStatus
	Schedule *ModelQualitySchedule
}

type ModelQualityScheduleWriter interface {
	UpsertModelQualitySchedule(context.Context, ModelQualityScheduleUpsertInput) (ModelQualityScheduleWriteResult, error)
	DeleteModelQualitySchedule(context.Context, ModelQualityScheduleDeleteInput) (ModelQualityScheduleWriteResult, error)
}

type ModelQualityScheduleClaimInput struct {
	OwnerID ModelQualityClaimOwnerID
	// LeaseDuration is applied to one PostgreSQL clock_timestamp() inside
	// each claim write. Callers cannot extend a lease with a skewed host clock.
	LeaseDuration time.Duration
	Limit         int
}

// ModelQualityScheduleClaim is a durable scheduler hand-off. The adapter must
// atomically select only active, owned accounts and persist Lease before
// returning it. AccountConfigRevision is captured for the model-check payload
// and must not be confused with the schedule revision.
type ModelQualityScheduleClaim struct {
	Schedule              ModelQualitySchedule
	Policy                ModelQualityPolicyRecord
	AccountConfigRevision modelquality.AccountRevision
	Lease                 ModelQualityScheduleLease
}

type ModelQualityScheduleClaimer interface {
	ClaimDueModelQualitySchedules(context.Context, ModelQualityScheduleClaimInput) ([]ModelQualityScheduleClaim, error)
}

type ModelQualityScheduleCompletionStatus string

const (
	ModelQualityScheduleRunCompleted ModelQualityScheduleCompletionStatus = "completed"
	ModelQualityScheduleRunFailed    ModelQualityScheduleCompletionStatus = "failed"
	ModelQualityScheduleRunCanceled  ModelQualityScheduleCompletionStatus = "canceled"
)

type ModelQualityScheduleCompleteInput struct {
	ScheduleID string
	// ExpectedRevision and Lease must both match in the same durable write.
	// A schedule edit, expired lease, or replacement claim therefore cannot be
	// completed by an older worker.
	ExpectedRevision modelquality.ScheduleRevision
	Lease            ModelQualityScheduleLease
	RunID            string
	Status           ModelQualityScheduleCompletionStatus
	// CompletedAt is retained for source compatibility only. PostgreSQL owns
	// completion time, lease expiry and next_run_at; adapters must not trust it.
	CompletedAt time.Time
	Interval    time.Duration
}

type ModelQualityScheduleCompleter interface {
	CompleteModelQualitySchedule(context.Context, ModelQualityScheduleCompleteInput) (bool, error)
}

type ModelQualityEnforcementState string

const (
	ModelQualityEnforcementActive  ModelQualityEnforcementState = "active"
	ModelQualityEnforcementCleared ModelQualityEnforcementState = "cleared"
)

// ModelQualityRecoveryLease is separate from ModelQualityScheduleLease to
// make it impossible to accidentally use a schedule claim to clear a quality
// isolation generation.
type ModelQualityRecoveryLease struct {
	OwnerID    ModelQualityClaimOwnerID
	ClaimToken ModelQualityRecoveryClaimToken
	Until      time.Time
}

type ModelQualityRecoveryClaimToken string

// ModelQualityEnforcementRecord is the durable control-plane state for one
// account. AccountConfigRevision starts as the pre-mutation account snapshot
// used to apply this enforcement generation, then a recovery claim refreshes
// it to that claim's current account revision. Recovery completion must compare
// it with its own expected revision and the current account row.
type ModelQualityEnforcementRecord struct {
	AccountID             string
	SystemAccountID       string
	Token                 modelquality.EnforcementToken
	State                 ModelQualityEnforcementState
	Action                modelquality.Action
	TriggerRunID          string
	PolicyRevision        modelquality.PolicyRevision
	AccountConfigRevision modelquality.AccountRevision
	BeforeStatus          modelquality.AccountStatus
	AfterStatus           modelquality.AccountStatus
	// FallbackWasEnabled and SuperPriorityWasEnabled are the account facts
	// captured before this enforcement generation. They remain durable audit
	// facts even when a later action changes one of the live account flags.
	FallbackWasEnabled      bool
	SuperPriorityWasEnabled bool
	RecoveryDueAt           *time.Time
	RecoveryLease           *ModelQualityRecoveryLease
	LastRecoveryRunID       string
	StartedAt               time.Time
	ClearedAt               *time.Time
	UpdatedAt               time.Time
}

type ModelQualityEnforcementApplyInput struct {
	SystemAccountID string
	AccountID       string
	RunID           string
	Trigger         modelquality.Trigger
	Action          modelquality.Action
	// ExpectedPolicyRevision and ExpectedAccountConfigRevision are both CAS
	// fences. The adapter reads policy/account and applies the chosen account
	// mutation plus enforcement record in one transaction.
	ExpectedPolicyRevision        modelquality.PolicyRevision
	ExpectedAccountConfigRevision modelquality.AccountRevision
	RecoveryInterval              time.Duration
	Message                       string
	DecidedAt                     time.Time
}

type ModelQualityEnforcementApplyStatus string

const (
	ModelQualityEnforcementApplied          ModelQualityEnforcementApplyStatus = "applied"
	ModelQualityEnforcementAlreadyEffective ModelQualityEnforcementApplyStatus = "already_effective"
	ModelQualityEnforcementSkipped          ModelQualityEnforcementApplyStatus = "skipped"
	ModelQualityEnforcementStale            ModelQualityEnforcementApplyStatus = "stale"
)

type ModelQualityEnforcementApplyResult struct {
	Status       ModelQualityEnforcementApplyStatus
	BeforeStatus *modelquality.AccountStatus
	AfterStatus  *modelquality.AccountStatus
	Enforcement  *ModelQualityEnforcementRecord
}

type ModelQualityEnforcementApplier interface {
	ApplyModelQualityEnforcement(context.Context, ModelQualityEnforcementApplyInput) (ModelQualityEnforcementApplyResult, error)
}

type ModelQualityRecoveryClaimInput struct {
	OwnerID ModelQualityClaimOwnerID
	// LeaseDuration is applied to one PostgreSQL clock_timestamp() inside
	// each claim write. Callers cannot extend a lease with a skewed host clock.
	LeaseDuration time.Duration
	Limit         int
}

// ModelQualityRecoveryClaim contains all three fences required to launch a
// recovery check. The adapter captures AccountConfigRevision while it acquires
// Lease, then the worker carries that exact value to completion.
type ModelQualityRecoveryClaim struct {
	AccountID                     string
	SystemAccountID               string
	Model                         string
	Policy                        ModelQualityPolicyRecord
	ExpectedAccountConfigRevision modelquality.AccountRevision
	Enforcement                   ModelQualityEnforcementRecord
	Lease                         ModelQualityRecoveryLease
}

type ModelQualityRecoveryClaimer interface {
	ClaimDueModelQualityRecoveries(context.Context, ModelQualityRecoveryClaimInput) ([]ModelQualityRecoveryClaim, error)
}

type ModelQualityRecoveryCompletionStatus string

const (
	ModelQualityRecoveryRecovered    ModelQualityRecoveryCompletionStatus = "recovered"
	ModelQualityRecoveryKeptIsolated ModelQualityRecoveryCompletionStatus = "kept_isolated"
	ModelQualityRecoveryStale        ModelQualityRecoveryCompletionStatus = "stale"
)

type ModelQualityRecoveryCompleteInput struct {
	AccountID string
	// ExpectedEnforcement includes the generation fence. It is paired with the
	// opaque recovery Lease so an older claim by the same owner cannot win.
	ExpectedEnforcement           modelquality.EnforcementToken
	ExpectedPolicyRevision        modelquality.PolicyRevision
	ExpectedAccountConfigRevision modelquality.AccountRevision
	Lease                         ModelQualityRecoveryLease
	RunID                         string
	Passed                        bool
	RecoveryInterval              time.Duration
	// CompletedAt is retained for source compatibility only. PostgreSQL owns
	// completion time, lease expiry and recovery_due_at; adapters must not trust it.
	CompletedAt time.Time
}

type ModelQualityRecoveryCompleteResult struct {
	Status         ModelQualityRecoveryCompletionStatus
	BeforeStatus   *modelquality.AccountStatus
	AfterStatus    *modelquality.AccountStatus
	NextRecoveryAt *time.Time
}

type ModelQualityRecoveryCompleter interface {
	CompleteModelQualityRecovery(context.Context, ModelQualityRecoveryCompleteInput) (ModelQualityRecoveryCompleteResult, error)
}

// ModelQualityHealthFailureInput is the retained statistics fact emitted when
// a completed model check cannot provide usable quality evidence. ObservedAt
// determines both the local statistics hour and last-write-wins order;
// UpdatedAt is audit metadata only and must never make an older observation
// overwrite a newer one.
type ModelQualityHealthFailureInput struct {
	AccountID       string
	SystemAccountID string
	ProviderCode    string
	ObservedAt      time.Time
	RunID           string
	Model           string
	Profile         modelquality.Profile
	Score           int
	Threshold       int
	Level           modelquality.Level
	ErrorCode       string
	ErrorMessage    string
	UpdatedAt       time.Time
}

type ModelQualityHealthFailureResult struct {
	Applied  bool
	StatHour string
}

// ModelQualityHealthFailureWriter writes one bounded, idempotent hourly fact.
// It intentionally does not own retry decisions: the dataset decision and
// this retained statistics row are separate durable steps.
type ModelQualityHealthFailureWriter interface {
	RecordModelQualityHealthFailure(context.Context, ModelQualityHealthFailureInput) (ModelQualityHealthFailureResult, error)
}

// ModelQualityHealthSyncLease is the durable ownership fence for one failed
// health-stat delivery. OwnerID is diagnostic; stale completion is prevented
// by the opaque token, monotonically increasing epoch and exact lease expiry.
// A process restart must use a new owner ID even when the operating-system PID
// is reused.
type ModelQualityHealthSyncLease struct {
	OwnerID    ModelQualityClaimOwnerID
	ClaimToken ModelQualityHealthSyncClaimToken
	Epoch      uint64
	Until      time.Time
}

type ModelQualityHealthSyncClaimToken string

type ModelQualityHealthSyncClaimInput struct {
	OwnerID ModelQualityClaimOwnerID
	// LeaseDuration is applied to the PostgreSQL clock inside the claim
	// transaction. Callers do not provide an absolute lease timestamp, so host
	// clock skew cannot extend ownership.
	LeaseDuration time.Duration
	Limit         int
}

// ModelQualityHealthSyncDecisionFence carries the exact bounded decision fact
// observed while the run row was locked. Completion compares both fields in
// the same UPDATE so a concurrent Node decision write cannot be overwritten.
// RawJSON is deliberately opaque to workers and must be returned unchanged.
type ModelQualityHealthSyncDecisionFence struct {
	RawJSON      string
	RawUpdatedAt string
}

type ModelQualityHealthSyncClaim struct {
	RunID         string
	Failure       ModelQualityHealthFailureInput
	DecisionFence ModelQualityHealthSyncDecisionFence
	Lease         ModelQualityHealthSyncLease
}

// ModelQualityHealthSyncClaimBatch reports malformed durable facts separately
// from transient storage errors. A bad row is durably delayed and cannot keep
// the head of the retry queue from starving valid work behind it.
type ModelQualityHealthSyncClaimBatch struct {
	Claims      []ModelQualityHealthSyncClaim
	Quarantined int
}

type ModelQualityHealthSyncClaimer interface {
	ClaimFailedModelQualityHealthSyncs(context.Context, ModelQualityHealthSyncClaimInput) (ModelQualityHealthSyncClaimBatch, error)
}

type ModelQualityHealthSyncCompleteInput struct {
	Claim       ModelQualityHealthSyncClaim
	CompletedAt time.Time
}

type ModelQualityHealthSyncCompleteResult struct {
	Applied  bool
	StatHour string
}

// ModelQualityHealthSyncCompleter commits the retained hourly fact and the
// dataset decision in one PostgreSQL transaction. Applied=false means the
// lease or decision fence became stale; the hourly upsert is rolled back too.
type ModelQualityHealthSyncCompleter interface {
	CompleteModelQualityHealthSync(context.Context, ModelQualityHealthSyncCompleteInput) (ModelQualityHealthSyncCompleteResult, error)
}

type ModelQualityHealthSyncReleaseInput struct {
	RunID string
	Lease ModelQualityHealthSyncLease
	// RetryDelay is applied to the PostgreSQL clock by the release CAS.
	RetryDelay   time.Duration
	ErrorClass   string
	ErrorMessage string
}

type ModelQualityHealthSyncReleaser interface {
	ReleaseModelQualityHealthSync(context.Context, ModelQualityHealthSyncReleaseInput) (bool, error)
}
